import 'package:flutter/widgets.dart';

import '../../l10n/feature_strings.dart';

/// The primary activities' words (lib/features/primary).
FeatureStrings primaryStrings(BuildContext context) => FeatureStrings(boardLang(context), primaryStringTable);

const primaryStringTable = <String, Map<String, String>>{
  'en': {
    'title': 'Primary activities',
    'tracing': 'Letter tracing',
    'numbers': 'Numbers',
    'shapes': 'Shapes and colours',
    'matching': 'Matching game',
    'rhymes': 'Rhymes',
    'stars': 'Star wall',
    'english': 'English',
    'hindi': 'Hindi',
    'kannada': 'Kannada',
    'digits': '1 2 3',
    'watch': 'Watch',
    'clear': 'Clear',
    'next': 'Next',
    'previous': 'Previous',
    'toBoard': 'Put on the board',
    'onBoard': 'On the board: trace it with the pen',
    'strokeOrder': 'Stroke order',
    'hintLatin': 'Start at the green dot. Follow the numbers and the arrows.',
    'hintHindi': '1. Draw the body of the letter. 2. Then the standing line. 3. The top line (shirorekha) comes last.',
    'hintKannada': '1. Start at the top left. 2. Go round in one smooth line. 3. Add the small top curve (talekattu) last.',
    'count': 'Count',
    'countHint': 'Tap each one and count aloud.',
    'counted': 'Well done! {n}!',
    'traceNumber': 'Trace the number',
    'findIt': 'Find the {n}',
    'great': 'Great!',
    'tryAgain': 'Try again',
    'newGame': 'New game',
    'play': 'Play',
    'edit': 'Edit',
    'addPair': 'Add a pair',
    'word': 'Word',
    'picture': 'Picture',
    'matchHint': 'Drag each word to its picture.',
    'allMatched': 'All matched! ⭐',
    'readAloud': 'Read aloud',
    'addRhyme': 'Add a rhyme',
    'rhymeTitle': 'Title',
    'rhymeLines': 'Lines (one per line)',
    'save': 'Save',
    'cancel': 'Cancel',
    'starOfDay': 'Star of the day: {n}',
    'noStars': 'Tap a name to give a star.',
    'reset': 'Start again',
    'circle': 'Circle',
    'square': 'Square',
    'triangle': 'Triangle',
    'rectangle': 'Rectangle',
    'star': 'Star',
    'oval': 'Oval',
    'diamond': 'Diamond',
    'heart': 'Heart',
    'red': 'Red',
    'blue': 'Blue',
    'green': 'Green',
    'yellow': 'Yellow',
    'orange': 'Orange',
    'purple': 'Purple',
    'pink': 'Pink',
    'brown': 'Brown',
    'black': 'Black',
    'white': 'White',
  },
  'hi': {
    'title': 'प्राथमिक गतिविधियाँ',
    'tracing': 'अक्षर अनुरेखण',
    'numbers': 'संख्याएँ',
    'shapes': 'आकार और रंग',
    'matching': 'मिलान खेल',
    'rhymes': 'कविताएँ',
    'stars': 'स्टार दीवार',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिंदी',
    'kannada': 'कन्नड़',
    'digits': '१ २ ३',
    'watch': 'देखें',
    'clear': 'मिटाएँ',
    'next': 'अगला',
    'previous': 'पिछला',
    'toBoard': 'बोर्ड पर रखें',
    'onBoard': 'बोर्ड पर: पेन से अनुरेखण करें',
    'strokeOrder': 'लिखने का क्रम',
    'hintLatin': 'हरे बिंदु से शुरू करें। संख्याओं और तीरों के साथ चलें।',
    'hintHindi': '1. पहले अक्षर का आकार बनाएँ। 2. फिर खड़ी पाई। 3. शिरोरेखा सबसे अंत में।',
    'hintKannada': '1. ऊपर बाईं ओर से शुरू करें। 2. एक ही रेखा में घुमाएँ। 3. तलेकट्टु अंत में लगाएँ।',
    'count': 'गिनें',
    'countHint': 'हर एक को छुएँ और ज़ोर से गिनें।',
    'counted': 'शाबाश! {n}!',
    'traceNumber': 'संख्या का अनुरेखण',
    'findIt': '{n} ढूँढें',
    'great': 'बहुत बढ़िया!',
    'tryAgain': 'फिर से कोशिश करें',
    'newGame': 'नया खेल',
    'play': 'खेलें',
    'edit': 'बदलें',
    'addPair': 'जोड़ी जोड़ें',
    'word': 'शब्द',
    'picture': 'चित्र',
    'matchHint': 'हर शब्द को उसके चित्र पर खींचें।',
    'allMatched': 'सब मिल गए! ⭐',
    'readAloud': 'पढ़कर सुनाएँ',
    'addRhyme': 'कविता जोड़ें',
    'rhymeTitle': 'शीर्षक',
    'rhymeLines': 'पंक्तियाँ (हर पंक्ति अलग)',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'starOfDay': 'आज का स्टार: {n}',
    'noStars': 'स्टार देने के लिए नाम छुएँ।',
    'reset': 'फिर से शुरू करें',
    'circle': 'वृत्त',
    'square': 'वर्ग',
    'triangle': 'त्रिभुज',
    'rectangle': 'आयत',
    'star': 'तारा',
    'oval': 'अंडाकार',
    'diamond': 'हीरा',
    'heart': 'दिल',
    'red': 'लाल',
    'blue': 'नीला',
    'green': 'हरा',
    'yellow': 'पीला',
    'orange': 'नारंगी',
    'purple': 'बैंगनी',
    'pink': 'गुलाबी',
    'brown': 'भूरा',
    'black': 'काला',
    'white': 'सफ़ेद',
  },
  'kn': {
    'title': 'ಪ್ರಾಥಮಿಕ ಚಟುವಟಿಕೆಗಳು',
    'tracing': 'ಅಕ್ಷರ ತಿದ್ದುವುದು',
    'numbers': 'ಸಂಖ್ಯೆಗಳು',
    'shapes': 'ಆಕಾರಗಳು ಮತ್ತು ಬಣ್ಣಗಳು',
    'matching': 'ಹೊಂದಿಸುವ ಆಟ',
    'rhymes': 'ಶಿಶುಗೀತೆಗಳು',
    'stars': 'ನಕ್ಷತ್ರ ಗೋಡೆ',
    'english': 'ಇಂಗ್ಲಿಷ್',
    'hindi': 'ಹಿಂದಿ',
    'kannada': 'ಕನ್ನಡ',
    'digits': '೧ ೨ ೩',
    'watch': 'ನೋಡಿ',
    'clear': 'ಅಳಿಸಿ',
    'next': 'ಮುಂದೆ',
    'previous': 'ಹಿಂದೆ',
    'toBoard': 'ಬೋರ್ಡ್‌ಗೆ ಹಾಕಿ',
    'onBoard': 'ಬೋರ್ಡ್‌ನಲ್ಲಿ: ಪೆನ್‌ನಿಂದ ತಿದ್ದಿ',
    'strokeOrder': 'ಬರೆಯುವ ಕ್ರಮ',
    'hintLatin': 'ಹಸಿರು ಚುಕ್ಕೆಯಿಂದ ಆರಂಭಿಸಿ. ಸಂಖ್ಯೆಗಳು ಮತ್ತು ಬಾಣಗಳನ್ನು ಅನುಸರಿಸಿ.',
    'hintHindi': '1. ಮೊದಲು ಅಕ್ಷರದ ದೇಹ. 2. ನಂತರ ನಿಂತ ಗೆರೆ. 3. ಶಿರೋರೇಖೆ ಕೊನೆಯಲ್ಲಿ.',
    'hintKannada': '1. ಮೇಲಿನ ಎಡದಿಂದ ಆರಂಭಿಸಿ. 2. ಒಂದೇ ಗೆರೆಯಲ್ಲಿ ಸುತ್ತಿ. 3. ತಲೆಕಟ್ಟು ಕೊನೆಯಲ್ಲಿ.',
    'count': 'ಎಣಿಸಿ',
    'countHint': 'ಒಂದೊಂದನ್ನೂ ಮುಟ್ಟಿ, ಜೋರಾಗಿ ಎಣಿಸಿ.',
    'counted': 'ಭೇಷ್! {n}!',
    'traceNumber': 'ಸಂಖ್ಯೆ ತಿದ್ದಿ',
    'findIt': '{n} ಹುಡುಕಿ',
    'great': 'ಅದ್ಭುತ!',
    'tryAgain': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'newGame': 'ಹೊಸ ಆಟ',
    'play': 'ಆಡಿ',
    'edit': 'ಬದಲಿಸಿ',
    'addPair': 'ಜೋಡಿ ಸೇರಿಸಿ',
    'word': 'ಪದ',
    'picture': 'ಚಿತ್ರ',
    'matchHint': 'ಪ್ರತಿ ಪದವನ್ನು ಅದರ ಚಿತ್ರಕ್ಕೆ ಎಳೆಯಿರಿ.',
    'allMatched': 'ಎಲ್ಲವೂ ಹೊಂದಿತು! ⭐',
    'readAloud': 'ಓದಿ ಹೇಳಿ',
    'addRhyme': 'ಗೀತೆ ಸೇರಿಸಿ',
    'rhymeTitle': 'ಶೀರ್ಷಿಕೆ',
    'rhymeLines': 'ಸಾಲುಗಳು (ಒಂದು ಸಾಲಿಗೆ ಒಂದು)',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'starOfDay': 'ಇಂದಿನ ನಕ್ಷತ್ರ: {n}',
    'noStars': 'ನಕ್ಷತ್ರ ಕೊಡಲು ಹೆಸರನ್ನು ಮುಟ್ಟಿ.',
    'reset': 'ಮತ್ತೆ ಆರಂಭಿಸಿ',
    'circle': 'ವೃತ್ತ',
    'square': 'ಚೌಕ',
    'triangle': 'ತ್ರಿಕೋನ',
    'rectangle': 'ಆಯತ',
    'star': 'ನಕ್ಷತ್ರ',
    'oval': 'ಅಂಡಾಕಾರ',
    'diamond': 'ವಜ್ರ',
    'heart': 'ಹೃದಯ',
    'red': 'ಕೆಂಪು',
    'blue': 'ನೀಲಿ',
    'green': 'ಹಸಿರು',
    'yellow': 'ಹಳದಿ',
    'orange': 'ಕಿತ್ತಳೆ',
    'purple': 'ನೇರಳೆ',
    'pink': 'ಗುಲಾಬಿ',
    'brown': 'ಕಂದು',
    'black': 'ಕಪ್ಪು',
    'white': 'ಬಿಳಿ',
  },
};
