-- Integrations: DigiLocker/NAD/ABC, live biometric and RFID devices, LTI and SCORM, OData tokens, embeddings, early alerts.
CREATE OR REPLACE FUNCTION kx_cosine(a real[], b real[]) RETURNS double precision LANGUAGE sql IMMUTABLE AS $$ SELECT coalesce(sum(x * y) / nullif(sqrt(sum(x * x)) * sqrt(sum(y * y)), 0), 0)::double precision FROM unnest(a, b) AS t(x, y) $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "integration_settings" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, key text NOT NULL, value jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, key));--> statement-breakpoint
ALTER TABLE "integration_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "integration_settings";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "integration_settings" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "integration_settings" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_academic_ids" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id), apaar_id text, abc_id text, source text NOT NULL DEFAULT 'admission', captured_by uuid REFERENCES users(id), captured_at timestamptz NOT NULL DEFAULT now(), UNIQUE (student_id));--> statement-breakpoint
ALTER TABLE "student_academic_ids" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "student_academic_ids";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "student_academic_ids" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "student_academic_ids" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "integration_exports" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, kind text NOT NULL, ref text NOT NULL, rows integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'built', content text NOT NULL DEFAULT '', error text, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), sent_at timestamptz);--> statement-breakpoint
ALTER TABLE "integration_exports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "integration_exports";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "integration_exports" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "integration_exports" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dl_documents" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id), doc_type text NOT NULL, title text NOT NULL, doc_ref text NOT NULL, uri text, status text NOT NULL DEFAULT 'pending', sha256 text, signature text, error text, attempts integer NOT NULL DEFAULT 0, payload jsonb NOT NULL DEFAULT '{}'::jsonb, nad_export_id uuid REFERENCES integration_exports(id) ON DELETE SET NULL, issued_at timestamptz, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, doc_ref));--> statement-breakpoint
ALTER TABLE "dl_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "dl_documents";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "dl_documents" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "dl_documents" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "access_devices" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, kind text NOT NULL, vendor text NOT NULL, serial text NOT NULL, name text NOT NULL, purpose text NOT NULL, location text NOT NULL DEFAULT '', config jsonb NOT NULL DEFAULT '{}'::jsonb, key_hash text NOT NULL, active boolean NOT NULL DEFAULT true, last_seen_at timestamptz, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, serial));--> statement-breakpoint
ALTER TABLE "access_devices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "access_devices";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "access_devices" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "access_devices" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "credential_tags" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, kind text NOT NULL, value text NOT NULL, subject_type text NOT NULL, subject_id uuid NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, kind, value));--> statement-breakpoint
ALTER TABLE "credential_tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "credential_tags";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "credential_tags" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "credential_tags" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "device_events" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, device_id uuid NOT NULL REFERENCES access_devices(id) ON DELETE CASCADE, tag_kind text NOT NULL, tag_value text NOT NULL, event_at timestamptz NOT NULL, direction text NOT NULL DEFAULT 'in', outcome text NOT NULL, detail jsonb NOT NULL DEFAULT '{}'::jsonb, subject_type text, subject_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (device_id, tag_value, event_at));--> statement-breakpoint
ALTER TABLE "device_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "device_events";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "device_events" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "device_events" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "transport_boardings" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id), route_id uuid REFERENCES transport_routes(id), device_id uuid REFERENCES access_devices(id) ON DELETE SET NULL, boarded_at timestamptz NOT NULL, on_date date NOT NULL);--> statement-breakpoint
ALTER TABLE "transport_boardings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "transport_boardings";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "transport_boardings" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "transport_boardings" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "api_tokens" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, scopes text[] NOT NULL, secret_hash text NOT NULL, created_by uuid NOT NULL REFERENCES users(id), revoked_at timestamptz, last_used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
ALTER TABLE "api_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "api_tokens";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "api_tokens" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "api_tokens" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lti_tools" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, client_id text NOT NULL, login_url text NOT NULL, launch_url text NOT NULL, jwks_url text, deployment_id text NOT NULL DEFAULT '1', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, client_id));--> statement-breakpoint
ALTER TABLE "lti_tools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "lti_tools";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "lti_tools" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "lti_tools" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lti_platforms" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, issuer text NOT NULL, client_id text NOT NULL, auth_url text NOT NULL, jwks_url text NOT NULL, deployment_id text NOT NULL DEFAULT '1', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, issuer, client_id));--> statement-breakpoint
ALTER TABLE "lti_platforms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "lti_platforms";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "lti_platforms" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "lti_platforms" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lti_states" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, kind text NOT NULL, state text NOT NULL UNIQUE, nonce text NOT NULL, ref jsonb NOT NULL DEFAULT '{}'::jsonb, expires_at timestamptz NOT NULL, used_at timestamptz);--> statement-breakpoint
ALTER TABLE "lti_states" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "lti_states";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "lti_states" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "lti_states" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scorm_packages" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, course_id uuid REFERENCES courses(id) ON DELETE SET NULL, title text NOT NULL, version text NOT NULL, launch_href text NOT NULL, manifest jsonb NOT NULL DEFAULT '{}'::jsonb, file_count integer NOT NULL DEFAULT 0, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
ALTER TABLE "scorm_packages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "scorm_packages";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "scorm_packages" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "scorm_packages" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scorm_files" (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, package_id uuid NOT NULL REFERENCES scorm_packages(id) ON DELETE CASCADE, path text NOT NULL, mime text NOT NULL, content bytea NOT NULL, PRIMARY KEY (package_id, path));--> statement-breakpoint
ALTER TABLE "scorm_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "scorm_files";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "scorm_files" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "scorm_files" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scorm_attempts" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, package_id uuid NOT NULL REFERENCES scorm_packages(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), cmi jsonb NOT NULL DEFAULT '{}'::jsonb, lesson_status text NOT NULL DEFAULT 'not attempted', score_raw numeric, total_time text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (package_id, user_id));--> statement-breakpoint
ALTER TABLE "scorm_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "scorm_attempts";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "scorm_attempts" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "scorm_attempts" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "content_embeddings" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, source_type text NOT NULL, source_id uuid NOT NULL, provider text NOT NULL, dims integer NOT NULL, vec real[] NOT NULL, label text NOT NULL DEFAULT '', text_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, source_type, source_id, provider));--> statement-breakpoint
ALTER TABLE "content_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "content_embeddings";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "content_embeddings" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "content_embeddings" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "early_alert_flags" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id), level text NOT NULL, score integer NOT NULL, reasons jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'open', mentor_user_id uuid REFERENCES users(id), computed_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, UNIQUE (student_id));--> statement-breakpoint
ALTER TABLE "early_alert_flags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "early_alert_flags";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "early_alert_flags" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "early_alert_flags" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "early_alert_interventions" (id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, flag_id uuid NOT NULL REFERENCES early_alert_flags(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id), by_user_id uuid NOT NULL REFERENCES users(id), action text NOT NULL, note text NOT NULL DEFAULT '', due_on date, outcome text, created_at timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
ALTER TABLE "early_alert_interventions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS tenant_isolation ON "early_alert_interventions";--> statement-breakpoint
CREATE POLICY tenant_isolation ON "early_alert_interventions" USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'kinetix_app') THEN GRANT SELECT, INSERT, UPDATE, DELETE ON "early_alert_interventions" TO kinetix_app; END IF; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS dl_documents_student_idx ON dl_documents (student_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS device_events_at_idx ON device_events (tenant_id, event_at DESC);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS transport_boardings_idx ON transport_boardings (student_id, on_date);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS content_embeddings_idx ON content_embeddings (tenant_id, provider, source_type);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS early_alert_flags_idx ON early_alert_flags (tenant_id, status, level);
