import { A4, Pdf, wrap } from '../common/pdf-doc.js';

export interface CourseFileData {
  institution: string;
  section: string;
  subject: string;
  subjectCode: string;
  version: number;
  generatedOn: string;
  generatedBy: string;
  syllabus: { chapter: string; topics: { title: string; coveredOn: string | null }[] }[];
  lessonPlans: { total: number; reviewed: number; first: string | null; last: string | null };
  timetable: { day: string; time: string; teacher: string }[];
  attendance: { sessions: number; averagePct: number | null; belowThreshold: number; threshold: number };
  assessments: { title: string; kind: string; heldOn: string; maxMarks: number; entered: number; averagePct: number | null; passPct: number | null }[];
  attainment: { code: string; direct: number | null; indirect: number | null; combined: number | null; target: number; met: boolean }[];
  whiteboards: { title: string; updatedOn: string; shared: boolean }[];
  recordings: { title: string; recordedOn: string; minutes: number }[];
}

const L = 40;
const R = A4.w - 40;
const BOTTOM = A4.h - 50;

/** A running cursor down the page that starts a new page when the next block will not fit. */
class Flow {
  y = 0;
  constructor(private readonly pdf: Pdf, private readonly footer: string) {
    this.newPage();
  }
  private pageNo = 0;
  newPage() {
    this.pdf.addPage();
    this.pageNo++;
    this.pdf.text(this.footer, L, A4.h - 28, { size: 8, color: '#777777' });
    this.pdf.text(`Page ${this.pageNo}`, R, A4.h - 28, { size: 8, color: '#777777', align: 'right' });
    this.y = 50;
  }
  need(h: number) {
    if (this.y + h > BOTTOM) this.newPage();
  }
  heading(s: string) {
    this.need(46);
    this.y += 10;
    this.pdf.rect(L, this.y - 12, R - L, 20, { fill: '#eef2f7' });
    this.pdf.text(s, L + 6, this.y + 2, { size: 11, bold: true });
    this.y += 26;
  }
  line(s: string, o: { bold?: boolean; indent?: number; color?: string; size?: number } = {}) {
    const size = o.size ?? 9.5;
    const x = L + (o.indent ?? 0);
    for (const l of wrap(s, R - x, size, o.bold)) {
      this.need(size * 1.5);
      this.pdf.text(l, x, this.y, { size, bold: o.bold, color: o.color });
      this.y += size * 1.5;
    }
  }
  /** A table row: cells are placed at the given x offsets (relative to the margin), long text is cut to its column. */
  row(cells: string[], cols: number[], o: { bold?: boolean } = {}) {
    this.need(16);
    cells.forEach((c, i) => {
      const w = (cols[i + 1] ?? R - L) - cols[i] - 6;
      const [first] = wrap(c, w, 9, o.bold);
      this.pdf.text(first ?? '', L + cols[i], this.y, { size: 9, bold: o.bold });
    });
    this.y += 14;
  }
  none(s: string) {
    this.line(s, { color: '#777777' });
  }
}

const pct = (n: number | null) => (n === null ? '-' : `${n}%`);

/** The course file for one section and subject, assembled from what the system already holds. */
export function courseFilePdf(d: CourseFileData): Buffer {
  const pdf = new Pdf(`Course file ${d.subjectCode} ${d.section}`);
  const f = new Flow(pdf, `${d.institution}  |  Course file ${d.subjectCode} ${d.section}  |  Version ${d.version}`);
  pdf.text(d.institution, A4.w / 2, f.y, { size: 16, bold: true, align: 'center' });
  f.y += 22;
  pdf.text('Course File', A4.w / 2, f.y, { size: 12, align: 'center', color: '#444444' });
  f.y += 12;
  pdf.line(L, f.y, R, f.y, { width: 1 });
  f.y += 20;
  for (const [k, v] of [
    ['Subject', `${d.subject} (${d.subjectCode})`],
    ['Class', d.section],
    ['Version', String(d.version)],
    ['Generated on', d.generatedOn],
    ['Generated by', d.generatedBy],
  ] as const) {
    pdf.text(k, L, f.y, { size: 9.5, color: '#666666' }).text(v, L + 90, f.y, { size: 9.5, bold: true });
    f.y += 15;
  }

  f.heading('1. Syllabus and coverage');
  const topics = d.syllabus.flatMap((c) => c.topics);
  const covered = topics.filter((t) => t.coveredOn).length;
  f.line(`${covered} of ${topics.length} topics covered`, { bold: true });
  if (d.syllabus.length === 0) f.none('No syllabus is linked to this subject.');
  for (const c of d.syllabus) {
    f.line(c.chapter, { bold: true });
    for (const t of c.topics) f.line(`${t.coveredOn ? `[${t.coveredOn}]` : '[not yet]'} ${t.title}`, { indent: 12 });
  }

  f.heading('2. Lesson plans');
  if (d.lessonPlans.total === 0) f.none('No lesson plans were written.');
  else f.line(`${d.lessonPlans.total} plans (${d.lessonPlans.reviewed} reviewed), from ${d.lessonPlans.first} to ${d.lessonPlans.last}`);

  f.heading('3. Timetable');
  if (d.timetable.length === 0) f.none('No periods are scheduled.');
  else {
    const cols = [0, 110, 230];
    f.row(['Day', 'Time', 'Teacher'], cols, { bold: true });
    for (const t of d.timetable) f.row([t.day, t.time, t.teacher], cols);
  }

  f.heading('4. Attendance summary');
  if (d.attendance.sessions === 0) f.none('No attendance has been taken for this subject.');
  else f.line(`${d.attendance.sessions} periods taken, class average ${pct(d.attendance.averagePct)}, ${d.attendance.belowThreshold} students below ${d.attendance.threshold}%`);

  f.heading('5. Assessments and marks');
  if (d.assessments.length === 0) f.none('No assessments were held.');
  else {
    const cols = [0, 190, 255, 325, 385, 450];
    f.row(['Assessment', 'Kind', 'Held on', 'Max', 'Average', 'Pass'], cols, { bold: true });
    for (const a of d.assessments) f.row([a.title, a.kind, a.heldOn, String(a.maxMarks), pct(a.averagePct), pct(a.passPct)], cols);
  }

  f.heading('6. Course outcome attainment');
  if (d.attainment.length === 0) f.none('No attainment has been calculated for this subject.');
  else {
    const cols = [0, 70, 140, 220, 300, 380];
    f.row(['CO', 'Direct', 'Indirect', 'Combined', 'Target', 'Result'], cols, { bold: true });
    for (const a of d.attainment) f.row([a.code, pct(a.direct), pct(a.indirect), pct(a.combined), pct(a.target), a.met ? 'Met' : 'Not met'], cols);
  }

  f.heading('7. Saved whiteboards');
  if (d.whiteboards.length === 0) f.none('No whiteboards were saved.');
  for (const w of d.whiteboards) f.line(`${w.updatedOn}  ${w.title}${w.shared ? '  (shared with class)' : ''}`);

  f.heading('8. Recorded lectures');
  if (d.recordings.length === 0) f.none('No lectures were recorded.');
  for (const r of d.recordings) f.line(`${r.recordedOn}  ${r.title}  (${r.minutes} min)`);

  return pdf.build();
}
