// KINETIX promo composition. Deterministic: window.renderAt(t) draws the frame at time t (seconds).
// Timeline (scene starts, VO starts, captions) comes from timeline.js (generated by timeline.py).
/* global TL */
(() => {
const S = document.getElementById('stage');
const CAP = document.querySelector('#cap span');
const SH = '../shots/';
const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const P = (t, a, b) => clamp((t - a) / (b - a));
const eo = (x) => 1 - Math.pow(1 - x, 3);
const eo5 = (x) => 1 - Math.pow(1 - x, 5);
const eio = (x) => (x < 0.5 ? 4 * x * x * x : 1 - Math.pow(-2 * x + 2, 3) / 2);
const lerp = (a, b, x) => a + (b - a) * x;
const el = (tag, cls, parent, html, style) => {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (html != null) e.innerHTML = html;
  if (style) Object.assign(e.style, style);
  (parent || S).appendChild(e);
  return e;
};
const img = (src, parent, style) => { const i = el('img', '', parent, null, style); i.src = SH + src; return i; };
// set(e, {o, x, y, z, s, rx, ry, rz, blur}) — x/y are the element's left/top in px.
const set = (e, p) => {
  if (p.o !== undefined) { e.style.opacity = p.o.toFixed(3); e.style.visibility = p.o <= 0.001 ? 'hidden' : 'visible'; }
  const tr = [];
  if (p.x !== undefined || p.y !== undefined) tr.push(`translate3d(${(p.x || 0).toFixed(2)}px,${(p.y || 0).toFixed(2)}px,${(p.z || 0).toFixed(2)}px)`);
  else if (p.z !== undefined) tr.push(`translateZ(${p.z.toFixed(2)}px)`);
  if (p.rx) tr.push(`rotateX(${p.rx.toFixed(3)}deg)`);
  if (p.ry) tr.push(`rotateY(${p.ry.toFixed(3)}deg)`);
  if (p.rz) tr.push(`rotateZ(${p.rz.toFixed(3)}deg)`);
  if (p.s !== undefined) tr.push(`scale(${p.s.toFixed(4)})`);
  if (tr.length) e.style.transform = tr.join(' ');
  if (p.blur !== undefined) e.style.filter = p.blur > 0.05 ? `blur(${p.blur.toFixed(2)}px)` : 'none';
};
// reveal: blur + rise + fade for text, progress x in [0,1]
const rv = (x, dy = 40, b = 16) => ({ o: eo(x), y: (1 - eo(x)) * dy, blur: (1 - eo(x)) * b });
const LOGO = (size) => `<svg width="${size}" height="${size}" viewBox="0 0 48 48"><defs><linearGradient id="lg${size}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#5B86FF"/><stop offset="1" stop-color="#1D4ED8"/></linearGradient></defs><rect width="48" height="48" rx="14" fill="url(#lg${size})"/><path d="M15 12v24M33 12 20.5 24 33 36" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

const sc = TL.scenes;
const T = (i) => sc[i].start;

// ---------- background ----------
const bg = el('div', 'layer', S, null, { background: 'radial-gradient(120% 90% at 50% 40%, #0B1238 0%, #070B24 45%, #04061A 100%)' });
const g1 = el('div', 'glow', bg, null, { width: '1500px', height: '1500px', background: 'radial-gradient(circle, rgba(29,78,216,.55) 0%, rgba(29,78,216,.18) 35%, rgba(29,78,216,0) 70%)' });
const g2 = el('div', 'glow', bg, null, { width: '1300px', height: '1300px', background: 'radial-gradient(circle, rgba(99,102,241,.42) 0%, rgba(99,102,241,.12) 40%, rgba(99,102,241,0) 70%)' });
const g3 = el('div', 'glow', bg, null, { width: '1000px', height: '1000px', background: 'radial-gradient(circle, rgba(56,189,248,.22) 0%, rgba(56,189,248,0) 65%)' });
const bloom = el('div', 'glow', bg, null, { width: '2000px', height: '2000px', left: '-40px', top: '-460px', background: 'radial-gradient(circle, rgba(120,150,255,.55) 0%, rgba(80,110,255,.15) 30%, rgba(0,0,0,0) 60%)' });
const vign = el('div', 'layer', S, null, { background: 'radial-gradient(130% 100% at 50% 50%, rgba(0,0,0,0) 55%, rgba(0,0,0,.55) 100%)', zIndex: 40 });
function bgAt(t) {
  const k = 1 + 0.25 * Math.exp(-Math.pow((t - T(2)) / 1.6, 2)) + 0.25 * Math.exp(-Math.pow((t - T(8)) / 2, 2));
  set(g1, { x: 960 - 750 + Math.sin(t * 0.13) * 260 - 220, y: 540 - 750 + Math.cos(t * 0.11) * 140 - 80, s: k, o: clamp(0.85 * k) });
  set(g2, { x: 960 - 650 + Math.cos(t * 0.09 + 1) * 320 + 360, y: 540 - 650 + Math.sin(t * 0.12 + 2) * 160 + 120, s: 1, o: 0.9 });
  set(g3, { x: 960 - 500 + Math.sin(t * 0.07 + 3) * 500, y: 540 - 500 + Math.cos(t * 0.1) * 220 + 260, o: 0.7 });
  const bl = Math.max(Math.exp(-Math.pow((t - T(2) - 0.2) / 0.9, 2)) * (t > T(2) - 0.6 ? 1 : 0.3), Math.exp(-Math.pow((t - T(8) - 0.2) / 1.0, 2)) * 0.8, Math.exp(-Math.pow((t - T(10) - 0.4) / 1.2, 2)) * 0.6);
  set(bloom, { o: bl * 0.7, s: 0.8 + bl * 0.3 });
}

// ---------- scene roots ----------
const roots = sc.map(() => el('div', 'layer'));
function sceneFade(i, t) {
  const a = sc[i].start, b = sc[i].end;
  const inX = i === 0 ? P(t, 0, 0.8) : P(t, a - 0.3, a + 0.4);
  const outX = i === sc.length - 1 ? P(t, b - 0.7, b) : P(t, b - 0.35, b + 0.35);
  const o = Math.min(eo(inX), 1 - eio(outX));
  const r = roots[i];
  if (o <= 0.001) { r.style.visibility = 'hidden'; r.style.display = 'none'; return 0; }
  r.style.display = 'block';
  const blur = i === 0 && t < 1 ? 0 : (1 - inX) * 10 + outX * 10;
  set(r, { o, s: lerp(0.965, 1, eo(inX)) * lerp(1, 1.035, outX), blur: i === sc.length - 1 ? 0 : blur });
  return o;
}

// ---------- S1 + S2: scattered words -> one line -> logo ----------
const wordsL = el('div', 'layer');
const WORDS = ['Attendance.', 'Fees.', 'Exams.', 'Homework.', 'Boards.'];
const SCAT = [[540, 320, -4, 1.0], [1390, 250, 3, 0.86], [1450, 720, -2, 1.08], [560, 770, 2, 0.92], [990, 520, 0, 1.16]];
const wEls = WORDS.map((w) => el('div', 'word', wordsL, w));
const CHIPS = ['Spreadsheets', 'Paper registers', 'WhatsApp groups', 'Fee ledger', 'Exam portal', 'Separate LMS', 'Payroll tool', 'Board software', 'Admission forms', 'Report cards'];
const CPOS = [[150, 150], [1560, 120], [120, 520], [1640, 470], [300, 930], [1500, 930], [860, 110], [800, 940], [1180, 380], [330, 400]];
const cEls = CHIPS.map((c) => el('div', 'chip', wordsL, c));
const uline = el('div', 'abs', wordsL, null, { height: '4px', borderRadius: '4px', background: 'linear-gradient(90deg, rgba(91,134,255,0), #7FA2FF 20%, #fff 50%, #7FA2FF 80%, rgba(91,134,255,0))', boxShadow: '0 0 24px #5B86FF, 0 0 60px #1D4ED8', top: '640px' });
let wW = null;
function words(t) {
  const end = T(2) + 0.3;
  if (t > end) { wordsL.style.display = 'none'; return; }
  wordsL.style.display = 'block';
  if (!wW) wW = wEls.map((e) => e.offsetWidth);
  const fs = 0.66, gap = 34;
  const total = wW.reduce((a, b) => a + b * fs, 0) + gap * (WORDS.length - 1);
  let cx = 960 - total / 2;
  const lineX = wW.map((w) => { const c = cx + (w * fs) / 2; cx += w * fs + gap; return c; });
  const u2 = t - T(1);
  wEls.forEach((e, i) => {
    const [sx, sy, rot, ss] = SCAT[i];
    const inX = P(t, 0.35 + i * 0.34, 1.35 + i * 0.34);
    const driftX = Math.sin(t * 0.45 + i * 1.7) * 14, driftY = Math.cos(t * 0.38 + i) * 10;
    const dim = P(t, 5.5, 6.9);
    const toLine = eio(P(u2, 0.1, 1.5));
    const conv = P(u2, 3.0 + Math.abs(i - 2) * 0.08, 3.9 + Math.abs(i - 2) * 0.08);
    let x = lerp(sx + driftX, lineX[i], toLine), y = lerp(sy + driftY, 540, toLine);
    let s = lerp(ss * lerp(1.4, 1, eo(inX)), fs, toLine);
    x = lerp(x, 960, eio(conv)); y = lerp(y, 540, eio(conv)); s *= lerp(1, 0.15, eio(conv));
    const o = eo(inX) * lerp(1, 0.3, dim) * (u2 > 0 ? lerp(lerp(1, 0.3, dim), 1, toLine) / lerp(1, 0.3, dim) : 1) * (1 - eo(conv));
    const blur = (1 - eo(inX)) * 22 + dim * 2.5 * (1 - toLine) + conv * 14;
    e.style.color = toLine > 0.5 ? '#fff' : '#E4EAFF';
    set(e, { x: x - wW[i] / 2, y: y - 64, rz: rot * (1 - toLine), s, o, blur });
  });
  cEls.forEach((e, i) => {
    const inX = P(t, 1.6 + i * 0.16, 2.4 + i * 0.16);
    const out = P(u2, 0, 0.9);
    const [x, y] = CPOS[i];
    set(e, { x: x + Math.sin(t * 0.3 + i) * 10, y: y + Math.cos(t * 0.33 + i * 2) * 8, o: eo(inX) * 0.75 * (1 - P(t, 5.5, 6.9) * 0.5) * (1 - out), blur: (1 - eo(inX)) * 10 + out * 10, s: lerp(0.9, 1, eo(inX)) });
  });
  const ul = eo(P(u2, 1.2, 2.2)) * (1 - eio(P(u2, 3.0, 3.8)));
  uline.style.width = `${total * ul + 4}px`;
  uline.style.left = `${960 - (total * ul + 4) / 2}px`;
  uline.style.opacity = ul;
}

// global logo used by S2 -> S3
const logoL = el('div', 'layer');
const logoG = el('div', 'glow', logoL, null, { width: '700px', height: '700px', background: 'radial-gradient(circle, rgba(91,134,255,.6) 0%, rgba(29,78,216,.22) 35%, rgba(0,0,0,0) 70%)' });
const logoM = el('div', 'abs', logoL, LOGO(220), { width: '220px', height: '220px', filter: 'drop-shadow(0 20px 60px rgba(29,78,216,.7))' });
function logo(t) {
  const u2 = t - T(1), u3 = t - T(2);
  if (u2 < 3.2 || t > T(3) + 0.4) { logoL.style.display = 'none'; return; }
  logoL.style.display = 'block';
  const inX = P(u2, 3.4, 4.7);
  const mv = eio(P(u3, 0, 0.9));
  const y = lerp(540, 300, mv), s = lerp(lerp(0.3, 1, eo5(inX)), 0.62, mv) * (1 + Math.sin(t * 1.2) * 0.008);
  const out = P(t, T(3) - 0.3, T(3) + 0.3);
  set(logoM, { x: 960 - 110, y: y - 110, s, o: eo(inX) * (1 - out), blur: (1 - eo(inX)) * 20 + out * 10, ry: (1 - eo(inX)) * 50 });
  set(logoG, { x: 960 - 350, y: y - 350, s: lerp(0.4, 1.1, eo(inX)) * lerp(1, 0.8, mv), o: eo(inX) * (1 - out) });
}

// ---------- S3: wordmark ----------
const r3 = roots[2];
const wm = el('div', 'abs title', r3, null, { left: 0, right: 0, top: '400px', textAlign: 'center', fontSize: '190px', fontWeight: 500, letterSpacing: '0.06em' });
const wmL = 'KINETIX'.split('').map((c) => el('span', '', wm, c, { display: 'inline-block', backgroundImage: 'linear-gradient(180deg,#fff 35%,#AFC4FF)', webkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' }));
const tag3 = el('div', 'abs', r3, 'The AI operating system for education.', { left: 0, right: 0, top: '640px', textAlign: 'center', fontSize: '50px', fontWeight: 500, color: '#C7D5FF', letterSpacing: '-0.005em' });
function s3(u) {
  wmL.forEach((e, i) => set(e, { ...rv(P(u, 0.05 + i * 0.06, 0.75 + i * 0.06), 50, 20), s: lerp(1.25, 1, eo(P(u, 0.05 + i * 0.06, 0.9 + i * 0.06))) }));
  wm.style.letterSpacing = `${lerp(0.22, 0.06, eo(P(u, 0, 1.4)))}em`;
  set(tag3, rv(P(u, 0.9, 1.7), 30, 12));
}

// ---------- device builders ----------
function board(parent) {
  const d = el('div', 'device board', parent);
  const scr = el('div', 'scr', d);
  el('div', 'brandbar', d, 'KINETIX');
  return { d, scr };
}
function laptop(parent) {
  const d = el('div', 'device laptop', parent);
  const lid = el('div', 'lid', d);
  const scr = el('div', 'scr', lid);
  el('div', 'deck', d);
  return { d, scr };
}
function phone(parent) {
  const d = el('div', 'device phone', parent);
  const scr = el('div', 'scr', d);
  el('div', 'island', scr);
  el('div', 'abs', scr, '9:41', { left: '34px', top: '20px', fontSize: '17px', fontWeight: 600, color: '#111', zIndex: 6 });
  el('div', 'abs', scr, '<svg width="66" height="14" viewBox="0 0 66 14"><g fill="#111"><rect x="0" y="9" width="3" height="5" rx="1"/><rect x="5" y="6" width="3" height="8" rx="1"/><rect x="10" y="3" width="3" height="11" rx="1"/><rect x="15" y="0" width="3" height="14" rx="1"/><path d="M27 4.5a10 10 0 0 1 13 0l-1.6 1.7a7.6 7.6 0 0 0-9.8 0zM30 8a5.5 5.5 0 0 1 7 0l-3.5 4z"/><rect x="45" y="1" width="18" height="12" rx="3" fill="none" stroke="#111" stroke-width="1.4"/><rect x="47" y="3" width="13" height="8" rx="1.5"/><rect x="64" y="5" width="1.6" height="4" rx=".8"/></g></svg>', { right: '26px', top: '22px', zIndex: 6 });
  el('div', 'abs', scr, null, { left: '50%', bottom: '8px', width: '120px', height: '5px', marginLeft: '-60px', borderRadius: '3px', background: '#111', zIndex: 6 });
  return { d, scr };
}
const shadowBlob = (parent, w, h) => el('div', 'glow', parent, null, { width: `${w}px`, height: `${h}px`, background: 'radial-gradient(closest-side, rgba(0,0,0,.55), rgba(0,0,0,0))' });

// ---------- S4: smartboard ----------
const r4 = roots[3];
const p4 = el('div', 'layer persp', r4);
const k4 = el('div', 'abs kicker', r4, 'In the classroom', { left: '120px', top: '300px' });
const t4 = el('div', 'abs title', r4, 'KINETIX AI<br>Smartboard', { left: '116px', top: '340px', fontSize: '86px', lineHeight: '1.02' });
const FEATS = ['Ink', '3D models', 'Live polls', 'AI lesson builder'];
const f4 = FEATS.map((f, i) => el('div', 'feat', r4, `<i></i><span>${f}</span>`, { left: '122px', top: `${560 + i * 62}px` }));
const B4 = board(p4);
const B4i = ['board-board.jpg', 'board-panel-3d.jpg', 'board-ask-class.jpg', 'board-todays-plan.jpg'].map((s) => img(s, B4.scr));
// handwritten ink, in the board's 1920x1080 coordinates
const inkSvg = el('div', 'layer', B4.scr, `<svg viewBox="0 0 1920 1080" width="100%" height="100%" style="position:absolute;inset:0">
<defs><clipPath id="inkclip"><rect id="inkrect" x="1340" y="380" width="0" height="300"/></clipPath></defs>
<g fill="none" stroke="#E8A400" stroke-width="7" stroke-linecap="round">
<circle id="sun" cx="1660" cy="250" r="52" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"/>
${[0, 45, 90, 135, 180, 225, 270, 315].map((a, i) => { const r1 = 74, r2 = 104, c = Math.cos(a * Math.PI / 180), s = Math.sin(a * Math.PI / 180); return `<line class="ray" x1="${1660 + r1 * c}" y1="${250 + r1 * s}" x2="${1660 + r2 * c}" y2="${250 + r2 * s}" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"/>`; }).join('')}
</g>
<path id="arrow" d="M1560 330 C 1500 380, 1460 400, 1420 430 M1420 430 l 34 -4 M1420 430 l 8 -32" fill="none" stroke="#1A73E8" stroke-width="6" stroke-linecap="round" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"/>
<g clip-path="url(#inkclip)" font-family="Kalam" fill="#1A73E8" font-size="60"><text x="1350" y="500">CO₂ + H₂O</text><text x="1350" y="590">→ glucose + O₂</text></g>
<path id="uline4" d="M1350 625 C 1480 612, 1640 640, 1800 618" fill="none" stroke="#D93025" stroke-width="6" stroke-linecap="round" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"/>
</svg>`);
const poll = el('div', 'card', p4, `<div style="padding:26px 30px">
<div style="display:flex;align-items:center;gap:10px;font-size:18px;font-weight:600;color:#1D4ED8"><span style="width:10px;height:10px;border-radius:50%;background:#e53935;box-shadow:0 0 0 4px rgba(229,57,53,.2)"></span>LIVE POLL · BCom Sem 3 A</div>
<div style="font-size:28px;font-weight:600;margin:10px 0 18px">Which gas do plants give out?</div>
${[['A', 'Carbon dioxide', 12], ['B', 'Oxygen', 71], ['C', 'Nitrogen', 9], ['D', 'Hydrogen', 8]].map(([k, n, v]) => `<div style="display:flex;align-items:center;gap:12px;margin:10px 0;font-size:20px"><b style="width:30px;height:30px;border-radius:8px;display:grid;place-items:center;background:${k === 'B' ? '#1D4ED8' : '#E8ECF8'};color:${k === 'B' ? '#fff' : '#334'}">${k}</b><span style="width:150px">${n}</span><span style="flex:1;height:16px;border-radius:8px;background:#EEF1FA;overflow:hidden"><i class="bar" data-v="${v}" style="display:block;height:100%;width:0;border-radius:8px;background:${k === 'B' ? 'linear-gradient(90deg,#3b6bff,#1D4ED8)' : '#AEB9D9'}"></i></span><span class="pv" data-v="${v}" style="width:52px;text-align:right;font-weight:600">0%</span></div>`).join('')}
<div style="font-size:16px;color:#5b6478;margin-top:14px">31 of 34 students answered</div></div>`, { width: '520px' });
const pollBars = [...poll.querySelectorAll('.bar')], pollVals = [...poll.querySelectorAll('.pv')];
const sh4 = shadowBlob(p4, 1300, 200);
function s4(u, t) {
  const inX = eo5(P(u, 0, 1.5));
  set(k4, rv(P(u, 0.3, 1.1)));
  set(t4, rv(P(u, 0.45, 1.3), 50, 18));
  const segs = [[0, 7.6], [7.6, 9.4], [9.4, 10.8], [10.8, 99]];
  const active = segs.findIndex(([a, b]) => u >= a && u < b);
  f4.forEach((f, i) => {
    const on = i === active && u > 1.2 ? 1 : (i < active ? 0.45 : 0);
    set(f, { ...rv(P(u, 0.8 + i * 0.12, 1.6 + i * 0.12), 20, 8), x: on * 10 });
    f.style.color = on === 1 ? '#fff' : '#8D9AC7';
    f.firstChild.style.background = on === 1 ? '#5B86FF' : '#34408a';
    f.firstChild.style.boxShadow = on === 1 ? '0 0 16px #5B86FF' : 'none';
  });
  // the board: entry, then a slow camera drift
  const ry = lerp(-42, -17, inX) + 7 * P(u, 1.5, 13);
  set(B4.d, { x: 1240 - 680, y: 520 - 420, z: lerp(-700, -80, inX) + 30 * Math.sin(u * 0.4), rx: 3 + Math.sin(u * 0.3) * 1, ry, s: 0.82, o: inX });
  set(sh4, { x: 1240 - 650, y: 860, o: inX * 0.8 });
  // screen sequence
  B4i.forEach((im, i) => { const [a] = segs[i]; const o = i === 0 ? 1 : eo(P(u, a - 0.15, a + 0.3)); im.style.opacity = o; });
  // ink on the first screen
  const ink = (id, a, b) => { const e = inkSvg.querySelector(id); e.setAttribute('stroke-dashoffset', (1 - eio(P(u, a, b))).toFixed(3)); };
  ink('#sun', 1.6, 2.4);
  inkSvg.querySelectorAll('.ray').forEach((r, i) => r.setAttribute('stroke-dashoffset', (1 - eo(P(u, 2.3 + i * 0.07, 2.6 + i * 0.07))).toFixed(3)));
  ink('#arrow', 2.9, 3.5);
  inkSvg.querySelector('#inkrect').setAttribute('width', (520 * eio(P(u, 3.5, 5.6))).toFixed(1));
  ink('#uline4', 5.7, 6.3);
  inkSvg.style.opacity = 1 - P(u, 7.4, 7.8);
  // live poll card in front of the board
  const pIn = eo5(P(u, 9.5, 10.2)), pOut = P(u, 10.7, 11.1);
  set(poll, { x: 1130, y: 360, z: lerp(-300, 110, pIn), ry: -12, o: pIn * (1 - pOut), blur: (1 - pIn) * 10 + pOut * 8 });
  pollBars.forEach((b, i) => { const v = +b.dataset.v * eo(P(u, 9.8 + i * 0.05, 10.5 + i * 0.05)); b.style.width = `${v}%`; pollVals[i].textContent = `${Math.round(v)}%`; });
}

// ---------- S5: QR sign-in, works offline ----------
const r5 = roots[4];
const p5 = el('div', 'layer persp', r5);
const B5 = board(p5);
img('board-sign-in.jpg', B5.scr);
const scan = el('div', 'abs', B5.scr, null, { left: '52.3%', width: '12.9%', height: '6px', borderRadius: '4px', background: 'linear-gradient(90deg, rgba(0,200,120,0), #00d084, rgba(0,200,120,0))', boxShadow: '0 0 18px #00d084' });
const ok5 = el('div', 'pill', B5.scr, '✓&nbsp; Signed in · Room 204 Board', { left: '38%', top: '76%', background: '#0f9d58', boxShadow: '0 10px 30px rgba(15,157,88,.45)' });
const P5 = phone(p5);
img('teacher-navHome.jpg', P5.scr, { objectFit: 'cover' });
const off5 = el('div', 'pill', r5, `<svg width="28" height="28" viewBox="0 0 24 24" style="vertical-align:-6px;margin-right:12px" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round"><path d="M2 2l20 20M8.5 16.5a5 5 0 0 1 7 0M5 13a10 10 0 0 1 5.2-2.8M19 13a10 10 0 0 0-2.3-1.6M2 8.8a15 15 0 0 1 4.2-2.7M22 8.8A15 15 0 0 0 10.7 5"/><circle cx="12" cy="20" r="1" fill="#fff"/></svg>Works offline`, { left: '150px', top: '120px', fontSize: '34px', padding: '18px 34px', background: 'linear-gradient(180deg,#F5A524,#D9820B)', boxShadow: '0 16px 40px rgba(245,165,36,.45)' });
const k5 = el('div', 'abs kicker', r5, 'Sign in with a scan', { left: '0', right: '0', top: '60px', textAlign: 'center' });
function s5(u) {
  const z = eio(P(u, 0.2, 2.2));
  // zoom toward the QR code on the board
  set(B5.d, { x: 860 - 680 - z * 60, y: 560 - 420 + z * 10, z: lerp(-160, 190, z), ry: lerp(-10, 2, z), rx: 2, s: 0.86, o: 1 });
  const ph = eo5(P(u, 0.9, 2.0));
  set(P5.d, { x: lerp(1950, 1450, ph), y: 200, z: 120, ry: -14, rz: lerp(8, 4, ph), s: 0.9, o: ph });
  const sp = P(u, 2.0, 3.0);
  scan.style.top = `${41 + 21 * eio(sp)}%`;
  scan.style.opacity = sp > 0 && sp < 1 ? 1 : 0;
  set(ok5, { ...rv(P(u, 3.0, 3.5), 14, 6), s: lerp(0.8, 1, eo5(P(u, 3.0, 3.5))) });
  set(off5, { ...rv(P(u, 2.4, 3.0), 30, 12), s: lerp(0.7, 1, eo5(P(u, 2.4, 3.1))) });
  set(k5, rv(P(u, 0.2, 1.0)));
}

// ---------- S6: ERP ----------
const r6 = roots[5];
const p6 = el('div', 'layer persp', r6);
const L6 = laptop(p6);
const E6 = ['erp-dashboard.jpg', 'erp-admissions.jpg', 'erp-exams.jpg', 'erp-fees.jpg', 'erp-hr.jpg', 'erp-obe.jpg'].map((s) => img(s, L6.scr));
const N6 = ['Principal dashboard', 'Admissions', 'Exams · hall tickets', 'Fees', 'HR', 'OBE · CO–PO matrix'];
const lab6 = N6.map((n) => el('div', 'pill', r6, n, { left: '0', top: '0', fontSize: '26px' }));
const k6 = el('div', 'abs kicker', r6, 'Behind it', { left: 0, right: 0, top: '58px', textAlign: 'center' });
const t6 = el('div', 'abs title', r6, 'One AI-powered ERP', { left: 0, right: 0, top: '92px', textAlign: 'center', fontSize: '60px' });
const sh6 = shadowBlob(p6, 1300, 180);
const CUT6 = [0, 5.3, 7.0, 8.7, 9.9, 11.1];
function s6(u) {
  const inX = eo5(P(u, 0, 1.6));
  set(k6, rv(P(u, 0.2, 1.0)));
  set(t6, rv(P(u, 0.35, 1.2), 40, 16));
  set(L6.d, { x: 960 - 640, y: lerp(560, 205, inX), z: lerp(-500, -60, inX) + 40 * P(u, 1.6, 16), rx: lerp(28, 5, inX), ry: lerp(-14, 9, eio(P(u, 0, 16))), s: 0.9, o: inX });
  set(sh6, { x: 960 - 650, y: 900, o: inX * 0.7 });
  E6.forEach((im, i) => {
    const a = CUT6[i];
    const o = i === 0 ? 1 : eo(P(u, a - 0.12, a + 0.22));
    im.style.opacity = o;
    im.style.transform = `scale(${lerp(1.04, 1, eo(P(u, a - 0.12, a + 0.8))).toFixed(4)})`;
  });
  const cur = CUT6.reduce((k, a, i) => (u >= a - 0.1 ? i : k), 0);
  lab6.forEach((l, i) => {
    const x = P(u, CUT6[i] - 0.1, CUT6[i] + 0.35), out = i === cur ? 0 : 1;
    set(l, { x: 300, y: 248, o: i === cur ? eo(x) * inX : 0, blur: (1 - eo(x)) * 8, s: lerp(0.9, 1, eo(x)) });
  });
}

// ---------- S7: AI assistants ----------
const r7 = roots[6];
const p7 = el('div', 'layer persp', r7);
const L7 = laptop(p7);
img('erp-admissions.jpg', L7.scr);
const ans = '49 follow-ups are due. Start with the 16 new enquiries, then the 19 families in counselling.';
const ai7 = el('div', 'card', p7, `<div style="padding:26px 30px;width:620px">
<div style="display:flex;align-items:center;gap:12px;font-size:22px;font-weight:600;color:#1D4ED8"><span style="width:34px;height:34px;border-radius:10px;background:linear-gradient(150deg,#5B86FF,#1D4ED8);display:grid;place-items:center;color:#fff;font-size:20px">✦</span>Ask KINETIX AI</div>
<div style="margin:16px 0 0 auto;width:fit-content;max-width:460px;background:#1D4ED8;color:#fff;border-radius:18px 18px 4px 18px;padding:12px 18px;font-size:21px">Which enquiries need a call today?</div>
<div class="ans" style="margin-top:14px;background:#F1F4FC;border-radius:18px 18px 18px 4px;padding:14px 18px;font-size:21px;line-height:1.4;min-height:96px"></div>
<div style="margin-top:12px;font-size:16px;color:#8a5a00;background:#FFF4DC;border-radius:10px;padding:8px 12px">AI draft. Check it against the figures before you act on it.</div></div>`);
const ansEl = ai7.querySelector('.ans');
const mk7 = el('div', 'card', p7, `<div style="padding:26px 30px;width:600px">
<div style="display:flex;justify-content:space-between;align-items:center"><div style="font-size:22px;font-weight:600;color:#1D4ED8">Marking help (AI draft)</div><div style="font-size:17px;color:#5b6478">Script 0417 · Q3</div></div>
<div style="display:flex;align-items:baseline;gap:14px;margin:14px 0 8px"><div style="font-size:46px;font-weight:700">Draft: <span class="mk">7</span> of 10</div></div>
<div style="font-size:18px;color:#3b4252;line-height:1.5">✓ Defines goodwill correctly<br>✓ Uses the average-profit method<br><span style="color:#b45309">⚑ Calculation step skipped — check</span></div>
<div style="display:flex;gap:12px;margin-top:18px"><span class="acc" style="padding:12px 24px;border-radius:999px;background:#1D4ED8;color:#fff;font-weight:600;font-size:20px">Accept draft</span><span style="padding:12px 24px;border-radius:999px;border:1.5px solid #c9d2ea;font-weight:600;font-size:20px;color:#1D4ED8">Change</span><span style="padding:12px 24px;border-radius:999px;border:1.5px solid #c9d2ea;font-weight:600;font-size:20px;color:#1D4ED8">Reject</span></div>
<div class="done" style="margin-top:14px;font-size:18px;font-weight:600;color:#0f9d58;opacity:0">✓ Marks entered by you</div>
<div style="margin-top:8px;font-size:16px;color:#5b6478">This is only a draft. No marks are entered until you accept or change it.</div></div>`);
const acc = mk7.querySelector('.acc'), done7 = mk7.querySelector('.done');
const CH7 = ['Draft', 'Check', 'Flag'].map((c) => el('div', 'pill', r7, c, { fontSize: '26px', padding: '12px 28px', background: 'rgba(29,78,216,.25)', boxShadow: 'none', border: '1.5px solid rgba(140,170,255,.4)' }));
const k7 = el('div', 'abs kicker', r7, 'People stay in control', { left: '130px', top: '96px' });
function s7(u) {
  const inX = eo5(P(u, 0, 1.2));
  set(L7.d, { x: 690 - 640, y: 250, z: lerp(-400, -260, inX), ry: lerp(30, 18, eo(P(u, 0, 8))), rx: 3, s: 0.8, o: inX });
  const a = eo5(P(u, 0.4, 1.3));
  set(ai7, { x: 1150, y: 110, z: lerp(-200, 60, a), ry: -8, o: a, blur: (1 - a) * 10 });
  const n = Math.floor(ans.length * P(u, 1.0, 3.0));
  ansEl.textContent = ans.slice(0, n);
  const b = eo5(P(u, 1.6, 2.5));
  set(mk7, { x: 1220, y: 505, z: lerp(-200, 120, b), ry: -8, o: b, blur: (1 - b) * 10 });
  CH7.forEach((c, i) => {
    const x = P(u, 0.9 + i * 0.5, 1.4 + i * 0.5);
    const lit = u > 0.9 + i * 0.5 && u < 3.0 ? 1 : 0.5;
    set(c, { x: 130 + i * 170, y: 140, ...{ o: eo(x) * (lit === 1 ? 1 : 0.7) }, s: lerp(0.8, 1, eo5(x)) });
    c.style.background = lit === 1 ? 'rgba(29,78,216,.85)' : 'rgba(29,78,216,.25)';
  });
  set(k7, rv(P(u, 3.0, 3.8), 20, 10));
  const press = P(u, 4.2, 4.6);
  acc.style.transform = `scale(${(1 - Math.sin(press * Math.PI) * 0.08).toFixed(3)})`;
  acc.style.boxShadow = press > 0 ? `0 0 0 ${(press * 14).toFixed(1)}px rgba(29,78,216,${(0.35 * (1 - press)).toFixed(2)})` : 'none';
  done7.style.opacity = eo(P(u, 4.6, 5.0)).toFixed(3);
}

// ---------- S8: three phones ----------
const r8 = roots[7];
const p8 = el('div', 'layer persp', r8);
const PH = [['teacher-navHome.jpg', 'teacher-navClasses.jpg', 'Teacher'], ['student-navHome.jpg', 'student-navLearn.jpg', 'Student'], ['parent-navHome.jpg', 'parent-navFees.jpg', 'Parent']].map(([a, b, n]) => {
  const p = phone(p8);
  const i1 = img(a, p.scr, { objectFit: 'cover' });
  const i2 = img(b, p.scr, { objectFit: 'cover', opacity: 0 });
  const lab = el('div', 'label', r8, n, { width: '336px' });
  return { ...p, i1, i2, lab };
});
const sh8 = shadowBlob(p8, 1500, 160);
const HL = [[2.3, 5.7], [5.7, 8.6], [8.6, 99]];
function s8(u) {
  const fan = eo5(P(u, 0.1, 1.6));
  PH.forEach((p, i) => {
    const k = i - 1;
    const [a, b] = HL[i];
    const hl = u > 2 ? clamp(Math.min(eo(P(u, a - 0.2, a + 0.4)), 1 - eo(P(u, b - 0.2, b + 0.3)))) : 0;
    const any = u > 2.1 ? 1 : 0;
    const x = 960 - 168 + k * lerp(40, 440, fan);
    set(p.d, { x, y: 120 + Math.sin(u * 0.8 + i) * 6 - hl * 14, z: lerp(-400, 0, fan) + hl * 90 - (any && !hl ? 40 : 0), ry: -k * lerp(0, 16, fan) * (1 - hl * 0.7), rz: k * lerp(0, 3, fan) * (1 - hl), s: 0.95, o: eo(P(u, 0, 0.6 + i * 0.1)) * (any ? lerp(0.55, 1, hl) : 1) });
    p.i2.style.opacity = eo(P(u, a + 0.5, a + 0.9)).toFixed(3);
    set(p.lab, { x: x, y: 860, o: eo(P(u, 1.0, 1.6)) * (any ? lerp(0.5, 1, hl) : 1) });
    p.lab.style.color = hl > 0.5 ? '#fff' : '#9fb0e0';
  });
  set(sh8, { x: 960 - 750, y: 790, o: fan * 0.7 });
}

// ---------- S9: network ----------
const r9 = roots[8];
const NODES = [['Smartboard', 'board-board.jpg', 430, 300], ['ERP', 'erp-dashboard.jpg', 1490, 300], ['Teacher app', 'teacher-navHome.jpg', 300, 660], ['Student app', 'student-navHome.jpg', 960, 770], ['Parent app', 'parent-navHome.jpg', 1620, 660]];
const svg9 = el('div', 'layer', r9, `<svg width="1920" height="1080" style="position:absolute;inset:0"><defs><linearGradient id="ln" x1="0" x2="1"><stop offset="0" stop-color="#7FA2FF"/><stop offset="1" stop-color="#38BDF8"/></linearGradient></defs>
${NODES.map(([, , x, y], i) => `<line class="ln" x1="960" y1="520" x2="${x}" y2="${y}" stroke="url(#ln)" stroke-width="3" stroke-linecap="round" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" style="filter:drop-shadow(0 0 6px #5B86FF)"/>`).join('')}
${NODES.map((n, i) => [0, 1, 2].map((j) => `<circle class="pd" data-i="${i}" data-j="${j}" r="6" fill="#fff" style="filter:drop-shadow(0 0 8px #7FA2FF)"/>`).join('')).join('')}
</svg>`);
const lines9 = [...svg9.querySelectorAll('.ln')], dots9 = [...svg9.querySelectorAll('.pd')];
const core = el('div', 'abs', r9, `<div style="width:210px;height:210px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle,#1a2a7a,#0b1238 70%);border:2px solid rgba(140,170,255,.5);box-shadow:0 0 80px rgba(60,100,255,.6),0 0 0 14px rgba(91,134,255,.08)">${LOGO(110)}</div>`, { left: '855px', top: '415px' });
const ring = el('div', 'abs', r9, null, { left: '960px', top: '520px', width: '210px', height: '210px', marginLeft: '-105px', marginTop: '-105px', borderRadius: '50%', border: '2px solid rgba(127,162,255,.6)' });
const nodes9 = NODES.map(([n, im, x, y]) => {
  const d = el('div', 'node', r9, `<div class="th"><img src="${SH + im}"></div><div class="nm"><b></b>${n}</div>`, { left: `${x - 150}px`, top: `${y - 118}px` });
  return d;
});
const t9 = el('div', 'abs title', r9, 'One source of truth.', { left: 0, right: 0, top: '40px', textAlign: 'center', fontSize: '60px' });
function s9(u) {
  set(core, { s: lerp(0.4, 1, eo5(P(u, 0, 0.9))), o: eo(P(u, 0, 0.6)) });
  const rp = (u % 1.8) / 1.8;
  set(ring, { s: 1 + rp * 0.9, o: (1 - rp) * 0.7 * P(u, 0.5, 1) });
  lines9.forEach((l, i) => l.setAttribute('stroke-dashoffset', (1 - eio(P(u, 0.3 + i * 0.12, 1.3 + i * 0.12))).toFixed(3)));
  nodes9.forEach((n, i) => set(n, { ...rv(P(u, 0.7 + i * 0.12, 1.5 + i * 0.12), 30, 12), s: lerp(0.85, 1, eo5(P(u, 0.7 + i * 0.12, 1.5 + i * 0.12))) }));
  dots9.forEach((d) => {
    const i = +d.dataset.i, j = +d.dataset.j;
    const [, , x, y] = NODES[i];
    let ph = ((u * 0.55 + j / 3 + i * 0.13) % 1);
    if ((i + j) % 2) ph = 1 - ph; // both directions: in sync
    const on = P(u, 1.5 + i * 0.12, 1.9 + i * 0.12);
    d.setAttribute('cx', lerp(960, x, ph).toFixed(1));
    d.setAttribute('cy', lerp(520, y, ph).toFixed(1));
    d.setAttribute('opacity', (on * Math.sin(ph * Math.PI)).toFixed(3));
  });
  set(t9, rv(P(u, 1.6, 2.4), 30, 14));
}

// ---------- S10: badges ----------
const r10 = roots[9];
const IC = {
  lang: '<svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h9M8.5 3v2M6 5c0 4 3 7 6 8M11 5c0 3-3 7-7 9M13 21l4-10 4 10M14.5 18h5"/></svg>',
  shield: '<svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/><path d="M8.5 12l2.5 2.5 4.5-5"/></svg>',
  off: '<svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round"><path d="M2 2l20 20M8.5 16.5a5 5 0 0 1 7 0M5 13a10 10 0 0 1 5.2-2.8M19 13a10 10 0 0 0-2.3-1.6M2 8.8a15 15 0 0 1 4.2-2.7M22 8.8A15 15 0 0 0 10.7 5"/><circle cx="12" cy="20" r="1" fill="#fff"/></svg>',
  cap: '<svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11v5c3 2 9 2 12 0v-5M22 9v6"/></svg>',
};
const BADGES = [
  ['lang', 'English · <span style="font-family:Deva">हिंदी</span> · <span style="font-family:Knda">ಕನ್ನಡ</span>', 'Every screen in three languages', 0.3],
  ['shield', 'Privacy-first · DPDP-ready', 'Consent and data rights built in', 3.1],
  ['off', 'Works offline', 'Boards and apps keep going without internet', 4.0],
  ['cap', 'Schools · Colleges · Universities', 'One platform for every campus', 4.9],
];
const b10 = BADGES.map(([ic, tx, sub], i) => el('div', 'badge', r10, `<div class="ic">${IC[ic]}</div><div><div class="tx">${tx}</div><div class="sub">${sub}</div></div>`, { left: `${i % 2 ? 980 : 100}px`, top: `${i < 2 ? 300 : 520}px`, width: '840px', padding: '0 36px', gap: '28px' }));
const k10 = el('div', 'abs kicker', r10, 'Built for India’s campuses', { left: 0, right: 0, top: '200px', textAlign: 'center' });
function s10(u) {
  set(k10, rv(P(u, 0.1, 0.9)));
  b10.forEach((b, i) => {
    const x = P(u, BADGES[i][3], BADGES[i][3] + 0.8);
    set(b, { ...rv(x, 50, 16), s: lerp(0.88, 1, eo5(x)) + Math.sin(u * 0.6 + i) * 0.004 });
  });
}

// ---------- S11: end card ----------
const r11 = roots[10];
const g11 = el('div', 'glow', r11, null, { width: '1200px', height: '900px', left: '360px', top: '40px', background: 'radial-gradient(closest-side, rgba(60,100,255,.35), rgba(0,0,0,0))' });
const lg11 = el('div', 'abs', r11, LOGO(150), { left: '885px', top: '170px', width: '150px', height: '150px', filter: 'drop-shadow(0 20px 50px rgba(29,78,216,.7))' });
const wm11 = el('div', 'abs title', r11, 'KINETIX', { left: 0, right: 0, top: '340px', textAlign: 'center', fontSize: '150px', letterSpacing: '0.06em', backgroundImage: 'linear-gradient(180deg,#fff 30%,#AFC4FF)', webkitBackgroundClip: 'text', color: 'transparent' });
const tg11 = el('div', 'abs', r11, 'The AI operating system for education.', { left: 0, right: 0, top: '540px', textAlign: 'center', fontSize: '46px', fontWeight: 500, color: '#C7D5FF' });
const bt11 = el('div', 'abs', r11, '<span class="btn">Book a demo&nbsp;&nbsp;→</span>', { left: 0, right: 0, top: '650px', textAlign: 'center' });
const ft11 = el('div', 'abs', r11, 'www.kinetix.example &nbsp;·&nbsp; hello@kinetix.example', { left: 0, right: 0, top: '820px', textAlign: 'center', fontSize: '30px', fontWeight: 500, color: '#9FB3FF', letterSpacing: '.01em' });
function s11(u) {
  set(lg11, { ...rv(P(u, 0, 0.9), 30, 16), s: lerp(0.6, 1, eo5(P(u, 0, 1))) });
  set(wm11, { ...rv(P(u, 0.25, 1.2), 40, 18) });
  wm11.style.letterSpacing = `${lerp(0.2, 0.06, eo(P(u, 0.25, 1.6)))}em`;
  set(tg11, rv(P(u, 0.7, 1.5), 30, 12));
  set(bt11, { ...rv(P(u, 1.2, 2.0), 30, 12), s: 1 + Math.sin(Math.max(0, u - 2.4) * 2.2) * 0.012 * P(u, 2.4, 3) });
  set(ft11, rv(P(u, 1.6, 2.4), 20, 8));
  set(g11, { o: 0.7 + 0.3 * Math.sin(u * 0.8), s: 1 });
}

const UPD = [null, null, s3, s4, s5, s6, s7, s8, s9, s10, s11];

// ---------- captions ----------
function captions(t) {
  const c = TL.captions.find((c) => t >= c.t0 - 0.05 && t < c.t1 + 0.1);
  if (!c) { CAP.style.opacity = 0; return; }
  if (CAP.textContent !== c.text) CAP.textContent = c.text;
  CAP.style.opacity = Math.min(P(t, c.t0 - 0.05, c.t0 + 0.12), 1 - P(t, c.t1 - 0.02, c.t1 + 0.1)).toFixed(3);
}

window.renderAt = (t) => {
  bgAt(t);
  words(t);
  logo(t);
  sc.forEach((s, i) => { const o = sceneFade(i, t); if (o > 0 && UPD[i]) UPD[i](t - s.start, t); });
  captions(t);
  const fin = P(t, TL.duration - 0.6, TL.duration);
  S.style.opacity = (1 - fin * 0.85).toFixed(3);
};
window.ready = Promise.all([document.fonts.ready, ...[...document.images].map((i) => (i.complete ? 1 : new Promise((r) => { i.onload = i.onerror = r; })))]);
const q = new URLSearchParams(location.search).get('t');
window.ready.then(() => window.renderAt(q ? +q : 0));
})();
