// Writes lib/src/viewer/catalogue_data.dart from assets/viewer3d/models/index.json, so
// the app knows every viewer model (id, titles, subject, classes, keywords) without
// reading assets first. build_models.mjs runs it after writing the index; run it alone
// with `node write_catalogue.mjs`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const models = join(here, '../../assets/viewer3d/models');
const out = join(here, '../../lib/src/viewer/catalogue_data.dart');

const str = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;
const text = (t) => `LocalText({${['en', 'hi', 'kn'].map((l) => `'${l}': ${str(t?.[l] ?? '')}`).join(', ')}})`;

export function writeCatalogue() {
  const { models: list } = JSON.parse(readFileSync(join(models, 'index.json'), 'utf8'));
  const entries = list.map((m) => {
    const manifest = JSON.parse(readFileSync(join(models, `${m.id}.json`), 'utf8'));
    return `  ViewerModelInfo(
    id: ${str(m.id)},
    subject: ${str(m.subject)},
    title: ${text(m.title)},
    summary: ${text(m.summary)},
    classes: [${(m.classes || []).join(', ')}],
    keywords: [${(m.keywords || []).map(str).join(', ')}],
    variants: [${(manifest.variants || []).map((v) => str(v.id)).join(', ')}],
    credit: ${str(manifest.credit || '')},
  ),`;
  });
  writeFileSync(
    out,
    `// Generated by tool/models/write_catalogue.mjs from assets/viewer3d/models/index.json.
// Do not edit by hand: change the recipe and rebuild the models.
part of 'catalogue_info.dart';

const _viewerModels = <ViewerModelInfo>[
${entries.join('\n')}
];
`,
  );
  console.log(`catalogue: ${list.length} models -> lib/src/viewer/catalogue_data.dart`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) writeCatalogue();
