import 'package:flutter/widgets.dart';

import '../../l10n/feature_strings.dart';

FeatureStrings plusStrings(BuildContext context) => FeatureStrings(boardLang(context), plusStringTable);

/// The words of the board's classroom additions (lib/features/classroom_plus): multi-user zones,
/// the buzzer, break reminders, voice commands, device diagnostics and the recording notice.
const plusStringTable = <String, Map<String, String>>{
  'en': {
    'zones': 'Multi-user zones',
    'zonesHint': 'Split the board so groups can write at the same time, each with its own pen.',
    'zone': 'Zone {n}',
    'zoneClear': 'Clear this zone',
    'zoneEraser': 'Eraser',
    'zonesEnd': 'End zones',
    'zonesCount': '{n} zones',
    'buzzer': 'Buzzer',
    'buzzerHint': 'The first team to press buzzes in. The others are locked until the next question.',
    'buzzerTeams': 'Teams',
    'buzzerFirst': '{n} buzzed first!',
    'buzzerWaiting': 'Waiting for a team to buzz',
    'buzzerReset': 'Next question',
    'team': 'Team {n}',
    'breakReminders': 'Break reminders (20-20-20)',
    'breakRemindersHint': 'After 20 minutes of continuous use, a reminder to look at something 20 feet away for 20 seconds.',
    'breakTitle': 'Time for an eye break',
    'breakBody': 'Look at something 20 feet (6 m) away for 20 seconds.',
    'breakLeft': '{n} s',
    'breakDone': 'Done',
    'breakLater': 'Later',
    'voiceCommands': 'Voice commands',
    'voiceListening': 'Listening… say a command',
    'voiceExamples': 'Try: "next page", "previous page", "new page", "start a 5 minute timer", "stop the timer", "pick a student", "take attendance", "undo", "next slide".',
    'voiceDone': 'Done: {n}',
    'voiceUnknown': 'Not a command: "{n}"',
    'voiceUnavailable': 'Speech recognition is not available on this board.',
    'voiceStop': 'Stop',
    'cmdNextPage': 'Next page',
    'cmdPreviousPage': 'Previous page',
    'cmdNewPage': 'New page',
    'cmdNextSlide': 'Next slide',
    'cmdPreviousSlide': 'Previous slide',
    'cmdTimer': 'Timer for {n} minutes',
    'cmdStopTimer': 'Stop the timer',
    'cmdPick': 'Pick a student',
    'cmdAttendance': 'Attendance',
    'cmdUndo': 'Undo',
    'cmdRedo': 'Redo',
    'voiceGuideTitle': 'Say any of these',
    'guideNextPage': '"Next page", "Previous page"',
    'guideNewPage': '"New page"',
    'guideSlide': '"Next slide", "Previous slide"',
    'guideTimer': '"Start a 5 minute timer"',
    'guideStopTimer': '"Stop the timer"',
    'guidePick': '"Pick a student"',
    'guideAttendance': '"Take attendance"',
    'guideUndo': '"Undo", "Redo"',
    'guidePenColor': '"Red pen", "Blue colour" (red, blue, green, black, white, yellow, orange, purple, pink)',
    'guidePen': '"Use the pen", "Highlighter"',
    'guideEraser': '"Eraser"',
    'guideOpen': '"Open calculator" (dictionary, key dates, seating, exit ticket, organiser, captions, reader, ruler, protractor, quiz...)',
    'guideStop': '"Stop listening"',
    'cmdPenColor': 'Pen colour: {n}',
    'cmdPen': 'Pen',
    'cmdEraser': 'Eraser',
    'cmdHighlighter': 'Highlighter',
    'cmdOpen': 'Opened: {n}',
    'cmdStopListening': 'Stopped listening',
    'diagnostics': 'Device diagnostics',
    'dgApp': 'App version',
    'dgServer': 'Server',
    'dgNotEnrolled': 'Not enrolled',
    'dgDevice': 'Board name',
    'dgConnection': 'Connection',
    'dgOnline': 'Online',
    'dgOffline': 'Offline (changes are kept and sent later)',
    'dgPending': 'Changes waiting to send',
    'dgStorage': 'Storage free',
    'dgBattery': 'Battery',
    'dgNoBattery': 'No battery (mains power)',
    'dgSystem': 'System',
    'dgScreen': 'Screen',
    'dgCheck': 'Check server',
    'dgChecking': 'Checking…',
    'dgReachable': 'Server answered in {n} ms',
    'dgUnreachable': 'The server did not answer',
    'dgUnknown': 'Unknown',
    'dgCopy': 'Copy report',
    'dgCopied': 'Report copied',
    'recNoticeTitle': 'Recording this lesson',
    'recNoticeBody': 'The board, the pages you open and your microphone will be recorded. When you share the recording, the students of this class and their parents can watch it. Let the class know before you start.',
    'recNoticeStart': 'Start recording',
    'recNotAllowed': 'Your institution has turned off lesson recording on this board.',
    'recImportant': 'Important moment',
    'recImportantHint': 'hold to mark an important moment',
    'cancel': 'Cancel',
    'close': 'Close',
  },
  'hi': {
    'zones': 'बहु-उपयोगकर्ता क्षेत्र',
    'zonesHint': 'बोर्ड को बाँटें ताकि समूह एक साथ लिख सकें, हर एक अपने पेन से।',
    'zone': 'क्षेत्र {n}',
    'zoneClear': 'यह क्षेत्र साफ़ करें',
    'zoneEraser': 'रबर',
    'zonesEnd': 'क्षेत्र बंद करें',
    'zonesCount': '{n} क्षेत्र',
    'buzzer': 'बज़र',
    'buzzerHint': 'जो टीम सबसे पहले दबाए, वह जीतती है। बाकी अगले प्रश्न तक रुकी रहती हैं।',
    'buzzerTeams': 'टीमें',
    'buzzerFirst': '{n} ने सबसे पहले बज़र दबाया!',
    'buzzerWaiting': 'किसी टीम के बज़र दबाने की प्रतीक्षा',
    'buzzerReset': 'अगला प्रश्न',
    'team': 'टीम {n}',
    'breakReminders': 'विराम याद दिलाना (२०-२०-२०)',
    'breakRemindersHint': 'लगातार २० मिनट उपयोग के बाद, २० सेकंड तक २० फ़ुट दूर किसी चीज़ को देखने की याद।',
    'breakTitle': 'आँखों को आराम देने का समय',
    'breakBody': '२० सेकंड तक २० फ़ुट (६ मीटर) दूर किसी चीज़ को देखें।',
    'breakLeft': '{n} सेकंड',
    'breakDone': 'हो गया',
    'breakLater': 'बाद में',
    'voiceCommands': 'आवाज़ से आदेश',
    'voiceListening': 'सुन रहा है… कोई आदेश बोलें',
    'voiceExamples': 'बोलकर देखें: "अगला पेज", "पिछला पेज", "नया पेज", "पाँच मिनट का टाइमर", "टाइमर रोको", "कोई विद्यार्थी चुनो", "हाज़िरी लो", "पूर्ववत करो", "अगली स्लाइड"।',
    'voiceDone': 'हो गया: {n}',
    'voiceUnknown': 'यह आदेश नहीं है: "{n}"',
    'voiceUnavailable': 'इस बोर्ड पर आवाज़ पहचान उपलब्ध नहीं है।',
    'voiceStop': 'रोकें',
    'cmdNextPage': 'अगला पेज',
    'cmdPreviousPage': 'पिछला पेज',
    'cmdNewPage': 'नया पेज',
    'cmdNextSlide': 'अगली स्लाइड',
    'cmdPreviousSlide': 'पिछली स्लाइड',
    'cmdTimer': '{n} मिनट का टाइमर',
    'cmdStopTimer': 'टाइमर रोकें',
    'cmdPick': 'विद्यार्थी चुनें',
    'cmdAttendance': 'हाज़िरी',
    'cmdUndo': 'पूर्ववत करें',
    'cmdRedo': 'फिर से करें',
    'voiceGuideTitle': 'इनमें से कुछ भी बोलें',
    'guideNextPage': '"अगला पेज", "पिछला पेज"',
    'guideNewPage': '"नया पेज"',
    'guideSlide': '"अगली स्लाइड", "पिछली स्लाइड"',
    'guideTimer': '"पाँच मिनट का टाइमर"',
    'guideStopTimer': '"टाइमर रोको"',
    'guidePick': '"कोई विद्यार्थी चुनो"',
    'guideAttendance': '"हाज़िरी लो"',
    'guideUndo': '"पूर्ववत करो", "फिर से करो"',
    'guidePenColor': '"लाल पेन", "नीला रंग" (लाल, नीला, हरा, काला, सफेद, पीला, नारंगी, बैंगनी, गुलाबी)',
    'guidePen': '"पेन चुनो", "हाइलाइटर"',
    'guideEraser': '"रबर"',
    'guideOpen': '"कैलकुलेटर खोलो" (शब्दकोश, समयरेखा, बैठने की योजना, एग्ज़िट टिकट, कैप्शन, रीडर, रूलर, चाँदा, क्विज़...)',
    'guideStop': '"सुनना बंद करो"',
    'cmdPenColor': 'पेन का रंग: {n}',
    'cmdPen': 'पेन',
    'cmdEraser': 'रबर',
    'cmdHighlighter': 'हाइलाइटर',
    'cmdOpen': 'खोला: {n}',
    'cmdStopListening': 'सुनना बंद',
    'diagnostics': 'डिवाइस जाँच',
    'dgApp': 'ऐप संस्करण',
    'dgServer': 'सर्वर',
    'dgNotEnrolled': 'पंजीकृत नहीं',
    'dgDevice': 'बोर्ड का नाम',
    'dgConnection': 'कनेक्शन',
    'dgOnline': 'ऑनलाइन',
    'dgOffline': 'ऑफ़लाइन (बदलाव रखे गए हैं और बाद में भेजे जाएँगे)',
    'dgPending': 'भेजे जाने वाले बदलाव',
    'dgStorage': 'खाली स्टोरेज',
    'dgBattery': 'बैटरी',
    'dgNoBattery': 'बैटरी नहीं (बिजली से चलता है)',
    'dgSystem': 'सिस्टम',
    'dgScreen': 'स्क्रीन',
    'dgCheck': 'सर्वर जाँचें',
    'dgChecking': 'जाँच हो रही है…',
    'dgReachable': 'सर्वर ने {n} मिलीसेकंड में उत्तर दिया',
    'dgUnreachable': 'सर्वर ने उत्तर नहीं दिया',
    'dgUnknown': 'अज्ञात',
    'dgCopy': 'रिपोर्ट कॉपी करें',
    'dgCopied': 'रिपोर्ट कॉपी हो गई',
    'recNoticeTitle': 'इस पाठ की रिकॉर्डिंग',
    'recNoticeBody': 'बोर्ड, आपके खोले गए पेज और आपका माइक्रोफ़ोन रिकॉर्ड होंगे। रिकॉर्डिंग साझा करने पर इस कक्षा के विद्यार्थी और उनके अभिभावक इसे देख सकते हैं। शुरू करने से पहले कक्षा को बता दें।',
    'recNoticeStart': 'रिकॉर्डिंग शुरू करें',
    'recNotAllowed': 'आपके संस्थान ने इस बोर्ड पर पाठ रिकॉर्डिंग बंद कर दी है।',
    'recImportant': 'महत्वपूर्ण क्षण',
    'recImportantHint': 'महत्वपूर्ण क्षण चिह्नित करने के लिए दबाकर रखें',
    'cancel': 'रद्द करें',
    'close': 'बंद करें',
  },
  'kn': {
    'zones': 'ಬಹು-ಬಳಕೆದಾರ ವಲಯಗಳು',
    'zonesHint': 'ಗುಂಪುಗಳು ಒಂದೇ ಸಮಯದಲ್ಲಿ ಬರೆಯಲು ಬೋರ್ಡ್ ಅನ್ನು ವಿಭಜಿಸಿ, ಪ್ರತಿಯೊಂದಕ್ಕೂ ತನ್ನದೇ ಪೆನ್.',
    'zone': 'ವಲಯ {n}',
    'zoneClear': 'ಈ ವಲಯವನ್ನು ಅಳಿಸಿ',
    'zoneEraser': 'ಅಳಿಸುವಿಕೆ',
    'zonesEnd': 'ವಲಯಗಳನ್ನು ಮುಗಿಸಿ',
    'zonesCount': '{n} ವಲಯಗಳು',
    'buzzer': 'ಬಜರ್',
    'buzzerHint': 'ಮೊದಲು ಒತ್ತಿದ ತಂಡ ಗೆಲ್ಲುತ್ತದೆ. ಉಳಿದವು ಮುಂದಿನ ಪ್ರಶ್ನೆಯವರೆಗೆ ನಿಲ್ಲುತ್ತವೆ.',
    'buzzerTeams': 'ತಂಡಗಳು',
    'buzzerFirst': '{n} ಮೊದಲು ಬಜರ್ ಒತ್ತಿತು!',
    'buzzerWaiting': 'ಯಾವುದಾದರೂ ತಂಡ ಬಜರ್ ಒತ್ತಲು ಕಾಯುತ್ತಿದೆ',
    'buzzerReset': 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
    'team': 'ತಂಡ {n}',
    'breakReminders': 'ವಿರಾಮದ ಜ್ಞಾಪನೆ (೨೦-೨೦-೨೦)',
    'breakRemindersHint': 'ನಿರಂತರ ೨೦ ನಿಮಿಷ ಬಳಕೆಯ ನಂತರ, ೨೦ ಸೆಕೆಂಡು ೨೦ ಅಡಿ ದೂರದ ವಸ್ತುವನ್ನು ನೋಡಲು ಜ್ಞಾಪನೆ.',
    'breakTitle': 'ಕಣ್ಣಿಗೆ ವಿರಾಮದ ಸಮಯ',
    'breakBody': '೨೦ ಸೆಕೆಂಡು ೨೦ ಅಡಿ (೬ ಮೀ) ದೂರದ ವಸ್ತುವನ್ನು ನೋಡಿ.',
    'breakLeft': '{n} ಸೆ',
    'breakDone': 'ಆಯಿತು',
    'breakLater': 'ನಂತರ',
    'voiceCommands': 'ಧ್ವನಿ ಆಜ್ಞೆಗಳು',
    'voiceListening': 'ಕೇಳುತ್ತಿದೆ… ಒಂದು ಆಜ್ಞೆ ಹೇಳಿ',
    'voiceExamples': 'ಹೇಳಿ ನೋಡಿ: "ಮುಂದಿನ ಪುಟ", "ಹಿಂದಿನ ಪುಟ", "ಹೊಸ ಪುಟ", "ಐದು ನಿಮಿಷದ ಟೈಮರ್", "ಟೈಮರ್ ನಿಲ್ಲಿಸಿ", "ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಆರಿಸಿ", "ಹಾಜರಾತಿ", "ರದ್ದುಮಾಡಿ", "ಮುಂದಿನ ಸ್ಲೈಡ್".',
    'voiceDone': 'ಆಯಿತು: {n}',
    'voiceUnknown': 'ಇದು ಆಜ್ಞೆಯಲ್ಲ: "{n}"',
    'voiceUnavailable': 'ಈ ಬೋರ್ಡ್‌ನಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ.',
    'voiceStop': 'ನಿಲ್ಲಿಸಿ',
    'cmdNextPage': 'ಮುಂದಿನ ಪುಟ',
    'cmdPreviousPage': 'ಹಿಂದಿನ ಪುಟ',
    'cmdNewPage': 'ಹೊಸ ಪುಟ',
    'cmdNextSlide': 'ಮುಂದಿನ ಸ್ಲೈಡ್',
    'cmdPreviousSlide': 'ಹಿಂದಿನ ಸ್ಲೈಡ್',
    'cmdTimer': '{n} ನಿಮಿಷದ ಟೈಮರ್',
    'cmdStopTimer': 'ಟೈಮರ್ ನಿಲ್ಲಿಸಿ',
    'cmdPick': 'ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಆರಿಸಿ',
    'cmdAttendance': 'ಹಾಜರಾತಿ',
    'cmdUndo': 'ರದ್ದುಮಾಡಿ',
    'cmdRedo': 'ಮತ್ತೆ ಮಾಡಿ',
    'voiceGuideTitle': 'ಇವುಗಳಲ್ಲಿ ಯಾವುದನ್ನಾದರೂ ಹೇಳಿ',
    'guideNextPage': '"ಮುಂದಿನ ಪುಟ", "ಹಿಂದಿನ ಪುಟ"',
    'guideNewPage': '"ಹೊಸ ಪುಟ"',
    'guideSlide': '"ಮುಂದಿನ ಸ್ಲೈಡ್", "ಹಿಂದಿನ ಸ್ಲೈಡ್"',
    'guideTimer': '"ಐದು ನಿಮಿಷದ ಟೈಮರ್"',
    'guideStopTimer': '"ಟೈಮರ್ ನಿಲ್ಲಿಸಿ"',
    'guidePick': '"ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಆರಿಸಿ"',
    'guideAttendance': '"ಹಾಜರಾತಿ"',
    'guideUndo': '"ರದ್ದುಮಾಡಿ", "ಮತ್ತೆ ಮಾಡಿ"',
    'guidePenColor': '"ಕೆಂಪು ಪೆನ್", "ನೀಲಿ ಬಣ್ಣ" (ಕೆಂಪು, ನೀಲಿ, ಹಸಿರು, ಕಪ್ಪು, ಬಿಳಿ, ಹಳದಿ, ಕಿತ್ತಳೆ, ನೇರಳೆ, ಗುಲಾಬಿ)',
    'guidePen': '"ಪೆನ್ ಬಳಸಿ", "ಹೈಲೈಟರ್"',
    'guideEraser': '"ಅಳಿಸು"',
    'guideOpen': '"ಕ್ಯಾಲ್ಕುಲೇಟರ್ ತೆರೆ" (ನಿಘಂಟು, ಕಾಲರೇಖೆ, ಆಸನ, ಎಕ್ಸಿಟ್ ಟಿಕೆಟ್, ಶೀರ್ಷಿಕೆ, ರೀಡರ್, ರೂಲರ್, ರಸಪ್ರಶ್ನೆ...)',
    'guideStop': '"ಕೇಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ"',
    'cmdPenColor': 'ಪೆನ್ ಬಣ್ಣ: {n}',
    'cmdPen': 'ಪೆನ್',
    'cmdEraser': 'ಅಳಿಸು',
    'cmdHighlighter': 'ಹೈಲೈಟರ್',
    'cmdOpen': 'ತೆರೆಯಿತು: {n}',
    'cmdStopListening': 'ಆಲಿಸುವುದು ನಿಂತಿತು',
    'diagnostics': 'ಸಾಧನ ಪರಿಶೀಲನೆ',
    'dgApp': 'ಆ್ಯಪ್ ಆವೃತ್ತಿ',
    'dgServer': 'ಸರ್ವರ್',
    'dgNotEnrolled': 'ನೋಂದಾಯಿಸಿಲ್ಲ',
    'dgDevice': 'ಬೋರ್ಡ್ ಹೆಸರು',
    'dgConnection': 'ಸಂಪರ್ಕ',
    'dgOnline': 'ಆನ್‌ಲೈನ್',
    'dgOffline': 'ಆಫ್‌ಲೈನ್ (ಬದಲಾವಣೆಗಳನ್ನು ಇರಿಸಿ ನಂತರ ಕಳುಹಿಸಲಾಗುತ್ತದೆ)',
    'dgPending': 'ಕಳುಹಿಸಲು ಕಾಯುತ್ತಿರುವ ಬದಲಾವಣೆಗಳು',
    'dgStorage': 'ಖಾಲಿ ಸಂಗ್ರಹಣೆ',
    'dgBattery': 'ಬ್ಯಾಟರಿ',
    'dgNoBattery': 'ಬ್ಯಾಟರಿ ಇಲ್ಲ (ವಿದ್ಯುತ್‌ನಿಂದ ಚಲಿಸುತ್ತದೆ)',
    'dgSystem': 'ಸಿಸ್ಟಮ್',
    'dgScreen': 'ಪರದೆ',
    'dgCheck': 'ಸರ್ವರ್ ಪರಿಶೀಲಿಸಿ',
    'dgChecking': 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
    'dgReachable': 'ಸರ್ವರ್ {n} ಮಿ.ಸೆ.ನಲ್ಲಿ ಉತ್ತರಿಸಿತು',
    'dgUnreachable': 'ಸರ್ವರ್ ಉತ್ತರಿಸಲಿಲ್ಲ',
    'dgUnknown': 'ತಿಳಿದಿಲ್ಲ',
    'dgCopy': 'ವರದಿ ನಕಲಿಸಿ',
    'dgCopied': 'ವರದಿ ನಕಲಾಯಿತು',
    'recNoticeTitle': 'ಈ ಪಾಠದ ರೆಕಾರ್ಡಿಂಗ್',
    'recNoticeBody': 'ಬೋರ್ಡ್, ನೀವು ತೆರೆಯುವ ಪುಟಗಳು ಮತ್ತು ನಿಮ್ಮ ಮೈಕ್ರೊಫೋನ್ ರೆಕಾರ್ಡ್ ಆಗುತ್ತವೆ. ರೆಕಾರ್ಡಿಂಗ್ ಹಂಚಿದಾಗ ಈ ತರಗತಿಯ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಅವರ ಪೋಷಕರು ನೋಡಬಹುದು. ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು ತರಗತಿಗೆ ತಿಳಿಸಿ.',
    'recNoticeStart': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    'recNotAllowed': 'ನಿಮ್ಮ ಸಂಸ್ಥೆ ಈ ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪಾಠ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಆಫ್ ಮಾಡಿದೆ.',
    'recImportant': 'ಮುಖ್ಯ ಕ್ಷಣ',
    'recImportantHint': 'ಮುಖ್ಯ ಕ್ಷಣ ಗುರುತಿಸಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'close': 'ಮುಚ್ಚಿ',
  },
};
