# Interface strings of the electronics benches. english: (hindi, kannada)
S = {
    'At the junction I1 + I2 − I3 is at most {a} mA (zero within the meter rounding): the current in equals the current out. Round loop 1 the voltages add to {v} V: the EMF equals the sum of the IR drops.': (
        'संधि पर I1 + I2 − I3 अधिकतम {a} mA है (मीटर की पूर्णांकन सीमा में शून्य): आने वाली धारा जाने वाली धारा के बराबर है। पाश 1 में वोल्टताओं का योग {v} V है: EMF, IR पातों के योग के बराबर है।',
        'ಸಂಧಿಯಲ್ಲಿ I1 + I2 − I3 ಗರಿಷ್ಠ {a} mA (ಮೀಟರ್ ಪೂರ್ಣಾಂಕದೊಳಗೆ ಶೂನ್ಯ): ಒಳಬರುವ ಪ್ರವಾಹ ಹೊರಹೋಗುವ ಪ್ರವಾಹಕ್ಕೆ ಸಮ. ಕುಣಿಕೆ 1 ರಲ್ಲಿ ವೋಲ್ಟೇಜ್‌ಗಳ ಮೊತ್ತ {v} V: EMF, IR ಇಳಿತಗಳ ಮೊತ್ತಕ್ಕೆ ಸಮ.'),
    'Beyond about ±13.5 V the output saturates at the supply rails.': ('लगभग ±13.5 V से आगे निर्गत आपूर्ति सीमाओं पर संतृप्त हो जाता है।', 'ಸುಮಾರು ±13.5 V ಆಚೆ ಹೊರಹರಿವು ಪೂರೈಕೆ ಮಿತಿಗಳಲ್ಲಿ ಸಂತೃಪ್ತವಾಗುತ್ತದೆ.'),
    'Bias': ('अभिनति', 'ಬಯಾಸ್'),
    'Capacitor': ('संधारित्र', 'ಧಾರಕ'),
    'Cell': ('सेल', 'ಕೋಶ'),
    'Characteristic': ('अभिलक्षण', 'ಲಕ್ಷಣ'),
    'Charging': ('आवेशन', 'ಆವೇಶ'),
    'Closed': ('बंद', 'ಮುಚ್ಚಿದ'),
    'Constantan': ('कॉन्सटैंटन', 'ಕಾನ್‌ಸ್ಟಂಟನ್'),
    'Current gain β = Ic ÷ Ib ≈ {b} in the active region (Vce above 1 V), where Ic hardly changes with Vce.': (
        'सक्रिय क्षेत्र (Vce 1 V से अधिक) में धारा लब्धि β = Ic ÷ Ib ≈ {b}, जहाँ Ic, Vce के साथ लगभग नहीं बदलता।',
        'ಸಕ್ರಿಯ ಪ್ರದೇಶದಲ್ಲಿ (Vce 1 V ಗಿಂತ ಹೆಚ್ಚು) ಪ್ರವಾಹ ಲಾಭ β = Ic ÷ Ib ≈ {b}; ಅಲ್ಲಿ Ic, Vce ಯೊಂದಿಗೆ ಬಹುತೇಕ ಬದಲಾಗುವುದಿಲ್ಲ.'),
    'Daniell cell': ('डेनियल सेल', 'ಡೇನಿಯಲ್ ಕೋಶ'),
    'Discharging': ('निरावेशन', 'ವಿಸರ್ಜನೆ'),
    'Duty cycle': ('कार्य चक्र', 'ಕಾರ್ಯ ಚಕ್ರ'),
    'Duty cycle (%)': ('कार्य चक्र (%)', 'ಕಾರ್ಯ ಚಕ್ರ (%)'),
    'E₁ ÷ E₂ = l₁ ÷ l₂ = {a} ÷ {b} = {r} (from the cells’ EMFs: 1.39).': ('E₁ ÷ E₂ = l₁ ÷ l₂ = {a} ÷ {b} = {r} (सेलों के EMF से: 1.39)।', 'E₁ ÷ E₂ = l₁ ÷ l₂ = {a} ÷ {b} = {r} (ಕೋಶಗಳ EMF ನಿಂದ: 1.39).'),
    'Filter (µF)': ('फ़िल्टर (µF)', 'ಫಿಲ್ಟರ್ (µF)'),
    'Find the null point for both cells.': ('दोनों सेलों के लिए शून्य बिंदु ज्ञात करें।', 'ಎರಡೂ ಕೋಶಗಳಿಗೆ ಶೂನ್ಯ ಬಿಂದು ಕಂಡುಹಿಡಿಯಿರಿ.'),
    'First find the null point with K₂ open (l₁).': ('पहले K₂ खुली रखकर शून्य बिंदु (l₁) ज्ञात करें।', 'ಮೊದಲು K₂ ತೆರೆದಿಟ್ಟು ಶೂನ್ಯ ಬಿಂದು (l₁) ಕಂಡುಹಿಡಿಯಿರಿ.'),
    'Forward': ('अग्र', 'ಮುಮ್ಮುಖ'),
    'Forward bias': ('अग्र अभिनति', 'ಮುಮ್ಮುಖ ಬಯಾಸ್'),
    'Frequency': ('आवृत्ति', 'ಆವರ್ತನ'),
    'From the straight line of ln(remaining voltage) against t, τ = {t} s. After one τ the capacitor has {what} 63 % of the way.': (
        'ln(शेष वोल्टता) और t की सीधी रेखा से τ = {t} s. एक τ के बाद संधारित्र 63 % तक {what} हो चुका है।',
        'ln(ಉಳಿದ ವೋಲ್ಟೇಜ್) ಮತ್ತು t ಸರಳರೇಖೆಯಿಂದ τ = {t} s. ಒಂದು τ ನಂತರ ಧಾರಕ 63 % ದಾರಿ {what}.'),
    'From two base currents, ΔIc ÷ ΔIb ≈ {b}.': ('दो आधार धाराओं से ΔIc ÷ ΔIb ≈ {b}.', 'ಎರಡು ಆಧಾರ ಪ್ರವಾಹಗಳಿಂದ ΔIc ÷ ΔIb ≈ {b}.'),
    'Gain': ('लब्धि', 'ಲಾಭ'),
    'Gate': ('गेट', 'ದ್ವಾರ'),
    'Half-power bandwidth {b} Hz, so the quality factor Q = f₀ ÷ bandwidth ≈ {q}.': ('अर्ध-शक्ति बैंड चौड़ाई {b} Hz, इसलिए गुणता गुणांक Q = f₀ ÷ बैंड चौड़ाई ≈ {q}.', 'ಅರ್ಧ-ಶಕ್ತಿ ಬ್ಯಾಂಡ್ ಅಗಲ {b} Hz; ಆದ್ದರಿಂದ ಗುಣಮಟ್ಟ ಅಂಶ Q = f₀ ÷ ಬ್ಯಾಂಡ್ ಅಗಲ ≈ {q}.'),
    'In reverse bias only a tiny current (microamperes) flows.': ('पश्च अभिनति में केवल बहुत छोटी धारा (माइक्रोऐम्पियर) बहती है।', 'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಅತಿ ಸಣ್ಣ ಪ್ರವಾಹ (ಮೈಕ್ರೋಆಂಪಿಯರ್) ಮಾತ್ರ ಹರಿಯುತ್ತದೆ.'),
    'Input': ('निवेश', 'ಒಳಹರಿವು'),
    'Input A': ('निवेश A', 'ಒಳಹರಿವು A'),
    'Input B': ('निवेश B', 'ಒಳಹರಿವು B'),
    'Input characteristic': ('निवेश अभिलक्षण', 'ಒಳಹರಿವು ಲಕ್ಷಣ'),
    'Input resistance ΔVbe ÷ ΔIb ≈ {r} Ω near the top of the curve; the base current starts only after Vbe ≈ 0.6 V.': (
        'वक्र के ऊपरी भाग के पास निवेश प्रतिरोध ΔVbe ÷ ΔIb ≈ {r} Ω; आधार धारा Vbe ≈ 0.6 V के बाद ही शुरू होती है।',
        'ವಕ್ರದ ಮೇಲ್ಭಾಗದ ಹತ್ತಿರ ಒಳಹರಿವು ರೋಧ ΔVbe ÷ ΔIb ≈ {r} Ω; ಆಧಾರ ಪ್ರವಾಹ Vbe ≈ 0.6 V ನಂತರವೇ ಆರಂಭ.'),
    'Internal resistance r = R(l₁ − l₂) ÷ l₂ = {r} Ω.': ('आंतरिक प्रतिरोध r = R(l₁ − l₂) ÷ l₂ = {r} Ω.', 'ಆಂತರಿಕ ರೋಧ r = R(l₁ − l₂) ÷ l₂ = {r} Ω.'),
    'Jockey': ('जॉकी', 'ಜಾಕಿ'),
    'Just glowing: record': ('बस चमक रहा है: दर्ज करें', 'ಕೇವಲ ಹೊಳೆಯುತ್ತಿದೆ: ದಾಖಲಿಸಿ'),
    'Key K₂ (R across the cell)': ('कुंजी K₂ (सेल के सिरों पर R)', 'ಕೀ K₂ (ಕೋಶಕ್ಕೆ ಅಡ್ಡ R)'),
    'Knee (cut-in) voltage ≈ {v} V: below it almost no current flows; above it the current rises steeply.': (
        'घुटना (कट-इन) वोल्टता ≈ {v} V: इससे नीचे लगभग कोई धारा नहीं बहती; इसके ऊपर धारा तेज़ी से बढ़ती है।',
        'ನೀ (ಕಟ್-ಇನ್) ವೋಲ್ಟೇಜ್ ≈ {v} V: ಅದರ ಕೆಳಗೆ ಬಹುತೇಕ ಪ್ರವಾಹವಿಲ್ಲ; ಮೇಲೆ ಪ್ರವಾಹ ವೇಗವಾಗಿ ಏರುತ್ತದೆ.'),
    'K₂': ('K₂', 'K₂'),
    'LED': ('LED', 'LED'),
    'Leclanché cell': ('लेक्लांशे सेल', 'ಲೆಕ್ಲಾಂಶೆ ಕೋಶ'),
    'Load': ('लोड', 'ಲೋಡ್'),
    'Loop 1': ('पाश 1', 'ಕುಣಿಕೆ 1'),
    'Loop 1: E1 − I1R1 − I3R3 (V)': ('पाश 1: E1 − I1R1 − I3R3 (V)', 'ಕುಣಿಕೆ 1: E1 − I1R1 − I3R3 (V)'),
    'Loop 2': ('पाश 2', 'ಕುಣಿಕೆ 2'),
    'Manganin': ('मैंगनिन', 'ಮ್ಯಾಂಗನಿನ್'),
    'Measured frequencies agree with f = 1.44 ÷ ((RA + 2RB)C) within {e} %. The duty cycle (RA + RB) ÷ (RA + 2RB) is always above 50 %, nearest 50 % when RB is much bigger than RA.': (
        'मापी गई आवृत्तियाँ f = 1.44 ÷ ((RA + 2RB)C) से {e} % के भीतर मेल खाती हैं। कार्य चक्र (RA + RB) ÷ (RA + 2RB) सदा 50 % से अधिक है, और RB के RA से बहुत बड़ा होने पर 50 % के सबसे निकट।',
        'ಅಳೆದ ಆವರ್ತನಗಳು f = 1.44 ÷ ((RA + 2RB)C) ಗೆ {e} % ಒಳಗೆ ಹೊಂದುತ್ತವೆ. ಕಾರ್ಯ ಚಕ್ರ (RA + RB) ÷ (RA + 2RB) ಯಾವಾಗಲೂ 50 % ಕ್ಕಿಂತ ಹೆಚ್ಚು; RB, RA ಗಿಂತ ಬಹಳ ದೊಡ್ಡದಾದಾಗ 50 % ಗೆ ಅತಿ ಹತ್ತಿರ.'),
    'Nichrome': ('नाइक्रोम', 'ನೈಕ್ರೋಮ್'),
    'No null point on the wire: lower the rheostat so the wire carries more current.': ('तार पर कोई शून्य बिंदु नहीं: रिओस्टेट घटाएँ ताकि तार में अधिक धारा बहे।', 'ತಂತಿಯಲ್ಲಿ ಶೂನ್ಯ ಬಿಂದು ಇಲ್ಲ: ತಂತಿಯಲ್ಲಿ ಹೆಚ್ಚು ಪ್ರವಾಹ ಹರಿಯುವಂತೆ ರಿಯೋಸ್ಟಾಟ್ ಕಡಿಮೆ ಮಾಡಿ.'),
    'Now close K₂ and find the null point again (l₂).': ('अब K₂ बंद करें और फिर शून्य बिंदु (l₂) ज्ञात करें।', 'ಈಗ K₂ ಮುಚ್ಚಿ ಮತ್ತೆ ಶೂನ್ಯ ಬಿಂದು (l₂) ಕಂಡುಹಿಡಿಯಿರಿ.'),
    'Open': ('खुली', 'ತೆರೆದ'),
    'Output': ('निर्गत', 'ಹೊರಹರಿವು'),
    'Output characteristic': ('निर्गत अभिलक्षण', 'ಹೊರಹರಿವು ಲಕ್ಷಣ'),
    'Process': ('प्रक्रिया', 'ಪ್ರಕ್ರಿಯೆ'),
    'Record the threshold voltage for at least two colours.': ('कम से कम दो रंगों के लिए देहली वोल्टता दर्ज करें।', 'ಕನಿಷ್ಠ ಎರಡು ಬಣ್ಣಗಳಿಗೆ ಹೊಸ್ತಿಲು ವೋಲ್ಟೇಜ್ ದಾಖಲಿಸಿ.'),
    'Resistance box': ('प्रतिरोध बॉक्स', 'ರೋಧ ಪೆಟ್ಟಿಗೆ'),
    'Reverse': ('पश्च', 'ಹಿಮ್ಮುಖ'),
    'Reverse bias': ('पश्च अभिनति', 'ಹಿಮ್ಮುಖ ಬಯಾಸ್'),
    'Reverse breakdown at about {v} V: after it the voltage stays nearly the same while the current grows.': ('लगभग {v} V पर पश्च भंजन: इसके बाद धारा बढ़ती है पर वोल्टता लगभग वही रहती है।', 'ಸುಮಾರು {v} V ನಲ್ಲಿ ಹಿಮ್ಮುಖ ಭಂಜನ: ನಂತರ ಪ್ರವಾಹ ಹೆಚ್ಚಿದರೂ ವೋಲ್ಟೇಜ್ ಬಹುತೇಕ ಅದೇ.'),
    'Ripple Vac (V)': ('ऊर्मिका Vac (V)', 'ತರಂಗ Vac (V)'),
    'Ripple factor γ': ('ऊर्मिका गुणांक γ', 'ತರಂಗ ಅಂಶ γ'),
    'Saturated': ('संतृप्त', 'ಸಂತೃಪ್ತ'),
    'Set an input voltage first.': ('पहले निवेश वोल्टता तय करें।', 'ಮೊದಲು ಒಳಹರಿವು ವೋಲ್ಟೇಜ್ ಹೊಂದಿಸಿ.'),
    'Slope of V against 1/λ = {k} V m, so h = e × slope ÷ c = {h} × 10⁻³⁴ J s (accepted value 6.63 × 10⁻³⁴ J s, {pct}% off).': (
        'V और 1/λ की प्रवणता = {k} V m, इसलिए h = e × प्रवणता ÷ c = {h} × 10⁻³⁴ J s (मान्य मान 6.63 × 10⁻³⁴ J s, {pct}% अंतर)।',
        'V ಮತ್ತು 1/λ ಇಳಿಜಾರು = {k} V m; ಆದ್ದರಿಂದ h = e × ಇಳಿಜಾರು ÷ c = {h} × 10⁻³⁴ J s (ಒಪ್ಪಿತ ಮೌಲ್ಯ 6.63 × 10⁻³⁴ J s, {pct}% ವ್ಯತ್ಯಾಸ).'),
    'Slope of Vout against Vin = {g}: the closed-loop gain.{sat}': ('Vout और Vin की प्रवणता = {g}: बंद-पाश लब्धि।{sat}', 'Vout ಮತ್ತು Vin ಇಳಿಜಾರು = {g}: ಮುಚ್ಚಿದ-ಕುಣಿಕೆ ಲಾಭ.{sat}'),
    'Supply': ('आपूर्ति', 'ಪೂರೈಕೆ'),
    'Take at least three readings at different times.': ('अलग-अलग समय पर कम से कम तीन पाठ्यांक लें।', 'ಬೇರೆ ಬೇರೆ ಸಮಯಗಳಲ್ಲಿ ಕನಿಷ್ಠ ಮೂರು ಓದುಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.'),
    'Take more readings where the current rises.': ('जहाँ धारा बढ़ती है वहाँ और पाठ्यांक लें।', 'ಪ್ರವಾಹ ಏರುವಲ್ಲಿ ಇನ್ನಷ್ಟು ಓದುಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.'),
    'Take readings with smaller inputs too, where the output is not saturated.': ('छोटे निवेशों पर भी पाठ्यांक लें, जहाँ निर्गत संतृप्त न हो।', 'ಹೊರಹರಿವು ಸಂತೃಪ್ತವಾಗದ ಸಣ್ಣ ಒಳಹರಿವುಗಳಲ್ಲೂ ಓದು ತೆಗೆದುಕೊಳ್ಳಿ.'),
    'The LED is not glowing yet: raise the voltage slowly.': ('LED अभी नहीं चमक रहा: वोल्टता धीरे-धीरे बढ़ाएँ।', 'LED ಇನ್ನೂ ಹೊಳೆಯುತ್ತಿಲ್ಲ: ವೋಲ್ಟೇಜನ್ನು ನಿಧಾನವಾಗಿ ಹೆಚ್ಚಿಸಿ.'),
    'The LED is too bright: lower the voltage until it only just glows.': ('LED बहुत तेज़ चमक रहा है: वोल्टता घटाएँ जब तक वह बस हल्का न चमके।', 'LED ಅತಿ ಪ್ರಕಾಶಮಾನ: ಅದು ಕೇವಲ ಹೊಳೆಯುವವರೆಗೆ ವೋಲ್ಟೇಜ್ ಕಡಿಮೆ ಮಾಡಿ.'),
    'The current is largest, {i} mA, at about {f} Hz: the resonant frequency.': ('धारा लगभग {f} Hz पर सबसे अधिक, {i} mA है: यही अनुनादी आवृत्ति है।', 'ಸುಮಾರು {f} Hz ನಲ್ಲಿ ಪ್ರವಾಹ ಗರಿಷ್ಠ, {i} mA: ಅದೇ ಅನುನಾದ ಆವರ್ತನ.'),
    'The galvanometer still deflects: slide the jockey to the null point.': ('गैल्वेनोमीटर अभी भी विक्षेपित है: जॉकी को शून्य बिंदु तक खिसकाएँ।', 'ಗ್ಯಾಲ್ವನೋಮೀಟರ್ ಇನ್ನೂ ವಿಚಲಿಸುತ್ತಿದೆ: ಜಾಕಿಯನ್ನು ಶೂನ್ಯ ಬಿಂದುವಿಗೆ ಸರಿಸಿ.'),
    'Too bright': ('बहुत तेज़', 'ಅತಿ ಪ್ರಕಾಶ'),
    'Transformer': ('ट्रांसफ़ॉर्मर', 'ಪರಿವರ್ತಕ'),
    'Turn up the supply first.': ('पहले आपूर्ति बढ़ाएँ।', 'ಮೊದಲು ಪೂರೈಕೆ ಹೆಚ್ಚಿಸಿ.'),
    'Unknown wire': ('अज्ञात तार', 'ಅಜ್ಞಾತ ತಂತಿ'),
    'Voltage': ('वोल्टता', 'ವೋಲ್ಟೇಜ್'),
    'With {c} µF the ripple factor falls to {g}: a bigger capacitor or a bigger load resistance gives a smoother output.': (
        '{c} µF के साथ ऊर्मिका गुणांक घटकर {g} हो जाता है: बड़ा संधारित्र या बड़ा लोड प्रतिरोध अधिक समतल निर्गत देता है।',
        '{c} µF ನೊಂದಿಗೆ ತರಂಗ ಅಂಶ {g} ಗೆ ಇಳಿಯುತ್ತದೆ: ದೊಡ್ಡ ಧಾರಕ ಅಥವಾ ದೊಡ್ಡ ಲೋಡ್ ರೋಧ ಹೆಚ್ಚು ನಯವಾದ ಹೊರಹರಿವು ನೀಡುತ್ತದೆ.'),
    'Without a filter the ripple factor is {g} (theory: 1.21 for half-wave, 0.48 for full-wave).': ('फ़िल्टर के बिना ऊर्मिका गुणांक {g} है (सिद्धांत: अर्ध-तरंग के लिए 1.21, पूर्ण-तरंग के लिए 0.48)।', 'ಫಿಲ್ಟರ್ ಇಲ್ಲದೆ ತರಂಗ ಅಂಶ {g} (ಸಿದ್ಧಾಂತ: ಅರ್ಧ-ತರಂಗಕ್ಕೆ 1.21, ಪೂರ್ಣ-ತರಂಗಕ್ಕೆ 0.48).'),
    'Zener': ('ज़ेनर', 'ಜೀನರ್'),
    'charged': ('आवेशित', 'ಆವೇಶಗೊಂಡಿದೆ'),
    'discharged': ('निरावेशित', 'ವಿಸರ್ಜನೆಯಾಗಿದೆ'),
    'f formula (Hz)': ('f सूत्र से (Hz)', 'f ಸೂತ್ರದಿಂದ (Hz)'),
    'f measured (Hz)': ('f मापी गई (Hz)', 'f ಅಳೆದದ್ದು (Hz)'),
    '{g}: some rows do not match {e}; check them again.': ('{g}: कुछ पंक्तियाँ {e} से मेल नहीं खातीं; उन्हें फिर जाँचें।', '{g}: ಕೆಲವು ಸಾಲುಗಳು {e} ಗೆ ಹೊಂದುತ್ತಿಲ್ಲ; ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.'),
    '{g}: the truth table is complete and matches {e}.': ('{g}: सत्यता सारणी पूरी है और {e} से मेल खाती है।', '{g}: ಸತ್ಯ ಕೋಷ್ಟಕ ಪೂರ್ಣ ಮತ್ತು {e} ಗೆ ಹೊಂದುತ್ತದೆ.'),
    '{g}: {n} of {m} input combinations recorded.': ('{g}: {m} में से {n} निवेश संयोजन दर्ज।', '{g}: {m} ರಲ್ಲಿ {n} ಒಳಹರಿವು ಸಂಯೋಜನೆಗಳು ದಾಖಲಾಗಿವೆ.'),
    '{w}: X = {x} Ω, so ρ = Xπr² ÷ L = {r} × 10⁻⁷ Ω m (L = {l} m, d = {d} mm; table value {t} × 10⁻⁷).': (
        '{w}: X = {x} Ω, इसलिए ρ = Xπr² ÷ L = {r} × 10⁻⁷ Ω m (L = {l} m, d = {d} mm; सारणी मान {t} × 10⁻⁷)।',
        '{w}: X = {x} Ω; ಆದ್ದರಿಂದ ρ = Xπr² ÷ L = {r} × 10⁻⁷ Ω m (L = {l} m, d = {d} mm; ಕೋಷ್ಟಕ ಮೌಲ್ಯ {t} × 10⁻⁷).'),
}
