# Interface strings of the optics, mechanics, heat, sound and modern-physics benches.
# english: (hindi, kannada)
S = {
    '20 oscillations take {t} s': ('20 दोलनों में {t} s लगते हैं', '20 ಆಂದೋಲನಗಳಿಗೆ {t} s ಬೇಕು'),
    'Accelerating voltage': ('त्वरक वोल्टता', 'ವೇಗವರ್ಧಕ ವೋಲ್ಟೇಜ್'),
    'After': ('बाद में', 'ನಂತರ'),
    'Air column': ('वायु स्तंभ', 'ಗಾಳಿ ಸ್ತಂಭ'),
    'Angle': ('कोण', 'ಕೋನ'),
    'Angle θ': ('कोण θ', 'ಕೋನ θ'),
    'Anode potential': ('ऐनोड विभव', 'ಆನೋಡ್ ವಿಭವ'),
    'At rest': ('स्थिर', 'ನಿಶ್ಚಲ'),
    'Ball radius': ('गोली की त्रिज्या', 'ಗುಂಡಿನ ತ್ರಿಜ್ಯ'),
    'Bare': ('खुला', 'ತೆರೆದ'),
    'Before': ('पहले', 'ಮೊದಲು'),
    'Bring H down from +600 A/m through zero to −600 A/m, recording as you go.': ('H को +600 A/m से शून्य होते हुए −600 A/m तक घटाएँ, साथ-साथ दर्ज करते जाएँ।', 'H ಅನ್ನು +600 A/m ನಿಂದ ಶೂನ್ಯದ ಮೂಲಕ −600 A/m ವರೆಗೆ ಇಳಿಸುತ್ತಾ ದಾಖಲಿಸಿ.'),
    'Calorimeter': ('कैलोरीमीटर', 'ಕ್ಯಾಲೊರಿಮೀಟರ್'),
    'Cart 1 must move faster than cart 2 to catch it.': ('गाड़ी 2 को पकड़ने के लिए गाड़ी 1 को उससे तेज़ चलना होगा।', 'ಗಾಡಿ 2 ಅನ್ನು ತಲುಪಲು ಗಾಡಿ 1 ಅದಕ್ಕಿಂತ ವೇಗವಾಗಿ ಚಲಿಸಬೇಕು.'),
    'Coil current': ('कुंडली धारा', 'ಸುರುಳಿ ಪ್ರವಾಹ'),
    'Collision': ('संघट्ट', 'ಘರ್ಷಣೆ'),
    'Concave mirror {k}': ('अवतल दर्पण {k}', 'ನಿಮ್ನ ದರ್ಪಣ {k}'),
    'Convex lens (10 cm) + concave lens {k}': ('उत्तल लेंस (10 cm) + अवतल लेंस {k}', 'ಪೀನ ಮಸೂರ (10 cm) + ನಿಮ್ನ ಮಸೂರ {k}'),
    'Convex lens {k}': ('उत्तल लेंस {k}', 'ಪೀನ ಮಸೂರ {k}'),
    'Convex mirror': ('उत्तल दर्पण', 'ಪೀನ ದರ್ಪಣ'),
    'Convex mirror {k}': ('उत्तल दर्पण {k}', 'ಪೀನ ದರ್ಪಣ {k}'),
    'Crown glass': ('क्राउन काँच', 'ಕ್ರೌನ್ ಗಾಜು'),
    'Dark ring {n}': ('काला वलय {n}', 'ಕಪ್ಪು ಉಂಗುರ {n}'),
    'Direction': ('दिशा', 'ದಿಕ್ಕು'),
    'Earth': ('पृथ्वी', 'ಭೂಮಿ'),
    'Elastic': ('प्रत्यास्थ', 'ಸ್ಥಿತಿಸ್ಥಾಪಕ'),
    'Extension (cm)': ('विस्तार (cm)', 'ವಿಸ್ತರಣೆ (cm)'),
    'Extension (mm)': ('विस्तार (mm)', 'ವಿಸ್ತರಣೆ (mm)'),
    'Extension {e} mm': ('विस्तार {e} mm', 'ವಿಸ್ತರಣೆ {e} mm'),
    'Extension ÷ force stays the same: extension ∝ load (Hooke’s law). Slope {s} cm/N, so the spring constant k = {k} N/m.': (
        'विस्तार ÷ बल समान रहता है: विस्तार ∝ भार (हुक का नियम)। प्रवणता {s} cm/N, अतः स्प्रिंग नियतांक k = {k} N/m.',
        'ವಿಸ್ತರಣೆ ÷ ಬಲ ಒಂದೇ ಇರುತ್ತದೆ: ವಿಸ್ತರಣೆ ∝ ಭಾರ (ಹುಕ್ ನಿಯಮ). ಇಳಿಜಾರು {s} cm/N, ಆದ್ದರಿಂದ ಸ್ಪ್ರಿಂಗ್ ಸ್ಥಿರಾಂಕ k = {k} N/m.'),
    'F against sin θ is a straight line through the origin: F = W sin θ with W = {w} N (the roller’s weight, mg = {mg} N).': (
        'F और sin θ का ग्राफ़ मूल बिंदु से जाने वाली सीधी रेखा है: F = W sin θ, जहाँ W = {w} N (रोलर का भार, mg = {mg} N)।',
        'F ಮತ್ತು sin θ ನಕ್ಷೆ ಮೂಲಬಿಂದುವಿನ ಮೂಲಕ ಸರಳರೇಖೆ: F = W sin θ, ಇಲ್ಲಿ W = {w} N (ರೋಲರ್‌ನ ತೂಕ, mg = {mg} N).'),
    'Falling': ('घटता', 'ಇಳಿಯುವ'),
    'Find both the first and the second resonance for a fork.': ('एक स्वरित्र के लिए पहला और दूसरा दोनों अनुनाद ढूँढें।', 'ಒಂದು ಶ್ರುತಿಕವೆಗೆ ಮೊದಲ ಮತ್ತು ಎರಡನೇ ಅನುನಾದ ಎರಡನ್ನೂ ಕಂಡುಹಿಡಿಯಿರಿ.'),
    'First': ('पहला', 'ಮೊದಲ'),
    'Flint glass': ('फ़्लिंट काँच', 'ಫ್ಲಿಂಟ್ ಗಾಜು'),
    'Focus on': ('इस पर फ़ोकस', 'ಇದರ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿ'),
    'Focused on': ('जिस पर फ़ोकस किया', 'ಕೇಂದ್ರೀಕರಿಸಿದ್ದು'),
    'For at least three filters, find the retarding potential at which the current just becomes zero.': ('कम से कम तीन फ़िल्टरों के लिए वह निरोधी विभव ढूँढें जिस पर धारा ठीक शून्य हो जाती है।', 'ಕನಿಷ್ಠ ಮೂರು ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಪ್ರವಾಹ ಕೇವಲ ಶೂನ್ಯವಾಗುವ ನಿಲುಗಡೆ ವಿಭವ ಕಂಡುಹಿಡಿಯಿರಿ.'),
    'Full': ('पूरी', 'ಪೂರ್ಣ'),
    'Grating': ('ग्रेटिंग', 'ಗ್ರೇಟಿಂಗ್'),
    'Half': ('आधी', 'ಅರ್ಧ'),
    'Height': ('ऊँचाई', 'ಎತ್ತರ'),
    'Image and needle do not coincide': ('प्रतिबिंब और सुई नहीं मिलते', 'ಪ್ರತಿಬಿಂಬ ಮತ್ತು ಸೂಜಿ ಸೇರುತ್ತಿಲ್ಲ'),
    'Image coincides with the needle': ('प्रतिबिंब सुई से मिल गया', 'ಪ್ರತಿಬಿಂಬ ಸೂಜಿಯೊಂದಿಗೆ ಸೇರಿದೆ'),
    'Image needle': ('प्रतिबिंब सुई', 'ಪ್ರತಿಬಿಂಬ ಸೂಜಿ'),
    'Intensity': ('तीव्रता', 'ತೀವ್ರತೆ'),
    'KE after (J)': ('बाद में गतिज ऊर्जा (J)', 'ನಂತರ ಚಲನ ಶಕ್ತಿ (J)'),
    'KE before (J)': ('पहले गतिज ऊर्जा (J)', 'ಮೊದಲು ಚಲನ ಶಕ್ತಿ (J)'),
    'Keep going: the falling branch must cross both axes.': ('जारी रखें: घटती शाखा को दोनों अक्ष पार करने चाहिए।', 'ಮುಂದುವರಿಸಿ: ಇಳಿಯುವ ಶಾಖೆ ಎರಡೂ ಅಕ್ಷಗಳನ್ನು ದಾಟಬೇಕು.'),
    'Lagged with cotton': ('रुई के आवरण सहित', 'ಹತ್ತಿಯ ಹೊದಿಕೆ ಸಹಿತ'),
    'Lamp': ('लैंप', 'ದೀಪ'),
    'Lens': ('लेंस', 'ಮಸೂರ'),
    'Lens radius R': ('लेंस त्रिज्या R', 'ಮಸೂರ ತ್ರಿಜ್ಯ R'),
    'Limiting friction F (N)': ('सीमांत घर्षण F (N)', 'ಮಿತಿ ಘರ್ಷಣೆ F (N)'),
    'Line': ('रेखा', 'ರೇಖೆ'),
    'Load (g)': ('भार (g)', 'ಭಾರ (g)'),
    'Load (kg)': ('भार (kg)', 'ಭಾರ (kg)'),
    'Load in pan': ('पलड़े में भार', 'ತಟ್ಟೆಯಲ್ಲಿ ಭಾರ'),
    'Loudness': ('प्रबलता', 'ಧ್ವನಿಯ ಜೋರು'),
    'Loudness {n}%': ('प्रबलता {n}%', 'ಧ್ವನಿಯ ಜೋರು {n}%'),
    'Mark seen through the slab': ('गुटके से दिखता निशान', 'ಚಪ್ಪಡಿಯ ಮೂಲಕ ಕಾಣುವ ಗುರುತು'),
    'Mark without the slab': ('गुटके के बिना निशान', 'ಚಪ್ಪಡಿಯಿಲ್ಲದೆ ಗುರುತು'),
    'Mars': ('मंगल', 'ಮಂಗಳ'),
    'Mass on block': ('गुटके पर द्रव्यमान', 'ಬ್ಲಾಕ್ ಮೇಲಿನ ದ್ರವ್ಯರಾಶಿ'),
    'Max height (m)': ('अधिकतम ऊँचाई (m)', 'ಗರಿಷ್ಠ ಎತ್ತರ (m)'),
    'Mean focal length f = uv/(u + v) = {f} cm.': ('माध्य फ़ोकस दूरी f = uv/(u + v) = {f} cm.', 'ಸರಾಸರಿ ನಾಭಿದೂರ f = uv/(u + v) = {f} cm.'),
    'Mercury': ('पारा', 'ಪಾದರಸ'),
    'Micrometer': ('माइक्रोमीटर', 'ಮೈಕ್ರೋಮೀಟರ್'),
    'Microscope': ('सूक्ष्मदर्शी', 'ಸೂಕ್ಷ್ಮದರ್ಶಕ'),
    'Mirror': ('दर्पण', 'ದರ್ಪಣ'),
    'Mirror M (cm)': ('दर्पण M (cm)', 'ದರ್ಪಣ M (cm)'),
    'Mirror position': ('दर्पण की स्थिति', 'ದರ್ಪಣದ ಸ್ಥಾನ'),
    'Momentum before and after agree within {d} kg m/s in every collision. Kinetic energy lost: {k}% (none in an elastic collision, most when the carts stick).': (
        'हर संघट्ट में पहले और बाद का संवेग {d} kg m/s के भीतर मेल खाता है। नष्ट गतिज ऊर्जा: {k}% (प्रत्यास्थ संघट्ट में कुछ नहीं, गाड़ियाँ चिपकने पर सबसे अधिक)।',
        'ಪ್ರತಿ ಘರ್ಷಣೆಯಲ್ಲೂ ಮೊದಲು ಮತ್ತು ನಂತರದ ಸಂವೇಗ {d} kg m/s ಒಳಗೆ ಹೊಂದುತ್ತದೆ. ನಷ್ಟವಾದ ಚಲನ ಶಕ್ತಿ: {k}% (ಸ್ಥಿತಿಸ್ಥಾಪಕ ಘರ್ಷಣೆಯಲ್ಲಿ ಇಲ್ಲ, ಗಾಡಿಗಳು ಅಂಟಿದಾಗ ಅತಿ ಹೆಚ್ಚು).'),
    'Moon': ('चंद्रमा', 'ಚಂದ್ರ'),
    'No parallax': ('लंबन नहीं', 'ಭ್ರಂಶ ಇಲ್ಲ'),
    'No real image': ('वास्तविक प्रतिबिंब नहीं', 'ನೈಜ ಪ್ರತಿಬಿಂಬ ಇಲ್ಲ'),
    'No real image forms: move the object beyond the focus.': ('वास्तविक प्रतिबिंब नहीं बनता: वस्तु को फ़ोकस से परे ले जाएँ।', 'ನೈಜ ಪ್ರತಿಬಿಂಬ ಮೂಡುತ್ತಿಲ್ಲ: ವಸ್ತುವನ್ನು ನಾಭಿಯ ಆಚೆ ಸರಿಸಿ.'),
    'Not in focus: turn the screw until the view is sharp.': ('फ़ोकस में नहीं: दृश्य स्पष्ट होने तक पेंच घुमाएँ।', 'ಕೇಂದ್ರೀಕೃತವಾಗಿಲ್ಲ: ನೋಟ ಸ್ಪಷ್ಟವಾಗುವವರೆಗೆ ತಿರುಪು ತಿರುಗಿಸಿ.'),
    'Object distance u': ('वस्तु दूरी u', 'ವಸ್ತು ದೂರ u'),
    'Of your launches from the ground, {a}° went farthest ({r} m): the range u² sin 2θ ÷ g is greatest at 45°.': (
        'भूमि से आपके प्रक्षेपणों में {a}° सबसे दूर ({r} m) गया: परास u² sin 2θ ÷ g, 45° पर सबसे अधिक होती है।',
        'ನೆಲದಿಂದ ನಿಮ್ಮ ಉಡಾವಣೆಗಳಲ್ಲಿ {a}° ಅತಿ ದೂರ ({r} m) ಹೋಯಿತು: ವ್ಯಾಪ್ತಿ u² sin 2θ ÷ g, 45° ನಲ್ಲಿ ಗರಿಷ್ಠ.'),
    'Out of focus': ('फ़ोकस से बाहर', 'ಕೇಂದ್ರೀಕರಣ ತಪ್ಪಿದೆ'),
    'P (cm)': ('P (cm)', 'P (cm)'),
    'Parallax: move the needle': ('लंबन है: सुई खिसकाएँ', 'ಭ್ರಂಶ ಇದೆ: ಸೂಜಿ ಸರಿಸಿ'),
    'Partly elastic': ('आंशिक प्रत्यास्थ', 'ಭಾಗಶಃ ಸ್ಥಿತಿಸ್ಥಾಪಕ'),
    'Perspex': ('पर्स्पेक्स', 'ಪರ್ಸ್ಪೆಕ್ಸ್'),
    'Planet': ('ग्रह', 'ಗ್ರಹ'),
    'Pointer (cm)': ('सूचक (cm)', 'ಸೂಚಕ (cm)'),
    'Pointer {r} cm': ('सूचक {r} cm', 'ಸೂಚಕ {r} cm'),
    'Powder on top of the slab': ('गुटके के ऊपर चूर्ण', 'ಚಪ್ಪಡಿಯ ಮೇಲಿನ ಪುಡಿ'),
    'R = {r} cm: slope of D² against n = {s} mm², so λ = slope ÷ 4R = {l} nm (sodium: 589.3 nm).': (
        'R = {r} cm: D² और n की प्रवणता = {s} mm², अतः λ = प्रवणता ÷ 4R = {l} nm (सोडियम: 589.3 nm)।',
        'R = {r} cm: D² ಮತ್ತು n ಇಳಿಜಾರು = {s} mm², ಆದ್ದರಿಂದ λ = ಇಳಿಜಾರು ÷ 4R = {l} nm (ಸೋಡಿಯಂ: 589.3 nm).'),
    'Radius of curvature R = {r} cm, so the focal length of the convex mirror is R/2 = {f} cm.': ('वक्रता त्रिज्या R = {r} cm, अतः उत्तल दर्पण की फ़ोकस दूरी R/2 = {f} cm है।', 'ವಕ್ರತಾ ತ್ರಿಜ್ಯ R = {r} cm, ಆದ್ದರಿಂದ ಪೀನ ದರ್ಪಣದ ನಾಭಿದೂರ R/2 = {f} cm.'),
    'Range (m)': ('परास (m)', 'ವ್ಯಾಪ್ತಿ (m)'),
    'Reading (cm)': ('पाठ्यांक (cm)', 'ಓದು (cm)'),
    'Reading {r} cm': ('पाठ्यांक {r} cm', 'ಓದು {r} cm'),
    'Real depth R₃ − R₁ = {a} cm, apparent depth R₃ − R₂ = {b} cm, so n = {n}. The mark appears raised by {s} cm.': (
        'वास्तविक गहराई R₃ − R₁ = {a} cm, आभासी गहराई R₃ − R₂ = {b} cm, अतः n = {n}. निशान {s} cm ऊपर उठा दिखता है।',
        'ನೈಜ ಆಳ R₃ − R₁ = {a} cm, ತೋರಿಕೆಯ ಆಳ R₃ − R₂ = {b} cm, ಆದ್ದರಿಂದ n = {n}. ಗುರುತು {s} cm ಮೇಲೆದ್ದಂತೆ ಕಾಣುತ್ತದೆ.'),
    'Record all three: the mark, the mark through the slab, and the top of the slab.': ('तीनों दर्ज करें: निशान, गुटके से दिखता निशान, और गुटके का ऊपरी तल।', 'ಮೂರನ್ನೂ ದಾಖಲಿಸಿ: ಗುರುತು, ಚಪ್ಪಡಿಯ ಮೂಲಕ ಗುರುತು, ಮತ್ತು ಚಪ್ಪಡಿಯ ಮೇಲ್ಮೈ.'),
    'Record at least three rings.': ('कम से कम तीन वलय दर्ज करें।', 'ಕನಿಷ್ಠ ಮೂರು ಉಂಗುರಗಳನ್ನು ದಾಖಲಿಸಿ.'),
    'Reference': ('संदर्भ', 'ಉಲ್ಲೇಖ'),
    'Resonance': ('अनुनाद', 'ಅನುನಾದ'),
    'Retentivity (B left when H = 0) ≈ {b} T; coercivity (H needed to bring B to zero) ≈ {h} A/m. The area of the loop is the energy lost per cycle per unit volume.': (
        'धारणशीलता (H = 0 पर बचा B) ≈ {b} T; निग्राहिता (B को शून्य करने के लिए आवश्यक H) ≈ {h} A/m. पाश का क्षेत्रफल प्रति चक्र प्रति इकाई आयतन खोई ऊर्जा है।',
        'ಧಾರಣಶೀಲತೆ (H = 0 ನಲ್ಲಿ ಉಳಿದ B) ≈ {b} T; ನಿಗ್ರಾಹಕತೆ (B ಶೂನ್ಯಗೊಳಿಸಲು ಬೇಕಾದ H) ≈ {h} A/m. ಕುಣಿಕೆಯ ವಿಸ್ತೀರ್ಣ ಪ್ರತಿ ಚಕ್ರಕ್ಕೆ ಪ್ರತಿ ಏಕಮಾನ ಘನಫಲಕ್ಕೆ ನಷ್ಟವಾದ ಶಕ್ತಿ.'),
    'Rising': ('बढ़ता', 'ಏರುವ'),
    'Room {t} °C': ('कमरा {t} °C', 'ಕೋಣೆ {t} °C'),
    'Second': ('दूसरा', 'ಎರಡನೇ'),
    'Set the cross-wire exactly on a spectral line.': ('क्रॉस-तार को ठीक किसी स्पेक्ट्रमी रेखा पर रखें।', 'ಅಡ್ಡತಂತಿಯನ್ನು ನಿಖರವಾಗಿ ಒಂದು ರೋಹಿತ ರೇಖೆಯ ಮೇಲಿಡಿ.'),
    'Set the cross-wire on the middle of a dark ring.': ('क्रॉस-तार को किसी काले वलय के बीच पर रखें।', 'ಅಡ್ಡತಂತಿಯನ್ನು ಒಂದು ಕಪ್ಪು ಉಂಗುರದ ಮಧ್ಯದಲ್ಲಿಡಿ.'),
    'Sliding': ('खिसक रहा है', 'ಜಾರುತ್ತಿದೆ'),
    'Sodium': ('सोडियम', 'ಸೋಡಿಯಂ'),
    'Speed': ('चाल', 'ವೇಗ'),
    'Spring': ('स्प्रिंग', 'ಸ್ಪ್ರಿಂಗ್'),
    'Spring balance F (N)': ('कमानीदार तुला F (N)', 'ಸ್ಪ್ರಿಂಗ್ ತುಲಾ F (N)'),
    'Sticky (inelastic)': ('चिपकने वाला (अप्रत्यास्थ)', 'ಅಂಟುವ (ಅಸ್ಥಿತಿಸ್ಥಾಪಕ)'),
    'Stopping potential rises in a straight line with frequency. Slope h/e gives h = {h} × 10⁻³⁴ J s; the intercept gives the work function φ = {p} eV (threshold {t} × 10¹⁴ Hz). Brighter light gives more current but the same stopping potential.': (
        'निरोधी विभव आवृत्ति के साथ सीधी रेखा में बढ़ता है। प्रवणता h/e से h = {h} × 10⁻³⁴ J s; अंतःखंड से कार्य फलन φ = {p} eV (देहली {t} × 10¹⁴ Hz)। तेज़ प्रकाश अधिक धारा देता है पर निरोधी विभव वही रहता है।',
        'ನಿಲುಗಡೆ ವಿಭವ ಆವರ್ತನದೊಂದಿಗೆ ಸರಳರೇಖೆಯಲ್ಲಿ ಏರುತ್ತದೆ. ಇಳಿಜಾರು h/e ಯಿಂದ h = {h} × 10⁻³⁴ J s; ಅಂತಃಖಂಡದಿಂದ ಕಾರ್ಯ ಫಲನ φ = {p} eV (ಹೊಸ್ತಿಲು {t} × 10¹⁴ Hz). ಪ್ರಕಾಶಮಾನ ಬೆಳಕು ಹೆಚ್ಚು ಪ್ರವಾಹ ನೀಡುತ್ತದೆ, ನಿಲುಗಡೆ ವಿಭವ ಅದೇ.'),
    'Telescope': ('दूरदर्शी', 'ದೂರದರ್ಶಕ'),
    'That is the direct (zero-order) image: turn the telescope to a coloured line.': ('यह सीधा (शून्य कोटि) प्रतिबिंब है: दूरदर्शी को किसी रंगीन रेखा की ओर घुमाएँ।', 'ಇದು ನೇರ (ಶೂನ್ಯ ಕ್ರಮ) ಪ್ರತಿಬಿಂಬ: ದೂರದರ್ಶಕವನ್ನು ಒಂದು ಬಣ್ಣದ ರೇಖೆಗೆ ತಿರುಗಿಸಿ.'),
    'The 1/v–1/u graph is a straight line meeting each axis at about 1/f: intercept {c} cm⁻¹ gives f = {f} cm.': (
        '1/v–1/u ग्राफ़ एक सीधी रेखा है जो हर अक्ष को लगभग 1/f पर काटती है: अंतःखंड {c} cm⁻¹ से f = {f} cm.',
        '1/v–1/u ನಕ್ಷೆ ಪ್ರತಿ ಅಕ್ಷವನ್ನು ಸುಮಾರು 1/f ನಲ್ಲಿ ಛೇದಿಸುವ ಸರಳರೇಖೆ: ಅಂತಃಖಂಡ {c} cm⁻¹ ಯಿಂದ f = {f} cm.'),
    'The block has not started to slide: add load to the pan.': ('गुटका अभी खिसका नहीं: पलड़े में भार बढ़ाएँ।', 'ಬ್ಲಾಕ್ ಇನ್ನೂ ಜಾರಿಲ್ಲ: ತಟ್ಟೆಗೆ ಭಾರ ಸೇರಿಸಿ.'),
    'The circle is too big for the scale: raise the coil current.': ('वृत्त पैमाने के लिए बहुत बड़ा है: कुंडली धारा बढ़ाएँ।', 'ವೃತ್ತ ಅಳತೆಗೆ ತುಂಬ ದೊಡ್ಡದು: ಸುರುಳಿ ಪ್ರವಾಹ ಹೆಚ್ಚಿಸಿ.'),
    'The circle is too small to read well: lower the coil current.': ('वृत्त ठीक से पढ़ने के लिए बहुत छोटा है: कुंडली धारा घटाएँ।', 'ವೃತ್ತ ಚೆನ್ನಾಗಿ ಓದಲು ತುಂಬ ಸಣ್ಣದು: ಸುರುಳಿ ಪ್ರವಾಹ ಕಡಿಮೆ ಮಾಡಿ.'),
    'The image is beyond the end of the bench: move the object farther away.': ('प्रतिबिंब बेंच के सिरे से आगे है: वस्तु को और दूर ले जाएँ।', 'ಪ್ರತಿಬಿಂಬ ಪೀಠದ ತುದಿಯ ಆಚೆ ಇದೆ: ವಸ್ತುವನ್ನು ಇನ್ನೂ ದೂರ ಸರಿಸಿ.'),
    'The image of the needle does not coincide with the needle yet: move the mirror.': ('सुई का प्रतिबिंब अभी सुई से नहीं मिला: दर्पण खिसकाएँ।', 'ಸೂಜಿಯ ಪ್ರತಿಬಿಂಬ ಇನ್ನೂ ಸೂಜಿಯೊಂದಿಗೆ ಸೇರಿಲ್ಲ: ದರ್ಪಣ ಸರಿಸಿ.'),
    'The mirror would have to sit on the lens: move the object nearer the focus so the image point is farther away.': ('दर्पण को लेंस पर ही रखना पड़ता: वस्तु को फ़ोकस के पास लाएँ ताकि प्रतिबिंब बिंदु दूर हो।', 'ದರ್ಪಣವನ್ನು ಮಸೂರದ ಮೇಲೆಯೇ ಇಡಬೇಕಾಗುತ್ತದೆ: ಪ್ರತಿಬಿಂಬ ಬಿಂದು ದೂರವಾಗುವಂತೆ ವಸ್ತುವನ್ನು ನಾಭಿಯ ಹತ್ತಿರ ತನ್ನಿ.'),
    'The sound is not loudest here: move the water level slowly to find the loudest point.': ('यहाँ ध्वनि सबसे तेज़ नहीं: सबसे तेज़ बिंदु ढूँढने के लिए पानी का स्तर धीरे-धीरे बदलें।', 'ಇಲ್ಲಿ ಧ್ವನಿ ಅತಿ ಜೋರಾಗಿಲ್ಲ: ಅತಿ ಜೋರಿನ ಬಿಂದು ಹುಡುಕಲು ನೀರಿನ ಮಟ್ಟವನ್ನು ನಿಧಾನವಾಗಿ ಬದಲಿಸಿ.'),
    'There is still parallax between the image and the needle.': ('प्रतिबिंब और सुई के बीच अभी लंबन है।', 'ಪ್ರತಿಬಿಂಬ ಮತ್ತು ಸೂಜಿಯ ನಡುವೆ ಇನ್ನೂ ಭ್ರಂಶ ಇದೆ.'),
    'Thickness': ('मोटाई', 'ದಪ್ಪ'),
    'Third': ('तीसरा', 'ಮೂರನೇ'),
    'Time (s)': ('समय (s)', 'ಸಮಯ (s)'),
    'Time between marks (s)': ('निशानों के बीच समय (s)', 'ಗುರುತುಗಳ ನಡುವಿನ ಸಮಯ (s)'),
    'Time between the marks': ('निशानों के बीच समय', 'ಗುರುತುಗಳ ನಡುವಿನ ಸಮಯ'),
    'Time for 20 (s)': ('20 का समय (s)', '20 ರ ಸಮಯ (s)'),
    'Timing…': ('समय माप रहे हैं…', 'ಸಮಯ ಅಳೆಯಲಾಗುತ್ತಿದೆ…'),
    'Too much: the block shoots off. Find the least load that just starts it moving.': ('बहुत अधिक: गुटका तेज़ी से भाग जाता है। वह न्यूनतम भार ढूँढें जिससे वह बस चलने लगे।', 'ಅತಿ ಹೆಚ್ಚು: ಬ್ಲಾಕ್ ಓಡಿಹೋಗುತ್ತದೆ. ಅದು ಕೇವಲ ಚಲಿಸಲಾರಂಭಿಸುವ ಕನಿಷ್ಠ ಭಾರ ಹುಡುಕಿ.'),
    'Tube radius': ('नली की त्रिज्या', 'ನಳಿಕೆಯ ತ್ರಿಜ್ಯ'),
    'Tuning fork': ('स्वरित्र', 'ಶ್ರುತಿಕವೆ'),
    'T² rises in a straight line with m (slope {s} s²/kg), so k = 4π² ÷ slope = {k} N/m. The line does not pass exactly through the origin because the spring’s own mass also moves.': (
        'T², m के साथ सीधी रेखा में बढ़ता है (प्रवणता {s} s²/kg), अतः k = 4π² ÷ प्रवणता = {k} N/m. रेखा ठीक मूल बिंदु से नहीं जाती क्योंकि स्प्रिंग का अपना द्रव्यमान भी चलता है।',
        'T², m ಯೊಂದಿಗೆ ಸರಳರೇಖೆಯಲ್ಲಿ ಏರುತ್ತದೆ (ಇಳಿಜಾರು {s} s²/kg), ಆದ್ದರಿಂದ k = 4π² ÷ ಇಳಿಜಾರು = {k} N/m. ಸ್ಪ್ರಿಂಗ್‌ನ ಸ್ವಂತ ದ್ರವ್ಯರಾಶಿಯೂ ಚಲಿಸುವುದರಿಂದ ರೇಖೆ ನಿಖರವಾಗಿ ಮೂಲಬಿಂದುವಿನ ಮೂಲಕ ಹೋಗುವುದಿಲ್ಲ.'),
    'Wood on glass': ('काँच पर लकड़ी', 'ಗಾಜಿನ ಮೇಲೆ ಮರ'),
    'Wood on sandpaper': ('रेगमाल पर लकड़ी', 'ಮರಳುಕಾಗದದ ಮೇಲೆ ಮರ'),
    'Wood on wood': ('लकड़ी पर लकड़ी', 'ಮರದ ಮೇಲೆ ಮರ'),
    'e/m = {v} × 10¹¹ C/kg (accepted value 1.759 × 10¹¹ C/kg). Reading the radius to 1 mm limits the accuracy.': ('e/m = {v} × 10¹¹ C/kg (मान्य मान 1.759 × 10¹¹ C/kg)। त्रिज्या को 1 mm तक पढ़ना परिशुद्धता को सीमित करता है।', 'e/m = {v} × 10¹¹ C/kg (ಒಪ್ಪಿತ ಮೌಲ್ಯ 1.759 × 10¹¹ C/kg). ತ್ರಿಜ್ಯವನ್ನು 1 mm ವರೆಗೆ ಓದುವುದು ನಿಖರತೆಯನ್ನು ಮಿತಿಗೊಳಿಸುತ್ತದೆ.'),
    'electrons (n-type)': ('इलेक्ट्रॉन (n-प्रकार)', 'ಎಲೆಕ್ಟ್ರಾನ್‌ಗಳು (n-ಪ್ರಕಾರ)'),
    'h × r stays the same: the narrower the tube, the higher the water. Surface tension T = hrρg ÷ 2 = {t} N/m (table: 0.072 N/m at 25 °C).': (
        'h × r समान रहता है: नली जितनी संकरी, पानी उतना ऊँचा। पृष्ठ तनाव T = hrρg ÷ 2 = {t} N/m (सारणी: 25 °C पर 0.072 N/m)।',
        'h × r ಒಂದೇ: ನಳಿಕೆ ಎಷ್ಟು ಕಿರಿದೋ ನೀರು ಅಷ್ಟು ಎತ್ತರ. ಮೇಲ್ಮೈ ಒತ್ತಡ T = hrρg ÷ 2 = {t} N/m (ಕೋಷ್ಟಕ: 25 °C ನಲ್ಲಿ 0.072 N/m).'),
    'holes (p-type)': ('होल (p-प्रकार)', 'ರಂಧ್ರಗಳು (p-ಪ್ರಕಾರ)'),
    'ln(T − T₀) falls in a straight line with time (slope {s} per min): the rate of cooling is proportional to the excess temperature, as Newton’s law says.': (
        'ln(T − T₀) समय के साथ सीधी रेखा में घटता है (प्रवणता {s} प्रति मिनट): शीतलन की दर अधिक ताप के अनुक्रमानुपाती है, जैसा न्यूटन का नियम कहता है।',
        'ln(T − T₀) ಸಮಯದೊಂದಿಗೆ ಸರಳರೇಖೆಯಲ್ಲಿ ಇಳಿಯುತ್ತದೆ (ಇಳಿಜಾರು ಪ್ರತಿ ನಿಮಿಷಕ್ಕೆ {s}): ನ್ಯೂಟನ್ ನಿಯಮ ಹೇಳುವಂತೆ ತಂಪಾಗುವ ದರ ಹೆಚ್ಚುವರಿ ತಾಪಕ್ಕೆ ಅನುಪಾತೀಯ.'),
    'p after (kg m/s)': ('बाद में p (kg m/s)', 'ನಂತರ p (kg m/s)'),
    'p before (kg m/s)': ('पहले p (kg m/s)', 'ಮೊದಲು p (kg m/s)'),
    'v is proportional to r² (straight line through the origin). From the slope, the viscosity of glycerine η = 2(ρ − σ)g ÷ (9 × slope) = {n} Pa s.': (
        'v, r² के अनुक्रमानुपाती है (मूल बिंदु से जाने वाली सीधी रेखा)। प्रवणता से ग्लिसरीन की श्यानता η = 2(ρ − σ)g ÷ (9 × प्रवणता) = {n} Pa s.',
        'v, r² ಗೆ ಅನುಪಾತೀಯ (ಮೂಲಬಿಂದುವಿನ ಮೂಲಕ ಸರಳರೇಖೆ). ಇಳಿಜಾರಿನಿಂದ ಗ್ಲಿಸರಿನ್‌ನ ಸ್ನಿಗ್ಧತೆ η = 2(ρ − σ)g ÷ (9 × ಇಳಿಜಾರು) = {n} Pa s.'),
    '{a}° and {b}° are complementary and gave the same range.': ('{a}° और {b}° पूरक हैं और उन्होंने समान परास दी।', '{a}° ಮತ್ತು {b}° ಪೂರಕ ಕೋನಗಳು, ಒಂದೇ ವ್ಯಾಪ್ತಿ ನೀಡಿದವು.'),
    '{c}: λ = {l} nm': ('{c}: λ = {l} nm', '{c}: λ = {l} nm'),
    '{f} Hz: L₁ = {a} cm, L₂ = {b} cm, so v = 2f(L₂ − L₁) = {v} m/s and the end correction e = (L₂ − 3L₁) ÷ 2 = {e} cm.': (
        '{f} Hz: L₁ = {a} cm, L₂ = {b} cm, अतः v = 2f(L₂ − L₁) = {v} m/s और सिरा संशोधन e = (L₂ − 3L₁) ÷ 2 = {e} cm.',
        '{f} Hz: L₁ = {a} cm, L₂ = {b} cm, ಆದ್ದರಿಂದ v = 2f(L₂ − L₁) = {v} m/s, ತುದಿ ತಿದ್ದುಪಡಿ e = (L₂ − 3L₁) ÷ 2 = {e} cm.'),
    '{s}: F ∝ N, coefficient of static friction μ = F ÷ N = {m}.': ('{s}: F ∝ N, स्थैतिक घर्षण गुणांक μ = F ÷ N = {m}.', '{s}: F ∝ N, ಸ್ಥಿರ ಘರ್ಷಣ ಗುಣಾಂಕ μ = F ÷ N = {m}.'),
    '{s}: Hall coefficient R_H = {r} × 10⁻³ m³/C; carriers are {c}, density n = 1 ÷ (|R_H| e) = {n} × 10²¹ m⁻³.': (
        '{s}: हॉल गुणांक R_H = {r} × 10⁻³ m³/C; वाहक {c} हैं, घनत्व n = 1 ÷ (|R_H| e) = {n} × 10²¹ m⁻³.',
        '{s}: ಹಾಲ್ ಗುಣಾಂಕ R_H = {r} × 10⁻³ m³/C; ವಾಹಕಗಳು {c}, ಸಾಂದ್ರತೆ n = 1 ÷ (|R_H| e) = {n} × 10²¹ m⁻³.'),
    "{w}: slope {s} mm/kg, so Young's modulus Y = gL ÷ (πr² × slope) = {y} × 10¹¹ Pa.": ('{w}: प्रवणता {s} mm/kg, अतः यंग गुणांक Y = gL ÷ (πr² × प्रवणता) = {y} × 10¹¹ Pa.', '{w}: ಇಳಿಜಾರು {s} mm/kg, ಆದ್ದರಿಂದ ಯಂಗ್ ಗುಣಾಂಕ Y = gL ÷ (πr² × ಇಳಿಜಾರು) = {y} × 10¹¹ Pa.'),
}
