# Interface strings of the chemistry benches (titrations, physical chemistry, spot tests).
# english: (hindi, kannada)
S = {
    ' (concordant)': (' (संगत)', ' (ಹೊಂದಾಣಿಕೆಯ)'),
    'A is proportional to c (Beer–Lambert law): slope {s} per 10⁻⁴ M, so ε = {e} L mol⁻¹ cm⁻¹.': ('A, c के समानुपाती है (बियर–लैम्बर्ट नियम): ढाल {s} प्रति 10⁻⁴ M, अतः ε = {e} L mol⁻¹ cm⁻¹।', 'A, c ಗೆ ಅನುಪಾತೀಯ (ಬಿಯರ್–ಲ್ಯಾಂಬರ್ಟ್ ನಿಯಮ): ಇಳಿಜಾರು ಪ್ರತಿ 10⁻⁴ M ಗೆ {s}, ಆದ್ದರಿಂದ ε = {e} L mol⁻¹ cm⁻¹.'),
    'Absent': ('अनुपस्थित', 'ಇಲ್ಲ'),
    'Acetic acid': ('ऐसीटिक अम्ल', 'ಅಸಿಟಿಕ್ ಆಮ್ಲ'),
    'Acetone': ('ऐसीटोन', 'ಅಸಿಟೋನ್'),
    'Acid': ('अम्ल', 'ಆಮ್ಲ'),
    'Add the reagent': ('अभिकर्मक डालें', 'ಕಾರಕ ಸೇರಿಸಿ'),
    'Add the reagent first.': ('पहले अभिकर्मक डालें।', 'ಮೊದಲು ಕಾರಕ ಸೇರಿಸಿ.'),
    'Ammonium chloride, NH₄Cl': ('अमोनियम क्लोराइड, NH₄Cl', 'ಅಮೋನಿಯಂ ಕ್ಲೋರೈಡ್, NH₄Cl'),
    'Apple green': ('सेब जैसा हरा', 'ಸೇಬು ಹಸಿರು'),
    'At half that volume pH = pKa = {p} (Ka = {k} × 10⁻⁵).': ('उसके आधे आयतन पर pH = pKa = {p} (Ka = {k} × 10⁻⁵)।', 'ಅದರ ಅರ್ಧ ಘನಫಲದಲ್ಲಿ pH = pKa = {p} (Ka = {k} × 10⁻⁵).'),
    'At one temperature 1/t is proportional to the thiosulphate concentration: the reaction is first order in thiosulphate.': ('एक ही ताप पर 1/t थायोसल्फ़ेट की सांद्रता के समानुपाती है: अभिक्रिया थायोसल्फ़ेट में प्रथम कोटि की है।', 'ಒಂದೇ ತಾಪದಲ್ಲಿ 1/t ಥಯೋಸಲ್ಫೇಟ್ ಸಾಂದ್ರತೆಗೆ ಅನುಪಾತೀಯ: ಪ್ರತಿಕ್ರಿಯೆ ಥಯೋಸಲ್ಫೇಟ್‌ನಲ್ಲಿ ಪ್ರಥಮ ಕ್ರಮದ್ದು.'),
    'Barium chloride': ('बेरियम क्लोराइड', 'ಬೇರಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Barium chloride, BaCl₂': ('बेरियम क्लोराइड, BaCl₂', 'ಬೇರಿಯಂ ಕ್ಲೋರೈಡ್, BaCl₂'),
    "Benedict's solution (boil)": ('बेनेडिक्ट विलयन (उबालें)', 'ಬೆನೆಡಿಕ್ಟ್ ದ್ರಾವಣ (ಕುದಿಸಿ)'),
    'Biuret test (NaOH + CuSO₄)': ('बाइयूरेट परीक्षण (NaOH + CuSO₄)', 'ಬೈಯುರೆಟ್ ಪರೀಕ್ಷೆ (NaOH + CuSO₄)'),
    'Black precipitate': ('काला अवक्षेप', 'ಕಪ್ಪು ಅವಕ್ಷೇಪ'),
    'Blue colour': ('नीला रंग', 'ನೀಲಿ ಬಣ್ಣ'),
    'Blue dye': ('नीला रंजक', 'ನೀಲಿ ವರ್ಣಕ'),
    'Blue flame': ('नीली ज्वाला', 'ನೀಲಿ ಜ್ವಾಲೆ'),
    'Blue precipitate': ('नीला अवक्षेप', 'ನೀಲಿ ಅವಕ್ಷೇಪ'),
    'Blue-black colour': ('नीला-काला रंग', 'ನೀಲಿ-ಕಪ್ಪು ಬಣ್ಣ'),
    'Blue-green': ('नीला-हरा', 'ನೀಲಿ-ಹಸಿರು'),
    'Bluish-white precipitate': ('नीलापन लिए सफ़ेद अवक्षेप', 'ನೀಲಿಮಿಶ್ರಿತ ಬಿಳಿ ಅವಕ್ಷೇಪ'),
    'Both solutions at room temperature': ('दोनों विलयन कमरे के ताप पर', 'ಎರಡೂ ದ್ರಾವಣಗಳು ಕೋಣೆಯ ತಾಪದಲ್ಲಿ'),
    'Brick red': ('ईंट जैसा लाल', 'ಇಟ್ಟಿಗೆ ಕೆಂಪು'),
    'Brick-red precipitate on boiling': ('उबालने पर ईंट जैसा लाल अवक्षेप', 'ಕುದಿಸಿದಾಗ ಇಟ್ಟಿಗೆ ಕೆಂಪು ಅವಕ್ಷೇಪ'),
    'Bright yellow precipitate': ('चमकीला पीला अवक्षेप', 'ಹೊಳೆಯುವ ಹಳದಿ ಅವಕ್ಷೇಪ'),
    'Brisk effervescence; the gas turns lime water milky': ('तीव्र बुदबुदाहट; गैस चूने के पानी को दूधिया करती है', 'ತೀವ್ರ ಗುಳ್ಳೆಗಳು; ಅನಿಲ ಸುಣ್ಣದ ನೀರನ್ನು ಹಾಲಿನಂತೆ ಮಾಡುತ್ತದೆ'),
    'Burette': ('ब्यूरेट', 'ಬ್ಯೂರೆಟ್'),
    'Burette {v} mL': ('ब्यूरेट {v} mL', 'ಬ್ಯೂರೆಟ್ {v} mL'),
    'Calcium chloride': ('कैल्सियम क्लोराइड', 'ಕ್ಯಾಲ್ಸಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Carotene (orange)': ('कैरोटीन (नारंगी)', 'ಕ್ಯಾರೋಟಿನ್ (ಕಿತ್ತಳೆ)'),
    'Chlorophyll a (blue-green)': ('क्लोरोफ़िल a (नीला-हरा)', 'ಕ್ಲೋರೋಫಿಲ್ a (ನೀಲಿ-ಹಸಿರು)'),
    'Chlorophyll b (yellow-green)': ('क्लोरोफ़िल b (पीला-हरा)', 'ಕ್ಲೋರೋಫಿಲ್ b (ಹಳದಿ-ಹಸಿರು)'),
    'Chocolate-brown precipitate': ('चॉकलेटी भूरा अवक्षेप', 'ಚಾಕೊಲೇಟ್ ಕಂದು ಅವಕ್ಷೇಪ'),
    'Colourless pungent gas; dense white fumes with a rod dipped in ammonia': ('रंगहीन तीखी गैस; अमोनिया में डुबोई छड़ के पास घने सफ़ेद धूम', 'ಬಣ್ಣರಹಿತ ಘಾಟು ಅನಿಲ; ಅಮೋನಿಯಾದಲ್ಲಿ ಅದ್ದಿದ ಕಡ್ಡಿಯ ಬಳಿ ದಟ್ಟ ಬಿಳಿ ಹೊಗೆ'),
    'Conc. H₂SO₄ (warm)': ('सांद्र H₂SO₄ (गुनगुना करें)', 'ಸಾರೀಕೃತ H₂SO₄ (ಬೆಚ್ಚಗೆ ಮಾಡಿ)'),
    'Conductivity meter': ('चालकतामापी', 'ವಾಹಕತಾಮಾಪಕ'),
    'Copper(II) chloride': ('कॉपर(II) क्लोराइड', 'ತಾಮ್ರ(II) ಕ್ಲೋರೈಡ್'),
    'Copper(II) sulphate, CuSO₄': ('कॉपर(II) सल्फ़ेट, CuSO₄', 'ತಾಮ್ರ(II) ಸಲ್ಫೇಟ್, CuSO₄'),
    'Crimson': ('किरमिजी', 'ಕಡುಗೆಂಪು'),
    'Crimson red': ('किरमिजी लाल', 'ಕಡುಗೆಂಪು ಕೆಂಪು'),
    'Curdy white precipitate, soluble in ammonium hydroxide': ('दही जैसा सफ़ेद अवक्षेप, अमोनियम हाइड्रॉक्साइड में विलेय', 'ಮೊಸರಿನಂತಹ ಬಿಳಿ ಅವಕ್ಷೇಪ, ಅಮೋನಿಯಂ ಹೈಡ್ರಾಕ್ಸೈಡ್‌ನಲ್ಲಿ ಕರಗುತ್ತದೆ'),
    'Cu²⁺ likely': ('Cu²⁺ संभावित', 'Cu²⁺ ಇರಬಹುದು'),
    'Cyan dye': ('सियान रंजक', 'ಸಯಾನ್ ವರ್ಣಕ'),
    'Deep blue solution with excess': ('अधिकता में गहरा नीला विलयन', 'ಹೆಚ್ಚುವರಿಯಲ್ಲಿ ಗಾಢ ನೀಲಿ ದ್ರಾವಣ'),
    'Dil. HCl (group I)': ('तनु HCl (समूह I)', 'ವಿರಳ HCl (ಗುಂಪು I)'),
    'Dil. H₂SO₄ (on the solid)': ('तनु H₂SO₄ (ठोस पर)', 'ವಿರಳ H₂SO₄ (ಘನದ ಮೇಲೆ)'),
    'Disodium hydrogen phosphate + NH₄OH': ('डाइसोडियम हाइड्रोजन फ़ॉस्फ़ेट + NH₄OH', 'ಡೈಸೋಡಿಯಂ ಹೈಡ್ರೋಜನ್ ಫಾಸ್ಫೇಟ್ + NH₄OH'),
    'Dull grey-black deposit on the copper strip': ('तांबे की पट्टी पर धुँधला धूसर-काला जमाव', 'ತಾಮ್ರದ ಪಟ್ಟಿಯ ಮೇಲೆ ಮಸುಕಾದ ಬೂದು-ಕಪ್ಪು ಲೇಪ'),
    'Each metal ion gives its own flame colour because its electrons, excited by the heat, give out light of particular wavelengths as they fall back.': ('हर धातु आयन अपना ज्वाला रंग देता है क्योंकि ऊष्मा से उत्तेजित उसके इलेक्ट्रॉन वापस गिरते समय विशेष तरंगदैर्ध्य का प्रकाश देते हैं।', 'ಪ್ರತಿ ಲೋಹ ಅಯಾನು ತನ್ನದೇ ಜ್ವಾಲೆ ಬಣ್ಣ ನೀಡುತ್ತದೆ: ಶಾಖದಿಂದ ಉದ್ರೇಕಗೊಂಡ ಅದರ ಎಲೆಕ್ಟ್ರಾನುಗಳು ಹಿಂದಿರುಗುವಾಗ ನಿರ್ದಿಷ್ಟ ತರಂಗಾಂತರದ ಬೆಳಕು ಹೊರಸೂಸುತ್ತವೆ.'),
    'Each pigment has its own Rf: the more soluble in the solvent and the less held by the paper, the higher it travels.': ('हर वर्णक का अपना Rf है: जो विलायक में जितना अधिक घुलता है और कागज़ से जितना कम बँधता है, वह उतना ऊपर जाता है।', 'ಪ್ರತಿ ವರ್ಣದ್ರವ್ಯಕ್ಕೂ ತನ್ನದೇ Rf: ದ್ರಾವಕದಲ್ಲಿ ಹೆಚ್ಚು ಕರಗುವ ಮತ್ತು ಕಾಗದಕ್ಕೆ ಕಡಿಮೆ ಅಂಟುವದು ಹೆಚ್ಚು ಎತ್ತರ ಸಾಗುತ್ತದೆ.'),
    'Egg albumin': ('अंडे का एल्ब्यूमिन', 'ಮೊಟ್ಟೆಯ ಆಲ್ಬುಮಿನ್'),
    'End point': ('अंतिम बिंदु', 'ಅಂತ್ಯ ಬಿಂದು'),
    'Ethanol': ('एथेनॉल', 'ಎಥನಾಲ್'),
    'Exhibit {n}': ('प्रदर्श {n}', 'ಪ್ರದರ್ಶಿತ ವಸ್ತು {n}'),
    'Fat present': ('वसा उपस्थित', 'ಕೊಬ್ಬು ಇದೆ'),
    'Ferric chloride': ('फ़ेरिक क्लोराइड', 'ಫೆರಿಕ್ ಕ್ಲೋರೈಡ್'),
    'Fe³⁺ likely': ('Fe³⁺ संभावित', 'Fe³⁺ ಇರಬಹುದು'),
    'Final (mL)': ('अंतिम (mL)', 'ಅಂತಿಮ (mL)'),
    'Flame colour': ('ज्वाला का रंग', 'ಜ್ವಾಲೆಯ ಬಣ್ಣ'),
    'Glucose solution': ('ग्लूकोज़ विलयन', 'ಗ್ಲೂಕೋಸ್ ದ್ರಾವಣ'),
    'Glycerol (20% in water)': ('ग्लिसरॉल (जल में 20%)', 'ಗ್ಲಿಸರಾಲ್ (ನೀರಿನಲ್ಲಿ 20%)'),
    'Golden yellow': ('सुनहरा पीला', 'ಚಿನ್ನದ ಹಳದಿ'),
    'Groundnut oil': ('मूँगफली का तेल', 'ಕಡಲೆಕಾಯಿ ಎಣ್ಣೆ'),
    'Group I: Pb²⁺': ('समूह I: Pb²⁺', 'ಗುಂಪು I: Pb²⁺'),
    'Group II: Cu²⁺ or Pb²⁺': ('समूह II: Cu²⁺ या Pb²⁺', 'ಗುಂಪು II: Cu²⁺ ಅಥವಾ Pb²⁺'),
    'Group III: Fe³⁺': ('समूह III: Fe³⁺', 'ಗುಂಪು III: Fe³⁺'),
    'Highest T (°C)': ('अधिकतम T (°C)', 'ಗರಿಷ್ಠ T (°C)'),
    'Highest temperature': ('अधिकतम ताप', 'ಗರಿಷ್ಠ ತಾಪ'),
    'Hold the wire in the flame': ('तार को ज्वाला में रखें', 'ತಂತಿಯನ್ನು ಜ್ವಾಲೆಯಲ್ಲಿ ಹಿಡಿಯಿರಿ'),
    'Hydrochloric acid': ('हाइड्रोक्लोरिक अम्ल', 'ಹೈಡ್ರೋಕ್ಲೋರಿಕ್ ಆಮ್ಲ'),
    'H₂S in dil. HCl (group II)': ('तनु HCl में H₂S (समूह II)', 'ವಿರಳ HCl ನಲ್ಲಿ H₂S (ಗುಂಪು II)'),
    'Inference': ('निष्कर्ष', 'ಅನುಮಾನ'),
    'Initial (mL)': ('प्रारंभिक (mL)', 'ಆರಂಭಿಕ (mL)'),
    'Initial T (°C)': ('प्रारंभिक T (°C)', 'ಆರಂಭಿಕ T (°C)'),
    'Ink from the questioned note': ('संदिग्ध पत्र की स्याही', 'ಸಂಶಯಾಸ್ಪದ ಪತ್ರದ ಶಾಯಿ'),
    'Insoluble sulphate: Ba²⁺ or Pb²⁺ likely': ('अविलेय सल्फ़ेट: Ba²⁺ या Pb²⁺ संभावित', 'ಕರಗದ ಸಲ್ಫೇಟ್: Ba²⁺ ಅಥವಾ Pb²⁺ ಇರಬಹುದು'),
    'Iodine solution': ('आयोडीन विलयन', 'ಅಯೋಡಿನ್ ದ್ರಾವಣ'),
    'Iron(III) chloride, FeCl₃': ('आयरन(III) क्लोराइड, FeCl₃', 'ಕಬ್ಬಿಣ(III) ಕ್ಲೋರೈಡ್, FeCl₃'),
    'Keep testing: no sample is fully identified yet.': ('परीक्षण जारी रखें: अभी कोई नमूना पूरी तरह पहचाना नहीं गया।', 'ಪರೀಕ್ಷೆ ಮುಂದುವರಿಸಿ: ಇನ್ನೂ ಯಾವ ಮಾದರಿಯೂ ಪೂರ್ಣವಾಗಿ ಗುರುತಾಗಿಲ್ಲ.'),
    'Lead(II) nitrate, Pb(NO₃)₂': ('लेड(II) नाइट्रेट, Pb(NO₃)₂', 'ಸೀಸ(II) ನೈಟ್ರೇಟ್, Pb(NO₃)₂'),
    'Let the solvent run further before measuring (at least half-way up).': ('मापने से पहले विलायक को और ऊपर चढ़ने दें (कम से कम आधे तक)।', 'ಅಳೆಯುವ ಮೊದಲು ದ್ರಾವಕ ಇನ್ನಷ್ಟು ಏರಲಿ (ಕನಿಷ್ಠ ಅರ್ಧದವರೆಗೆ).'),
    'Light pink': ('हल्का गुलाबी', 'ತಿಳಿ ಗುಲಾಬಿ'),
    'Lilac': ('बैंगनी-गुलाबी (लाइलैक)', 'ನಸುನೇರಳೆ'),
    'Lithium chloride': ('लिथियम क्लोराइड', 'ಲಿಥಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Magnesium carbonate, MgCO₃': ('मैग्नीशियम कार्बोनेट, MgCO₃', 'ಮೆಗ್ನೀಸಿಯಂ ಕಾರ್ಬೋನೇಟ್, MgCO₃'),
    'Marquis reagent': ('मार्की अभिकर्मक', 'ಮಾರ್ಕಿ ಕಾರಕ'),
    'Measure spot': ('धब्बा मापें', 'ಚುಕ್ಕೆ ಅಳೆಯಿರಿ'),
    'Metal ion': ('धातु आयन', 'ಲೋಹ ಅಯಾನು'),
    'Methyl acetate + HCl': ('मेथिल ऐसीटेट + HCl', 'ಮೀಥೈಲ್ ಅಸಿಟೇಟ್ + HCl'),
    'Mg²⁺ likely': ('Mg²⁺ संभावित', 'Mg²⁺ ಇರಬಹುದು'),
    'Milk': ('दूध', 'ಹಾಲು'),
    'Mix the acid and the alkali first.': ('पहले अम्ल और क्षार मिलाएँ।', 'ಮೊದಲು ಆಮ್ಲ ಮತ್ತು ಕ್ಷಾರ ಬೆರೆಸಿ.'),
    "Mohr's salt": ('मोर लवण', 'ಮೋರ್ ಲವಣ'),
    'Molarity found (M)': ('प्राप्त मोलरता (M)', 'ಕಂಡುಬಂದ ಮೋಲಾರಿಟಿ (M)'),
    'NH₄Cl + NH₄OH (group III)': ('NH₄Cl + NH₄OH (समूह III)', 'NH₄Cl + NH₄OH (ಗುಂಪು III)'),
    'NaOH added': ('डाला गया NaOH', 'ಸೇರಿಸಿದ NaOH'),
    'Negative': ('ऋणात्मक', 'ಋಣಾತ್ಮಕ'),
    'New titration': ('नया अनुमापन', 'ಹೊಸ ಅನುಮಾಪನ'),
    'No change (the reagent keeps its colour)': ('कोई परिवर्तन नहीं (अभिकर्मक का रंग वही रहता है)', 'ಬದಲಾವಣೆ ಇಲ್ಲ (ಕಾರಕದ ಬಣ್ಣ ಹಾಗೇ ಇರುತ್ತದೆ)'),
    'No pen measured so far gives the same spots and Rf values as the note.': ('अब तक मापा गया कोई पेन पत्र जैसे धब्बे और Rf मान नहीं देता।', 'ಇದುವರೆಗೆ ಅಳೆದ ಯಾವ ಪೆನ್ನೂ ಪತ್ರದಂತೆಯೇ ಚುಕ್ಕೆಗಳು ಮತ್ತು Rf ಮೌಲ್ಯಗಳನ್ನು ನೀಡುವುದಿಲ್ಲ.'),
    'Not at the end point yet: add the titrant drop by drop, swirling the flask.': ('अभी अंतिम बिंदु नहीं आया: फ्लास्क घुमाते हुए अनुमापक बूँद-बूँद डालें।', 'ಇನ್ನೂ ಅಂತ್ಯ ಬಿಂದು ಬಂದಿಲ್ಲ: ಫ್ಲಾಸ್ಕ್ ತಿರುಗಿಸುತ್ತಾ ಅನುಮಾಪಕವನ್ನು ಹನಿ ಹನಿಯಾಗಿ ಸೇರಿಸಿ.'),
    'Observation': ('प्रेक्षण', 'ವೀಕ್ಷಣೆ'),
    'On warming, a gas smelling of ammonia; turns moist red litmus blue': ('गरम करने पर अमोनिया गंध वाली गैस; नम लाल लिटमस को नीला करती है', 'ಬಿಸಿಮಾಡಿದಾಗ ಅಮೋನಿಯಾ ವಾಸನೆಯ ಅನಿಲ; ತೇವ ಕೆಂಪು ಲಿಟ್ಮಸ್ ನೀಲಿಯಾಗುತ್ತದೆ'),
    'Orange turning brown': ('नारंगी जो भूरा होता जाता है', 'ಕಿತ್ತಳೆ, ನಂತರ ಕಂದು'),
    'Orange-red precipitate on boiling': ('उबालने पर नारंगी-लाल अवक्षेप', 'ಕುದಿಸಿದಾಗ ಕಿತ್ತಳೆ-ಕೆಂಪು ಅವಕ್ಷೇಪ'),
    'Oxalic acid': ('ऑक्ज़ैलिक अम्ल', 'ಆಕ್ಸಾಲಿಕ್ ಆಮ್ಲ'),
    'Pale blue precipitate': ('हल्का नीला अवक्षेप', 'ತಿಳಿ ನೀಲಿ ಅವಕ್ಷೇಪ'),
    'Pb²⁺ or Ba²⁺': ('Pb²⁺ या Ba²⁺', 'Pb²⁺ ಅಥವಾ Ba²⁺'),
    'Pb²⁺, Zn²⁺ or Al³⁺ likely': ('Pb²⁺, Zn²⁺ या Al³⁺ संभावित', 'Pb²⁺, Zn²⁺ ಅಥವಾ Al³⁺ ಇರಬಹುದು'),
    'Pen A (suspect 1)': ('पेन A (संदिग्ध 1)', 'ಪೆನ್ A (ಶಂಕಿತ 1)'),
    'Pen B (suspect 2)': ('पेन B (संदिग्ध 2)', 'ಪೆನ್ B (ಶಂಕಿತ 2)'),
    'Pen C (suspect 3)': ('पेन C (संदिग्ध 3)', 'ಪೆನ್ C (ಶಂಕಿತ 3)'),
    'Pink dye': ('गुलाबी रंजक', 'ಗುಲಾಬಿ ವರ್ಣಕ'),
    'Potassium chloride': ('पोटैशियम क्लोराइड', 'ಪೊಟ್ಯಾಸಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Potassium chromate': ('पोटैशियम क्रोमेट', 'ಪೊಟ್ಯಾಸಿಯಂ ಕ್ರೋಮೇಟ್'),
    'Potassium ferrocyanide': ('पोटैशियम फ़ेरोसायनाइड', 'ಪೊಟ್ಯಾಸಿಯಂ ಫೆರೋಸಯನೈಡ್'),
    'Potassium iodide': ('पोटैशियम आयोडाइड', 'ಪೊಟ್ಯಾಸಿಯಂ ಅಯೋಡೈಡ್'),
    'Potassium permanganate': ('पोटैशियम परमैंगनेट', 'ಪೊಟ್ಯಾಸಿಯಂ ಪರ್ಮ್ಯಾಂಗನೇಟ್'),
    'Pour in the NaOH and stir': ('NaOH डालें और हिलाएँ', 'NaOH ಸುರಿದು ಕಲಕಿ'),
    'Presumptive: a phenol (morphine gives this)': ('अनुमानित: एक फ़ीनॉल (मॉर्फ़ीन यह देता है)', 'ಊಹಾತ್ಮಕ: ಒಂದು ಫೀನಾಲ್ (ಮಾರ್ಫೀನ್ ಇದನ್ನು ನೀಡುತ್ತದೆ)'),
    'Presumptive: a salicylate (such as aspirin)': ('अनुमानित: एक सैलिसिलेट (जैसे ऐस्पिरिन)', 'ಊಹಾತ್ಮಕ: ಒಂದು ಸ್ಯಾಲಿಸಿಲೇಟ್ (ಆಸ್ಪಿರಿನ್‌ನಂತೆ)'),
    'Presumptive: an amphetamine': ('अनुमानित: एक ऐम्फ़ेटामीन', 'ಊಹಾತ್ಮಕ: ಒಂದು ಆಂಫೆಟಮೈನ್'),
    'Presumptive: an opiate (such as morphine)': ('अनुमानित: एक ओपिएट (जैसे मॉर्फ़ीन)', 'ಊಹಾತ್ಮಕ: ಒಂದು ಓಪಿಯೇಟ್ (ಮಾರ್ಫೀನ್‌ನಂತೆ)'),
    'Presumptive: arsenic (or mercury, antimony)': ('अनुमानित: आर्सेनिक (या पारा, ऐन्टिमनी)', 'ಊಹಾತ್ಮಕ: ಆರ್ಸೆನಿಕ್ (ಅಥವಾ ಪಾದರಸ, ಆಂಟಿಮನಿ)'),
    'Presumptive: cocaine': ('अनुमानित: कोकेन', 'ಊಹಾತ್ಮಕ: ಕೊಕೇನ್'),
    'Protein present': ('प्रोटीन उपस्थित', 'ಪ್ರೋಟೀನ್ ಇದೆ'),
    'Prussian blue colour': ('प्रशियन नीला रंग', 'ಪ್ರಷ್ಯನ್ ನೀಲಿ ಬಣ್ಣ'),
    'Purple-violet colour': ('बैंगनी रंग', 'ನೇರಳೆ ಬಣ್ಣ'),
    'Put the wire with the salt into the flame first.': ('पहले लवण लगे तार को ज्वाला में रखें।', 'ಮೊದಲು ಲವಣವಿರುವ ತಂತಿಯನ್ನು ಜ್ವಾಲೆಗೆ ಹಿಡಿಯಿರಿ.'),
    'Raising the temperature from {a} °C to {b} °C made the reaction {r} times faster.': ('ताप {a} °C से {b} °C करने पर अभिक्रिया {r} गुना तेज़ हुई।', 'ತಾಪವನ್ನು {a} °C ನಿಂದ {b} °C ಗೆ ಏರಿಸಿದಾಗ ಪ್ರತಿಕ್ರಿಯೆ {r} ಪಟ್ಟು ವೇಗವಾಯಿತು.'),
    'Reagent': ('अभिकर्मक', 'ಕಾರಕ'),
    'Red-stained oily layer floats on top': ('लाल रँगी तैलीय परत ऊपर तैरती है', 'ಕೆಂಪು ಬಣ್ಣದ ಎಣ್ಣೆಯ ಪದರ ಮೇಲೆ ತೇಲುತ್ತದೆ'),
    'Reddish-brown precipitate': ('लाल-भूरा अवक्षेप', 'ಕೆಂಪು-ಕಂದು ಅವಕ್ಷೇಪ'),
    'Reducing sugar (lactose) present': ('अपचायी शर्करा (लैक्टोज़) उपस्थित', 'ಅಪಕರ್ಷಕ ಸಕ್ಕರೆ (ಲ್ಯಾಕ್ಟೋಸ್) ಇದೆ'),
    'Reducing sugar present': ('अपचायी शर्करा उपस्थित', 'ಅಪಕರ್ಷಕ ಸಕ್ಕರೆ ಇದೆ'),
    'Reinsch test (copper strip)': ('राइन्श परीक्षण (तांबे की पट्टी)', 'ರೈನ್ಶ್ ಪರೀಕ್ಷೆ (ತಾಮ್ರದ ಪಟ್ಟಿ)'),
    'Rub on paper': ('कागज़ पर रगड़ें', 'ಕಾಗದದ ಮೇಲೆ ಉಜ್ಜಿ'),
    'Run the titrant in from the burette first.': ('पहले ब्यूरेट से अनुमापक डालें।', 'ಮೊದಲು ಬ್ಯೂರೆಟ್‌ನಿಂದ ಅನುಮಾಪಕ ಹರಿಸಿ.'),
    'Salt on the wire': ('तार पर लवण', 'ತಂತಿಯ ಮೇಲೆ ಲವಣ'),
    'Salt {s}': ('लवण {s}', 'ಲವಣ {s}'),
    'Salt {s} is {n}.': ('लवण {s} है: {n}।', 'ಲವಣ {s}: {n}.'),
    'Sample {s}: mean titre {v} mL{c}, so its molarity is {m} M.': ('नमूना {s}: औसत अनुमापांक {v} mL{c}, अतः इसकी मोलरता {m} M है।', 'ಮಾದರಿ {s}: ಸರಾಸರಿ ಅನುಮಾಪನಾಂಕ {v} mL{c}, ಆದ್ದರಿಂದ ಮೋಲಾರಿಟಿ {m} M.'),
    'Scott (cobalt thiocyanate) test': ('स्कॉट (कोबाल्ट थायोसायनेट) परीक्षण', 'ಸ್ಕಾಟ್ (ಕೋಬಾಲ್ಟ್ ಥಯೋಸಯನೇಟ್) ಪರೀಕ್ಷೆ'),
    'Silver nitrate': ('सिल्वर नाइट्रेट', 'ಸಿಲ್ವರ್ ನೈಟ್ರೇಟ್'),
    'Sodium chloride': ('सोडियम क्लोराइड', 'ಸೋಡಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Sodium hydroxide': ('सोडियम हाइड्रॉक्साइड', 'ಸೋಡಿಯಂ ಹೈಡ್ರಾಕ್ಸೈಡ್'),
    'Sodium hydroxide (warm)': ('सोडियम हाइड्रॉक्साइड (गुनगुना करें)', 'ಸೋಡಿಯಂ ಹೈಡ್ರಾಕ್ಸೈಡ್ (ಬೆಚ್ಚಗೆ ಮಾಡಿ)'),
    'Solvent front (cm)': ('विलायक अग्र (cm)', 'ದ್ರಾವಕ ಮುಂಚೂಣಿ (cm)'),
    'Solvent front {f} cm': ('विलायक अग्र {f} cm', 'ದ್ರಾವಕ ಮುಂಚೂಣಿ {f} cm'),
    'Spinach leaf extract': ('पालक पत्ती का सत्त', 'ಪಾಲಕ್ ಎಲೆಯ ಸಾರ'),
    'Spot': ('धब्बा', 'ಚುಕ್ಕೆ'),
    'Spot distance (cm)': ('धब्बे की दूरी (cm)', 'ಚುಕ್ಕೆಯ ದೂರ (cm)'),
    'Standard': ('मानक', 'ಮಾನಕ'),
    'Starch present': ('मंड उपस्थित', 'ಪಿಷ್ಟ ಇದೆ'),
    'Starch solution': ('मंड विलयन', 'ಪಿಷ್ಟ ದ್ರಾವಣ'),
    'Steepest rise (largest ΔpH/ΔV) at {v} mL: the equivalence point, so the acid is {c} M.{pka}': ('सबसे तीव्र वृद्धि (अधिकतम ΔpH/ΔV) {v} mL पर: यही तुल्यता बिंदु है, अतः अम्ल {c} M है।{pka}', 'ಅತ್ಯಂತ ಕಡಿದಾದ ಏರಿಕೆ (ಗರಿಷ್ಠ ΔpH/ΔV) {v} mL ನಲ್ಲಿ: ಅದೇ ಸಮಾನತಾ ಬಿಂದು, ಆದ್ದರಿಂದ ಆಮ್ಲ {c} M.{pka}'),
    'Strontium chloride': ('स्ट्रॉन्शियम क्लोराइड', 'ಸ್ಟ್ರಾನ್ಶಿಯಂ ಕ್ಲೋರೈಡ್'),
    'Sudan III': ('सूडान III', 'ಸುಡಾನ್ III'),
    'Sulphur is clouding the solution…': ('गंधक विलयन को धुँधला कर रहा है…', 'ಗಂಧಕ ದ್ರಾವಣವನ್ನು ಮಸುಕಾಗಿಸುತ್ತಿದೆ…'),
    'Take at least three titrations at different times.': ('अलग-अलग समय पर कम से कम तीन अनुमापन करें।', 'ಬೇರೆ ಬೇರೆ ಸಮಯಗಳಲ್ಲಿ ಕನಿಷ್ಠ ಮೂರು ಅನುಮಾಪನ ಮಾಡಿ.'),
    'Take more readings, closer together near the steep rise.': ('और पाठ्यांक लें, तीव्र वृद्धि के पास अधिक निकट।', 'ಇನ್ನಷ್ಟು ಓದುವಿಕೆ ತೆಗೆದುಕೊಳ್ಳಿ, ಕಡಿದಾದ ಏರಿಕೆಯ ಬಳಿ ಹತ್ತಿರ ಹತ್ತಿರ.'),
    'Take readings before and well after the turning point.': ('मोड़ बिंदु से पहले और काफ़ी बाद तक पाठ्यांक लें।', 'ತಿರುವು ಬಿಂದುವಿನ ಮೊದಲು ಮತ್ತು ಸಾಕಷ್ಟು ನಂತರ ಓದುವಿಕೆ ತೆಗೆದುಕೊಳ್ಳಿ.'),
    'Temperature': ('ताप', 'ತಾಪ'),
    'Test': ('परीक्षण', 'ಪರೀಕ್ಷೆ'),
    'The absorbance is largest near {l} nm: work at λmax.': ('अवशोषणांक {l} nm के पास सबसे अधिक है: λmax पर काम करें।', 'ಹೀರಿಕೆ {l} nm ಬಳಿ ಗರಿಷ್ಠ: λmax ನಲ್ಲಿ ಕೆಲಸ ಮಾಡಿ.'),
    'The cross has disappeared': ('क्रॉस का निशान ओझल हो गया', 'ಅಡ್ಡಗುರುತು ಮರೆಯಾಯಿತು'),
    'The ink of the note separates into the same dyes with the same Rf values as {p}: that pen could have written it (supporting, not conclusive, evidence).': ('पत्र की स्याही {p} जैसे ही रंजकों में उन्हीं Rf मानों के साथ अलग होती है: वह पेन इसे लिख सकता था (सहायक, निर्णायक नहीं, साक्ष्य)।', 'ಪತ್ರದ ಶಾಯಿ {p} ನಂತೆಯೇ ಅದೇ Rf ಮೌಲ್ಯಗಳ ವರ್ಣಕಗಳಾಗಿ ಬೇರ್ಪಡುತ್ತದೆ: ಆ ಪೆನ್ ಅದನ್ನು ಬರೆದಿರಬಹುದು (ಬೆಂಬಲ ಸಾಕ್ಷ್ಯ, ನಿರ್ಣಾಯಕವಲ್ಲ).'),
    'The unknown has A = {a}, so its concentration is {c} × 10⁻⁴ M.': ('अज्ञात का A = {a}, अतः उसकी सांद्रता {c} × 10⁻⁴ M है।', 'ಅಜ್ಞಾತದ A = {a}, ಆದ್ದರಿಂದ ಅದರ ಸಾಂದ್ರತೆ {c} × 10⁻⁴ M.'),
    'The weak acid gives slightly less heat: some energy is used to ionise it completely.': ('दुर्बल अम्ल थोड़ी कम ऊष्मा देता है: कुछ ऊर्जा उसे पूरी तरह आयनित करने में लगती है।', 'ದುರ್ಬಲ ಆಮ್ಲ ಸ್ವಲ್ಪ ಕಡಿಮೆ ಶಾಖ ನೀಡುತ್ತದೆ: ಕೆಲವು ಶಕ್ತಿ ಅದನ್ನು ಪೂರ್ಣ ಅಯಾನೀಕರಿಸಲು ಬಳಕೆಯಾಗುತ್ತದೆ.'),
    'Thiosulphate (mL of 0.1 M, made up to 50 mL)': ('थायोसल्फ़ेट (0.1 M के mL, 50 mL तक बनाया)', 'ಥಯೋಸಲ್ಫೇಟ್ (0.1 M ನ mL, 50 mL ಗೆ ತುಂಬಿಸಿದ)'),
    'Tiny red-stained droplets': ('लाल रँगी नन्ही बूँदें', 'ಕೆಂಪು ಬಣ್ಣದ ಸಣ್ಣ ಹನಿಗಳು'),
    'Translucent greasy spot on paper': ('कागज़ पर पारभासी चिकना धब्बा', 'ಕಾಗದದ ಮೇಲೆ ಅರೆಪಾರದರ್ಶಕ ಜಿಡ್ಡಿನ ಕಲೆ'),
    'Unknown': ('अज्ञात', 'ಅಜ್ಞಾತ'),
    'Violet colour': ('बैंगनी रंग', 'ನೇರಳೆ ಬಣ್ಣ'),
    'Violet dye': ('बैंगनी रंजक', 'ನೇರಳೆ ವರ್ಣಕ'),
    'Volume used (mL)': ('प्रयुक्त आयतन (mL)', 'ಬಳಸಿದ ಘನಫಲ (mL)'),
    'Wavelength': ('तरंगदैर्ध्य', 'ತರಂಗಾಂತರ'),
    'White crystalline precipitate on scratching': ('खुरचने पर सफ़ेद क्रिस्टलीय अवक्षेप', 'ಕೆರೆದಾಗ ಬಿಳಿ ಸ್ಫಟಿಕ ಅವಕ್ಷೇಪ'),
    'White precipitate, dissolves in excess': ('सफ़ेद अवक्षेप, अधिकता में घुल जाता है', 'ಬಿಳಿ ಅವಕ್ಷೇಪ, ಹೆಚ್ಚುವರಿಯಲ್ಲಿ ಕರಗುತ್ತದೆ'),
    'White precipitate, dissolves in excess NaOH': ('सफ़ेद अवक्षेप, अधिक NaOH में घुल जाता है', 'ಬಿಳಿ ಅವಕ್ಷೇಪ, ಹೆಚ್ಚುವರಿ NaOH ನಲ್ಲಿ ಕರಗುತ್ತದೆ'),
    'White precipitate, dissolves in hot water': ('सफ़ेद अवक्षेप, गरम पानी में घुल जाता है', 'ಬಿಳಿ ಅವಕ್ಷೇಪ, ಬಿಸಿನೀರಿನಲ್ಲಿ ಕರಗುತ್ತದೆ'),
    'White precipitate, insoluble in conc. HCl': ('सफ़ेद अवक्षेप, सांद्र HCl में अविलेय', 'ಬಿಳಿ ಅವಕ್ಷೇಪ, ಸಾರೀಕೃತ HCl ನಲ್ಲಿ ಕರಗದು'),
    'White precipitate, insoluble in excess NaOH': ('सफ़ेद अवक्षेप, अधिक NaOH में अविलेय', 'ಬಿಳಿ ಅವಕ್ಷೇಪ, ಹೆಚ್ಚುವರಿ NaOH ನಲ್ಲಿ ಕರಗದು'),
    'With copper turnings: reddish-brown fumes': ('तांबे की छीलन के साथ: लाल-भूरे धूम', 'ತಾಮ್ರದ ಚೂರುಗಳೊಂದಿಗೆ: ಕೆಂಪು-ಕಂದು ಹೊಗೆ'),
    'Xanthophyll (yellow)': ('ज़ैंथोफ़िल (पीला)', 'ಕ್ಸಾಂಥೋಫಿಲ್ (ಹಳದಿ)'),
    'Yellow dye': ('पीला रंजक', 'ಹಳದಿ ವರ್ಣಕ'),
    'Yellow precipitate (in acetic acid)': ('पीला अवक्षेप (ऐसीटिक अम्ल में)', 'ಹಳದಿ ಅವಕ್ಷೇಪ (ಅಸಿಟಿಕ್ ಆಮ್ಲದಲ್ಲಿ)'),
    'You have gone past the end point (the colour is too deep). Start a new titration.': ('आप अंतिम बिंदु से आगे निकल गए (रंग बहुत गहरा है)। नया अनुमापन शुरू करें।', 'ನೀವು ಅಂತ್ಯ ಬಿಂದುವನ್ನು ದಾಟಿದ್ದೀರಿ (ಬಣ್ಣ ತುಂಬ ಗಾಢ). ಹೊಸ ಅನುಮಾಪನ ಆರಂಭಿಸಿ.'),
    'Zinc sulphate, ZnSO₄': ('ज़िंक सल्फ़ेट, ZnSO₄', 'ಸತು ಸಲ್ಫೇಟ್, ZnSO₄'),
    'Zn²⁺ likely': ('Zn²⁺ संभावित', 'Zn²⁺ ಇರಬಹುದು'),
    'a salicylate': ('एक सैलिसिलेट', 'ಒಂದು ಸ್ಯಾಲಿಸಿಲೇಟ್'),
    'an amphetamine': ('एक ऐम्फ़ेटामीन', 'ಒಂದು ಆಂಫೆಟಮೈನ್'),
    'an opiate': ('एक ओपिएट', 'ಒಂದು ಓಪಿಯೇಟ್'),
    'arsenic': ('आर्सेनिक', 'ಆರ್ಸೆನಿಕ್'),
    'cocaine': ('कोकेन', 'ಕೊಕೇನ್'),
    'fat': ('वसा', 'ಕೊಬ್ಬು'),
    'in the burette: {b}': ('ब्यूरेट में: {b}', 'ಬ್ಯೂರೆಟ್‌ನಲ್ಲಿ: {b}'),
    'pH meter': ('pH मीटर', 'pH ಮೀಟರ್'),
    'protein': ('प्रोटीन', 'ಪ್ರೋಟೀನ್'),
    'reducing sugar': ('अपचायी शर्करा', 'ಅಪಕರ್ಷಕ ಸಕ್ಕರೆ'),
    'starch': ('मंड', 'ಪಿಷ್ಟ'),
    '{a}: the two straight parts meet at {v} mL, the equivalence point, so the acid is {c} M.': ('{a}: दोनों सीधे भाग {v} mL पर मिलते हैं, यही तुल्यता बिंदु है, अतः अम्ल {c} M है।', '{a}: ಎರಡು ನೇರ ಭಾಗಗಳು {v} mL ನಲ್ಲಿ ಸಂಧಿಸುತ್ತವೆ, ಅದೇ ಸಮಾನತಾ ಬಿಂದು, ಆದ್ದರಿಂದ ಆಮ್ಲ {c} M.'),
    '{a}: ΔH = {h} kJ/mol of water formed.': ('{a}: ΔH = {h} kJ प्रति मोल बने जल।', '{a}: ΔH = ಉಂಟಾದ ನೀರಿನ ಪ್ರತಿ ಮೋಲ್‌ಗೆ {h} kJ.'),
    '{l}: η = η_water × ρt ÷ (ρ_w t_w) = {e} mPa s.': ('{l}: η = η_जल × ρt ÷ (ρ_w t_w) = {e} mPa s।', '{l}: η = η_ನೀರು × ρt ÷ (ρ_w t_w) = {e} mPa s.'),
    '{r} present': ('{r} उपस्थित', '{r} ಇದೆ'),
    '{s} contains: {f}.': ('{s} में है: {f}।', '{s} ಒಳಗೊಂಡಿದೆ: {f}.'),
    '{s}: {f}. A presumptive test only narrows it down; a laboratory confirms with chromatography or spectroscopy.': ('{s}: {f}। अनुमानात्मक परीक्षण केवल संभावनाएँ घटाता है; प्रयोगशाला वर्णलेखन या स्पेक्ट्रमिकी से पुष्टि करती है।', '{s}: {f}. ಊಹಾತ್ಮಕ ಪರೀಕ್ಷೆ ಸಾಧ್ಯತೆಗಳನ್ನು ಮಾತ್ರ ಕಿರಿದಾಗಿಸುತ್ತದೆ; ಪ್ರಯೋಗಾಲಯ ವರ್ಣರೇಖನ ಅಥವಾ ರೋಹಿತದರ್ಶನದಿಂದ ದೃಢೀಕರಿಸುತ್ತದೆ.'),
    '{t} °C: log(V∞ − Vt) falls in a straight line, so the reaction is first order; k = −2.303 × slope = {k} per min (half-life {h} min).': ('{t} °C: log(V∞ − Vt) सरल रेखा में घटता है, अतः अभिक्रिया प्रथम कोटि की है; k = −2.303 × ढाल = {k} प्रति मिनट (अर्धायु {h} मिनट)।', '{t} °C: log(V∞ − Vt) ನೇರ ರೇಖೆಯಲ್ಲಿ ಇಳಿಯುತ್ತದೆ, ಆದ್ದರಿಂದ ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರಥಮ ಕ್ರಮದ್ದು; k = −2.303 × ಇಳಿಜಾರು = ನಿಮಿಷಕ್ಕೆ {k} (ಅರ್ಧಾಯು {h} ನಿಮಿಷ).'),
}
