import 'package:flutter/widgets.dart';

import '../../l10n/feature_strings.dart';

FeatureStrings classroomStrings(BuildContext context) => FeatureStrings(boardLang(context), classroomStringTable);

const classroomStringTable = <String, Map<String, String>>{
  'en': {
    'seating': 'Seating chart',
    'seatingHint': 'Drag a student onto another seat to swap. The plan is kept for this class.',
    'rows': 'Rows',
    'cols': 'Columns',
    'shuffle': 'Shuffle',
    'alphabetical': 'A to Z',
    'empty': 'Empty',
    'front': 'Front (board)',
    'groups': 'Group maker',
    'groupCount': 'Groups: {n}',
    'make': 'Make groups',
    'group': 'Group {n}',
    'toBoard': 'Put on the board',
    'onBoard': 'Put on the board',
    'noRoster': 'Open a class to use its students (the sample class is shown).',
    'magnifier': 'Magnifier',
    'magnifierHint': 'Drag the lens over the board',
    'notes': "Teacher's notes",
    'notesPrivate': 'Private: only on this panel. Not shown on the projector, the live view or recordings.',
    'notesHint': 'Reminders for this class, answers, who to check on…',
    'saved': 'Saved',
    'close': 'Close',
  },
  'hi': {
    'seating': 'बैठक व्यवस्था',
    'seatingHint': 'अदला-बदली के लिए विद्यार्थी को दूसरी सीट पर खींचें। योजना इस कक्षा के लिए रखी जाती है।',
    'rows': 'पंक्तियाँ',
    'cols': 'स्तंभ',
    'shuffle': 'मिलाएँ',
    'alphabetical': 'अ से ज्ञ',
    'empty': 'खाली',
    'front': 'आगे (बोर्ड)',
    'groups': 'समूह बनाएँ',
    'groupCount': 'समूह: {n}',
    'make': 'समूह बनाएँ',
    'group': 'समूह {n}',
    'toBoard': 'बोर्ड पर रखें',
    'onBoard': 'बोर्ड पर रखें',
    'noRoster': 'विद्यार्थियों के लिए कक्षा खोलें (नमूना कक्षा दिखाई गई है)।',
    'magnifier': 'आवर्धक',
    'magnifierHint': 'लेंस को बोर्ड पर खींचें',
    'notes': 'शिक्षक के नोट्स',
    'notesPrivate': 'निजी: केवल इस पैनल पर। प्रोजेक्टर, लाइव व्यू या रिकॉर्डिंग में नहीं दिखते।',
    'notesHint': 'इस कक्षा के लिए याद दिलाने वाली बातें, उत्तर, किस पर ध्यान देना है…',
    'saved': 'सहेजा गया',
    'close': 'बंद करें',
  },
  'kn': {
    'seating': 'ಆಸನ ವ್ಯವಸ್ಥೆ',
    'seatingHint': 'ಅದಲು-ಬದಲಿಗೆ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಇನ್ನೊಂದು ಆಸನಕ್ಕೆ ಎಳೆಯಿರಿ. ಯೋಜನೆ ಈ ತರಗತಿಗಾಗಿ ಉಳಿಯುತ್ತದೆ.',
    'rows': 'ಸಾಲುಗಳು',
    'cols': 'ಕಾಲಮ್‌ಗಳು',
    'shuffle': 'ಬೆರೆಸಿ',
    'alphabetical': 'ಅ ಇಂದ ಳ',
    'empty': 'ಖಾಲಿ',
    'front': 'ಮುಂದೆ (ಬೋರ್ಡ್)',
    'groups': 'ಗುಂಪು ತಯಾರಕ',
    'groupCount': 'ಗುಂಪುಗಳು: {n}',
    'make': 'ಗುಂಪು ಮಾಡಿ',
    'group': 'ಗುಂಪು {n}',
    'toBoard': 'ಬೋರ್ಡ್‌ಗೆ ಹಾಕಿ',
    'onBoard': 'ಬೋರ್ಡ್‌ಗೆ ಹಾಕಿ',
    'noRoster': 'ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ ತರಗತಿ ತೆರೆಯಿರಿ (ಮಾದರಿ ತರಗತಿ ತೋರಿಸಲಾಗಿದೆ).',
    'magnifier': 'ಭೂತಗನ್ನಡಿ',
    'magnifierHint': 'ಮಸೂರವನ್ನು ಬೋರ್ಡ್ ಮೇಲೆ ಎಳೆಯಿರಿ',
    'notes': 'ಶಿಕ್ಷಕರ ಟಿಪ್ಪಣಿಗಳು',
    'notesPrivate': 'ಖಾಸಗಿ: ಈ ಫಲಕದಲ್ಲಿ ಮಾತ್ರ. ಪ್ರೊಜೆಕ್ಟರ್, ಲೈವ್ ವೀಕ್ಷಣೆ ಅಥವಾ ರೆಕಾರ್ಡಿಂಗ್‌ನಲ್ಲಿ ಕಾಣುವುದಿಲ್ಲ.',
    'notesHint': 'ಈ ತರಗತಿಗೆ ನೆನಪುಗಳು, ಉತ್ತರಗಳು, ಯಾರನ್ನು ಗಮನಿಸಬೇಕು…',
    'saved': 'ಉಳಿಸಲಾಗಿದೆ',
    'close': 'ಮುಚ್ಚಿ',
  },
};
