import 'package:flutter/widgets.dart';

/// The CS kit's and code lab's words in English, Hindi and Kannada (as the 3D viewer and the
/// labs keep theirs). Technical names that classes use as they are (FCFS, LRU, BCNF, SQL,
/// stdin) are not translated.
///
/// First-draft translations: they need review by native speakers before release (docs/i18n/).
class CsStrings {
  const CsStrings(this.lang);

  factory CsStrings.of(BuildContext context) => CsStrings(switch (Localizations.maybeLocaleOf(context)?.languageCode) {
    'hi' => 'hi',
    'kn' => 'kn',
    _ => 'en',
  });

  final String lang;

  int get _i => switch (lang) {
    'hi' => 1,
    'kn' => 2,
    _ => 0,
  };

  /// The words for [key], with {0}, {1}… filled from [args]; the key itself if unknown.
  String t(String key, [List<Object> args = const []]) {
    var s = words[key]?[_i] ?? key;
    for (var i = 0; i < args.length; i++) {
      s = s.replaceAll('{$i}', '${args[i]}');
    }
    return s;
  }

  static const words = <String, List<String>>{
    // --- Code lab ---
    'codeLab': ['Code lab', 'कोड लैब', 'ಕೋಡ್ ಲ್ಯಾಬ್'],
    'run': ['Run', 'चलाएँ', 'ರನ್ ಮಾಡಿ'],
    'stop': ['Stop', 'रोकें', 'ನಿಲ್ಲಿಸಿ'],
    'running': ['Running…', 'चल रहा है…', 'ನಡೆಯುತ್ತಿದೆ…'],
    'input': ['Input (stdin)', 'इनपुट (stdin)', 'ಇನ್‌ಪುಟ್ (stdin)'],
    'inputHint': ['Lines the program reads, one per line', 'प्रोग्राम जो पंक्तियाँ पढ़ेगा, एक पंक्ति में एक', 'ಪ್ರೋಗ್ರಾಂ ಓದುವ ಸಾಲುಗಳು, ಸಾಲಿಗೆ ಒಂದು'],
    'output': ['Output', 'आउटपुट', 'ಔಟ್‌ಪುಟ್'],
    'samples': ['Samples', 'उदाहरण', 'ಉದಾಹರಣೆಗಳು'],
    'language': ['Language', 'भाषा', 'ಭಾಷೆ'],
    'database': ['Database', 'डेटाबेस', 'ಡೇಟಾಬೇಸ್'],
    'emptyDb': ['Empty database', 'खाली डेटाबेस', 'ಖಾಲಿ ಡೇಟಾಬೇಸ್'],
    'dbstudents': ['Students', 'विद्यार्थी', 'ವಿದ್ಯಾರ್ಥಿಗಳು'],
    'dbemployees': ['Employees', 'कर्मचारी', 'ನೌಕರರು'],
    'dblibrary': ['Library', 'पुस्तकालय', 'ಗ್ರಂಥಾಲಯ'],
    'textSize': ['Text size', 'अक्षर का आकार', 'ಅಕ್ಷರದ ಗಾತ್ರ'],
    'putOnBoard': ['Put on board', 'बोर्ड पर लगाएँ', 'ಬೋರ್ಡ್‌ಗೆ ಹಾಕಿ'],
    'putCode': ['Code', 'कोड', 'ಕೋಡ್'],
    'putCodeOutput': ['Code and output', 'कोड और आउटपुट', 'ಕೋಡ್ ಮತ್ತು ಔಟ್‌ಪುಟ್'],
    'putOutput': ['Output only', 'केवल आउटपुट', 'ಔಟ್‌ಪುಟ್ ಮಾತ್ರ'],
    'onDevice': ['Runs on this device, offline', 'इसी डिवाइस पर चलता है, बिना इंटरनेट', 'ಈ ಸಾಧನದಲ್ಲೇ ನಡೆಯುತ್ತದೆ, ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ'],
    'onServer': ["Runs on the college's server in India", 'कॉलेज के सर्वर पर (भारत में) चलता है', 'ಕಾಲೇಜಿನ ಸರ್ವರ್‌ನಲ್ಲಿ (ಭಾರತದಲ್ಲಿ) ನಡೆಯುತ್ತದೆ'],
    'startingPython': ['Starting Python… (only the first time)', 'Python शुरू हो रहा है… (केवल पहली बार)', 'Python ಆರಂಭವಾಗುತ್ತಿದೆ… (ಮೊದಲ ಬಾರಿ ಮಾತ್ರ)'],
    'noOutput': ['(no output)', '(कोई आउटपुट नहीं)', '(ಔಟ್‌ಪುಟ್ ಇಲ್ಲ)'],
    'timeMs': ['{0} ms', '{0} ms', '{0} ms'],
    'status_ok': ['Finished', 'पूरा हुआ', 'ಮುಗಿಯಿತು'],
    'status_compile_error': ['Compile error', 'कंपाइल त्रुटि', 'ಕಂಪೈಲ್ ದೋಷ'],
    'status_runtime_error': ['Error while running', 'चलते समय त्रुटि', 'ನಡೆಯುವಾಗ ದೋಷ'],
    'status_timeout': ['Took too long, so it was stopped', 'बहुत समय लगा, इसलिए रोका गया', 'ತುಂಬಾ ಸಮಯ ತೆಗೆದುಕೊಂಡಿತು, ನಿಲ್ಲಿಸಲಾಯಿತು'],
    'status_memory_limit': ['Used too much memory', 'बहुत अधिक मेमोरी ली', 'ತುಂಬಾ ಮೆಮೊರಿ ಬಳಸಿತು'],
    'status_output_limit': ['Printed too much, so it was stopped', 'बहुत अधिक छापा, इसलिए रोका गया', 'ತುಂಬಾ ಮುದ್ರಿಸಿತು, ನಿಲ್ಲಿಸಲಾಯಿತು'],
    'status_stopped': ['Stopped', 'रोका गया', 'ನಿಲ್ಲಿಸಲಾಗಿದೆ'],
    'status_unavailable': ['Cannot run here', 'यहाँ नहीं चल सकता', 'ಇಲ್ಲಿ ನಡೆಸಲಾಗದು'],
    'status_rate_limited': ['Too many runs. Wait a minute.', 'बहुत बार चलाया। एक मिनट रुकें।', 'ತುಂಬಾ ಬಾರಿ ನಡೆಸಲಾಗಿದೆ. ಒಂದು ನಿಮಿಷ ಕಾಯಿರಿ.'],
    'why_signIn': ['Sign in to run C, C++ and Java.', 'C, C++ और Java चलाने के लिए साइन इन करें।', 'C, C++ ಮತ್ತು Java ನಡೆಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.'],
    'why_noServer': ['C, C++ and Java run on the KINETIX server, which this app is not connected to.', 'C, C++ और Java KINETIX सर्वर पर चलते हैं, जिससे यह ऐप जुड़ा नहीं है।', 'C, C++ ಮತ್ತು Java KINETIX ಸರ್ವರ್‌ನಲ್ಲಿ ನಡೆಯುತ್ತವೆ; ಈ ಆ್ಯಪ್ ಅದಕ್ಕೆ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ.'],
    'why_noWebView': ['This device cannot run Python and JavaScript (no WebView). SQL still works.', 'यह डिवाइस Python और JavaScript नहीं चला सकता (WebView नहीं है)। SQL चलता है।', 'ಈ ಸಾಧನ Python ಮತ್ತು JavaScript ನಡೆಸಲಾರದು (WebView ಇಲ್ಲ). SQL ನಡೆಯುತ್ತದೆ.'],
    'why_offline': ['No connection to the server. Python, JavaScript and SQL still work offline.', 'सर्वर से कनेक्शन नहीं। Python, JavaScript और SQL बिना इंटरनेट चलते हैं।', 'ಸರ್ವರ್ ಸಂಪರ್ಕವಿಲ್ಲ. Python, JavaScript ಮತ್ತು SQL ಆಫ್‌ಲೈನ್‌ನಲ್ಲೂ ನಡೆಯುತ್ತವೆ.'],
    'why_server': ['The code runner is not available right now. Try again in a little while.', 'कोड रनर अभी उपलब्ध नहीं है। थोड़ी देर में फिर कोशिश करें।', 'ಕೋಡ್ ರನ್ನರ್ ಈಗ ಲಭ್ಯವಿಲ್ಲ. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.'],
    'sampleHello': ['Hello, name', 'नमस्ते, नाम', 'ನಮಸ್ಕಾರ, ಹೆಸರು'],
    'sampleFactorial': ['Factorial (recursion)', 'फ़ैक्टोरियल (रिकर्शन)', 'ಫ್ಯಾಕ್ಟೋರಿಯಲ್ (ರಿಕರ್ಷನ್)'],
    'samplePrimes': ['Prime numbers', 'अभाज्य संख्याएँ', 'ಅವಿಭಾಜ್ಯ ಸಂಖ್ಯೆಗಳು'],
    'sampleBubble': ['Bubble sort', 'बबल सॉर्ट', 'ಬಬಲ್ ಸಾರ್ಟ್'],
    'sampleMarks': ['Marks and grades', 'अंक और ग्रेड', 'ಅಂಕಗಳು ಮತ್ತು ಗ್ರೇಡ್'],
    'sampleFibonacci': ['Fibonacci series', 'फ़िबोनाची श्रेणी', 'ಫಿಬೊನಾಚಿ ಶ್ರೇಣಿ'],
    'sampleObjects': ['Arrays and objects', 'ऐरे और ऑब्जेक्ट', 'ಅರೇ ಮತ್ತು ಆಬ್ಜೆಕ್ಟ್'],
    'sampleSelect': ['SELECT … WHERE', 'SELECT … WHERE', 'SELECT … WHERE'],
    'sampleJoin': ['GROUP BY and HAVING', 'GROUP BY और HAVING', 'GROUP BY ಮತ್ತು HAVING'],
    'sampleEmployees': ['Self join: managers', 'सेल्फ़ जॉइन: मैनेजर', 'ಸೆಲ್ಫ್ ಜಾಯಿನ್: ಮ್ಯಾನೇಜರ್'],
    'sampleLibrary': ['Books not returned', 'वापस न की गई किताबें', 'ಹಿಂದಿರುಗಿಸದ ಪುಸ್ತಕಗಳು'],
    'sampleCreate': ['CREATE, INSERT, UPDATE', 'CREATE, INSERT, UPDATE', 'CREATE, INSERT, UPDATE'],
    'samplePointers': ['Pointers: swap', 'पॉइंटर: स्वैप', 'ಪಾಯಿಂಟರ್: ಸ್ವಾಪ್'],
    'sampleClass': ['Classes and objects', 'क्लास और ऑब्जेक्ट', 'ಕ್ಲಾಸ್ ಮತ್ತು ಆಬ್ಜೆಕ್ಟ್'],
    'sampleStack': ['Stack (STL)', 'स्टैक (STL)', 'ಸ್ಟ್ಯಾಕ್ (STL)'],

    // --- Algorithm player ---
    'algorithms': ['Algorithms', 'एल्गोरिद्म', 'ಅಲ್ಗಾರಿದಮ್‌ಗಳು'],
    'play': ['Play', 'चलाएँ', 'ಪ್ಲೇ'],
    'pause': ['Pause', 'रोकें', 'ವಿರಾಮ'],
    'back': ['Back', 'पीछे', 'ಹಿಂದೆ'],
    'next': ['Next', 'आगे', 'ಮುಂದೆ'],
    'restart': ['Start again', 'फिर से शुरू', 'ಮತ್ತೆ ಆರಂಭಿಸಿ'],
    'speed': ['Speed', 'गति', 'ವೇಗ'],
    'stepOf': ['Step {0} of {1}', 'चरण {0} / {1}', 'ಹಂತ {0} / {1}'],
    'values': ['Values', 'मान', 'ಮೌಲ್ಯಗಳು'],
    'find': ['Find', 'खोजें', 'ಹುಡುಕಿ'],
    'operations': ['Operations', 'संक्रियाएँ', 'ಕ್ರಿಯೆಗಳು'],
    'opsHint': ['e.g. push 5; pop; peek', 'जैसे push 5; pop; peek', 'ಉದಾ. push 5; pop; peek'],
    'listOpsHint': ['e.g. insertHead 5; insertAt 7 2; delete 3; search 7', 'जैसे insertHead 5; insertAt 7 2; delete 3; search 7', 'ಉದಾ. insertHead 5; insertAt 7 2; delete 3; search 7'],
    'edges': ['Edges (A-B 4, …)', 'किनारे (A-B 4, …)', 'ಅಂಚುಗಳು (A-B 4, …)'],
    'startAt': ['Start at', 'यहाँ से शुरू', 'ಇಲ್ಲಿಂದ ಆರಂಭ'],
    'deletes': ['Then delete', 'फिर हटाएँ', 'ನಂತರ ಅಳಿಸಿ'],
    'tableSize': ['Table size', 'तालिका का आकार', 'ಕೋಷ್ಟಕದ ಗಾತ್ರ'],
    'apply': ['Apply', 'लागू करें', 'ಅನ್ವಯಿಸಿ'],
    'putStep': ['Put this step on board', 'यह चरण बोर्ड पर लगाएँ', 'ಈ ಹಂತವನ್ನು ಬೋರ್ಡ್‌ಗೆ ಹಾಕಿ'],
    'grpSorting': ['Sorting', 'सॉर्टिंग', 'ವಿಂಗಡಣೆ'],
    'grpSearching': ['Searching', 'खोज', 'ಹುಡುಕಾಟ'],
    'grpStructures': ['Data structures', 'डेटा संरचनाएँ', 'ಡೇಟಾ ರಚನೆಗಳು'],
    'grpTrees': ['Trees and graphs', 'ट्री और ग्राफ़', 'ಟ್ರೀ ಮತ್ತು ಗ್ರಾಫ್'],
    'algo_bubble': ['Bubble sort', 'बबल सॉर्ट', 'ಬಬಲ್ ಸಾರ್ಟ್'],
    'algo_insertion': ['Insertion sort', 'इंसर्शन सॉर्ट', 'ಇನ್ಸರ್ಷನ್ ಸಾರ್ಟ್'],
    'algo_selection': ['Selection sort', 'सिलेक्शन सॉर्ट', 'ಸೆಲೆಕ್ಷನ್ ಸಾರ್ಟ್'],
    'algo_merge': ['Merge sort', 'मर्ज सॉर्ट', 'ಮರ್ಜ್ ಸಾರ್ಟ್'],
    'algo_quick': ['Quick sort', 'क्विक सॉर्ट', 'ಕ್ವಿಕ್ ಸಾರ್ಟ್'],
    'algo_heap': ['Heap sort', 'हीप सॉर्ट', 'ಹೀಪ್ ಸಾರ್ಟ್'],
    'algo_linear': ['Linear search', 'रैखिक खोज', 'ರೇಖೀಯ ಹುಡುಕಾಟ'],
    'algo_binary': ['Binary search', 'बाइनरी खोज', 'ಬೈನರಿ ಹುಡುಕಾಟ'],
    'algo_stack': ['Stack', 'स्टैक', 'ಸ್ಟ್ಯಾಕ್'],
    'algo_queue': ['Queue', 'क्यू', 'ಕ್ಯೂ'],
    'algo_list': ['Linked list', 'लिंक्ड लिस्ट', 'ಲಿಂಕ್ಡ್ ಲಿಸ್ಟ್'],
    'algo_hash': ['Hashing', 'हैशिंग', 'ಹ್ಯಾಶಿಂಗ್'],
    'algo_bst': ['Binary search tree', 'बाइनरी सर्च ट्री', 'ಬೈನರಿ ಸರ್ಚ್ ಟ್ರೀ'],
    'algo_bfs': ['Breadth-first search', 'चौड़ाई-प्रथम खोज (BFS)', 'ಅಗಲ-ಮೊದಲ ಹುಡುಕಾಟ (BFS)'],
    'algo_dfs': ['Depth-first search', 'गहराई-प्रथम खोज (DFS)', 'ಆಳ-ಮೊದಲ ಹುಡುಕಾಟ (DFS)'],
    'algo_dijkstra': ["Dijkstra's shortest paths", 'डाइकस्ट्रा का लघुतम पथ', 'ಡೈಕ್‌ಸ್ಟ್ರಾ ಅತಿ ಚಿಕ್ಕ ಮಾರ್ಗ'],
    'trav_inorder': ['In-order', 'इन-ऑर्डर', 'ಇನ್-ಆರ್ಡರ್'],
    'trav_preorder': ['Pre-order', 'प्री-ऑर्डर', 'ಪ್ರೀ-ಆರ್ಡರ್'],
    'trav_postorder': ['Post-order', 'पोस्ट-ऑर्डर', 'ಪೋಸ್ಟ್-ಆರ್ಡರ್'],
    'trav_level': ['Level order', 'लेवल ऑर्डर', 'ಲೆವೆಲ್ ಆರ್ಡರ್'],
    'probe_chaining': ['Chaining', 'चेनिंग', 'ಚೈನಿಂಗ್'],
    'probe_linear': ['Linear probing', 'रैखिक प्रोबिंग', 'ರೇಖೀಯ ಪ್ರೋಬಿಂಗ್'],
    'probe_quadratic': ['Quadratic probing', 'द्विघात प्रोबिंग', 'ವರ್ಗ ಪ್ರೋಬಿಂಗ್'],
    // Step captions.
    'sortStart': ['The unsorted array.', 'बिना क्रम का ऐरे।', 'ಕ್ರಮವಿಲ್ಲದ ಅರೇ.'],
    'compare': ['Compare {0} and {1}.', '{0} और {1} की तुलना।', '{0} ಮತ್ತು {1} ಹೋಲಿಸಿ.'],
    'swap': ['Swap {0} and {1}.', '{0} और {1} की अदला-बदली।', '{0} ಮತ್ತು {1} ಅದಲುಬದಲು.'],
    'inPlace': ['{0} is in its final place.', '{0} अपनी अंतिम जगह पर है।', '{0} ತನ್ನ ಅಂತಿಮ ಸ್ಥಾನದಲ್ಲಿದೆ.'],
    'noSwaps': ['No swaps in this pass: the array is sorted.', 'इस पास में कोई अदला-बदली नहीं: ऐरे क्रम में है।', 'ಈ ಸುತ್ತಿನಲ್ಲಿ ಅದಲುಬದಲು ಇಲ್ಲ: ಅರೇ ಕ್ರಮದಲ್ಲಿದೆ.'],
    'pickKey': ['Take {0} and insert it into the sorted part.', '{0} लेकर क्रमबद्ध भाग में डालें।', '{0} ತೆಗೆದು ಕ್ರಮಗೊಂಡ ಭಾಗಕ್ಕೆ ಸೇರಿಸಿ.'],
    'newMin': ['New smallest: {0}.', 'नया सबसे छोटा: {0}।', 'ಹೊಸ ಚಿಕ್ಕದು: {0}.'],
    'split': ['Split positions {0} to {1}.', 'स्थान {0} से {1} को बाँटें।', 'ಸ್ಥಾನ {0} ರಿಂದ {1} ವಿಭಜಿಸಿ.'],
    'mergeTake': ['Take {0} into the merged list.', '{0} को मिली हुई सूची में लें।', '{0} ಅನ್ನು ವಿಲೀನ ಪಟ್ಟಿಗೆ ತೆಗೆದುಕೊಳ್ಳಿ.'],
    'merged': ['Merged positions {0} to {1}.', 'स्थान {0} से {1} मिल गए।', 'ಸ್ಥಾನ {0} ರಿಂದ {1} ವಿಲೀನಗೊಂಡಿವೆ.'],
    'pivot': ['Pivot: {0}.', 'पिवट: {0}।', 'ಪಿವಟ್: {0}.'],
    'pivotPlaced': ['Pivot {0} is in its final place.', 'पिवट {0} अपनी अंतिम जगह पर है।', 'ಪಿವಟ್ {0} ಅಂತಿಮ ಸ್ಥಾನದಲ್ಲಿದೆ.'],
    'buildHeap': ['Build a max-heap.', 'मैक्स-हीप बनाएँ।', 'ಮ್ಯಾಕ್ಸ್-ಹೀಪ್ ನಿರ್ಮಿಸಿ.'],
    'sortDone': ['Sorted: {0} comparisons, {1} swaps.', 'क्रमबद्ध: {0} तुलनाएँ, {1} अदला-बदली।', 'ವಿಂಗಡಿಸಲಾಗಿದೆ: {0} ಹೋಲಿಕೆಗಳು, {1} ಅದಲುಬದಲು.'],
    'linearStart': ['Look for {0} from the left.', 'बाएँ से {0} खोजें।', 'ಎಡದಿಂದ {0} ಹುಡುಕಿ.'],
    'binaryStart': ['Look for {0} in the sorted array.', 'क्रमबद्ध ऐरे में {0} खोजें।', 'ಕ್ರಮಗೊಂಡ ಅರೇಯಲ್ಲಿ {0} ಹುಡುಕಿ.'],
    'found': ['Found {0} at position {1}.', '{0} स्थान {1} पर मिला।', '{0} ಸ್ಥಾನ {1} ರಲ್ಲಿ ಸಿಕ್ಕಿತು.'],
    'notFound': ['{0} is not there.', '{0} नहीं है।', '{0} ಇಲ್ಲ.'],
    'goRight': ['{0} is smaller: search the right half.', '{0} छोटा है: दाहिना आधा खोजें।', '{0} ಚಿಕ್ಕದು: ಬಲ ಅರ್ಧ ಹುಡುಕಿ.'],
    'goLeft': ['{0} is larger: search the left half.', '{0} बड़ा है: बायाँ आधा खोजें।', '{0} ದೊಡ್ಡದು: ಎಡ ಅರ್ಧ ಹುಡುಕಿ.'],
    'stackStart': ['An empty stack.', 'खाली स्टैक।', 'ಖಾಲಿ ಸ್ಟ್ಯಾಕ್.'],
    'push': ['Push {0} on top.', '{0} को ऊपर पुश करें।', '{0} ಮೇಲೆ ಪುಶ್ ಮಾಡಿ.'],
    'pop': ['Pop {0} from the top.', 'ऊपर से {0} पॉप करें।', 'ಮೇಲಿನಿಂದ {0} ಪಾಪ್ ಮಾಡಿ.'],
    'popped': ['{0} items left.', '{0} चीज़ें बचीं।', '{0} ಅಂಶಗಳು ಉಳಿದಿವೆ.'],
    'peek': ['The top is {0}.', 'ऊपर {0} है।', 'ಮೇಲೆ {0} ಇದೆ.'],
    'overflow': ['Overflow: no room for {0}.', 'ओवरफ़्लो: {0} के लिए जगह नहीं।', 'ಓವರ್‌ಫ್ಲೋ: {0} ಗೆ ಜಾಗವಿಲ್ಲ.'],
    'underflow': ['Underflow: it is empty.', 'अंडरफ़्लो: यह खाली है।', 'ಅಂಡರ್‌ಫ್ಲೋ: ಇದು ಖಾಲಿ.'],
    'queueStart': ['An empty queue.', 'खाली क्यू।', 'ಖಾಲಿ ಕ್ಯೂ.'],
    'enqueue': ['Enqueue {0} at the rear.', '{0} को पीछे जोड़ें।', '{0} ಅನ್ನು ಹಿಂಭಾಗಕ್ಕೆ ಸೇರಿಸಿ.'],
    'dequeue': ['Dequeue {0} from the front.', 'आगे से {0} निकालें।', 'ಮುಂಭಾಗದಿಂದ {0} ತೆಗೆಯಿರಿ.'],
    'queueSize': ['{0} items left.', '{0} चीज़ें बचीं।', '{0} ಅಂಶಗಳು ಉಳಿದಿವೆ.'],
    'listStart': ['The linked list.', 'लिंक्ड लिस्ट।', 'ಲಿಂಕ್ಡ್ ಲಿಸ್ಟ್.'],
    'walk': ['Visit {0}.', '{0} पर जाएँ।', '{0} ಗೆ ಭೇಟಿ.'],
    'insertHead': ['Insert {0} at the head.', '{0} को शुरू में जोड़ें।', '{0} ಅನ್ನು ತಲೆಯಲ್ಲಿ ಸೇರಿಸಿ.'],
    'insertTail': ['Insert {0} at the tail.', '{0} को अंत में जोड़ें।', '{0} ಅನ್ನು ಬಾಲದಲ್ಲಿ ಸೇರಿಸಿ.'],
    'insertAt': ['Insert {0} at position {1}.', '{0} को स्थान {1} पर जोड़ें।', '{0} ಅನ್ನು ಸ್ಥಾನ {1} ರಲ್ಲಿ ಸೇರಿಸಿ.'],
    'unlink': ['Unlink {0}.', '{0} को अलग करें।', '{0} ಅನ್ನು ಬೇರ್ಪಡಿಸಿ.'],
    'deleted': ['Deleted {0}.', '{0} हटाया गया।', '{0} ಅಳಿಸಲಾಗಿದೆ.'],
    'hashStart': ['A table of {0} slots; h(k) = k mod {0}.', '{0} खानों की तालिका; h(k) = k mod {0}।', '{0} ಸ್ಲಾಟ್‌ಗಳ ಕೋಷ್ಟಕ; h(k) = k mod {0}.'],
    'hash': ['h({0}) = {0} mod {1} = {2}.', 'h({0}) = {0} mod {1} = {2}।', 'h({0}) = {0} mod {1} = {2}.'],
    'chain': ['Add {0} to the chain at {1}.', '{0} को {1} की चेन में जोड़ें।', '{0} ಅನ್ನು {1} ರ ಚೈನ್‌ಗೆ ಸೇರಿಸಿ.'],
    'placed': ['Put {0} in slot {1}.', '{0} को खाने {1} में रखें।', '{0} ಅನ್ನು ಸ್ಲಾಟ್ {1} ರಲ್ಲಿ ಇಡಿ.'],
    'collision': ['Slot {0} is taken: probe on.', 'खाना {0} भरा है: आगे देखें।', 'ಸ್ಲಾಟ್ {0} ತುಂಬಿದೆ: ಮುಂದೆ ನೋಡಿ.'],
    'tableFull': ['No free slot for {0}.', '{0} के लिए कोई खाली खाना नहीं।', '{0} ಗೆ ಖಾಲಿ ಸ್ಲಾಟ್ ಇಲ್ಲ.'],
    'bstStart': ['An empty tree.', 'खाली ट्री।', 'ಖಾಲಿ ಟ್ರೀ.'],
    'bstRoot': ['{0} becomes the root.', '{0} रूट बनता है।', '{0} ರೂಟ್ ಆಗುತ್ತದೆ.'],
    'duplicate': ['{0} is already in the tree.', '{0} पहले से ट्री में है।', '{0} ಈಗಾಗಲೇ ಟ್ರೀಯಲ್ಲಿದೆ.'],
    'bstLeftChild': ['{0} < {1}: left child of {1}.', '{0} < {1}: {1} का बायाँ बच्चा।', '{0} < {1}: {1} ರ ಎಡ ಮಗು.'],
    'bstRightChild': ['{0} > {1}: right child of {1}.', '{0} > {1}: {1} का दायाँ बच्चा।', '{0} > {1}: {1} ರ ಬಲ ಮಗು.'],
    'successor': ['Replace {1} with its in-order successor {0}.', '{1} को उसके इन-ऑर्डर उत्तराधिकारी {0} से बदलें।', '{1} ಅನ್ನು ಅದರ ಇನ್-ಆರ್ಡರ್ ಉತ್ತರಾಧಿಕಾರಿ {0} ಯಿಂದ ಬದಲಿಸಿ.'],
    'deleteLeaf': ['{0} is a leaf: remove it.', '{0} पत्ता है: इसे हटाएँ।', '{0} ಎಲೆ: ಅದನ್ನು ತೆಗೆಯಿರಿ.'],
    'deleteOneChild': ['{0} has one child: link the child up.', '{0} का एक बच्चा है: बच्चे को ऊपर जोड़ें।', '{0} ಗೆ ಒಂದು ಮಗು: ಮಗುವನ್ನು ಮೇಲಕ್ಕೆ ಜೋಡಿಸಿ.'],
    'visit': ['Visit {0}.', '{0} पर जाएँ।', '{0} ಗೆ ಭೇಟಿ.'],
    'traversal': ['Order: {0}.', 'क्रम: {0}।', 'ಕ್ರಮ: {0}.'],
    'bfsStart': ['BFS from {0}: put it in the queue.', '{0} से BFS: इसे क्यू में रखें।', '{0} ಯಿಂದ BFS: ಅದನ್ನು ಕ್ಯೂಗೆ ಹಾಕಿ.'],
    'dfsStart': ['DFS from {0}.', '{0} से DFS।', '{0} ಯಿಂದ DFS.'],
    'visitNode': ['Visit {0}.', '{0} पर जाएँ।', '{0} ಗೆ ಭೇಟಿ.'],
    'discover': ['Discover {0}: add it to the queue.', '{0} मिला: इसे क्यू में जोड़ें।', '{0} ಸಿಕ್ಕಿತು: ಕ್ಯೂಗೆ ಸೇರಿಸಿ.'],
    'backtrack': ['Back to {0}.', 'वापस {0} पर।', 'ಮತ್ತೆ {0} ಗೆ.'],
    'order': ['Visit order: {0}.', 'भ्रमण क्रम: {0}।', 'ಭೇಟಿ ಕ್ರಮ: {0}.'],
    'dijkstraStart': ['Distance to {0} is 0; every other is ∞.', '{0} की दूरी 0; बाकी सब ∞।', '{0} ಗೆ ದೂರ 0; ಉಳಿದವು ∞.'],
    'settle': ['{0} is settled at distance {1}.', '{0} की दूरी {1} पक्की हुई।', '{0} ದೂರ {1} ರಲ್ಲಿ ಸ್ಥಿರವಾಯಿತು.'],
    'relax': ['Shorter path to {0}: {1} via {2}.', '{0} तक छोटा पथ: {2} से होकर {1}।', '{0} ಗೆ ಚಿಕ್ಕ ಮಾರ್ಗ: {2} ಮೂಲಕ {1}.'],
    'dijkstraDone': ['All shortest distances found.', 'सभी लघुतम दूरियाँ मिल गईं।', 'ಎಲ್ಲಾ ಅತಿ ಚಿಕ್ಕ ದೂರಗಳು ಸಿಕ್ಕಿವೆ.'],

    // --- Simulations ---
    'simulations': ['CS labs', 'CS लैब', 'CS ಲ್ಯಾಬ್‌ಗಳು'],
    'grpNumbersLogic': ['Numbers and logic', 'संख्याएँ और तर्क', 'ಸಂಖ್ಯೆಗಳು ಮತ್ತು ತರ್ಕ'],
    'grpNetworks': ['Computer networks', 'कंप्यूटर नेटवर्क', 'ಕಂಪ್ಯೂಟರ್ ಜಾಲಗಳು'],
    'grpOs': ['Operating systems', 'ऑपरेटिंग सिस्टम', 'ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್'],
    'grpDbms': ['DBMS', 'DBMS', 'DBMS'],
    'sim_numbers': ['Number systems and bits', 'संख्या पद्धतियाँ और बिट', 'ಸಂಖ್ಯಾ ಪದ್ಧತಿಗಳು ಮತ್ತು ಬಿಟ್‌ಗಳು'],
    'sim_logic': ['Truth table', 'सत्य सारणी', 'ಸತ್ಯ ಕೋಷ್ಟಕ'],
    'sim_osi': ['OSI encapsulation', 'OSI एनकैप्सुलेशन', 'OSI ಎನ್‌ಕ್ಯಾಪ್ಸುಲೇಷನ್'],
    'sim_tcp': ['TCP handshake', 'TCP हैंडशेक', 'TCP ಹ್ಯಾಂಡ್‌ಶೇಕ್'],
    'sim_subnet': ['Subnet calculator', 'सबनेट कैलकुलेटर', 'ಸಬ್‌ನೆಟ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್'],
    'sim_cpu': ['CPU scheduling', 'CPU शेड्यूलिंग', 'CPU ವೇಳಾಪಟ್ಟಿ'],
    'sim_paging': ['Page replacement', 'पेज रिप्लेसमेंट', 'ಪುಟ ಬದಲಿಕೆ'],
    'sim_banker': ["Banker's algorithm", 'बैंकर एल्गोरिद्म', 'ಬ್ಯಾಂಕರ್ ಅಲ್ಗಾರಿದಮ್'],
    'sim_normal': ['Normalisation', 'नॉर्मलाइज़ेशन', 'ನಾರ್ಮಲೈಸೇಶನ್'],
    'decimal': ['Decimal', 'दशमलव', 'ದಶಮಾನ'],
    'binary': ['Binary', 'द्विआधारी', 'ದ್ವಿಮಾನ'],
    'octal': ['Octal', 'अष्टाधारी', 'ಅಷ್ಟಮಾನ'],
    'hex': ['Hexadecimal', 'षोडशाधारी', 'ಷೋಡಶಮಾನ'],
    'base': ['Base', 'आधार', 'ಆಧಾರ'],
    'bits': ['Bits', 'बिट', 'ಬಿಟ್‌ಗಳು'],
    'twos': ["Two's complement", 'टू का पूरक', 'ಟೂಸ್ ಕಾಂಪ್ಲಿಮೆಂಟ್'],
    'doesNotFit': ['Does not fit in {0} bits', '{0} बिट में नहीं आता', '{0} ಬಿಟ್‌ಗಳಲ್ಲಿ ಹಿಡಿಸದು'],
    'division': ['Repeated division by {0}', '{0} से बार-बार भाग', '{0} ರಿಂದ ಪುನರಾವರ್ತಿತ ಭಾಗಾಕಾರ'],
    'placeValue': ['Place values', 'स्थानीय मान', 'ಸ್ಥಾನ ಮೌಲ್ಯಗಳು'],
    'bitwise': ['Bitwise with', 'बिटवाइज़, इसके साथ', 'ಬಿಟ್‌ವೈಸ್, ಇದರೊಂದಿಗೆ'],
    'expression': ['Expression', 'व्यंजक', 'ಅಭಿವ್ಯಕ್ತಿ'],
    'exprHint': ["e.g. A'B + AB', (A AND B) OR NOT C", "जैसे A'B + AB', (A AND B) OR NOT C", "ಉದಾ. A'B + AB', (A AND B) OR NOT C"],
    'minterms': ['Minterms', 'मिनटर्म', 'ಮಿನ್‌ಟರ್ಮ್‌ಗಳು'],
    'sop': ['Sum of products', 'गुणनफलों का योग', 'ಗುಣಲಬ್ಧಗಳ ಮೊತ್ತ'],
    'badInput': ['Check what you typed', 'जो लिखा उसे जाँचें', 'ಟೈಪ್ ಮಾಡಿದ್ದನ್ನು ಪರಿಶೀಲಿಸಿ'],
    'message': ['Message', 'संदेश', 'ಸಂದೇಶ'],
    'osiApplication': ['Application', 'अनुप्रयोग', 'ಅನ್ವಯ'],
    'osiPresentation': ['Presentation', 'प्रस्तुति', 'ಪ್ರಸ್ತುತಿ'],
    'osiSession': ['Session', 'सत्र', 'ಅಧಿವೇಶನ'],
    'osiTransport': ['Transport', 'परिवहन', 'ಸಾರಿಗೆ'],
    'osiNetwork': ['Network', 'नेटवर्क', 'ನೆಟ್‌ವರ್ಕ್'],
    'osiDataLink': ['Data link', 'डेटा लिंक', 'ಡೇಟಾ ಲಿಂಕ್'],
    'osiPhysical': ['Physical', 'भौतिक', 'ಭೌತಿಕ'],
    'adds': ['adds', 'जोड़ता है', 'ಸೇರಿಸುತ್ತದೆ'],
    'clientIsn': ['Client ISN', 'क्लाइंट ISN', 'ಕ್ಲೈಂಟ್ ISN'],
    'serverIsn': ['Server ISN', 'सर्वर ISN', 'ಸರ್ವರ್ ISN'],
    'dataBytes': ['Data bytes', 'डेटा बाइट', 'ಡೇಟಾ ಬೈಟ್‌ಗಳು'],
    'client': ['Client', 'क्लाइंट', 'ಕ್ಲೈಂಟ್'],
    'server': ['Server', 'सर्वर', 'ಸರ್ವರ್'],
    'addressPrefix': ['Address/prefix', 'पता/प्रीफ़िक्स', 'ವಿಳಾಸ/ಪ್ರಿಫಿಕ್ಸ್'],
    'network': ['Network', 'नेटवर्क', 'ನೆಟ್‌ವರ್ಕ್'],
    'mask': ['Mask', 'मास्क', 'ಮಾಸ್ಕ್'],
    'wildcard': ['Wildcard', 'वाइल्डकार्ड', 'ವೈಲ್ಡ್‌ಕಾರ್ಡ್'],
    'broadcast': ['Broadcast', 'ब्रॉडकास्ट', 'ಬ್ರಾಡ್‌ಕಾಸ್ಟ್'],
    'firstHost': ['First host', 'पहला होस्ट', 'ಮೊದಲ ಹೋಸ್ಟ್'],
    'lastHost': ['Last host', 'अंतिम होस्ट', 'ಕೊನೆಯ ಹೋಸ್ಟ್'],
    'hosts': ['Usable hosts', 'उपयोगी होस्ट', 'ಬಳಸಬಹುದಾದ ಹೋಸ್ಟ್‌ಗಳು'],
    'ipClass': ['Class', 'क्लास', 'ವರ್ಗ'],
    'privateNet': ['Private', 'निजी', 'ಖಾಸಗಿ'],
    'publicNet': ['Public', 'सार्वजनिक', 'ಸಾರ್ವಜನಿಕ'],
    'splitInto': ['Split into', 'इतने भागों में बाँटें', 'ಇಷ್ಟು ಭಾಗಗಳಾಗಿ ವಿಭಜಿಸಿ'],
    'processes': ['Processes: id arrival burst [priority]', 'प्रक्रियाएँ: id आगमन burst [प्राथमिकता]', 'ಪ್ರಕ್ರಿಯೆಗಳು: id ಆಗಮನ burst [ಆದ್ಯತೆ]'],
    'quantum': ['Time quantum', 'टाइम क्वांटम', 'ಸಮಯ ಕ್ವಾಂಟಮ್'],
    'sched_fcfs': ['FCFS', 'FCFS', 'FCFS'],
    'sched_sjf': ['SJF', 'SJF', 'SJF'],
    'sched_srtf': ['SRTF (pre-emptive SJF)', 'SRTF (प्री-एम्प्टिव SJF)', 'SRTF (ಪ್ರೀ-ಎಂಪ್ಟಿವ್ SJF)'],
    'sched_priority': ['Priority', 'प्राथमिकता', 'ಆದ್ಯತೆ'],
    'sched_priorityPreemptive': ['Priority (pre-emptive)', 'प्राथमिकता (प्री-एम्प्टिव)', 'ಆದ್ಯತೆ (ಪ್ರೀ-ಎಂಪ್ಟಿವ್)'],
    'sched_roundRobin': ['Round robin', 'राउंड रॉबिन', 'ರೌಂಡ್ ರಾಬಿನ್'],
    'idle': ['idle', 'खाली', 'ಖಾಲಿ'],
    'completion': ['Completion', 'समापन', 'ಪೂರ್ಣಗೊಂಡದ್ದು'],
    'turnaround': ['Turnaround', 'टर्नअराउंड', 'ಟರ್ನ್‌ಅರೌಂಡ್'],
    'waiting': ['Waiting', 'प्रतीक्षा', 'ಕಾಯುವಿಕೆ'],
    'response': ['Response', 'प्रतिक्रिया', 'ಪ್ರತಿಕ್ರಿಯೆ'],
    'average': ['Average', 'औसत', 'ಸರಾಸರಿ'],
    'references': ['Reference string', 'संदर्भ स्ट्रिंग', 'ಉಲ್ಲೇಖ ಸರಣಿ'],
    'frames': ['Frames', 'फ़्रेम', 'ಫ್ರೇಮ್‌ಗಳು'],
    'faults': ['Page faults: {0}, hits: {1}', 'पेज फ़ॉल्ट: {0}, हिट: {1}', 'ಪುಟ ದೋಷಗಳು: {0}, ಹಿಟ್: {1}'],
    'page_fifo': ['FIFO', 'FIFO', 'FIFO'],
    'page_lru': ['LRU', 'LRU', 'LRU'],
    'page_optimal': ['Optimal', 'इष्टतम (Optimal)', 'ಅತ್ಯುತ್ತಮ (Optimal)'],
    'allocation': ['Allocation', 'आवंटन', 'ಹಂಚಿಕೆ'],
    'max': ['Max', 'अधिकतम', 'ಗರಿಷ್ಠ'],
    'available': ['Available', 'उपलब्ध', 'ಲಭ್ಯ'],
    'need': ['Need', 'आवश्यकता', 'ಅಗತ್ಯ'],
    'work': ['Work', 'वर्क', 'ವರ್ಕ್'],
    'matrixHint': ['One process per line, numbers separated by spaces', 'हर पंक्ति में एक प्रक्रिया, संख्याएँ स्पेस से अलग', 'ಸಾಲಿಗೆ ಒಂದು ಪ್ರಕ್ರಿಯೆ, ಸಂಖ್ಯೆಗಳ ನಡುವೆ ಸ್ಪೇಸ್'],
    'safe': ['Safe. Safe sequence: {0}', 'सुरक्षित। सुरक्षित क्रम: {0}', 'ಸುರಕ್ಷಿತ. ಸುರಕ್ಷಿತ ಕ್ರಮ: {0}'],
    'unsafe': ['Unsafe: no safe sequence exists.', 'असुरक्षित: कोई सुरक्षित क्रम नहीं है।', 'ಅಸುರಕ್ಷಿತ: ಸುರಕ್ಷಿತ ಕ್ರಮವಿಲ್ಲ.'],
    'request': ['Request', 'अनुरोध', 'ವಿನಂತಿ'],
    'process': ['Process', 'प्रक्रिया', 'ಪ್ರಕ್ರಿಯೆ'],
    'granted': ['Granted: the system stays safe.', 'स्वीकृत: सिस्टम सुरक्षित रहता है।', 'ಮಂಜೂರು: ವ್ಯವಸ್ಥೆ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ.'],
    'bankerExceedsNeed': ['Refused: more than the process said it needs.', 'अस्वीकृत: प्रक्रिया की घोषित आवश्यकता से अधिक।', 'ನಿರಾಕರಿಸಲಾಗಿದೆ: ಪ್ರಕ್ರಿಯೆ ಹೇಳಿದ ಅಗತ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚು.'],
    'bankerMustWait': ['Must wait: not enough is available.', 'प्रतीक्षा करनी होगी: पर्याप्त उपलब्ध नहीं।', 'ಕಾಯಬೇಕು: ಸಾಕಷ್ಟು ಲಭ್ಯವಿಲ್ಲ.'],
    'bankerUnsafe': ['Refused: it would leave the system unsafe.', 'अस्वीकृत: सिस्टम असुरक्षित हो जाएगा।', 'ನಿರಾಕರಿಸಲಾಗಿದೆ: ವ್ಯವಸ್ಥೆ ಅಸುರಕ್ಷಿತವಾಗುತ್ತದೆ.'],
    'attributes': ['Attributes', 'गुण (एट्रिब्यूट)', 'ಗುಣಲಕ್ಷಣಗಳು'],
    'fds': ['Functional dependencies', 'फ़ंक्शनल डिपेंडेंसी', 'ಫಂಕ್ಷನಲ್ ಡಿಪೆಂಡೆನ್ಸಿಗಳು'],
    'fdHint': ['e.g. A->B, BC->D (use ; between them when attributes are words)', 'जैसे A->B, BC->D (गुण शब्द हों तो बीच में ; लगाएँ)', 'ಉದಾ. A->B, BC->D (ಗುಣಗಳು ಪದಗಳಾದರೆ ನಡುವೆ ; ಬಳಸಿ)'],
    'keys': ['Candidate keys', 'कैंडिडेट की', 'ಕ್ಯಾಂಡಿಡೇಟ್ ಕೀಗಳು'],
    'closures': ['Closures', 'क्लोज़र', 'ಕ್ಲೋಶರ್‌ಗಳು'],
    'highestNf': ['Highest normal form: {0}', 'उच्चतम नॉर्मल फ़ॉर्म: {0}', 'ಅತ್ಯುನ್ನತ ನಾರ್ಮಲ್ ಫಾರ್ಮ್: {0}'],
    'breaks': ['{0} breaks {1}', '{0} से {1} टूटता है', '{0} {1} ಅನ್ನು ಮುರಿಯುತ್ತದೆ'],
    'cover': ['Minimal cover', 'न्यूनतम कवर', 'ಕನಿಷ್ಠ ಕವರ್'],
    'to3nf': ['3NF decomposition', '3NF विभाजन', '3NF ವಿಭಜನೆ'],
    'toBcnf': ['BCNF decomposition', 'BCNF विभाजन', 'BCNF ವಿಭಜನೆ'],

    // --- Diagrams ---
    'diagrams': ['Diagrams', 'आरेख', 'ರೇಖಾಚಿತ್ರಗಳು'],
    'flowchart': ['Flowchart', 'फ़्लोचार्ट', 'ಫ್ಲೋಚಾರ್ಟ್'],
    'umlClass': ['UML class diagram', 'UML क्लास आरेख', 'UML ಕ್ಲಾಸ್ ರೇಖಾಚಿತ್ರ'],
    'umlSequence': ['UML sequence diagram', 'UML सीक्वेंस आरेख', 'UML ಸೀಕ್ವೆನ್ಸ್ ರೇಖಾಚಿತ್ರ'],
    'er': ['ER diagram', 'ER आरेख', 'ER ರೇಖಾಚಿತ್ರ'],
    'connectors': ['Connectors', 'कनेक्टर', 'ಸಂಪರ್ಕಕಗಳು'],
    'connectHint': ['Select two shapes on the board, then choose a connector.', 'बोर्ड पर दो आकृतियाँ चुनें, फिर कनेक्टर चुनें।', 'ಬೋರ್ಡ್‌ನಲ್ಲಿ ಎರಡು ಆಕಾರಗಳನ್ನು ಆರಿಸಿ, ನಂತರ ಸಂಪರ್ಕಕ ಆರಿಸಿ.'],
    'selectTwo': ['Select two shapes first.', 'पहले दो आकृतियाँ चुनें।', 'ಮೊದಲು ಎರಡು ಆಕಾರಗಳನ್ನು ಆರಿಸಿ.'],
    'conn_arrow': ['Arrow', 'तीर', 'ಬಾಣ'],
    'conn_association': ['Association', 'एसोसिएशन', 'ಅಸೋಸಿಯೇಷನ್'],
    'conn_inheritance': ['Inheritance', 'इनहेरिटेंस', 'ಇನ್‌ಹೆರಿಟೆನ್ಸ್'],
    'conn_composition': ['Composition', 'कंपोज़िशन', 'ಕಾಂಪೊಸಿಷನ್'],
    'conn_aggregation': ['Aggregation', 'एग्रीगेशन', 'ಅಗ್ರಿಗೇಶನ್'],
    'conn_dependency': ['Dependency', 'डिपेंडेंसी', 'ಡಿಪೆಂಡೆನ್ಸಿ'],
    'conn_message': ['Message', 'संदेश', 'ಸಂದೇಶ'],
    'conn_reply': ['Reply', 'उत्तर', 'ಉತ್ತರ'],
    'conn_line': ['Line (ER)', 'रेखा (ER)', 'ರೇಖೆ (ER)'],
    'classBox': ['Class', 'क्लास', 'ಕ್ಲಾಸ್'],
    'classHint': ['Name, then attributes, then -- and methods, one per line', 'नाम, फिर गुण, फिर -- और मेथड, हर पंक्ति में एक', 'ಹೆಸರು, ನಂತರ ಗುಣಗಳು, ನಂತರ -- ಮತ್ತು ಮೆಥಡ್‌ಗಳು, ಸಾಲಿಗೆ ಒಂದು'],
    'interfaceBox': ['Interface', 'इंटरफ़ेस', 'ಇಂಟರ್‌ಫೇಸ್'],
    'lifeline': ['Lifeline', 'लाइफ़लाइन', 'ಲೈಫ್‌ಲೈನ್'],
    'actor': ['Actor', 'एक्टर', 'ಆಕ್ಟರ್'],
    'activation': ['Activation bar', 'एक्टिवेशन बार', 'ಆಕ್ಟಿವೇಶನ್ ಬಾರ್'],
    'er_entity': ['Entity', 'एंटिटी', 'ಎಂಟಿಟಿ'],
    'er_weakEntity': ['Weak entity', 'कमज़ोर एंटिटी', 'ದುರ್ಬಲ ಎಂಟಿಟಿ'],
    'er_attribute': ['Attribute', 'एट्रिब्यूट', 'ಗುಣಲಕ್ಷಣ'],
    'er_key': ['Key attribute', 'की एट्रिब्यूट', 'ಕೀ ಗುಣಲಕ್ಷಣ'],
    'er_multivalued': ['Multivalued attribute', 'बहुमानी एट्रिब्यूट', 'ಬಹುಮೌಲ್ಯ ಗುಣಲಕ್ಷಣ'],
    'er_derived': ['Derived attribute', 'व्युत्पन्न एट्रिब्यूट', 'ವ್ಯುತ್ಪನ್ನ ಗುಣಲಕ್ಷಣ'],
    'er_relationship': ['Relationship', 'संबंध', 'ಸಂಬಂಧ'],
    'er_identifying': ['Identifying relationship', 'पहचान संबंध', 'ಗುರುತಿಸುವ ಸಂಬಂಧ'],
    'flow_startEnd': ['Start / end', 'आरंभ / अंत', 'ಆರಂಭ / ಅಂತ್ಯ'],
    'flow_process': ['Process', 'प्रक्रिया', 'ಪ್ರಕ್ರಿಯೆ'],
    'flow_decision': ['Decision', 'निर्णय', 'ನಿರ್ಧಾರ'],
    'flow_io': ['Input / output', 'इनपुट / आउटपुट', 'ಇನ್‌ಪುಟ್ / ಔಟ್‌ಪುಟ್'],
    'flow_predefined': ['Predefined process', 'पूर्वनिर्धारित प्रक्रिया', 'ಪೂರ್ವನಿರ್ಧಾರಿತ ಪ್ರಕ್ರಿಯೆ'],
    'flow_connector': ['On-page connector', 'पेज कनेक्टर', 'ಪುಟ ಸಂಪರ್ಕಕ'],
    'label': ['Label', 'लेबल', 'ಲೇಬಲ್'],
    'add': ['Add', 'जोड़ें', 'ಸೇರಿಸಿ'],
    'cancel': ['Cancel', 'रद्द करें', 'ರದ್ದುಮಾಡಿ'],
    'close': ['Close', 'बंद करें', 'ಮುಚ್ಚಿ'],
  };
}
