// Written by tool/models/write_scenes.mjs from the scene scripts in tool/models/src/scenes.
// Do not edit by hand: change the script and run `node write_scenes.mjs`.
part of 'scenes.dart';

/// Every narrated scene ([ProcessScene.all]).
const processScenes = <ProcessScene>[
  ProcessScene(
    id: 'photosynthesis',
    subject: 'Biology',
    classes: [7, 10, 11],
    keywords: ['photosynthesis', 'chloroplast', 'chlorophyll', 'leaf', 'stomata', 'thylakoid', 'light reaction', 'calvin cycle', 'atp', 'nadph', 'glucose', 'nutrition in plants', 'life processes'],
    title: LocalText({'en': 'Photosynthesis', 'hi': 'प्रकाश संश्लेषण', 'kn': 'ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆ'}),
    summary: LocalText({'en': 'From a leaf in sunlight to the chloroplast: light splits water and makes ATP and NADPH, and the Calvin cycle turns carbon dioxide into sugar.', 'hi': 'धूप में पत्ती से हरितलवक तक: प्रकाश जल का विघटन कर ATP और NADPH बनाता है, और केल्विन चक्र कार्बन डाइऑक्साइड को शर्करा में बदलता है।', 'kn': 'ಬಿಸಿಲಿನಲ್ಲಿರುವ ಎಲೆಯಿಂದ ಹರಿತ್ತಿನ ಕಣದವರೆಗೆ: ಬೆಳಕು ನೀರನ್ನು ವಿಭಜಿಸಿ ATP ಮತ್ತು NADPH ತಯಾರಿಸುತ್ತದೆ, ಮತ್ತು ಕ್ಯಾಲ್ವಿನ್ ಚಕ್ರ ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡನ್ನು ಸಕ್ಕರೆಯಾಗಿಸುತ್ತದೆ.'}),
    groups: [
      ViewerGroup('leaf', LocalText({'en': 'Leaf', 'hi': 'पत्ती', 'kn': 'ಎಲೆ'})),
      ViewerGroup('cell', LocalText({'en': 'Cell', 'hi': 'कोशिका', 'kn': 'ಕೋಶ'})),
      ViewerGroup('chloroplast', LocalText({'en': 'Chloroplast', 'hi': 'हरितलवक', 'kn': 'ಹರಿತ್ತಿನ ಕಣ'})),
      ViewerGroup('membrane', LocalText({'en': 'Thylakoid membrane', 'hi': 'थायलाकॉइड झिल्ली', 'kn': 'ಥೈಲಕಾಯ್ಡ್ ಪೊರೆ'})),
      ViewerGroup('molecules', LocalText({'en': 'Molecules', 'hi': 'अणु', 'kn': 'ಅಣುಗಳು'})),
    ],
    parts: [
      ViewerPart(id: 'leaf', group: 'leaf', color: '#4a8a32', name: LocalText({'en': 'Leaf', 'hi': 'पत्ती', 'kn': 'ಎಲೆ'}), info: LocalText({'en': 'A thin, flat blade that catches as much light as it can.', 'hi': 'एक पतला, चपटा फलक जो अधिक से अधिक प्रकाश पकड़ता है।', 'kn': 'ಸಾಧ್ಯವಾದಷ್ಟು ಬೆಳಕನ್ನು ಹಿಡಿಯುವ ತೆಳುವಾದ, ಚಪ್ಪಟೆ ಪತ್ರ.'})),
      ViewerPart(id: 'vein', group: 'leaf', color: '#b9cf7a', name: LocalText({'en': 'Vein', 'hi': 'शिरा', 'kn': 'ಎಲೆಯ ನರ'}), info: LocalText({'en': 'Brings water and minerals from the roots, and carries food away.', 'hi': 'जड़ों से जल और खनिज लाती है, और भोजन को दूर ले जाती है।', 'kn': 'ಬೇರುಗಳಿಂದ ನೀರು ಮತ್ತು ಖನಿಜಗಳನ್ನು ತರುತ್ತದೆ, ಆಹಾರವನ್ನು ಸಾಗಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'stem', group: 'leaf', color: '#6f7d3a', name: LocalText({'en': 'Stem', 'hi': 'तना', 'kn': 'ಕಾಂಡ'}), info: LocalText({'en': 'Holds the leaves up to the light.', 'hi': 'पत्तियों को प्रकाश की ओर थामे रखता है।', 'kn': 'ಎಲೆಗಳನ್ನು ಬೆಳಕಿನತ್ತ ಎತ್ತಿ ಹಿಡಿಯುತ್ತದೆ.'})),
      ViewerPart(id: 'sunlight', group: 'molecules', color: '#ffe9a8', name: LocalText({'en': 'Sunlight', 'hi': 'सूर्य का प्रकाश', 'kn': 'ಸೂರ್ಯನ ಬೆಳಕು'}), info: LocalText({'en': 'The energy that drives photosynthesis.', 'hi': 'वह ऊर्जा जो प्रकाश संश्लेषण को चलाती है।', 'kn': 'ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆಯನ್ನು ನಡೆಸುವ ಶಕ್ತಿ.'})),
      ViewerPart(id: 'co2', group: 'molecules', color: '#3c4046', name: LocalText({'en': 'Carbon dioxide (CO₂)', 'hi': 'कार्बन डाइऑक्साइड (CO₂)', 'kn': 'ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ (CO₂)'}), info: LocalText({'en': 'Taken from the air; its carbon ends up in sugar.', 'hi': 'हवा से ली जाती है; इसका कार्बन शर्करा में पहुँचता है।', 'kn': 'ಗಾಳಿಯಿಂದ ಪಡೆಯಲಾಗುತ್ತದೆ; ಅದರ ಇಂಗಾಲ ಸಕ್ಕರೆಯಲ್ಲಿ ಸೇರುತ್ತದೆ.'})),
      ViewerPart(id: 'oxygen', group: 'molecules', color: '#c9473d', name: LocalText({'en': 'Oxygen (O₂)', 'hi': 'ऑक्सीजन (O₂)', 'kn': 'ಆಮ್ಲಜನಕ (O₂)'}), info: LocalText({'en': 'Released from split water; it leaves through the stomata.', 'hi': 'विघटित जल से निकलती है; रंध्रों से बाहर जाती है।', 'kn': 'ವಿಭಜಿತ ನೀರಿನಿಂದ ಬಿಡುಗಡೆಯಾಗಿ ಪತ್ರರಂಧ್ರಗಳ ಮೂಲಕ ಹೊರಹೋಗುತ್ತದೆ.'})),
      ViewerPart(id: 'water', group: 'molecules', color: '#5aa0e0', name: LocalText({'en': 'Water (H₂O)', 'hi': 'जल (H₂O)', 'kn': 'ನೀರು (H₂O)'}), info: LocalText({'en': 'Comes up from the roots; it is split to give electrons.', 'hi': 'जड़ों से ऊपर आता है; इलेक्ट्रॉन देने के लिए इसका विघटन होता है।', 'kn': 'ಬೇರುಗಳಿಂದ ಮೇಲೆ ಬರುತ್ತದೆ; ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳಿಗಾಗಿ ವಿಭಜನೆಯಾಗುತ್ತದೆ.'})),
      ViewerPart(id: 'cuticle', group: 'leaf', color: '#d6e3a0', name: LocalText({'en': 'Cuticle', 'hi': 'उपत्वचा', 'kn': 'ಹೊರಪೊರೆ'}), info: LocalText({'en': 'A waxy, waterproof layer that stops the leaf drying out.', 'hi': 'मोम जैसी जलरोधी परत जो पत्ती को सूखने से बचाती है।', 'kn': 'ಎಲೆ ಒಣಗದಂತೆ ತಡೆಯುವ ಮೇಣದಂತಹ ಜಲನಿರೋಧಕ ಪದರ.'})),
      ViewerPart(id: 'epidermis', group: 'leaf', color: '#dfe8cf', name: LocalText({'en': 'Epidermis', 'hi': 'बाह्यत्वचा', 'kn': 'ಹೊರಚರ್ಮ'}), info: LocalText({'en': 'The leaf’s clear skin: light passes through it.', 'hi': 'पत्ती की पारदर्शी त्वचा: प्रकाश इसके पार जाता है।', 'kn': 'ಎಲೆಯ ಪಾರದರ್ಶಕ ಚರ್ಮ: ಬೆಳಕು ಇದರ ಮೂಲಕ ಹಾದುಹೋಗುತ್ತದೆ.'})),
      ViewerPart(id: 'palisade', group: 'leaf', color: '#6fa64a', name: LocalText({'en': 'Palisade cells', 'hi': 'खंभ कोशिकाएँ', 'kn': 'ಸ್ತಂಭ ಕೋಶಗಳು'}), info: LocalText({'en': 'Tall cells packed with chloroplasts, where most photosynthesis happens.', 'hi': 'हरितलवकों से भरी लंबी कोशिकाएँ, जहाँ अधिकतर प्रकाश संश्लेषण होता है।', 'kn': 'ಹರಿತ್ತಿನ ಕಣಗಳಿಂದ ತುಂಬಿದ ಉದ್ದ ಕೋಶಗಳು; ಹೆಚ್ಚಿನ ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆ ಇಲ್ಲೇ.'})),
      ViewerPart(id: 'spongy', group: 'leaf', color: '#8dbb62', name: LocalText({'en': 'Spongy cells', 'hi': 'स्पंजी कोशिकाएँ', 'kn': 'ಸ್ಪಂಜು ಕೋಶಗಳು'}), info: LocalText({'en': 'Loosely packed, with air spaces for gases to move through.', 'hi': 'ढीले-ढाले जमे, गैसों के आने-जाने के लिए हवा के स्थानों सहित।', 'kn': 'ಅನಿಲಗಳು ಚಲಿಸಲು ಗಾಳಿಯ ಅವಕಾಶಗಳಿರುವ ಸಡಿಲ ಕೋಶಗಳು.'})),
      ViewerPart(id: 'xylem', group: 'leaf', color: '#9a6a48', name: LocalText({'en': 'Xylem', 'hi': 'जाइलम', 'kn': 'ಕ್ಸೈಲಮ್'}), info: LocalText({'en': 'Tubes that carry water up from the roots.', 'hi': 'नलिकाएँ जो जड़ों से जल ऊपर ले जाती हैं।', 'kn': 'ಬೇರುಗಳಿಂದ ನೀರನ್ನು ಮೇಲೆ ಸಾಗಿಸುವ ನಳಿಕೆಗಳು.'})),
      ViewerPart(id: 'phloem', group: 'leaf', color: '#c9cf7a', name: LocalText({'en': 'Phloem', 'hi': 'फ्लोएम', 'kn': 'ಫ್ಲೋಯಮ್'}), info: LocalText({'en': 'Tubes that carry the sugar made in the leaf to the rest of the plant.', 'hi': 'नलिकाएँ जो पत्ती में बनी शर्करा पौधे के बाकी भागों तक ले जाती हैं।', 'kn': 'ಎಲೆಯಲ್ಲಿ ತಯಾರಾದ ಸಕ್ಕರೆಯನ್ನು ಸಸ್ಯದ ಇತರ ಭಾಗಗಳಿಗೆ ಸಾಗಿಸುವ ನಳಿಕೆಗಳು.'})),
      ViewerPart(id: 'stoma', group: 'leaf', color: '#5c8f3a', name: LocalText({'en': 'Stoma and guard cells', 'hi': 'रंध्र और द्वार कोशिकाएँ', 'kn': 'ಪತ್ರರಂಧ್ರ ಮತ್ತು ಕಾವಲು ಕೋಶಗಳು'}), info: LocalText({'en': 'A pore between two guard cells that open and close it, letting CO₂ in and O₂ and water vapour out.', 'hi': 'दो द्वार कोशिकाओं के बीच का छिद्र, जो इसे खोलती-बंद करती हैं; इससे CO₂ अंदर और O₂ व जलवाष्प बाहर जाती है।', 'kn': 'ಎರಡು ಕಾವಲು ಕೋಶಗಳ ನಡುವಿನ ರಂಧ್ರ; ಅವು ಅದನ್ನು ತೆರೆದು ಮುಚ್ಚುತ್ತವೆ. CO₂ ಒಳಗೆ, O₂ ಮತ್ತು ನೀರಾವಿ ಹೊರಗೆ.'})),
      ViewerPart(id: 'cell_wall', group: 'cell', color: '#b9cf8a', name: LocalText({'en': 'Cell wall', 'hi': 'कोशिका भित्ति', 'kn': 'ಕೋಶಭಿತ್ತಿ'}), info: LocalText({'en': 'A stiff wall of cellulose round the cell.', 'hi': 'कोशिका के चारों ओर सेल्यूलोज़ की कठोर भित्ति।', 'kn': 'ಕೋಶದ ಸುತ್ತ ಸೆಲ್ಯುಲೋಸ್‌ನ ಗಟ್ಟಿ ಗೋಡೆ.'})),
      ViewerPart(id: 'vacuole', group: 'cell', color: '#a8d4e6', name: LocalText({'en': 'Central vacuole', 'hi': 'केंद्रीय रिक्तिका', 'kn': 'ಕೇಂದ್ರ ರಸದಾನಿ'}), info: LocalText({'en': 'A large sac of cell sap that keeps the cell firm.', 'hi': 'कोशिका रस की बड़ी थैली जो कोशिका को कड़ा बनाए रखती है।', 'kn': 'ಕೋಶವನ್ನು ಬಿಗಿಯಾಗಿಡುವ ಕೋಶರಸದ ದೊಡ್ಡ ಚೀಲ.'})),
      ViewerPart(id: 'nucleus', group: 'cell', color: '#8f7bb5', name: LocalText({'en': 'Nucleus', 'hi': 'केंद्रक', 'kn': 'ಕೋಶಕೇಂದ್ರ'}), info: LocalText({'en': 'Holds the cell’s DNA and controls its work.', 'hi': 'कोशिका का DNA रखता है और उसके काम नियंत्रित करता है।', 'kn': 'ಕೋಶದ DNA ಹೊಂದಿದ್ದು ಅದರ ಕೆಲಸಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'chloroplasts', group: 'cell', color: '#3f8a3a', name: LocalText({'en': 'Chloroplasts', 'hi': 'हरितलवक', 'kn': 'ಹರಿತ್ತಿನ ಕಣಗಳು'}), info: LocalText({'en': 'The green organelles where photosynthesis takes place.', 'hi': 'हरे कोशिकांग जहाँ प्रकाश संश्लेषण होता है।', 'kn': 'ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆ ನಡೆಯುವ ಹಸಿರು ಅಂಗಕಗಳು.'})),
      ViewerPart(id: 'envelope', group: 'chloroplast', color: '#9fc27a', name: LocalText({'en': 'Double membrane', 'hi': 'दोहरी झिल्ली', 'kn': 'ಎರಡು ಪದರದ ಪೊರೆ'}), info: LocalText({'en': 'An outer and an inner membrane enclose the chloroplast.', 'hi': 'एक बाहरी और एक भीतरी झिल्ली हरितलवक को घेरती हैं।', 'kn': 'ಹೊರ ಮತ್ತು ಒಳ ಪೊರೆಗಳು ಹರಿತ್ತಿನ ಕಣವನ್ನು ಸುತ್ತುವರಿದಿವೆ.'})),
      ViewerPart(id: 'stroma', group: 'chloroplast', color: '#d6dd9a', name: LocalText({'en': 'Stroma', 'hi': 'स्ट्रोमा', 'kn': 'ಸ್ಟ್ರೋಮಾ'}), info: LocalText({'en': 'The fluid inside the chloroplast, where the Calvin cycle makes sugar.', 'hi': 'हरितलवक के अंदर का द्रव, जहाँ केल्विन चक्र शर्करा बनाता है।', 'kn': 'ಹರಿತ್ತಿನ ಕಣದೊಳಗಿನ ದ್ರವ; ಕ್ಯಾಲ್ವಿನ್ ಚಕ್ರ ಇಲ್ಲಿ ಸಕ್ಕರೆ ತಯಾರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'granum', group: 'chloroplast', color: '#2f6b2a', name: LocalText({'en': 'Granum (stack of thylakoids)', 'hi': 'ग्रेनम (थायलाकॉइड का ढेर)', 'kn': 'ಗ್ರಾನಮ್ (ಥೈಲಕಾಯ್ಡ್ ರಾಶಿ)'}), info: LocalText({'en': 'Flat discs stacked like coins; light reactions happen in their membranes.', 'hi': 'सिक्कों की तरह जमी चपटी थैलियाँ; प्रकाश अभिक्रियाएँ इनकी झिल्लियों में होती हैं।', 'kn': 'ನಾಣ್ಯಗಳಂತೆ ಜೋಡಿಸಿದ ಚಪ್ಪಟೆ ಬಿಲ್ಲೆಗಳು; ಬೆಳಕಿನ ಕ್ರಿಯೆಗಳು ಇವುಗಳ ಪೊರೆಗಳಲ್ಲಿ.'})),
      ViewerPart(id: 'lamella', group: 'chloroplast', color: '#4d8a3e', name: LocalText({'en': 'Stroma lamella', 'hi': 'स्ट्रोमा पटलिका', 'kn': 'ಸ್ಟ್ರೋಮಾ ಪಟಲ'}), info: LocalText({'en': 'Thylakoid bridges that join one granum to the next.', 'hi': 'थायलाकॉइड के पुल जो एक ग्रेनम को दूसरे से जोड़ते हैं।', 'kn': 'ಒಂದು ಗ್ರಾನಮ್ ಅನ್ನು ಇನ್ನೊಂದಕ್ಕೆ ಜೋಡಿಸುವ ಥೈಲಕಾಯ್ಡ್ ಸೇತುವೆಗಳು.'})),
      ViewerPart(id: 'starch', group: 'chloroplast', color: '#efe8d8', name: LocalText({'en': 'Starch grain', 'hi': 'मंड कण', 'kn': 'ಪಿಷ್ಟದ ಕಣ'}), info: LocalText({'en': 'Stored sugar.', 'hi': 'जमा की गई शर्करा।', 'kn': 'ಸಂಗ್ರಹಿಸಿದ ಸಕ್ಕರೆ.'})),
      ViewerPart(id: 'membrane', group: 'membrane', color: '#d8dcb0', name: LocalText({'en': 'Thylakoid membrane', 'hi': 'थायलाकॉइड झिल्ली', 'kn': 'ಥೈಲಕಾಯ್ಡ್ ಪೊರೆ'}), info: LocalText({'en': 'A double layer of lipids holding the light-reaction proteins.', 'hi': 'लिपिड की दोहरी परत जिसमें प्रकाश अभिक्रिया के प्रोटीन लगे होते हैं।', 'kn': 'ಬೆಳಕಿನ ಕ್ರಿಯೆಯ ಪ್ರೋಟೀನ್‌ಗಳನ್ನು ಹಿಡಿದಿರುವ ಲಿಪಿಡ್‌ಗಳ ಎರಡು ಪದರ.'})),
      ViewerPart(id: 'lumen', group: 'membrane', color: '#7fb7b0', name: LocalText({'en': 'Thylakoid space (lumen)', 'hi': 'थायलाकॉइड का भीतरी स्थान (ल्यूमेन)', 'kn': 'ಥೈಲಕಾಯ್ಡ್ ಒಳಾವಕಾಶ (ಲ್ಯೂಮೆನ್)'}), info: LocalText({'en': 'Inside the thylakoid; H⁺ ions crowd in here.', 'hi': 'थायलाकॉइड के अंदर; H⁺ आयन यहाँ इकट्ठा होते हैं।', 'kn': 'ಥೈಲಕಾಯ್ಡ್‌ನ ಒಳಗೆ; H⁺ ಅಯಾನುಗಳು ಇಲ್ಲಿ ಕಿಕ್ಕಿರಿಯುತ್ತವೆ.'})),
      ViewerPart(id: 'psii', group: 'membrane', color: '#5aa36a', name: LocalText({'en': 'Photosystem II', 'hi': 'फोटोसिस्टम II', 'kn': 'ಫೋಟೋಸಿಸ್ಟಮ್ II'}), info: LocalText({'en': 'Absorbs light, and splits water to replace its lost electrons.', 'hi': 'प्रकाश सोखता है, और खोए इलेक्ट्रॉनों की पूर्ति के लिए जल का विघटन करता है।', 'kn': 'ಬೆಳಕನ್ನು ಹೀರುತ್ತದೆ; ಕಳೆದುಕೊಂಡ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳ ಬದಲಿಗೆ ನೀರನ್ನು ವಿಭಜಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'lhc', group: 'membrane', color: '#86c46e', name: LocalText({'en': 'Light-harvesting chlorophyll', 'hi': 'प्रकाश-संग्राही क्लोरोफिल', 'kn': 'ಬೆಳಕು ಸಂಗ್ರಹಿಸುವ ಪತ್ರಹರಿತ್ತು'}), info: LocalText({'en': 'Antenna proteins full of chlorophyll that catch light and pass its energy on.', 'hi': 'क्लोरोफिल से भरे एंटीना प्रोटीन जो प्रकाश पकड़कर उसकी ऊर्जा आगे देते हैं।', 'kn': 'ಬೆಳಕನ್ನು ಹಿಡಿದು ಅದರ ಶಕ್ತಿಯನ್ನು ಮುಂದೆ ನೀಡುವ ಪತ್ರಹರಿತ್ತು ತುಂಬಿದ ಆಂಟೆನಾ ಪ್ರೋಟೀನ್‌ಗಳು.'})),
      ViewerPart(id: 'cytb6f', group: 'membrane', color: '#d29b46', name: LocalText({'en': 'Cytochrome b6f', 'hi': 'साइटोक्रोम b6f', 'kn': 'ಸೈಟೋಕ್ರೋಮ್ b6f'}), info: LocalText({'en': 'Passes electrons on and pumps H⁺ into the thylakoid.', 'hi': 'इलेक्ट्रॉन आगे बढ़ाता है और H⁺ को थायलाकॉइड में पंप करता है।', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಮುಂದೆ ಸಾಗಿಸಿ H⁺ ಅನ್ನು ಥೈಲಕಾಯ್ಡ್ ಒಳಗೆ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'psi', group: 'membrane', color: '#4f98ad', name: LocalText({'en': 'Photosystem I', 'hi': 'फोटोसिस्टम I', 'kn': 'ಫೋಟೋಸಿಸ್ಟಮ್ I'}), info: LocalText({'en': 'Uses light to re-energise electrons for making NADPH.', 'hi': 'NADPH बनाने के लिए प्रकाश से इलेक्ट्रॉनों को फिर ऊर्जा देता है।', 'kn': 'NADPH ತಯಾರಿಸಲು ಬೆಳಕಿನಿಂದ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳಿಗೆ ಮತ್ತೆ ಶಕ್ತಿ ನೀಡುತ್ತದೆ.'})),
      ViewerPart(id: 'atp_synthase', group: 'membrane', color: '#c96a5e', name: LocalText({'en': 'ATP synthase', 'hi': 'ATP सिंथेज़', 'kn': 'ATP ಸಿಂಥೇಸ್'}), info: LocalText({'en': 'A rotary enzyme: H⁺ flowing through it turn its rotor, and it makes ATP.', 'hi': 'घूमने वाला एंजाइम: इससे होकर बहते H⁺ इसका रोटर घुमाते हैं, और यह ATP बनाता है।', 'kn': 'ತಿರುಗುವ ಕಿಣ್ವ: ಇದರ ಮೂಲಕ ಹರಿಯುವ H⁺ ಇದರ ರೋಟರ್ ತಿರುಗಿಸುತ್ತವೆ; ಇದು ATP ತಯಾರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'electron', group: 'molecules', color: '#7fe3ff', name: LocalText({'en': 'Electrons', 'hi': 'इलेक्ट्रॉन', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು'}), info: LocalText({'en': 'Carry the energy captured from light.', 'hi': 'प्रकाश से पकड़ी गई ऊर्जा ले जाते हैं।', 'kn': 'ಬೆಳಕಿನಿಂದ ಹಿಡಿದ ಶಕ್ತಿಯನ್ನು ಸಾಗಿಸುತ್ತವೆ.'})),
      ViewerPart(id: 'hion', group: 'molecules', color: '#ff9e7a', name: LocalText({'en': 'Hydrogen ions (H⁺)', 'hi': 'हाइड्रोजन आयन (H⁺)', 'kn': 'ಹೈಡ್ರೋಜನ್ ಅಯಾನುಗಳು (H⁺)'}), info: LocalText({'en': 'Build up inside the thylakoid and flow out through ATP synthase.', 'hi': 'थायलाकॉइड के अंदर जमा होकर ATP सिंथेज़ से बाहर बहते हैं।', 'kn': 'ಥೈಲಕಾಯ್ಡ್ ಒಳಗೆ ಸಂಗ್ರಹವಾಗಿ ATP ಸಿಂಥೇಸ್ ಮೂಲಕ ಹೊರಗೆ ಹರಿಯುತ್ತವೆ.'})),
      ViewerPart(id: 'nadph', group: 'molecules', color: '#4fb3a5', name: LocalText({'en': 'NADPH', 'hi': 'NADPH', 'kn': 'NADPH'}), info: LocalText({'en': 'Carries high-energy electrons to the Calvin cycle.', 'hi': 'उच्च ऊर्जा वाले इलेक्ट्रॉन केल्विन चक्र तक ले जाता है।', 'kn': 'ಹೆಚ್ಚಿನ ಶಕ್ತಿಯ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಕ್ಯಾಲ್ವಿನ್ ಚಕ್ರಕ್ಕೆ ಒಯ್ಯುತ್ತದೆ.'})),
      ViewerPart(id: 'atp', group: 'molecules', color: '#e08d2b', name: LocalText({'en': 'ATP', 'hi': 'ATP', 'kn': 'ATP'}), info: LocalText({'en': 'The cell’s energy currency.', 'hi': 'कोशिका की ऊर्जा मुद्रा।', 'kn': 'ಕೋಶದ ಶಕ್ತಿಯ ನಾಣ್ಯ.'})),
      ViewerPart(id: 'rubisco', group: 'chloroplast', color: '#5f9e8f', name: LocalText({'en': 'RuBisCO', 'hi': 'रुबिस्को', 'kn': 'ರುಬಿಸ್ಕೋ'}), info: LocalText({'en': 'The enzyme that fixes CO₂ — the most abundant protein on Earth.', 'hi': 'वह एंजाइम जो CO₂ का स्थिरीकरण करता है — पृथ्वी पर सबसे अधिक पाया जाने वाला प्रोटीन।', 'kn': 'CO₂ ಅನ್ನು ಸ್ಥಿರೀಕರಿಸುವ ಕಿಣ್ವ — ಭೂಮಿಯ ಮೇಲೆ ಅತಿ ಹೆಚ್ಚು ಇರುವ ಪ್ರೋಟೀನ್.'})),
      ViewerPart(id: 'rubp', group: 'molecules', color: '#9a7bd0', name: LocalText({'en': 'RuBP (5-carbon sugar)', 'hi': 'RuBP (5-कार्बन शर्करा)', 'kn': 'RuBP (5-ಕಾರ್ಬನ್ ಸಕ್ಕರೆ)'}), info: LocalText({'en': 'Accepts CO₂ at the start of the cycle and is rebuilt at its end.', 'hi': 'चक्र की शुरुआत में CO₂ ग्रहण करता है और अंत में फिर बनता है।', 'kn': 'ಚಕ್ರದ ಆರಂಭದಲ್ಲಿ CO₂ ಸ್ವೀಕರಿಸಿ ಕೊನೆಯಲ್ಲಿ ಮತ್ತೆ ತಯಾರಾಗುತ್ತದೆ.'})),
      ViewerPart(id: 'g3p', group: 'molecules', color: '#e0b04a', name: LocalText({'en': 'G3P (3-carbon sugar)', 'hi': 'G3P (3-कार्बन शर्करा)', 'kn': 'G3P (3-ಕಾರ್ಬನ್ ಸಕ್ಕರೆ)'}), info: LocalText({'en': 'The sugar the cycle makes; two of them make one glucose.', 'hi': 'चक्र द्वारा बनी शर्करा; दो से एक ग्लूकोज़ बनता है।', 'kn': 'ಚಕ್ರ ತಯಾರಿಸುವ ಸಕ್ಕರೆ; ಎರಡರಿಂದ ಒಂದು ಗ್ಲೂಕೋಸ್.'})),
      ViewerPart(id: 'glucose', group: 'molecules', color: '#f0e2b8', name: LocalText({'en': 'Glucose', 'hi': 'ग्लूकोज़', 'kn': 'ಗ್ಲೂಕೋಸ್'}), info: LocalText({'en': 'C₆H₁₂O₆: food the plant uses for energy and growth.', 'hi': 'C₆H₁₂O₆: वह भोजन जिसे पौधा ऊर्जा और वृद्धि के लिए उपयोग करता है।', 'kn': 'C₆H₁₂O₆: ಸಸ್ಯ ಶಕ್ತಿ ಮತ್ತು ಬೆಳವಣಿಗೆಗೆ ಬಳಸುವ ಆಹಾರ.'})),
    ],
    steps: [
      ProcessSceneStep(
        id: 'leaf',
        stage: 'leaf',
        seconds: 9.0,
        title: LocalText({'en': 'A green leaf', 'hi': 'हरी पत्ती', 'kn': 'ಹಸಿರು ಎಲೆ'}),
        caption: LocalText({'en': 'Green plants make their own food by photosynthesis. Most of it happens in the leaves.', 'hi': 'हरे पौधे प्रकाश संश्लेषण द्वारा अपना भोजन स्वयं बनाते हैं। यह अधिकतर पत्तियों में होता है।', 'kn': 'ಹಸಿರು ಸಸ್ಯಗಳು ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆಯ ಮೂಲಕ ತಮ್ಮ ಆಹಾರವನ್ನು ತಾವೇ ತಯಾರಿಸುತ್ತವೆ. ಇದು ಹೆಚ್ಚಾಗಿ ಎಲೆಗಳಲ್ಲಿ ನಡೆಯುತ್ತದೆ.'}),
        highlight: ['leaf'],
        labels: ['leaf', 'vein', 'stem'],
      ),
      ProcessSceneStep(
        id: 'inputs',
        stage: 'leaf',
        seconds: 12.0,
        title: LocalText({'en': 'What goes in and out', 'hi': 'क्या अंदर जाता है, क्या बाहर आता है', 'kn': 'ಒಳಗೆ ಹೋಗುವುದು, ಹೊರಗೆ ಬರುವುದು'}),
        caption: LocalText({'en': 'Sunlight falls on the leaf. Carbon dioxide enters through tiny pores called stomata, and water comes up from the roots through the veins. Oxygen goes out.', 'hi': 'पत्ती पर सूर्य का प्रकाश पड़ता है। कार्बन डाइऑक्साइड रंध्र नामक छोटे छिद्रों से अंदर आती है, और जल जड़ों से शिराओं द्वारा ऊपर आता है। ऑक्सीजन बाहर निकलती है।', 'kn': 'ಎಲೆಯ ಮೇಲೆ ಸೂರ್ಯನ ಬೆಳಕು ಬೀಳುತ್ತದೆ. ಪತ್ರರಂಧ್ರಗಳೆಂಬ ಸಣ್ಣ ರಂಧ್ರಗಳ ಮೂಲಕ ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ ಒಳಗೆ ಬರುತ್ತದೆ, ಮತ್ತು ನೀರು ಬೇರುಗಳಿಂದ ನಾಳಗಳ ಮೂಲಕ ಮೇಲೆ ಬರುತ್ತದೆ. ಆಮ್ಲಜನಕ ಹೊರಗೆ ಹೋಗುತ್ತದೆ.'}),
        highlight: ['vein'],
        labels: ['sunlight', 'co2', 'oxygen', 'water'],
      ),
      ProcessSceneStep(
        id: 'tissue',
        stage: 'tissue',
        seconds: 12.0,
        title: LocalText({'en': 'Inside the leaf', 'hi': 'पत्ती के अंदर', 'kn': 'ಎಲೆಯ ಒಳಗೆ'}),
        caption: LocalText({'en': 'A slice of the leaf: tall palisade cells under the upper skin, loosely packed spongy cells with air spaces below, a vein carrying water, and a stoma on the underside.', 'hi': 'पत्ती का एक टुकड़ा: ऊपरी त्वचा के नीचे लंबी खंभ कोशिकाएँ, उनके नीचे हवा के स्थानों वाली ढीली स्पंजी कोशिकाएँ, जल ले जाने वाली एक शिरा, और निचली सतह पर एक रंध्र।', 'kn': 'ಎಲೆಯ ಒಂದು ತುಂಡು: ಮೇಲಿನ ಚರ್ಮದ ಕೆಳಗೆ ಉದ್ದವಾದ ಸ್ತಂಭ ಕೋಶಗಳು, ಅವುಗಳ ಕೆಳಗೆ ಗಾಳಿಯ ಅವಕಾಶಗಳಿರುವ ಸಡಿಲವಾದ ಸ್ಪಂಜು ಕೋಶಗಳು, ನೀರನ್ನು ಸಾಗಿಸುವ ನಾಳ, ಮತ್ತು ಕೆಳಭಾಗದಲ್ಲಿ ಒಂದು ಪತ್ರರಂಧ್ರ.'}),
        highlight: ['palisade'],
        labels: ['cuticle', 'epidermis', 'palisade', 'spongy', 'xylem', 'stoma'],
      ),
      ProcessSceneStep(
        id: 'cell',
        stage: 'cell',
        seconds: 11.0,
        title: LocalText({'en': 'A palisade cell', 'hi': 'एक खंभ कोशिका', 'kn': 'ಒಂದು ಸ್ತಂಭ ಕೋಶ'}),
        caption: LocalText({'en': 'Each palisade cell is packed with green chloroplasts. They drift slowly along the cell wall, around the large central vacuole, to catch the light.', 'hi': 'हर खंभ कोशिका हरे हरितलवकों से भरी होती है। वे बड़ी केंद्रीय रिक्तिका के चारों ओर, कोशिका भित्ति के साथ-साथ धीरे-धीरे घूमते हैं ताकि प्रकाश पकड़ सकें।', 'kn': 'ಪ್ರತಿ ಸ್ತಂಭ ಕೋಶವು ಹಸಿರು ಹರಿತ್ತಿನ ಕಣಗಳಿಂದ ತುಂಬಿರುತ್ತದೆ. ಬೆಳಕನ್ನು ಹಿಡಿಯಲು ಅವು ದೊಡ್ಡ ಕೇಂದ್ರ ರಸದಾನಿಯ ಸುತ್ತ, ಕೋಶಭಿತ್ತಿಯ ಉದ್ದಕ್ಕೂ ನಿಧಾನವಾಗಿ ಚಲಿಸುತ್ತವೆ.'}),
        highlight: ['chloroplasts'],
        labels: ['cell_wall', 'vacuole', 'nucleus', 'chloroplasts'],
      ),
      ProcessSceneStep(
        id: 'chloroplast',
        stage: 'chloroplast',
        seconds: 12.0,
        title: LocalText({'en': 'The chloroplast', 'hi': 'हरितलवक', 'kn': 'ಹರಿತ್ತಿನ ಕಣ'}),
        caption: LocalText({'en': 'Inside its double membrane, a chloroplast holds stacks of flat discs called thylakoids (a stack is a granum) in a fluid called the stroma. The green pigment chlorophyll sits in the thylakoid membranes.', 'hi': 'अपनी दोहरी झिल्ली के अंदर हरितलवक में थायलाकॉइड नामक चपटी थैलियों के ढेर (ग्रेनम) होते हैं, जो स्ट्रोमा नामक द्रव में रहते हैं। हरा वर्णक क्लोरोफिल थायलाकॉइड की झिल्लियों में होता है।', 'kn': 'ತನ್ನ ಎರಡು ಪದರದ ಪೊರೆಯೊಳಗೆ ಹರಿತ್ತಿನ ಕಣವು ಸ್ಟ್ರೋಮಾ ಎಂಬ ದ್ರವದಲ್ಲಿ ಥೈಲಕಾಯ್ಡ್‌ಗಳೆಂಬ ಚಪ್ಪಟೆ ಬಿಲ್ಲೆಗಳ ರಾಶಿಗಳನ್ನು (ಗ್ರಾನಮ್) ಹೊಂದಿದೆ. ಹಸಿರು ವರ್ಣದ್ರವ್ಯ ಪತ್ರಹರಿತ್ತು ಥೈಲಕಾಯ್ಡ್ ಪೊರೆಗಳಲ್ಲಿರುತ್ತದೆ.'}),
        highlight: ['granum'],
        labels: ['envelope', 'stroma', 'granum', 'lamella', 'starch'],
      ),
      ProcessSceneStep(
        id: 'light',
        stage: 'membrane',
        seconds: 11.0,
        title: LocalText({'en': 'Capturing light', 'hi': 'प्रकाश को पकड़ना', 'kn': 'ಬೆಳಕನ್ನು ಹಿಡಿಯುವುದು'}),
        caption: LocalText({'en': 'The light reactions begin. Chlorophyll in photosystem II absorbs light energy, and this energy lifts electrons to a high-energy state.', 'hi': 'प्रकाश अभिक्रियाएँ शुरू होती हैं। फोटोसिस्टम II में क्लोरोफिल प्रकाश ऊर्जा सोखता है, और यह ऊर्जा इलेक्ट्रॉनों को उच्च ऊर्जा अवस्था में पहुँचा देती है।', 'kn': 'ಬೆಳಕಿನ ಕ್ರಿಯೆಗಳು ಆರಂಭವಾಗುತ್ತವೆ. ಫೋಟೋಸಿಸ್ಟಮ್ II ರಲ್ಲಿರುವ ಪತ್ರಹರಿತ್ತು ಬೆಳಕಿನ ಶಕ್ತಿಯನ್ನು ಹೀರಿಕೊಳ್ಳುತ್ತದೆ; ಈ ಶಕ್ತಿ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಹೆಚ್ಚಿನ ಶಕ್ತಿಯ ಸ್ಥಿತಿಗೆ ಏರಿಸುತ್ತದೆ.'}),
        highlight: ['psii', 'lhc'],
        labels: ['membrane', 'lhc', 'psii', 'electron'],
      ),
      ProcessSceneStep(
        id: 'water',
        stage: 'membrane',
        seconds: 12.0,
        title: LocalText({'en': 'Splitting water', 'hi': 'जल का विघटन', 'kn': 'ನೀರಿನ ವಿಭಜನೆ'}),
        caption: LocalText({'en': 'To replace those electrons, water is split inside the thylakoid. Oxygen is released as a by-product, and hydrogen ions (H⁺) are left behind.', 'hi': 'उन इलेक्ट्रॉनों की पूर्ति के लिए थायलाकॉइड के अंदर जल का विघटन होता है। ऑक्सीजन उप-उत्पाद के रूप में मुक्त होती है, और हाइड्रोजन आयन (H⁺) पीछे रह जाते हैं।', 'kn': 'ಆ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳ ಬದಲಿಗೆ ಥೈಲಕಾಯ್ಡ್ ಒಳಗೆ ನೀರು ವಿಭಜನೆಯಾಗುತ್ತದೆ. ಆಮ್ಲಜನಕ ಉಪ-ಉತ್ಪನ್ನವಾಗಿ ಬಿಡುಗಡೆಯಾಗುತ್ತದೆ, ಮತ್ತು ಹೈಡ್ರೋಜನ್ ಅಯಾನುಗಳು (H⁺) ಉಳಿಯುತ್ತವೆ.'}),
        highlight: ['psii'],
        labels: ['water', 'oxygen', 'hion', 'lumen'],
      ),
      ProcessSceneStep(
        id: 'transport',
        stage: 'membrane',
        seconds: 14.0,
        title: LocalText({'en': 'Electron transport and NADPH', 'hi': 'इलेक्ट्रॉन परिवहन और NADPH', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್ ಸಾಗಣೆ ಮತ್ತು NADPH'}),
        caption: LocalText({'en': 'The electrons pass along a chain of proteins to photosystem I, which uses more light to boost them again. They are used to make NADPH. On the way, H⁺ ions are pumped into the thylakoid.', 'hi': 'इलेक्ट्रॉन प्रोटीनों की एक शृंखला से होकर फोटोसिस्टम I तक जाते हैं, जो और प्रकाश लेकर उन्हें फिर ऊर्जा देता है। इनसे NADPH बनता है। रास्ते में H⁺ आयन थायलाकॉइड के अंदर पंप किए जाते हैं।', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು ಪ್ರೋಟೀನ್‌ಗಳ ಸರಪಳಿಯ ಮೂಲಕ ಫೋಟೋಸಿಸ್ಟಮ್ I ಗೆ ಸಾಗುತ್ತವೆ; ಅದು ಇನ್ನಷ್ಟು ಬೆಳಕನ್ನು ಬಳಸಿ ಅವುಗಳಿಗೆ ಮತ್ತೆ ಶಕ್ತಿ ನೀಡುತ್ತದೆ. ಅವುಗಳಿಂದ NADPH ತಯಾರಾಗುತ್ತದೆ. ದಾರಿಯಲ್ಲಿ H⁺ ಅಯಾನುಗಳನ್ನು ಥೈಲಕಾಯ್ಡ್ ಒಳಗೆ ಪಂಪ್ ಮಾಡಲಾಗುತ್ತದೆ.'}),
        highlight: ['cytb6f', 'psi'],
        labels: ['psii', 'cytb6f', 'psi', 'nadph', 'electron'],
      ),
      ProcessSceneStep(
        id: 'atp',
        stage: 'membrane',
        seconds: 12.0,
        title: LocalText({'en': 'Making ATP', 'hi': 'ATP का बनना', 'kn': 'ATP ತಯಾರಿಕೆ'}),
        caption: LocalText({'en': 'H⁺ ions flow back out through ATP synthase. The flow spins it like a turbine, and it joins ADP and phosphate into ATP, the cell’s energy currency.', 'hi': 'H⁺ आयन ATP सिंथेज़ से होकर वापस बाहर बहते हैं। यह बहाव उसे टरबाइन की तरह घुमाता है, और वह ADP तथा फॉस्फेट को जोड़कर ATP बनाता है, जो कोशिका की ऊर्जा मुद्रा है।', 'kn': 'H⁺ ಅಯಾನುಗಳು ATP ಸಿಂಥೇಸ್ ಮೂಲಕ ಮರಳಿ ಹೊರಗೆ ಹರಿಯುತ್ತವೆ. ಈ ಹರಿವು ಅದನ್ನು ಟರ್ಬೈನಿನಂತೆ ತಿರುಗಿಸುತ್ತದೆ, ಮತ್ತು ಅದು ADP ಮತ್ತು ಫಾಸ್ಫೇಟನ್ನು ಸೇರಿಸಿ ಕೋಶದ ಶಕ್ತಿಯ ನಾಣ್ಯವಾದ ATP ಯನ್ನು ತಯಾರಿಸುತ್ತದೆ.'}),
        highlight: ['atp_synthase'],
        labels: ['atp_synthase', 'hion', 'atp'],
      ),
      ProcessSceneStep(
        id: 'calvin',
        stage: 'stroma',
        seconds: 15.0,
        title: LocalText({'en': 'The Calvin cycle', 'hi': 'केल्विन चक्र', 'kn': 'ಕ್ಯಾಲ್ವಿನ್ ಚಕ್ರ'}),
        caption: LocalText({'en': 'In the stroma, the enzyme RuBisCO fixes carbon dioxide onto a five-carbon sugar, RuBP. Using ATP and NADPH from the light reactions, the cycle turns it into a three-carbon sugar, G3P.', 'hi': 'स्ट्रोमा में रुबिस्को एंजाइम कार्बन डाइऑक्साइड को पाँच-कार्बन शर्करा RuBP से जोड़ देता है। प्रकाश अभिक्रियाओं से मिले ATP और NADPH की मदद से यह चक्र उसे तीन-कार्बन शर्करा G3P में बदल देता है।', 'kn': 'ಸ್ಟ್ರೋಮಾದಲ್ಲಿ ರುಬಿಸ್ಕೋ ಕಿಣ್ವವು ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡನ್ನು ಐದು-ಕಾರ್ಬನ್ ಸಕ್ಕರೆ RuBP ಗೆ ಜೋಡಿಸುತ್ತದೆ. ಬೆಳಕಿನ ಕ್ರಿಯೆಗಳಿಂದ ಬಂದ ATP ಮತ್ತು NADPH ಬಳಸಿ ಈ ಚಕ್ರವು ಅದನ್ನು ಮೂರು-ಕಾರ್ಬನ್ ಸಕ್ಕರೆ G3P ಆಗಿ ಬದಲಾಯಿಸುತ್ತದೆ.'}),
        highlight: ['rubisco'],
        labels: ['rubisco', 'co2', 'rubp', 'atp', 'nadph'],
      ),
      ProcessSceneStep(
        id: 'glucose',
        stage: 'stroma',
        seconds: 12.0,
        title: LocalText({'en': 'Sugar is made', 'hi': 'शर्करा बनती है', 'kn': 'ಸಕ್ಕರೆ ತಯಾರಾಗುತ್ತದೆ'}),
        caption: LocalText({'en': 'Most G3P stays in the cycle to rebuild RuBP. The rest is joined into glucose, which the plant uses for energy or stores as starch.', 'hi': 'अधिकांश G3P चक्र में रहकर फिर से RuBP बनाता है। बाकी जुड़कर ग्लूकोज़ बनाता है, जिसे पौधा ऊर्जा के लिए उपयोग करता है या मंड (स्टार्च) के रूप में जमा करता है।', 'kn': 'ಹೆಚ್ಚಿನ G3P ಚಕ್ರದಲ್ಲೇ ಉಳಿದು ಮತ್ತೆ RuBP ಯನ್ನು ತಯಾರಿಸುತ್ತದೆ. ಉಳಿದದ್ದು ಸೇರಿ ಗ್ಲೂಕೋಸ್ ಆಗುತ್ತದೆ; ಸಸ್ಯವು ಅದನ್ನು ಶಕ್ತಿಗಾಗಿ ಬಳಸುತ್ತದೆ ಅಥವಾ ಪಿಷ್ಟವಾಗಿ ಸಂಗ್ರಹಿಸುತ್ತದೆ.'}),
        labels: ['g3p', 'glucose', 'rubp'],
      ),
      ProcessSceneStep(
        id: 'summary',
        stage: 'leaf',
        seconds: 12.0,
        title: LocalText({'en': 'In short', 'hi': 'संक्षेप में', 'kn': 'ಸಂಕ್ಷಿಪ್ತವಾಗಿ'}),
        caption: LocalText({'en': '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ (glucose) + 6O₂. Chlorophyll in the leaf turns light into the chemical energy of food.', 'hi': '6CO₂ + 6H₂O + प्रकाश ऊर्जा → C₆H₁₂O₆ (ग्लूकोज़) + 6O₂। पत्ती का क्लोरोफिल प्रकाश ऊर्जा को भोजन की रासायनिक ऊर्जा में बदल देता है।', 'kn': '6CO₂ + 6H₂O + ಬೆಳಕಿನ ಶಕ್ತಿ → C₆H₁₂O₆ (ಗ್ಲೂಕೋಸ್) + 6O₂. ಎಲೆಯ ಪತ್ರಹರಿತ್ತು ಬೆಳಕಿನ ಶಕ್ತಿಯನ್ನು ಆಹಾರದ ರಾಸಾಯನಿಕ ಶಕ್ತಿಯಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ.'}),
        highlight: ['leaf'],
        labels: ['sunlight', 'co2', 'water', 'oxygen'],
      ),
    ],
  ),
  ProcessScene(
    id: 'respiration',
    subject: 'Biology',
    classes: [7, 10, 11],
    keywords: ['respiration', 'cellular respiration', 'mitochondria', 'glycolysis', 'krebs cycle', 'electron transport chain', 'atp', 'aerobic', 'anaerobic', 'lactic acid', 'fermentation', 'life processes'],
    title: LocalText({'en': 'Cellular respiration', 'hi': 'कोशिकीय श्वसन', 'kn': 'ಕೋಶೀಯ ಉಸಿರಾಟ'}),
    summary: LocalText({'en': 'How a cell releases the energy in glucose: glycolysis in the cytoplasm, then the Krebs cycle and the electron transport chain in the mitochondria, where oxygen is used and most ATP is made.', 'hi': 'कोशिका ग्लूकोज़ की ऊर्जा कैसे मुक्त करती है: कोशिकाद्रव्य में ग्लाइकोलाइसिस, फिर माइटोकॉन्ड्रिया में क्रेब्स चक्र और इलेक्ट्रॉन परिवहन शृंखला, जहाँ ऑक्सीजन का उपयोग होता है और अधिकांश ATP बनता है।', 'kn': 'ಕೋಶವು ಗ್ಲೂಕೋಸ್‌ನ ಶಕ್ತಿಯನ್ನು ಹೇಗೆ ಬಿಡುಗಡೆ ಮಾಡುತ್ತದೆ: ಕೋಶದ್ರವ್ಯದಲ್ಲಿ ಗ್ಲೈಕೊಲಿಸಿಸ್, ನಂತರ ಮೈಟೊಕಾಂಡ್ರಿಯದಲ್ಲಿ ಕ್ರೆಬ್ಸ್ ಚಕ್ರ ಮತ್ತು ಇಲೆಕ್ಟ್ರಾನ್ ಸಾಗಣೆ ಸರಪಳಿ; ಅಲ್ಲಿ ಆಮ್ಲಜನಕ ಬಳಕೆಯಾಗಿ ಹೆಚ್ಚಿನ ATP ತಯಾರಾಗುತ್ತದೆ.'}),
    groups: [
      ViewerGroup('cell', LocalText({'en': 'Cell', 'hi': 'कोशिका', 'kn': 'ಕೋಶ'})),
      ViewerGroup('mito', LocalText({'en': 'Mitochondrion', 'hi': 'माइटोकॉन्ड्रिया', 'kn': 'ಮೈಟೊಕಾಂಡ್ರಿಯ'})),
      ViewerGroup('chain', LocalText({'en': 'Electron transport chain', 'hi': 'इलेक्ट्रॉन परिवहन शृंखला', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್ ಸಾಗಣೆ ಸರಪಳಿ'})),
      ViewerGroup('molecules', LocalText({'en': 'Molecules', 'hi': 'अणु', 'kn': 'ಅಣುಗಳು'})),
    ],
    parts: [
      ViewerPart(id: 'membrane', group: 'cell', color: '#d8b4a6', name: LocalText({'en': 'Cell membrane', 'hi': 'कोशिका झिल्ली', 'kn': 'ಕೋಶ ಪೊರೆ'}), info: LocalText({'en': 'Lets glucose and oxygen in, and carbon dioxide out.', 'hi': 'ग्लूकोज़ और ऑक्सीजन को अंदर और कार्बन डाइऑक्साइड को बाहर जाने देती है।', 'kn': 'ಗ್ಲೂಕೋಸ್ ಮತ್ತು ಆಮ್ಲಜನಕವನ್ನು ಒಳಗೆ, ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡನ್ನು ಹೊರಗೆ ಬಿಡುತ್ತದೆ.'})),
      ViewerPart(id: 'nucleus', group: 'cell', color: '#7d68a6', name: LocalText({'en': 'Nucleus', 'hi': 'केंद्रक', 'kn': 'ಕೋಶಕೇಂದ್ರ'}), info: LocalText({'en': 'Controls the cell.', 'hi': 'कोशिका को नियंत्रित करता है।', 'kn': 'ಕೋಶವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'cytoplasm', group: 'cell', color: '#8a6a66', name: LocalText({'en': 'Cytoplasm', 'hi': 'कोशिकाद्रव्य', 'kn': 'ಕೋಶದ್ರವ್ಯ'}), info: LocalText({'en': 'The jelly-like fluid of the cell, where glycolysis happens.', 'hi': 'कोशिका का जेली जैसा द्रव, जहाँ ग्लाइकोलाइसिस होता है।', 'kn': 'ಕೋಶದ ಲೋಳೆಯಂತಹ ದ್ರವ; ಗ್ಲೈಕೊಲಿಸಿಸ್ ಇಲ್ಲಿ ನಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'mitochondria', group: 'cell', color: '#c46a4f', name: LocalText({'en': 'Mitochondria', 'hi': 'माइटोकॉन्ड्रिया', 'kn': 'ಮೈಟೊಕಾಂಡ್ರಿಯಗಳು'}), info: LocalText({'en': 'The powerhouses of the cell, where aerobic respiration releases most of the energy.', 'hi': 'कोशिका के ऊर्जा घर, जहाँ वायवीय श्वसन से अधिकांश ऊर्जा मुक्त होती है।', 'kn': 'ಕೋಶದ ಶಕ್ತಿ ಕೇಂದ್ರಗಳು; ವಾಯುವಿಕ ಉಸಿರಾಟ ಹೆಚ್ಚಿನ ಶಕ್ತಿಯನ್ನು ಇಲ್ಲಿ ಬಿಡುಗಡೆ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'enzymes', group: 'cell', color: '#7f9a86', name: LocalText({'en': 'Enzymes of glycolysis', 'hi': 'ग्लाइकोलाइसिस के एंजाइम', 'kn': 'ಗ್ಲೈಕೊಲಿಸಿಸ್ ಕಿಣ್ವಗಳು'}), info: LocalText({'en': 'Ten enzymes break glucose down step by step.', 'hi': 'दस एंजाइम ग्लूकोज़ को चरण-दर-चरण तोड़ते हैं।', 'kn': 'ಹತ್ತು ಕಿಣ್ವಗಳು ಗ್ಲೂಕೋಸನ್ನು ಹಂತ ಹಂತವಾಗಿ ವಿಭಜಿಸುತ್ತವೆ.'})),
      ViewerPart(id: 'outer_membrane', group: 'mito', color: '#c97a5a', name: LocalText({'en': 'Outer membrane', 'hi': 'बाहरी झिल्ली', 'kn': 'ಹೊರಪೊರೆ'}), info: LocalText({'en': 'A smooth membrane around the mitochondrion.', 'hi': 'माइटोकॉन्ड्रिया के चारों ओर एक चिकनी झिल्ली।', 'kn': 'ಮೈಟೊಕಾಂಡ್ರಿಯದ ಸುತ್ತ ನಯವಾದ ಪೊರೆ.'})),
      ViewerPart(id: 'cristae', group: 'mito', color: '#e0957a', name: LocalText({'en': 'Inner membrane (cristae)', 'hi': 'भीतरी झिल्ली (क्रिस्टी)', 'kn': 'ಒಳಪೊರೆ (ಕ್ರಿಸ್ಟೇ)'}), info: LocalText({'en': 'Folded many times to make room for the electron transport chain and ATP synthase.', 'hi': 'इलेक्ट्रॉन परिवहन शृंखला और ATP सिंथेज़ के लिए जगह बनाने हेतु कई बार मुड़ी हुई।', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್ ಸಾಗಣೆ ಸರಪಳಿ ಮತ್ತು ATP ಸಿಂಥೇಸ್‌ಗೆ ಜಾಗ ಮಾಡಲು ಹಲವು ಬಾರಿ ಮಡಿಚಲಾಗಿದೆ.'})),
      ViewerPart(id: 'matrix', group: 'mito', color: '#7a3e36', name: LocalText({'en': 'Matrix', 'hi': 'मैट्रिक्स', 'kn': 'ಮ್ಯಾಟ್ರಿಕ್ಸ್'}), info: LocalText({'en': 'The fluid inside the inner membrane, where the Krebs cycle runs.', 'hi': 'भीतरी झिल्ली के अंदर का द्रव, जहाँ क्रेब्स चक्र चलता है।', 'kn': 'ಒಳಪೊರೆಯೊಳಗಿನ ದ್ರವ; ಕ್ರೆಬ್ಸ್ ಚಕ್ರ ಇಲ್ಲಿ ನಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'ims', group: 'mito', color: '#b07a6a', name: LocalText({'en': 'Space between the membranes', 'hi': 'झिल्लियों के बीच का स्थान', 'kn': 'ಪೊರೆಗಳ ನಡುವಿನ ಜಾಗ'}), info: LocalText({'en': 'H⁺ ions are pumped in here and build up.', 'hi': 'H⁺ आयन यहाँ पंप होकर जमा होते हैं।', 'kn': 'H⁺ ಅಯಾನುಗಳು ಇಲ್ಲಿಗೆ ಪಂಪ್ ಆಗಿ ಸಂಗ್ರಹವಾಗುತ್ತವೆ.'})),
      ViewerPart(id: 'complex1', group: 'chain', color: '#8a6fae', name: LocalText({'en': 'Complex I', 'hi': 'कॉम्प्लेक्स I', 'kn': 'ಕಾಂಪ್ಲೆಕ್ಸ್ I'}), info: LocalText({'en': 'Takes electrons from NADH and pumps H⁺.', 'hi': 'NADH से इलेक्ट्रॉन लेता है और H⁺ पंप करता है।', 'kn': 'NADH ನಿಂದ ಇಲೆಕ್ಟ್ರಾನ್ ಪಡೆದು H⁺ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'complex2', group: 'chain', color: '#c2a35a', name: LocalText({'en': 'Complex II', 'hi': 'कॉम्प्लेक्स II', 'kn': 'ಕಾಂಪ್ಲೆಕ್ಸ್ II'}), info: LocalText({'en': 'Takes electrons from FADH₂.', 'hi': 'FADH₂ से इलेक्ट्रॉन लेता है।', 'kn': 'FADH₂ ನಿಂದ ಇಲೆಕ್ಟ್ರಾನ್ ಪಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'complex3', group: 'chain', color: '#4f8fa0', name: LocalText({'en': 'Complex III', 'hi': 'कॉम्प्लेक्स III', 'kn': 'ಕಾಂಪ್ಲೆಕ್ಸ್ III'}), info: LocalText({'en': 'Passes electrons on to cytochrome c and pumps H⁺.', 'hi': 'इलेक्ट्रॉन साइटोक्रोम c को देता है और H⁺ पंप करता है।', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಸೈಟೋಕ್ರೋಮ್ c ಗೆ ನೀಡಿ H⁺ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'complex4', group: 'chain', color: '#6f9f6a', name: LocalText({'en': 'Complex IV', 'hi': 'कॉम्प्लेक्स IV', 'kn': 'ಕಾಂಪ್ಲೆಕ್ಸ್ IV'}), info: LocalText({'en': 'Gives the electrons to oxygen, making water, and pumps H⁺.', 'hi': 'इलेक्ट्रॉन ऑक्सीजन को देकर जल बनाता है, और H⁺ पंप करता है।', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಆಮ್ಲಜನಕಕ್ಕೆ ನೀಡಿ ನೀರು ತಯಾರಿಸುತ್ತದೆ; H⁺ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'atp_synthase', group: 'chain', color: '#a8574d', name: LocalText({'en': 'ATP synthase', 'hi': 'ATP सिंथेज़', 'kn': 'ATP ಸಿಂಥೇಸ್'}), info: LocalText({'en': 'A rotary enzyme driven by H⁺ flowing through it; it makes ATP.', 'hi': 'इससे होकर बहते H⁺ से चलने वाला घूर्णी एंजाइम; यह ATP बनाता है।', 'kn': 'ಇದರ ಮೂಲಕ ಹರಿಯುವ H⁺ ನಿಂದ ತಿರುಗುವ ಕಿಣ್ವ; ಇದು ATP ತಯಾರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'glucose', group: 'molecules', color: '#f0e2b8', name: LocalText({'en': 'Glucose', 'hi': 'ग्लूकोज़', 'kn': 'ಗ್ಲೂಕೋಸ್'}), info: LocalText({'en': 'C₆H₁₂O₆, the fuel.', 'hi': 'C₆H₁₂O₆, ईंधन।', 'kn': 'C₆H₁₂O₆, ಇಂಧನ.'})),
      ViewerPart(id: 'pyruvate', group: 'molecules', color: '#d9b06a', name: LocalText({'en': 'Pyruvate', 'hi': 'पाइरुवेट', 'kn': 'ಪೈರುವೇಟ್'}), info: LocalText({'en': 'A three-carbon molecule; glycolysis makes two from each glucose.', 'hi': 'तीन-कार्बन अणु; ग्लाइकोलाइसिस हर ग्लूकोज़ से दो बनाता है।', 'kn': 'ಮೂರು-ಕಾರ್ಬನ್ ಅಣು; ಗ್ಲೈಕೊಲಿಸಿಸ್ ಪ್ರತಿ ಗ್ಲೂಕೋಸ್‌ನಿಂದ ಎರಡು ತಯಾರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'acetyl_coa', group: 'molecules', color: '#c9a64a', name: LocalText({'en': 'Acetyl-CoA', 'hi': 'एसिटाइल-CoA', 'kn': 'ಅಸಿಟೈಲ್-CoA'}), info: LocalText({'en': 'Carries two carbons into the Krebs cycle.', 'hi': 'दो कार्बन क्रेब्स चक्र में ले जाता है।', 'kn': 'ಎರಡು ಕಾರ್ಬನ್‌ಗಳನ್ನು ಕ್ರೆಬ್ಸ್ ಚಕ್ರಕ್ಕೆ ಒಯ್ಯುತ್ತದೆ.'})),
      ViewerPart(id: 'citrate', group: 'molecules', color: '#9a7bd0', name: LocalText({'en': 'Citric acid (6 carbons)', 'hi': 'साइट्रिक अम्ल (6 कार्बन)', 'kn': 'ಸಿಟ್ರಿಕ್ ಆಮ್ಲ (6 ಕಾರ್ಬನ್)'}), info: LocalText({'en': 'Formed when acetyl-CoA joins the four-carbon acid.', 'hi': 'एसिटाइल-CoA के चार-कार्बन अम्ल से जुड़ने पर बनता है।', 'kn': 'ಅಸಿಟೈಲ್-CoA ನಾಲ್ಕು-ಕಾರ್ಬನ್ ಆಮ್ಲದೊಂದಿಗೆ ಸೇರಿದಾಗ ಉಂಟಾಗುತ್ತದೆ.'})),
      ViewerPart(id: 'co2', group: 'molecules', color: '#3c4046', name: LocalText({'en': 'Carbon dioxide (CO₂)', 'hi': 'कार्बन डाइऑक्साइड (CO₂)', 'kn': 'ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ (CO₂)'}), info: LocalText({'en': 'The waste carbon, breathed out.', 'hi': 'अपशिष्ट कार्बन, जो साँस से बाहर जाता है।', 'kn': 'ತ್ಯಾಜ್ಯ ಇಂಗಾಲ; ಉಸಿರಿನಿಂದ ಹೊರಹೋಗುತ್ತದೆ.'})),
      ViewerPart(id: 'nadh', group: 'molecules', color: '#4fb3a5', name: LocalText({'en': 'NADH and FADH₂', 'hi': 'NADH और FADH₂', 'kn': 'NADH ಮತ್ತು FADH₂'}), info: LocalText({'en': 'Carry high-energy electrons to the electron transport chain.', 'hi': 'उच्च ऊर्जा वाले इलेक्ट्रॉन इलेक्ट्रॉन परिवहन शृंखला तक ले जाते हैं।', 'kn': 'ಹೆಚ್ಚಿನ ಶಕ್ತಿಯ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಸಾಗಣೆ ಸರಪಳಿಗೆ ಒಯ್ಯುತ್ತವೆ.'})),
      ViewerPart(id: 'atp', group: 'molecules', color: '#e08d2b', name: LocalText({'en': 'ATP', 'hi': 'ATP', 'kn': 'ATP'}), info: LocalText({'en': 'The cell’s energy currency.', 'hi': 'कोशिका की ऊर्जा मुद्रा।', 'kn': 'ಕೋಶದ ಶಕ್ತಿಯ ನಾಣ್ಯ.'})),
      ViewerPart(id: 'oxygen', group: 'molecules', color: '#c9473d', name: LocalText({'en': 'Oxygen (O₂)', 'hi': 'ऑक्सीजन (O₂)', 'kn': 'ಆಮ್ಲಜನಕ (O₂)'}), info: LocalText({'en': 'Accepts the electrons at the end of the chain.', 'hi': 'शृंखला के अंत में इलेक्ट्रॉन ग्रहण करती है।', 'kn': 'ಸರಪಳಿಯ ಕೊನೆಯಲ್ಲಿ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಸ್ವೀಕರಿಸುತ್ತದೆ.'})),
      ViewerPart(id: 'water', group: 'molecules', color: '#5aa0e0', name: LocalText({'en': 'Water (H₂O)', 'hi': 'जल (H₂O)', 'kn': 'ನೀರು (H₂O)'}), info: LocalText({'en': 'Made from oxygen, electrons and H⁺.', 'hi': 'ऑक्सीजन, इलेक्ट्रॉनों और H⁺ से बनता है।', 'kn': 'ಆಮ್ಲಜನಕ, ಇಲೆಕ್ಟ್ರಾನ್ ಮತ್ತು H⁺ ನಿಂದ ತಯಾರಾಗುತ್ತದೆ.'})),
      ViewerPart(id: 'electron', group: 'molecules', color: '#7fe3ff', name: LocalText({'en': 'Electrons', 'hi': 'इलेक्ट्रॉन', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು'}), info: LocalText({'en': 'Their energy pumps the H⁺ ions.', 'hi': 'इनकी ऊर्जा H⁺ आयनों को पंप करती है।', 'kn': 'ಇವುಗಳ ಶಕ್ತಿ H⁺ ಅಯಾನುಗಳನ್ನು ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'hion', group: 'molecules', color: '#ff9e7a', name: LocalText({'en': 'Hydrogen ions (H⁺)', 'hi': 'हाइड्रोजन आयन (H⁺)', 'kn': 'ಹೈಡ್ರೋಜನ್ ಅಯಾನುಗಳು (H⁺)'}), info: LocalText({'en': 'Pumped between the membranes; flowing back, they drive ATP synthase.', 'hi': 'झिल्लियों के बीच पंप होते हैं; लौटते समय ATP सिंथेज़ को चलाते हैं।', 'kn': 'ಪೊರೆಗಳ ನಡುವೆ ಪಂಪ್ ಆಗುತ್ತವೆ; ಮರಳುವಾಗ ATP ಸಿಂಥೇಸ್ ಅನ್ನು ನಡೆಸುತ್ತವೆ.'})),
      ViewerPart(id: 'lactate', group: 'molecules', color: '#e0c08a', name: LocalText({'en': 'Lactic acid', 'hi': 'लैक्टिक अम्ल', 'kn': 'ಲ್ಯಾಕ್ಟಿಕ್ ಆಮ್ಲ'}), info: LocalText({'en': 'Made from pyruvate in muscles short of oxygen.', 'hi': 'ऑक्सीजन की कमी वाली पेशियों में पाइरुवेट से बनता है।', 'kn': 'ಆಮ್ಲಜನಕದ ಕೊರತೆಯಿರುವ ಸ್ನಾಯುಗಳಲ್ಲಿ ಪೈರುವೇಟ್‌ನಿಂದ ತಯಾರಾಗುತ್ತದೆ.'})),
    ],
    steps: [
      ProcessSceneStep(
        id: 'cell',
        stage: 'cell',
        seconds: 11.0,
        title: LocalText({'en': 'Energy from food', 'hi': 'भोजन से ऊर्जा', 'kn': 'ಆಹಾರದಿಂದ ಶಕ್ತಿ'}),
        caption: LocalText({'en': 'Every living cell releases energy from food by respiration. Glucose and oxygen go in; carbon dioxide and water come out, and the energy is stored as ATP.', 'hi': 'हर जीवित कोशिका श्वसन द्वारा भोजन से ऊर्जा मुक्त करती है। ग्लूकोज़ और ऑक्सीजन अंदर जाते हैं; कार्बन डाइऑक्साइड और जल बाहर आते हैं, और ऊर्जा ATP के रूप में जमा होती है।', 'kn': 'ಪ್ರತಿಯೊಂದು ಜೀವಕೋಶವೂ ಉಸಿರಾಟದ ಮೂಲಕ ಆಹಾರದಿಂದ ಶಕ್ತಿಯನ್ನು ಬಿಡುಗಡೆ ಮಾಡುತ್ತದೆ. ಗ್ಲೂಕೋಸ್ ಮತ್ತು ಆಮ್ಲಜನಕ ಒಳಗೆ ಹೋಗುತ್ತವೆ; ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ ಮತ್ತು ನೀರು ಹೊರಬರುತ್ತವೆ, ಮತ್ತು ಶಕ್ತಿ ATP ರೂಪದಲ್ಲಿ ಸಂಗ್ರಹವಾಗುತ್ತದೆ.'}),
        highlight: ['mitochondria'],
        labels: ['membrane', 'nucleus', 'mitochondria', 'glucose', 'oxygen'],
      ),
      ProcessSceneStep(
        id: 'glycolysis',
        stage: 'cytosol',
        seconds: 14.0,
        title: LocalText({'en': 'Glycolysis', 'hi': 'ग्लाइकोलाइसिस', 'kn': 'ಗ್ಲೈಕೊಲಿಸಿಸ್'}),
        caption: LocalText({'en': 'In the cytoplasm, glucose (6 carbons) is split into two pyruvate molecules (3 carbons each). This needs no oxygen and gives a small gain of 2 ATP and 2 NADH.', 'hi': 'कोशिकाद्रव्य में ग्लूकोज़ (6 कार्बन) दो पाइरुवेट अणुओं (3-3 कार्बन) में टूट जाता है। इसमें ऑक्सीजन की ज़रूरत नहीं होती और 2 ATP व 2 NADH का छोटा लाभ मिलता है।', 'kn': 'ಕೋಶದ್ರವ್ಯದಲ್ಲಿ ಗ್ಲೂಕೋಸ್ (6 ಕಾರ್ಬನ್) ಎರಡು ಪೈರುವೇಟ್ ಅಣುಗಳಾಗಿ (ತಲಾ 3 ಕಾರ್ಬನ್) ವಿಭಜನೆಯಾಗುತ್ತದೆ. ಇದಕ್ಕೆ ಆಮ್ಲಜನಕ ಬೇಕಿಲ್ಲ; 2 ATP ಮತ್ತು 2 NADH ನ ಸಣ್ಣ ಲಾಭ ಸಿಗುತ್ತದೆ.'}),
        highlight: ['enzymes'],
        labels: ['glucose', 'enzymes', 'pyruvate', 'atp', 'nadh'],
      ),
      ProcessSceneStep(
        id: 'mitochondrion',
        stage: 'mito',
        seconds: 12.0,
        title: LocalText({'en': 'The mitochondrion', 'hi': 'माइटोकॉन्ड्रिया', 'kn': 'ಮೈಟೊಕಾಂಡ್ರಿಯ'}),
        caption: LocalText({'en': 'With oxygen, pyruvate goes on into a mitochondrion. Its smooth outer membrane encloses an inner membrane folded into cristae, around a fluid called the matrix.', 'hi': 'ऑक्सीजन होने पर पाइरुवेट माइटोकॉन्ड्रिया में जाता है। इसकी चिकनी बाहरी झिल्ली के अंदर एक भीतरी झिल्ली होती है जो क्रिस्टी नामक तहों में मुड़ी होती है; इसके बीच मैट्रिक्स नामक द्रव होता है।', 'kn': 'ಆಮ್ಲಜನಕವಿದ್ದಾಗ ಪೈರುವೇಟ್ ಮೈಟೊಕಾಂಡ್ರಿಯದೊಳಗೆ ಹೋಗುತ್ತದೆ. ಇದರ ನಯವಾದ ಹೊರಪೊರೆಯೊಳಗೆ ಕ್ರಿಸ್ಟೇ ಎಂಬ ಮಡಿಕೆಗಳಾಗಿ ಮಡಿಚಿದ ಒಳಪೊರೆಯಿದೆ; ಅದರ ನಡುವೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಎಂಬ ದ್ರವವಿದೆ.'}),
        highlight: ['cristae'],
        labels: ['outer_membrane', 'cristae', 'matrix', 'ims'],
      ),
      ProcessSceneStep(
        id: 'link',
        stage: 'mito',
        seconds: 11.0,
        title: LocalText({'en': 'Into the matrix', 'hi': 'मैट्रिक्स में', 'kn': 'ಮ್ಯಾಟ್ರಿಕ್ಸ್‌ನೊಳಗೆ'}),
        caption: LocalText({'en': 'In the matrix, each pyruvate loses one carbon as carbon dioxide and becomes acetyl-CoA, which feeds the Krebs cycle.', 'hi': 'मैट्रिक्स में हर पाइरुवेट एक कार्बन को कार्बन डाइऑक्साइड के रूप में खोकर एसिटाइल-CoA बन जाता है, जो क्रेब्स चक्र में जाता है।', 'kn': 'ಮ್ಯಾಟ್ರಿಕ್ಸ್‌ನಲ್ಲಿ ಪ್ರತಿಯೊಂದು ಪೈರುವೇಟ್ ಒಂದು ಕಾರ್ಬನ್ ಅನ್ನು ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ ಆಗಿ ಕಳೆದುಕೊಂಡು ಅಸಿಟೈಲ್-CoA ಆಗುತ್ತದೆ; ಅದು ಕ್ರೆಬ್ಸ್ ಚಕ್ರಕ್ಕೆ ಸೇರುತ್ತದೆ.'}),
        labels: ['pyruvate', 'acetyl_coa', 'co2', 'matrix'],
      ),
      ProcessSceneStep(
        id: 'krebs',
        stage: 'matrix',
        seconds: 15.0,
        title: LocalText({'en': 'The Krebs cycle', 'hi': 'क्रेब्स चक्र', 'kn': 'ಕ್ರೆಬ್ಸ್ ಚಕ್ರ'}),
        caption: LocalText({'en': 'Acetyl-CoA joins a four-carbon acid to make citric acid. Turn by turn, the cycle releases the carbons as CO₂ and loads high-energy electrons onto NADH and FADH₂, making a little ATP too.', 'hi': 'एसिटाइल-CoA एक चार-कार्बन अम्ल से जुड़कर साइट्रिक अम्ल बनाता है। हर चक्कर में यह चक्र कार्बनों को CO₂ के रूप में छोड़ता है और उच्च ऊर्जा वाले इलेक्ट्रॉनों को NADH और FADH₂ पर लादता है; थोड़ा ATP भी बनता है।', 'kn': 'ಅಸಿಟೈಲ್-CoA ಒಂದು ನಾಲ್ಕು-ಕಾರ್ಬನ್ ಆಮ್ಲದೊಂದಿಗೆ ಸೇರಿ ಸಿಟ್ರಿಕ್ ಆಮ್ಲವಾಗುತ್ತದೆ. ಪ್ರತಿ ಸುತ್ತಿನಲ್ಲಿ ಈ ಚಕ್ರ ಕಾರ್ಬನ್‌ಗಳನ್ನು CO₂ ಆಗಿ ಬಿಡುತ್ತದೆ ಮತ್ತು ಹೆಚ್ಚಿನ ಶಕ್ತಿಯ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು NADH ಮತ್ತು FADH₂ ಮೇಲೆ ಹೇರುತ್ತದೆ; ಸ್ವಲ್ಪ ATP ಕೂಡ ತಯಾರಾಗುತ್ತದೆ.'}),
        labels: ['acetyl_coa', 'citrate', 'co2', 'nadh', 'atp'],
      ),
      ProcessSceneStep(
        id: 'chain',
        stage: 'crista',
        seconds: 15.0,
        title: LocalText({'en': 'The electron transport chain', 'hi': 'इलेक्ट्रॉन परिवहन शृंखला', 'kn': 'ಇಲೆಕ್ಟ್ರಾನ್ ಸಾಗಣೆ ಸರಪಳಿ'}),
        caption: LocalText({'en': 'NADH and FADH₂ hand their electrons to a chain of proteins in the inner membrane. As the electrons pass along, their energy pumps H⁺ ions out into the space between the membranes.', 'hi': 'NADH और FADH₂ अपने इलेक्ट्रॉन भीतरी झिल्ली में प्रोटीनों की एक शृंखला को देते हैं। इलेक्ट्रॉनों के आगे बढ़ने पर उनकी ऊर्जा H⁺ आयनों को दोनों झिल्लियों के बीच के स्थान में पंप करती है।', 'kn': 'NADH ಮತ್ತು FADH₂ ತಮ್ಮ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಒಳಪೊರೆಯಲ್ಲಿರುವ ಪ್ರೋಟೀನ್‌ಗಳ ಸರಪಳಿಗೆ ನೀಡುತ್ತವೆ. ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು ಮುಂದೆ ಸಾಗುವಾಗ ಅವುಗಳ ಶಕ್ತಿ H⁺ ಅಯಾನುಗಳನ್ನು ಎರಡು ಪೊರೆಗಳ ನಡುವಿನ ಜಾಗಕ್ಕೆ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'}),
        highlight: ['complex1', 'complex3', 'complex4'],
        labels: ['complex1', 'complex2', 'complex3', 'complex4', 'nadh', 'electron'],
      ),
      ProcessSceneStep(
        id: 'oxygen',
        stage: 'crista',
        seconds: 12.0,
        title: LocalText({'en': 'Oxygen, the last acceptor', 'hi': 'ऑक्सीजन, अंतिम ग्राही', 'kn': 'ಆಮ್ಲಜನಕ, ಕೊನೆಯ ಸ್ವೀಕಾರಕ'}),
        caption: LocalText({'en': 'At the end of the chain, oxygen accepts the electrons and joins with H⁺ to form water. This is why we need to breathe oxygen.', 'hi': 'शृंखला के अंत में ऑक्सीजन इलेक्ट्रॉनों को ग्रहण करती है और H⁺ से मिलकर जल बनाती है। इसीलिए हमें साँस से ऑक्सीजन लेनी पड़ती है।', 'kn': 'ಸರಪಳಿಯ ಕೊನೆಯಲ್ಲಿ ಆಮ್ಲಜನಕ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಸ್ವೀಕರಿಸಿ H⁺ ನೊಂದಿಗೆ ಸೇರಿ ನೀರಾಗುತ್ತದೆ. ಅದಕ್ಕಾಗಿಯೇ ನಾವು ಆಮ್ಲಜನಕವನ್ನು ಉಸಿರಾಡಬೇಕು.'}),
        highlight: ['complex4'],
        labels: ['complex4', 'oxygen', 'water', 'electron'],
      ),
      ProcessSceneStep(
        id: 'atp',
        stage: 'crista',
        seconds: 13.0,
        title: LocalText({'en': 'Most ATP is made here', 'hi': 'अधिकांश ATP यहीं बनता है', 'kn': 'ಹೆಚ್ಚಿನ ATP ಇಲ್ಲೇ ತಯಾರಾಗುತ್ತದೆ'}),
        caption: LocalText({'en': 'H⁺ ions rush back into the matrix through ATP synthase, turning it like a turbine. About 34 of the 38 ATP from one glucose are made this way.', 'hi': 'H⁺ आयन ATP सिंथेज़ से होकर तेज़ी से मैट्रिक्स में लौटते हैं और उसे टरबाइन की तरह घुमाते हैं। एक ग्लूकोज़ से बनने वाले 38 ATP में से लगभग 34 इसी तरह बनते हैं।', 'kn': 'H⁺ ಅಯಾನುಗಳು ATP ಸಿಂಥೇಸ್ ಮೂಲಕ ಮ್ಯಾಟ್ರಿಕ್ಸ್‌ಗೆ ವೇಗವಾಗಿ ಮರಳಿ ಅದನ್ನು ಟರ್ಬೈನಿನಂತೆ ತಿರುಗಿಸುತ್ತವೆ. ಒಂದು ಗ್ಲೂಕೋಸ್‌ನಿಂದ ಸಿಗುವ 38 ATP ಗಳಲ್ಲಿ ಸುಮಾರು 34 ಹೀಗೆಯೇ ತಯಾರಾಗುತ್ತವೆ.'}),
        highlight: ['atp_synthase'],
        labels: ['atp_synthase', 'hion', 'atp'],
      ),
      ProcessSceneStep(
        id: 'anaerobic',
        stage: 'cytosol',
        seconds: 14.0,
        title: LocalText({'en': 'Without oxygen', 'hi': 'ऑक्सीजन के बिना', 'kn': 'ಆಮ್ಲಜನಕವಿಲ್ಲದೆ'}),
        caption: LocalText({'en': 'When oxygen runs short, as in a hard-working muscle, pyruvate is turned into lactic acid instead, which causes cramps. Yeast makes ethanol and carbon dioxide. Far less ATP is made.', 'hi': 'जब ऑक्सीजन कम पड़ जाती है, जैसे ज़ोर से काम करती पेशी में, तब पाइरुवेट लैक्टिक अम्ल में बदल जाता है, जिससे ऐंठन होती है। यीस्ट एथेनॉल और कार्बन डाइऑक्साइड बनाता है। इसमें ATP बहुत कम बनता है।', 'kn': 'ಹೆಚ್ಚು ಕೆಲಸ ಮಾಡುವ ಸ್ನಾಯುವಿನಂತೆ ಆಮ್ಲಜನಕ ಕಡಿಮೆಯಾದಾಗ, ಪೈರುವೇಟ್ ಲ್ಯಾಕ್ಟಿಕ್ ಆಮ್ಲವಾಗಿ ಬದಲಾಗುತ್ತದೆ; ಇದರಿಂದ ಸೆಳೆತ ಉಂಟಾಗುತ್ತದೆ. ಯೀಸ್ಟ್ ಎಥೆನಾಲ್ ಮತ್ತು ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್ ತಯಾರಿಸುತ್ತದೆ. ಇದರಲ್ಲಿ ATP ತುಂಬಾ ಕಡಿಮೆ ಸಿಗುತ್ತದೆ.'}),
        labels: ['pyruvate', 'lactate'],
      ),
      ProcessSceneStep(
        id: 'summary',
        stage: 'cell',
        seconds: 12.0,
        title: LocalText({'en': 'In short', 'hi': 'संक्षेप में', 'kn': 'ಸಂಕ್ಷಿಪ್ತವಾಗಿ'}),
        caption: LocalText({'en': 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy (ATP). Respiration is the reverse of photosynthesis: it releases the energy that plants stored in sugar.', 'hi': 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ऊर्जा (ATP)। श्वसन प्रकाश संश्लेषण का उलटा है: यह उस ऊर्जा को मुक्त करता है जो पौधों ने शर्करा में जमा की थी।', 'kn': 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ಶಕ್ತಿ (ATP). ಉಸಿರಾಟವು ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆಯ ವಿರುದ್ಧ ಕ್ರಿಯೆ: ಸಸ್ಯಗಳು ಸಕ್ಕರೆಯಲ್ಲಿ ಸಂಗ್ರಹಿಸಿದ ಶಕ್ತಿಯನ್ನು ಇದು ಬಿಡುಗಡೆ ಮಾಡುತ್ತದೆ.'}),
        highlight: ['mitochondria'],
        labels: ['glucose', 'oxygen', 'co2', 'water', 'mitochondria'],
      ),
    ],
  ),
  ProcessScene(
    id: 'heart',
    subject: 'Biology',
    classes: [7, 10, 11],
    keywords: ['heart', 'circulation', 'double circulation', 'blood', 'atrium', 'ventricle', 'valves', 'aorta', 'pulmonary', 'heartbeat', 'transportation', 'life processes', 'blood vessels'],
    title: LocalText({'en': 'The human heart and circulation', 'hi': 'मानव हृदय और परिसंचरण', 'kn': 'ಮಾನವ ಹೃದಯ ಮತ್ತು ರಕ್ತಪರಿಚಲನೆ'}),
    summary: LocalText({'en': 'The heart’s four chambers and valves, how blood flows through each side as the heart beats, and the double circulation through the lungs and the body.', 'hi': 'हृदय के चार कक्ष और कपाट, धड़कते हृदय के हर भाग से रक्त कैसे बहता है, और फेफड़ों तथा शरीर से होकर दोहरा परिसंचरण।', 'kn': 'ಹೃದಯದ ನಾಲ್ಕು ಕೋಣೆಗಳು ಮತ್ತು ಕವಾಟಗಳು, ಹೃದಯ ಬಡಿಯುವಾಗ ಪ್ರತಿ ಭಾಗದ ಮೂಲಕ ರಕ್ತ ಹೇಗೆ ಹರಿಯುತ್ತದೆ, ಮತ್ತು ಶ್ವಾಸಕೋಶ ಹಾಗೂ ದೇಹದ ಮೂಲಕ ದ್ವಿ ರಕ್ತಪರಿಚಲನೆ.'}),
    groups: [
      ViewerGroup('chambers', LocalText({'en': 'Chambers', 'hi': 'कक्ष', 'kn': 'ಕೋಣೆಗಳು'})),
      ViewerGroup('valves', LocalText({'en': 'Valves', 'hi': 'कपाट (वाल्व)', 'kn': 'ಕವಾಟಗಳು'})),
      ViewerGroup('vessels', LocalText({'en': 'Blood vessels', 'hi': 'रक्त वाहिकाएँ', 'kn': 'ರಕ್ತನಾಳಗಳು'})),
      ViewerGroup('supply', LocalText({'en': 'The heart’s own blood supply', 'hi': 'हृदय की अपनी रक्त आपूर्ति', 'kn': 'ಹೃದಯಕ್ಕೇ ರಕ್ತ ಪೂರೈಕೆ'})),
      ViewerGroup('blood', LocalText({'en': 'Blood', 'hi': 'रक्त', 'kn': 'ರಕ್ತ'})),
      ViewerGroup('body', LocalText({'en': 'Lungs and body', 'hi': 'फेफड़े और शरीर', 'kn': 'ಶ್ವಾಸಕೋಶಗಳು ಮತ್ತು ದೇಹ'})),
    ],
    parts: [
      ViewerPart(id: 'right_atrium', group: 'chambers', color: '#a3404a', name: LocalText({'en': 'Right atrium', 'hi': 'दायाँ अलिंद', 'kn': 'ಬಲ ಹೃತ್ಕರ್ಣ'}), info: LocalText({'en': 'Receives blood low in oxygen from the whole body through the venae cavae.', 'hi': 'पूरे शरीर से कम ऑक्सीजन वाला रक्त महाशिराओं द्वारा प्राप्त करता है।', 'kn': 'ಇಡೀ ದೇಹದಿಂದ ಕಡಿಮೆ ಆಮ್ಲಜನಕವಿರುವ ರಕ್ತವನ್ನು ಮಹಾಭಿಧಮನಿಗಳ ಮೂಲಕ ಪಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'left_atrium', group: 'chambers', color: '#a3404a', name: LocalText({'en': 'Left atrium', 'hi': 'बायाँ अलिंद', 'kn': 'ಎಡ ಹೃತ್ಕರ್ಣ'}), info: LocalText({'en': 'Receives blood rich in oxygen from the lungs through the pulmonary veins.', 'hi': 'फेफड़ों से ऑक्सीजन-युक्त रक्त फुप्फुसीय शिराओं द्वारा प्राप्त करता है।', 'kn': 'ಶ್ವಾಸಕೋಶಗಳಿಂದ ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತವನ್ನು ಶ್ವಾಸಕೋಶೀಯ ಅಭಿಧಮನಿಗಳ ಮೂಲಕ ಪಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'right_ventricle', group: 'chambers', color: '#8c2430', name: LocalText({'en': 'Right ventricle', 'hi': 'दायाँ निलय', 'kn': 'ಬಲ ಹೃತ್ಕುಕ್ಷಿ'}), info: LocalText({'en': 'Pumps blood to the lungs through the pulmonary artery. Its wall is thinner than the left ventricle’s.', 'hi': 'रक्त को फुप्फुसीय धमनी द्वारा फेफड़ों में पंप करता है। इसकी दीवार बाएँ निलय से पतली होती है।', 'kn': 'ಶ್ವಾಸಕೋಶೀಯ ಅಪಧಮನಿಯ ಮೂಲಕ ರಕ್ತವನ್ನು ಶ್ವಾಸಕೋಶಗಳಿಗೆ ಪಂಪ್ ಮಾಡುತ್ತದೆ. ಇದರ ಗೋಡೆ ಎಡ ಹೃತ್ಕುಕ್ಷಿಗಿಂತ ತೆಳುವಾಗಿದೆ.'})),
      ViewerPart(id: 'left_ventricle', group: 'chambers', color: '#8c2430', name: LocalText({'en': 'Left ventricle', 'hi': 'बायाँ निलय', 'kn': 'ಎಡ ಹೃತ್ಕುಕ್ಷಿ'}), info: LocalText({'en': 'The strongest chamber: its thick wall pumps blood through the aorta to the whole body.', 'hi': 'सबसे शक्तिशाली कक्ष: इसकी मोटी दीवार महाधमनी द्वारा रक्त को पूरे शरीर में पंप करती है।', 'kn': 'ಅತ್ಯಂತ ಬಲಿಷ್ಠ ಕೋಣೆ: ಇದರ ದಪ್ಪ ಗೋಡೆ ಮಹಾಪಧಮನಿಯ ಮೂಲಕ ರಕ್ತವನ್ನು ಇಡೀ ದೇಹಕ್ಕೆ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'})),
      ViewerPart(id: 'septum', group: 'chambers', color: '#76202b', name: LocalText({'en': 'Septum', 'hi': 'पट (सेप्टम)', 'kn': 'ವಿಭಾಜಕ ಭಿತ್ತಿ (ಸೆಪ್ಟಮ್)'}), info: LocalText({'en': 'The wall between the two ventricles. It keeps blood rich in oxygen apart from blood low in oxygen.', 'hi': 'दोनों निलयों के बीच की दीवार। यह ऑक्सीजन-युक्त और ऑक्सीजन-रहित रक्त को मिलने नहीं देती।', 'kn': 'ಎರಡು ಹೃತ್ಕುಕ್ಷಿಗಳ ನಡುವಿನ ಗೋಡೆ. ಇದು ಆಮ್ಲಜನಕಯುಕ್ತ ಮತ್ತು ಆಮ್ಲಜನಕರಹಿತ ರಕ್ತ ಬೆರೆಯದಂತೆ ತಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'tricuspid_valve', group: 'valves', color: '#eadcbc', name: LocalText({'en': 'Tricuspid valve', 'hi': 'त्रिवलनी कपाट', 'kn': 'ತ್ರಿದಳ ಕವಾಟ'}), info: LocalText({'en': 'Three flaps between the right atrium and right ventricle. It stops blood flowing back.', 'hi': 'दाएँ अलिंद और दाएँ निलय के बीच तीन पल्लों वाला कपाट। यह रक्त को वापस बहने से रोकता है।', 'kn': 'ಬಲ ಹೃತ್ಕರ್ಣ ಮತ್ತು ಬಲ ಹೃತ್ಕುಕ್ಷಿಯ ನಡುವೆ ಮೂರು ದಳಗಳ ಕವಾಟ. ರಕ್ತ ಹಿಂದಕ್ಕೆ ಹರಿಯದಂತೆ ತಡೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'mitral_valve', group: 'valves', color: '#eadcbc', name: LocalText({'en': 'Bicuspid (mitral) valve', 'hi': 'द्विवलनी (माइट्रल) कपाट', 'kn': 'ದ್ವಿದಳ (ಮಿಟ್ರಲ್) ಕವಾಟ'}), info: LocalText({'en': 'Two flaps between the left atrium and left ventricle.', 'hi': 'बाएँ अलिंद और बाएँ निलय के बीच दो पल्लों वाला कपाट।', 'kn': 'ಎಡ ಹೃತ್ಕರ್ಣ ಮತ್ತು ಎಡ ಹೃತ್ಕುಕ್ಷಿಯ ನಡುವೆ ಎರಡು ದಳಗಳ ಕವಾಟ.'})),
      ViewerPart(id: 'pulmonary_valve', group: 'valves', color: '#eadcbc', name: LocalText({'en': 'Pulmonary valve', 'hi': 'फुप्फुसीय कपाट', 'kn': 'ಶ್ವಾಸಕೋಶೀಯ ಕವಾಟ'}), info: LocalText({'en': 'At the exit of the right ventricle, into the pulmonary artery.', 'hi': 'दाएँ निलय के निकास पर, फुप्फुसीय धमनी में खुलता है।', 'kn': 'ಬಲ ಹೃತ್ಕುಕ್ಷಿಯ ನಿರ್ಗಮನದಲ್ಲಿ, ಶ್ವಾಸಕೋಶೀಯ ಅಪಧಮನಿಗೆ ತೆರೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'aortic_valve', group: 'valves', color: '#eadcbc', name: LocalText({'en': 'Aortic valve', 'hi': 'महाधमनी कपाट', 'kn': 'ಮಹಾಪಧಮನಿ ಕವಾಟ'}), info: LocalText({'en': 'At the exit of the left ventricle, into the aorta.', 'hi': 'बाएँ निलय के निकास पर, महाधमनी में खुलता है।', 'kn': 'ಎಡ ಹೃತ್ಕುಕ್ಷಿಯ ನಿರ್ಗಮನದಲ್ಲಿ, ಮಹಾಪಧಮನಿಗೆ ತೆರೆಯುತ್ತದೆ.'})),
      ViewerPart(id: 'aorta', group: 'vessels', color: '#c42b2b', name: LocalText({'en': 'Aorta', 'hi': 'महाधमनी', 'kn': 'ಮಹಾಪಧಮನಿ'}), info: LocalText({'en': 'The largest artery. It carries blood rich in oxygen from the left ventricle to the body.', 'hi': 'सबसे बड़ी धमनी। यह बाएँ निलय से ऑक्सीजन-युक्त रक्त शरीर तक ले जाती है।', 'kn': 'ಅತಿ ದೊಡ್ಡ ಅಪಧಮನಿ. ಎಡ ಹೃತ್ಕುಕ್ಷಿಯಿಂದ ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತವನ್ನು ದೇಹಕ್ಕೆ ಒಯ್ಯುತ್ತದೆ.'})),
      ViewerPart(id: 'pulmonary_trunk', group: 'vessels', color: '#2f57bf', name: LocalText({'en': 'Pulmonary artery', 'hi': 'फुप्फुसीय धमनी', 'kn': 'ಶ್ವಾಸಕೋಶೀಯ ಅಪಧಮನಿ'}), info: LocalText({'en': 'Carries blood low in oxygen from the right ventricle towards the lungs. The only artery with blood low in oxygen.', 'hi': 'दाएँ निलय से कम ऑक्सीजन वाला रक्त फेफड़ों की ओर ले जाती है। यही एकमात्र धमनी है जिसमें ऑक्सीजन-रहित रक्त बहता है।', 'kn': 'ಬಲ ಹೃತ್ಕುಕ್ಷಿಯಿಂದ ಕಡಿಮೆ ಆಮ್ಲಜನಕದ ರಕ್ತವನ್ನು ಶ್ವಾಸಕೋಶಗಳತ್ತ ಒಯ್ಯುತ್ತದೆ. ಆಮ್ಲಜನಕರಹಿತ ರಕ್ತ ಹರಿಯುವ ಏಕೈಕ ಅಪಧಮನಿ.'})),
      ViewerPart(id: 'pulmonary_veins', group: 'vessels', color: '#c42b2b', name: LocalText({'en': 'Pulmonary veins', 'hi': 'फुप्फुसीय शिराएँ', 'kn': 'ಶ್ವಾಸಕೋಶೀಯ ಅಭಿಧಮನಿಗಳು'}), info: LocalText({'en': 'Bring blood rich in oxygen from the lungs to the left atrium. The only veins with blood rich in oxygen.', 'hi': 'फेफड़ों से ऑक्सीजन-युक्त रक्त बाएँ अलिंद में लाती हैं। यही एकमात्र शिराएँ हैं जिनमें ऑक्सीजन-युक्त रक्त बहता है।', 'kn': 'ಶ್ವಾಸಕೋಶಗಳಿಂದ ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತವನ್ನು ಎಡ ಹೃತ್ಕರ್ಣಕ್ಕೆ ತರುತ್ತವೆ. ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತ ಹರಿಯುವ ಏಕೈಕ ಅಭಿಧಮನಿಗಳು.'})),
      ViewerPart(id: 'vena_cava', group: 'vessels', color: '#2f57bf', name: LocalText({'en': 'Venae cavae', 'hi': 'महाशिराएँ', 'kn': 'ಮಹಾಭಿಧಮನಿಗಳು'}), info: LocalText({'en': 'The two great veins that bring blood back from the body to the right atrium.', 'hi': 'वे दो बड़ी शिराएँ जो शरीर से रक्त दाएँ अलिंद में वापस लाती हैं।', 'kn': 'ದೇಹದಿಂದ ರಕ್ತವನ್ನು ಬಲ ಹೃತ್ಕರ್ಣಕ್ಕೆ ಮರಳಿ ತರುವ ಎರಡು ಮಹಾ ಅಭಿಧಮನಿಗಳು.'})),
      ViewerPart(id: 'coronary_arteries', group: 'supply', color: '#e0372f', name: LocalText({'en': 'Coronary arteries', 'hi': 'कोरोनरी धमनियाँ', 'kn': 'ಕೊರೊನರಿ ಅಪಧಮನಿಗಳು'}), info: LocalText({'en': 'They feed the heart muscle itself. A blocked coronary artery causes a heart attack.', 'hi': 'ये स्वयं हृदय की पेशी को रक्त देती हैं। इनमें रुकावट से दिल का दौरा पड़ता है।', 'kn': 'ಇವು ಹೃದಯದ ಸ್ನಾಯುವಿಗೇ ರಕ್ತ ನೀಡುತ್ತವೆ. ಇವುಗಳಲ್ಲಿ ಅಡಚಣೆಯಾದರೆ ಹೃದಯಾಘಾತವಾಗುತ್ತದೆ.'})),
      ViewerPart(id: 'deoxy_blood', group: 'blood', color: '#5566b0', name: LocalText({'en': 'Blood low in oxygen', 'hi': 'कम ऑक्सीजन वाला रक्त', 'kn': 'ಕಡಿಮೆ ಆಮ್ಲಜನಕದ ರಕ್ತ'}), info: LocalText({'en': 'Back from the body, in the right side of the heart.', 'hi': 'शरीर से लौटा, हृदय के दाएँ भाग में।', 'kn': 'ದೇಹದಿಂದ ಹಿಂದಿರುಗಿದ್ದು, ಹೃದಯದ ಬಲಭಾಗದಲ್ಲಿ.'})),
      ViewerPart(id: 'oxy_blood', group: 'blood', color: '#c8473b', name: LocalText({'en': 'Blood rich in oxygen', 'hi': 'ऑक्सीजन-युक्त रक्त', 'kn': 'ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತ'}), info: LocalText({'en': 'Back from the lungs, in the left side of the heart.', 'hi': 'फेफड़ों से लौटा, हृदय के बाएँ भाग में।', 'kn': 'ಶ್ವಾಸಕೋಶಗಳಿಂದ ಹಿಂದಿರುಗಿದ್ದು, ಹೃದಯದ ಎಡಭಾಗದಲ್ಲಿ.'})),
      ViewerPart(id: 'lungs', group: 'body', color: '#d99a9a', name: LocalText({'en': 'Lungs', 'hi': 'फेफड़े', 'kn': 'ಶ್ವಾಸಕೋಶಗಳು'}), info: LocalText({'en': 'Blood picks up oxygen and gives up carbon dioxide here.', 'hi': 'यहाँ रक्त ऑक्सीजन लेता है और कार्बन डाइऑक्साइड छोड़ता है।', 'kn': 'ಇಲ್ಲಿ ರಕ್ತ ಆಮ್ಲಜನಕವನ್ನು ಪಡೆದು ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡನ್ನು ಬಿಡುತ್ತದೆ.'})),
      ViewerPart(id: 'body', group: 'body', color: '#b0706a', name: LocalText({'en': 'Body tissues', 'hi': 'शरीर के ऊतक', 'kn': 'ದೇಹದ ಅಂಗಾಂಶಗಳು'}), info: LocalText({'en': 'Capillaries give oxygen and food to the cells and take away their wastes.', 'hi': 'केशिकाएँ कोशिकाओं को ऑक्सीजन और भोजन देती हैं और उनके अपशिष्ट ले जाती हैं।', 'kn': 'ಲೋಮನಾಳಗಳು ಕೋಶಗಳಿಗೆ ಆಮ್ಲಜನಕ ಮತ್ತು ಆಹಾರ ನೀಡಿ ತ್ಯಾಜ್ಯಗಳನ್ನು ಒಯ್ಯುತ್ತವೆ.'})),
      ViewerPart(id: 'pulmonary_circuit', group: 'body', color: '#8a7ab0', name: LocalText({'en': 'Pulmonary circulation', 'hi': 'फुप्फुसीय परिसंचरण', 'kn': 'ಶ್ವಾಸಕೋಶೀಯ ರಕ್ತಪರಿಚಲನೆ'}), info: LocalText({'en': 'Heart → lungs → heart.', 'hi': 'हृदय → फेफड़े → हृदय।', 'kn': 'ಹೃದಯ → ಶ್ವಾಸಕೋಶ → ಹೃದಯ.'})),
      ViewerPart(id: 'systemic_circuit', group: 'body', color: '#b07a6a', name: LocalText({'en': 'Systemic circulation', 'hi': 'दैहिक परिसंचरण', 'kn': 'ದೈಹಿಕ ರಕ್ತಪರಿಚಲನೆ'}), info: LocalText({'en': 'Heart → body → heart.', 'hi': 'हृदय → शरीर → हृदय।', 'kn': 'ಹೃದಯ → ದೇಹ → ಹೃದಯ.'})),
    ],
    steps: [
      ProcessSceneStep(
        id: 'outside',
        stage: 'heart',
        seconds: 13.0,
        title: LocalText({'en': 'A muscular pump', 'hi': 'एक पेशीय पंप', 'kn': 'ಸ್ನಾಯುವಿನ ಪಂಪ್'}),
        caption: LocalText({'en': 'The heart is a pump of muscle about the size of your fist. It beats about 72 times a minute, all your life. The coronary arteries on its surface feed the heart muscle itself.', 'hi': 'हृदय लगभग आपकी मुट्ठी के आकार का पेशी से बना पंप है। यह जीवन भर लगभग 72 बार प्रति मिनट धड़कता है। इसकी सतह पर कोरोनरी धमनियाँ स्वयं हृदय की पेशी को रक्त देती हैं।', 'kn': 'ಹೃದಯವು ಸುಮಾರು ನಿಮ್ಮ ಮುಷ್ಟಿಯ ಗಾತ್ರದ ಸ್ನಾಯುವಿನ ಪಂಪ್. ಇದು ಜೀವನವಿಡೀ ನಿಮಿಷಕ್ಕೆ ಸುಮಾರು 72 ಬಾರಿ ಬಡಿಯುತ್ತದೆ. ಇದರ ಮೇಲ್ಮೈಯ ಕೊರೊನರಿ ಅಪಧಮನಿಗಳು ಹೃದಯ ಸ್ನಾಯುವಿಗೇ ರಕ್ತ ನೀಡುತ್ತವೆ.'}),
        highlight: ['coronary_arteries'],
        labels: ['aorta', 'pulmonary_trunk', 'vena_cava', 'right_ventricle', 'left_ventricle', 'coronary_arteries'],
      ),
      ProcessSceneStep(
        id: 'chambers',
        stage: 'heart',
        seconds: 12.0,
        title: LocalText({'en': 'Four chambers', 'hi': 'चार कक्ष', 'kn': 'ನಾಲ್ಕು ಕೋಣೆಗಳು'}),
        caption: LocalText({'en': 'Cut open, the heart has four chambers: two atria above that receive blood, and two ventricles below that pump it out. The septum keeps the right and left sides apart.', 'hi': 'काटकर देखने पर हृदय में चार कक्ष दिखते हैं: ऊपर दो अलिंद जो रक्त प्राप्त करते हैं, और नीचे दो निलय जो उसे बाहर पंप करते हैं। पट दाएँ और बाएँ भागों को अलग रखता है।', 'kn': 'ಕತ್ತರಿಸಿ ನೋಡಿದರೆ ಹೃದಯದಲ್ಲಿ ನಾಲ್ಕು ಕೋಣೆಗಳಿವೆ: ಮೇಲೆ ರಕ್ತವನ್ನು ಪಡೆಯುವ ಎರಡು ಹೃತ್ಕರ್ಣಗಳು, ಕೆಳಗೆ ಅದನ್ನು ಹೊರಗೆ ಪಂಪ್ ಮಾಡುವ ಎರಡು ಹೃತ್ಕುಕ್ಷಿಗಳು. ವಿಭಾಜಕ ಭಿತ್ತಿ ಬಲ ಮತ್ತು ಎಡ ಭಾಗಗಳನ್ನು ಬೇರೆಯಾಗಿಡುತ್ತದೆ.'}),
        highlight: ['septum'],
        labels: ['right_atrium', 'left_atrium', 'right_ventricle', 'left_ventricle', 'septum'],
      ),
      ProcessSceneStep(
        id: 'right_side',
        stage: 'heart',
        seconds: 14.0,
        title: LocalText({'en': 'The right side: to the lungs', 'hi': 'दायाँ भाग: फेफड़ों की ओर', 'kn': 'ಬಲಭಾಗ: ಶ್ವಾಸಕೋಶಗಳತ್ತ'}),
        caption: LocalText({'en': 'Blood low in oxygen comes back from the body through the venae cavae into the right atrium. It passes the tricuspid valve into the right ventricle, which pumps it to the lungs.', 'hi': 'कम ऑक्सीजन वाला रक्त शरीर से महाशिराओं द्वारा दाएँ अलिंद में लौटता है। यह त्रिवलनी कपाट से होकर दाएँ निलय में जाता है, जो इसे फेफड़ों में पंप करता है।', 'kn': 'ಕಡಿಮೆ ಆಮ್ಲಜನಕದ ರಕ್ತ ದೇಹದಿಂದ ಮಹಾಭಿಧಮನಿಗಳ ಮೂಲಕ ಬಲ ಹೃತ್ಕರ್ಣಕ್ಕೆ ಮರಳುತ್ತದೆ. ಅದು ತ್ರಿದಳ ಕವಾಟದ ಮೂಲಕ ಬಲ ಹೃತ್ಕುಕ್ಷಿಗೆ ಹೋಗುತ್ತದೆ; ಅದು ರಕ್ತವನ್ನು ಶ್ವಾಸಕೋಶಗಳಿಗೆ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'}),
        highlight: ['right_atrium', 'right_ventricle'],
        labels: ['vena_cava', 'right_atrium', 'tricuspid_valve', 'right_ventricle', 'pulmonary_trunk', 'deoxy_blood'],
      ),
      ProcessSceneStep(
        id: 'left_side',
        stage: 'heart',
        seconds: 14.0,
        title: LocalText({'en': 'The left side: to the body', 'hi': 'बायाँ भाग: शरीर की ओर', 'kn': 'ಎಡಭಾಗ: ದೇಹದತ್ತ'}),
        caption: LocalText({'en': 'Blood rich in oxygen returns from the lungs through the pulmonary veins into the left atrium, then through the bicuspid valve into the left ventricle. Its thick wall pumps the blood into the aorta, to the whole body.', 'hi': 'ऑक्सीजन-युक्त रक्त फेफड़ों से फुप्फुसीय शिराओं द्वारा बाएँ अलिंद में लौटता है, फिर द्विवलनी कपाट से होकर बाएँ निलय में जाता है। इसकी मोटी दीवार रक्त को महाधमनी में, पूरे शरीर के लिए पंप करती है।', 'kn': 'ಆಮ್ಲಜನಕಯುಕ್ತ ರಕ್ತ ಶ್ವಾಸಕೋಶಗಳಿಂದ ಶ್ವಾಸಕೋಶೀಯ ಅಭಿಧಮನಿಗಳ ಮೂಲಕ ಎಡ ಹೃತ್ಕರ್ಣಕ್ಕೆ, ನಂತರ ದ್ವಿದಳ ಕವಾಟದ ಮೂಲಕ ಎಡ ಹೃತ್ಕುಕ್ಷಿಗೆ ಬರುತ್ತದೆ. ಅದರ ದಪ್ಪ ಗೋಡೆ ರಕ್ತವನ್ನು ಮಹಾಪಧಮನಿಗೆ, ಇಡೀ ದೇಹಕ್ಕಾಗಿ ಪಂಪ್ ಮಾಡುತ್ತದೆ.'}),
        highlight: ['left_atrium', 'left_ventricle'],
        labels: ['pulmonary_veins', 'left_atrium', 'mitral_valve', 'left_ventricle', 'aorta', 'oxy_blood'],
      ),
      ProcessSceneStep(
        id: 'beat',
        stage: 'heart',
        seconds: 15.0,
        title: LocalText({'en': 'One heartbeat, slowed down', 'hi': 'एक धड़कन, धीमी गति में', 'kn': 'ಒಂದು ಹೃದಯಬಡಿತ, ನಿಧಾನವಾಗಿ'}),
        caption: LocalText({'en': 'First the atria squeeze, filling the ventricles. Then the ventricles squeeze: the valves between them snap shut (“lub”), blood rushes out, and the valves at the exits close (“dub”). Valves let blood flow only one way.', 'hi': 'पहले अलिंद सिकुड़कर निलयों को भरते हैं। फिर निलय सिकुड़ते हैं: उनके बीच के कपाट झट से बंद होते हैं (“लब”), रक्त तेज़ी से बाहर निकलता है, और निकास के कपाट बंद होते हैं (“डब”)। कपाट रक्त को केवल एक दिशा में बहने देते हैं।', 'kn': 'ಮೊದಲು ಹೃತ್ಕರ್ಣಗಳು ಸಂಕುಚಿಸಿ ಹೃತ್ಕುಕ್ಷಿಗಳನ್ನು ತುಂಬಿಸುತ್ತವೆ. ನಂತರ ಹೃತ್ಕುಕ್ಷಿಗಳು ಸಂಕುಚಿಸುತ್ತವೆ: ಅವುಗಳ ನಡುವಿನ ಕವಾಟಗಳು ಪಟ್ಟನೆ ಮುಚ್ಚುತ್ತವೆ (“ಲಬ್”), ರಕ್ತ ವೇಗವಾಗಿ ಹೊರಹೋಗುತ್ತದೆ, ಮತ್ತು ನಿರ್ಗಮನದ ಕವಾಟಗಳು ಮುಚ್ಚುತ್ತವೆ (“ಡಬ್”). ಕವಾಟಗಳು ರಕ್ತವನ್ನು ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಹರಿಯಲು ಬಿಡುತ್ತವೆ.'}),
        highlight: ['tricuspid_valve', 'mitral_valve', 'aortic_valve', 'pulmonary_valve'],
        labels: ['tricuspid_valve', 'mitral_valve', 'aortic_valve', 'pulmonary_valve'],
      ),
      ProcessSceneStep(
        id: 'double',
        stage: 'circulation',
        seconds: 15.0,
        title: LocalText({'en': 'Double circulation', 'hi': 'दोहरा परिसंचरण', 'kn': 'ದ್ವಿ ರಕ್ತಪರಿಚಲನೆ'}),
        caption: LocalText({'en': 'Blood goes round two circuits. The right side sends it to the lungs to pick up oxygen and back (pulmonary circulation); the left side sends it round the body and back (systemic circulation).', 'hi': 'रक्त दो परिपथों में घूमता है। दायाँ भाग इसे ऑक्सीजन लेने के लिए फेफड़ों में भेजता है और वह लौट आता है (फुप्फुसीय परिसंचरण); बायाँ भाग इसे पूरे शरीर में भेजता है और वह लौट आता है (दैहिक परिसंचरण)।', 'kn': 'ರಕ್ತ ಎರಡು ಸುತ್ತುಗಳಲ್ಲಿ ಹರಿಯುತ್ತದೆ. ಬಲಭಾಗ ಅದನ್ನು ಆಮ್ಲಜನಕ ಪಡೆಯಲು ಶ್ವಾಸಕೋಶಗಳಿಗೆ ಕಳುಹಿಸಿ ಮರಳಿ ಪಡೆಯುತ್ತದೆ (ಶ್ವಾಸಕೋಶೀಯ ರಕ್ತಪರಿಚಲನೆ); ಎಡಭಾಗ ಅದನ್ನು ಇಡೀ ದೇಹಕ್ಕೆ ಕಳುಹಿಸಿ ಮರಳಿ ಪಡೆಯುತ್ತದೆ (ದೈಹಿಕ ರಕ್ತಪರಿಚಲನೆ).'}),
        highlight: ['lungs', 'body'],
        labels: ['lungs', 'body', 'pulmonary_circuit', 'systemic_circuit'],
      ),
      ProcessSceneStep(
        id: 'summary',
        stage: 'circulation',
        seconds: 13.0,
        title: LocalText({'en': 'Why two circuits?', 'hi': 'दो परिपथ क्यों?', 'kn': 'ಎರಡು ಸುತ್ತುಗಳೇಕೆ?'}),
        caption: LocalText({'en': 'In each round, blood passes through the heart twice. Keeping blood rich in oxygen apart from blood low in oxygen gives the body a steady, rich supply of oxygen, which warm-blooded animals like us need.', 'hi': 'हर चक्कर में रक्त दो बार हृदय से होकर गुज़रता है। ऑक्सीजन-युक्त और ऑक्सीजन-रहित रक्त को अलग रखने से शरीर को ऑक्सीजन की भरपूर और लगातार आपूर्ति मिलती है, जिसकी हम जैसे नियततापी जंतुओं को ज़रूरत होती है।', 'kn': 'ಪ್ರತಿ ಸುತ್ತಿನಲ್ಲಿ ರಕ್ತ ಎರಡು ಬಾರಿ ಹೃದಯದ ಮೂಲಕ ಹಾದುಹೋಗುತ್ತದೆ. ಆಮ್ಲಜನಕಯುಕ್ತ ಮತ್ತು ಆಮ್ಲಜನಕರಹಿತ ರಕ್ತವನ್ನು ಬೇರೆಯಾಗಿಡುವುದರಿಂದ ದೇಹಕ್ಕೆ ಆಮ್ಲಜನಕದ ಸಮೃದ್ಧ ಮತ್ತು ನಿರಂತರ ಪೂರೈಕೆ ಸಿಗುತ್ತದೆ; ನಮ್ಮಂತಹ ಬಿಸಿರಕ್ತದ ಪ್ರಾಣಿಗಳಿಗೆ ಇದು ಬೇಕು.'}),
        labels: ['oxy_blood', 'deoxy_blood', 'pulmonary_circuit', 'systemic_circuit'],
      ),
    ],
  ),
];
