import 'package:flutter/widgets.dart';

/// Words of the pen configuration screen in English, Hindi and Kannada.
class PenConfigStrings {
  const PenConfigStrings(this.lang);

  final String lang;

  static PenConfigStrings of(BuildContext context) => PenConfigStrings(Localizations.maybeLocaleOf(context)?.languageCode ?? 'en');

  String call(String key) => (all[lang] ?? all['en']!)[key] ?? all['en']![key] ?? key;

  static const all = <String, Map<String, String>>{
    'en': {
      'title': 'Pen configuration',
      'touch': 'Touch size',
      'stylus': 'Active stylus',
      'dual': 'Two pens',
      'calibrate': 'Calibration',
      'test': 'Test area',
      'touchHint': 'The size of a touch tells a pen tip, a finger and a palm apart. A palm erases; a thin tip writes as a pen.',
      'autoLearn': 'Learn this screen automatically',
      'autoLearnHint': 'Uses the usual finger size of this screen to spot palms.',
      'penMax': 'Largest pen-tip size',
      'palmMin': 'Smallest palm size',
      'off': 'off',
      'auto': 'auto',
      'learn': 'Learn from your touches',
      'learnStart': 'Start',
      'learnPen': 'Touch the pad several times with the pen tip.',
      'learnFinger': 'Touch the pad several times with one finger.',
      'learnPalm': 'Rest your palm on the pad a few times.',
      'samples': 'Touches',
      'next': 'Next',
      'finish': 'Finish',
      'pressure': 'Pressure',
      'pressureHint': 'Lines get thicker the harder you press.',
      'eraserEnd': 'Eraser end',
      'eraserEndHint': 'The back of the pen erases (or does what Two Side pen sets).',
      'button1': 'First barrel button',
      'button2': 'Second barrel button',
      'act.none': 'Nothing',
      'act.erase': 'Erase',
      'act.highlight': 'Highlight',
      'act.select': 'Select',
      'act.undo': 'Undo',
      'dualOn': 'Two pens, two colours',
      'dualHint': 'Each pen writes in its own colour so two writers can share the board.',
      'pen1': 'First pen colour',
      'pen2': 'Second pen colour',
      'tipSplit': 'Tip size that splits the pens',
      'byOrder': 'by who touches first',
      'calibrateHint': 'Touch the filled target',
      'calibrated': 'Calibrated, offset',
      'reset': 'Reset',
      'testHint': 'Write here with the pen, a finger or a palm.',
      'clear': 'Clear',
      'class.pen': 'Pen',
      'class.finger': 'Finger',
      'class.palm': 'Palm',
      'eraserEndName': '(eraser end)',
      'size': 'size',
      'pressureName': 'pressure',
      'tilt': 'tilt',
      'buttons': 'buttons',
      'penConfig': 'Pen configuration',
    },
    'hi': {
      'title': 'पेन कॉन्फ़िगरेशन',
      'touch': 'स्पर्श आकार',
      'stylus': 'सक्रिय स्टाइलस',
      'dual': 'दो पेन',
      'calibrate': 'अंशांकन',
      'test': 'परीक्षण क्षेत्र',
      'touchHint': 'स्पर्श के आकार से पेन की नोक, उँगली और हथेली की पहचान होती है। हथेली मिटाती है; पतली नोक पेन की तरह लिखती है।',
      'autoLearn': 'इस स्क्रीन को अपने आप सीखें',
      'autoLearnHint': 'हथेली पहचानने के लिए इस स्क्रीन पर उँगली का सामान्य आकार इस्तेमाल होता है।',
      'penMax': 'पेन की नोक का अधिकतम आकार',
      'palmMin': 'हथेली का न्यूनतम आकार',
      'off': 'बंद',
      'auto': 'स्वचालित',
      'learn': 'अपने स्पर्श से सीखें',
      'learnStart': 'शुरू करें',
      'learnPen': 'पेन की नोक से पैड को कई बार छुएँ।',
      'learnFinger': 'एक उँगली से पैड को कई बार छुएँ।',
      'learnPalm': 'हथेली को पैड पर कुछ बार रखें।',
      'samples': 'स्पर्श',
      'next': 'आगे',
      'finish': 'पूरा करें',
      'pressure': 'दबाव',
      'pressureHint': 'जितना ज़्यादा दबाएँगे, रेखा उतनी मोटी होगी।',
      'eraserEnd': 'मिटाने वाला सिरा',
      'eraserEndHint': 'पेन का पिछला सिरा मिटाता है (या दो-तरफ़ा पेन की सेटिंग के अनुसार काम करता है)।',
      'button1': 'पहला बटन',
      'button2': 'दूसरा बटन',
      'act.none': 'कुछ नहीं',
      'act.erase': 'मिटाएँ',
      'act.highlight': 'हाइलाइट',
      'act.select': 'चुनें',
      'act.undo': 'पूर्ववत',
      'dualOn': 'दो पेन, दो रंग',
      'dualHint': 'हर पेन अपने रंग में लिखता है ताकि दो लोग एक साथ लिख सकें।',
      'pen1': 'पहले पेन का रंग',
      'pen2': 'दूसरे पेन का रंग',
      'tipSplit': 'पेन अलग करने वाला नोक का आकार',
      'byOrder': 'जो पहले छुए',
      'calibrateHint': 'भरे हुए निशान को छुएँ',
      'calibrated': 'अंशांकित, अंतर',
      'reset': 'रीसेट',
      'testHint': 'यहाँ पेन, उँगली या हथेली से लिखें।',
      'clear': 'साफ़ करें',
      'class.pen': 'पेन',
      'class.finger': 'उँगली',
      'class.palm': 'हथेली',
      'eraserEndName': '(मिटाने वाला सिरा)',
      'size': 'आकार',
      'pressureName': 'दबाव',
      'tilt': 'झुकाव',
      'buttons': 'बटन',
      'penConfig': 'पेन कॉन्फ़िगरेशन',
    },
    'kn': {
      'title': 'ಪೆನ್ ಸಂರಚನೆ',
      'touch': 'ಸ್ಪರ್ಶದ ಗಾತ್ರ',
      'stylus': 'ಸಕ್ರಿಯ ಸ್ಟೈಲಸ್',
      'dual': 'ಎರಡು ಪೆನ್',
      'calibrate': 'ಮಾಪನಾಂಕ',
      'test': 'ಪರೀಕ್ಷಾ ಪ್ರದೇಶ',
      'touchHint': 'ಸ್ಪರ್ಶದ ಗಾತ್ರದಿಂದ ಪೆನ್ ತುದಿ, ಬೆರಳು ಮತ್ತು ಅಂಗೈಯನ್ನು ಗುರುತಿಸಲಾಗುತ್ತದೆ. ಅಂಗೈ ಅಳಿಸುತ್ತದೆ; ತೆಳು ತುದಿ ಪೆನ್‌ನಂತೆ ಬರೆಯುತ್ತದೆ.',
      'autoLearn': 'ಈ ಪರದೆಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕಲಿಯಿರಿ',
      'autoLearnHint': 'ಅಂಗೈ ಗುರುತಿಸಲು ಈ ಪರದೆಯ ಸಾಮಾನ್ಯ ಬೆರಳಿನ ಗಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ.',
      'penMax': 'ಪೆನ್ ತುದಿಯ ಗರಿಷ್ಠ ಗಾತ್ರ',
      'palmMin': 'ಅಂಗೈಯ ಕನಿಷ್ಠ ಗಾತ್ರ',
      'off': 'ಆಫ್',
      'auto': 'ಸ್ವಯಂ',
      'learn': 'ನಿಮ್ಮ ಸ್ಪರ್ಶದಿಂದ ಕಲಿಯಿರಿ',
      'learnStart': 'ಪ್ರಾರಂಭಿಸಿ',
      'learnPen': 'ಪೆನ್ ತುದಿಯಿಂದ ಪ್ಯಾಡ್ ಅನ್ನು ಹಲವು ಬಾರಿ ಮುಟ್ಟಿ.',
      'learnFinger': 'ಒಂದು ಬೆರಳಿನಿಂದ ಪ್ಯಾಡ್ ಅನ್ನು ಹಲವು ಬಾರಿ ಮುಟ್ಟಿ.',
      'learnPalm': 'ಅಂಗೈಯನ್ನು ಪ್ಯಾಡ್ ಮೇಲೆ ಕೆಲವು ಬಾರಿ ಇರಿಸಿ.',
      'samples': 'ಸ್ಪರ್ಶಗಳು',
      'next': 'ಮುಂದೆ',
      'finish': 'ಮುಗಿಸಿ',
      'pressure': 'ಒತ್ತಡ',
      'pressureHint': 'ಹೆಚ್ಚು ಒತ್ತಿದಷ್ಟೂ ಗೆರೆ ದಪ್ಪವಾಗುತ್ತದೆ.',
      'eraserEnd': 'ಅಳಿಸುವ ತುದಿ',
      'eraserEndHint': 'ಪೆನ್‌ನ ಹಿಂಭಾಗ ಅಳಿಸುತ್ತದೆ (ಅಥವಾ ಎರಡು-ಬದಿ ಪೆನ್ ಸೆಟ್ ಮಾಡಿದಂತೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ).',
      'button1': 'ಮೊದಲ ಬಟನ್',
      'button2': 'ಎರಡನೇ ಬಟನ್',
      'act.none': 'ಏನೂ ಇಲ್ಲ',
      'act.erase': 'ಅಳಿಸಿ',
      'act.highlight': 'ಹೈಲೈಟ್',
      'act.select': 'ಆಯ್ಕೆ',
      'act.undo': 'ರದ್ದುಮಾಡಿ',
      'dualOn': 'ಎರಡು ಪೆನ್, ಎರಡು ಬಣ್ಣ',
      'dualHint': 'ಪ್ರತಿ ಪೆನ್ ತನ್ನ ಬಣ್ಣದಲ್ಲಿ ಬರೆಯುತ್ತದೆ, ಇದರಿಂದ ಇಬ್ಬರು ಒಟ್ಟಿಗೆ ಬರೆಯಬಹುದು.',
      'pen1': 'ಮೊದಲ ಪೆನ್ ಬಣ್ಣ',
      'pen2': 'ಎರಡನೇ ಪೆನ್ ಬಣ್ಣ',
      'tipSplit': 'ಪೆನ್‌ಗಳನ್ನು ಬೇರ್ಪಡಿಸುವ ತುದಿಯ ಗಾತ್ರ',
      'byOrder': 'ಮೊದಲು ಮುಟ್ಟಿದವರು',
      'calibrateHint': 'ತುಂಬಿದ ಗುರಿಯನ್ನು ಮುಟ್ಟಿ',
      'calibrated': 'ಮಾಪನಾಂಕ ಮುಗಿದಿದೆ, ವ್ಯತ್ಯಾಸ',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'testHint': 'ಇಲ್ಲಿ ಪೆನ್, ಬೆರಳು ಅಥವಾ ಅಂಗೈಯಿಂದ ಬರೆಯಿರಿ.',
      'clear': 'ತೆರವುಗೊಳಿಸಿ',
      'class.pen': 'ಪೆನ್',
      'class.finger': 'ಬೆರಳು',
      'class.palm': 'ಅಂಗೈ',
      'eraserEndName': '(ಅಳಿಸುವ ತುದಿ)',
      'size': 'ಗಾತ್ರ',
      'pressureName': 'ಒತ್ತಡ',
      'tilt': 'ಓರೆ',
      'buttons': 'ಬಟನ್‌ಗಳು',
      'penConfig': 'ಪೆನ್ ಸಂರಚನೆ',
    },
  };
}
