import 'package:flutter/widgets.dart';

import '../flow_chart.dart';
import '../ink_models.dart';
import 'graph_templates.dart';

/// Words of the canvas tools (geometry box, flowcharts, graph templates) in English, Hindi and
/// Kannada. Kept here, apart from the Board's ARB files, so the tools carry their own words to
/// every app that shows the board. Unknown languages fall back to English.
class ToolStrings {
  const ToolStrings(this.lang);

  final String lang;

  static ToolStrings of(BuildContext context) => ToolStrings(Localizations.maybeLocaleOf(context)?.languageCode ?? 'en');

  String t(String key) => _strings[lang]?[key] ?? _strings['en']![key] ?? key;

  String shape(FlowBlock s) => t('shape.${s.name}');
  String pattern(FlowPattern p) => t('pattern.${p.name}');
  String subject(GraphSubject s) => t('subject.${s.name}');
  String template(GraphTemplate g) => _strings[lang]?['graph.${g.id}'] ?? g.title;

  FlowWords get flowWords => FlowWords(
    yes: t('yes'),
    no: t('no'),
    condition: t('condition'),
    step: t('step'),
    cases: [t('case1'), t('case2'), t('case3')],
    loop: t('repeat'),
    forEach: t('forEach'),
    done: t('doneWord'),
    topic: t('idea'),
    start: t('start'),
  );

  static const _strings = <String, Map<String, String>>{
    'en': {
      'ruler': 'Ruler',
      'protractor': 'Protractor',
      'protractor360': 'Full-circle protractor',
      'setSquare45': 'Set square 45°',
      'setSquare3060': 'Set square 30°–60°',
      'compass': 'Compass',
      'lock': 'Lock in place',
      'unlock': 'Unlock',
      'flip': 'Flip',
      'close': 'Put away',
      'rotate': 'Turn (hold to turn freely)',
      'circle': 'Draw a circle',
      'radius': 'Radius',
      'calibrate': 'Calibrate',
      'calibrateTitle': 'Match the scale to this screen',
      'calibrateHint': 'Hold a real ruler against the screen and drag until the marks match. The setting is kept for this device.',
      'cm': 'cm',
      'inch': 'inch',
      'units': 'Units',
      'smaller': 'Smaller',
      'bigger': 'Bigger',
      'done': 'Done',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'addNext': 'Add next',
      'blocks': 'Blocks',
      'suggestedNext': 'Suggested next',
      'conditions': 'Conditions and loops',
      'editText': 'Edit text',
      'flowchart': 'Flowchart',
      'mindMap': 'Mind map',
      'insertFlowTitle': 'Start a diagram',
      'flowchartHint': 'Select a block, then tap ＋ on any side to add the next one.',
      'shape.process': 'Process',
      'shape.decision': 'Decision',
      'shape.inputOutput': 'Input / output',
      'shape.terminal': 'Start / end',
      'shape.subprocess': 'Sub-process',
      'shape.document': 'Document',
      'shape.database': 'Database',
      'shape.loopLimit': 'Loop limit',
      'shape.connector': 'Connector',
      'shape.comment': 'Comment',
      'shape.manualInput': 'Manual input',
      'shape.dataStore': 'Data store',
      'shape.display': 'Display',
      'shape.merge': 'Merge',
      'shape.topic': 'Topic',
      'pattern.ifElse': 'If / else',
      'pattern.switch3': 'Switch (3 cases)',
      'pattern.whileLoop': 'While loop',
      'pattern.forLoop': 'For loop',
      'yes': 'Yes',
      'no': 'No',
      'condition': 'Condition?',
      'step': 'Step',
      'case1': 'Case 1',
      'case2': 'Case 2',
      'case3': 'Case 3',
      'repeat': 'Repeat',
      'forEach': 'For i = 1 to n',
      'doneWord': 'Done',
      'idea': 'Idea',
      'start': 'Start',
      'graphs': 'Graphs',
      'subject': 'Subject',
      'topic': 'Topic',
      'allSubjects': 'All subjects',
      'search': 'Search graphs',
      'addToBoard': 'Add to board',
      'noMatches': 'No graph matches that search.',
      'editGraph': 'Edit graph',
      'expression': 'y =',
      'moreCurves': 'More curves (one per line)',
      'xLabel': 'x-axis label',
      'yLabel': 'y-axis label',
      'title': 'Title',
      'shade': 'Shade from x =',
      'shadeTo': 'to',
      'points': 'Drag the points to move them',
      'apply': 'Apply',
      'subject.maths': 'Mathematics',
      'subject.physics': 'Physics',
      'subject.chemistry': 'Chemistry',
      'subject.biology': 'Biology',
      'subject.economics': 'Economics and commerce',
      'subject.statistics': 'Statistics',
    },
    'hi': {
      'ruler': 'रूलर',
      'protractor': 'चाँदा',
      'protractor360': 'पूर्ण-वृत्त चाँदा',
      'setSquare45': 'सेट स्क्वेयर 45°',
      'setSquare3060': 'सेट स्क्वेयर 30°–60°',
      'compass': 'परकार',
      'lock': 'जगह पर लॉक करें',
      'unlock': 'अनलॉक करें',
      'flip': 'पलटें',
      'close': 'हटाएँ',
      'rotate': 'घुमाएँ (खुलकर घुमाने के लिए दबाए रखें)',
      'circle': 'वृत्त बनाएँ',
      'radius': 'त्रिज्या',
      'calibrate': 'कैलिब्रेट करें',
      'calibrateTitle': 'पैमाने को इस स्क्रीन से मिलाएँ',
      'calibrateHint': 'असली रूलर स्क्रीन पर रखें और निशान मिलने तक खींचें। यह सेटिंग इस डिवाइस के लिए रखी जाती है।',
      'cm': 'सेमी',
      'inch': 'इंच',
      'units': 'इकाई',
      'smaller': 'छोटा करें',
      'bigger': 'बड़ा करें',
      'done': 'हो गया',
      'cancel': 'रद्द करें',
      'reset': 'रीसेट',
      'addNext': 'अगला जोड़ें',
      'blocks': 'ब्लॉक',
      'suggestedNext': 'सुझाया गया अगला',
      'conditions': 'शर्तें और लूप',
      'editText': 'लिखावट बदलें',
      'flowchart': 'फ़्लोचार्ट',
      'mindMap': 'माइंड मैप',
      'insertFlowTitle': 'आरेख शुरू करें',
      'flowchartHint': 'कोई ब्लॉक चुनें, फिर अगला जोड़ने के लिए किसी भी ओर ＋ दबाएँ।',
      'shape.process': 'प्रक्रिया',
      'shape.decision': 'निर्णय',
      'shape.inputOutput': 'इनपुट / आउटपुट',
      'shape.terminal': 'आरंभ / अंत',
      'shape.subprocess': 'उप-प्रक्रिया',
      'shape.document': 'दस्तावेज़',
      'shape.database': 'डेटाबेस',
      'shape.loopLimit': 'लूप सीमा',
      'shape.connector': 'कनेक्टर',
      'shape.comment': 'टिप्पणी',
      'shape.manualInput': 'हाथ से इनपुट',
      'shape.dataStore': 'डेटा भंडार',
      'shape.display': 'डिस्प्ले',
      'shape.merge': 'मिलान',
      'shape.topic': 'विषय',
      'pattern.ifElse': 'यदि / अन्यथा',
      'pattern.switch3': 'स्विच (3 स्थितियाँ)',
      'pattern.whileLoop': 'व्हाइल लूप',
      'pattern.forLoop': 'फ़ॉर लूप',
      'yes': 'हाँ',
      'no': 'नहीं',
      'condition': 'शर्त?',
      'step': 'चरण',
      'case1': 'स्थिति 1',
      'case2': 'स्थिति 2',
      'case3': 'स्थिति 3',
      'repeat': 'दोहराएँ',
      'forEach': 'i = 1 से n तक',
      'doneWord': 'समाप्त',
      'idea': 'विचार',
      'start': 'आरंभ',
      'graphs': 'ग्राफ़',
      'subject': 'विषय',
      'topic': 'प्रकरण',
      'allSubjects': 'सभी विषय',
      'search': 'ग्राफ़ खोजें',
      'addToBoard': 'बोर्ड पर जोड़ें',
      'noMatches': 'इस खोज से कोई ग्राफ़ नहीं मिला।',
      'editGraph': 'ग्राफ़ बदलें',
      'expression': 'y =',
      'moreCurves': 'और वक्र (हर पंक्ति में एक)',
      'xLabel': 'x-अक्ष का नाम',
      'yLabel': 'y-अक्ष का नाम',
      'title': 'शीर्षक',
      'shade': 'छायांकन x =',
      'shadeTo': 'से',
      'points': 'बिंदुओं को खींचकर हिलाएँ',
      'apply': 'लागू करें',
      'subject.maths': 'गणित',
      'subject.physics': 'भौतिकी',
      'subject.chemistry': 'रसायन विज्ञान',
      'subject.biology': 'जीव विज्ञान',
      'subject.economics': 'अर्थशास्त्र और वाणिज्य',
      'subject.statistics': 'सांख्यिकी',
      'graph.linear': 'सरल रेखा',
      'graph.quadratic': 'द्विघात',
      'graph.cubic': 'त्रिघात',
      'graph.exponential': 'घातांकीय',
      'graph.log': 'लघुगणक',
      'graph.trig': 'साइन और कोसाइन',
      'graph.circle': 'वृत्त',
      'graph.parabola': 'परवलय',
      'graph.vt': 'वेग–समय',
      'graph.st': 'दूरी–समय',
      'graph.ohm': 'ओम का नियम',
      'graph.projectile': 'प्रक्षेप्य',
      'graph.shm': 'सरल आवर्त गति',
      'graph.titration': 'अनुमापन वक्र',
      'graph.rate': 'दर बनाम सांद्रता',
      'graph.boyle': 'बॉयल का नियम',
      'graph.population': 'जनसंख्या वृद्धि',
      'graph.enzymeTemp': 'एंजाइम सक्रियता बनाम तापमान',
      'graph.enzymePh': 'एंजाइम सक्रियता बनाम pH',
      'graph.demandSupply': 'माँग और पूर्ति',
      'graph.costCurves': 'लागत वक्र',
      'graph.breakEven': 'सम-विच्छेद',
      'graph.ppf': 'उत्पादन संभावना वक्र',
      'graph.lorenz': 'लॉरेंज वक्र',
      'graph.normal': 'प्रसामान्य बंटन',
    },
    'kn': {
      'ruler': 'ಅಳತೆಪಟ್ಟಿ',
      'protractor': 'ಕೋನಮಾಪಕ',
      'protractor360': 'ಪೂರ್ಣ ವೃತ್ತ ಕೋನಮಾಪಕ',
      'setSquare45': 'ಮೂಲೆಮಟ್ಟ 45°',
      'setSquare3060': 'ಮೂಲೆಮಟ್ಟ 30°–60°',
      'compass': 'ಕೈವಾರ',
      'lock': 'ಸ್ಥಳದಲ್ಲಿ ಲಾಕ್ ಮಾಡಿ',
      'unlock': 'ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
      'flip': 'ತಿರುಗಿಸಿ ಹಾಕಿ',
      'close': 'ತೆಗೆದಿಡಿ',
      'rotate': 'ತಿರುಗಿಸಿ (ಮುಕ್ತವಾಗಿ ತಿರುಗಿಸಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ)',
      'circle': 'ವೃತ್ತ ಎಳೆಯಿರಿ',
      'radius': 'ತ್ರಿಜ್ಯ',
      'calibrate': 'ಹೊಂದಿಸಿ',
      'calibrateTitle': 'ಅಳತೆಯನ್ನು ಈ ಪರದೆಗೆ ಹೊಂದಿಸಿ',
      'calibrateHint': 'ನಿಜವಾದ ಅಳತೆಪಟ್ಟಿಯನ್ನು ಪರದೆಗೆ ಹಿಡಿದು ಗುರುತುಗಳು ಹೊಂದುವವರೆಗೆ ಎಳೆಯಿರಿ. ಈ ಸಾಧನಕ್ಕೆ ಇದನ್ನು ಉಳಿಸಲಾಗುತ್ತದೆ.',
      'cm': 'ಸೆಂ.ಮೀ',
      'inch': 'ಇಂಚು',
      'units': 'ಘಟಕ',
      'smaller': 'ಚಿಕ್ಕದು ಮಾಡಿ',
      'bigger': 'ದೊಡ್ಡದು ಮಾಡಿ',
      'done': 'ಆಯಿತು',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'addNext': 'ಮುಂದಿನದನ್ನು ಸೇರಿಸಿ',
      'blocks': 'ಬ್ಲಾಕ್‌ಗಳು',
      'suggestedNext': 'ಸೂಚಿಸಿದ ಮುಂದಿನದು',
      'conditions': 'ಷರತ್ತುಗಳು ಮತ್ತು ಲೂಪ್‌ಗಳು',
      'editText': 'ಪಠ್ಯ ಬದಲಿಸಿ',
      'flowchart': 'ಫ್ಲೋಚಾರ್ಟ್',
      'mindMap': 'ಮೈಂಡ್ ಮ್ಯಾಪ್',
      'insertFlowTitle': 'ರೇಖಾಚಿತ್ರ ಪ್ರಾರಂಭಿಸಿ',
      'flowchartHint': 'ಒಂದು ಬ್ಲಾಕ್ ಆರಿಸಿ, ನಂತರ ಮುಂದಿನದನ್ನು ಸೇರಿಸಲು ಯಾವುದೇ ಬದಿಯ ＋ ಒತ್ತಿ.',
      'shape.process': 'ಪ್ರಕ್ರಿಯೆ',
      'shape.decision': 'ನಿರ್ಧಾರ',
      'shape.inputOutput': 'ಇನ್‌ಪುಟ್ / ಔಟ್‌ಪುಟ್',
      'shape.terminal': 'ಪ್ರಾರಂಭ / ಅಂತ್ಯ',
      'shape.subprocess': 'ಉಪ-ಪ್ರಕ್ರಿಯೆ',
      'shape.document': 'ದಾಖಲೆ',
      'shape.database': 'ಡೇಟಾಬೇಸ್',
      'shape.loopLimit': 'ಲೂಪ್ ಮಿತಿ',
      'shape.connector': 'ಸಂಪರ್ಕಕ',
      'shape.comment': 'ಟಿಪ್ಪಣಿ',
      'shape.manualInput': 'ಕೈ ಇನ್‌ಪುಟ್',
      'shape.dataStore': 'ಡೇಟಾ ಸಂಗ್ರಹ',
      'shape.display': 'ಪ್ರದರ್ಶನ',
      'shape.merge': 'ವಿಲೀನ',
      'shape.topic': 'ವಿಷಯ',
      'pattern.ifElse': 'ಒಂದು ವೇಳೆ / ಇಲ್ಲದಿದ್ದರೆ',
      'pattern.switch3': 'ಸ್ವಿಚ್ (3 ಸಂದರ್ಭಗಳು)',
      'pattern.whileLoop': 'ವೈಲ್ ಲೂಪ್',
      'pattern.forLoop': 'ಫಾರ್ ಲೂಪ್',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'condition': 'ಷರತ್ತು?',
      'step': 'ಹಂತ',
      'case1': 'ಸಂದರ್ಭ 1',
      'case2': 'ಸಂದರ್ಭ 2',
      'case3': 'ಸಂದರ್ಭ 3',
      'repeat': 'ಪುನರಾವರ್ತಿಸಿ',
      'forEach': 'i = 1 ರಿಂದ n ವರೆಗೆ',
      'doneWord': 'ಮುಗಿದಿದೆ',
      'idea': 'ಆಲೋಚನೆ',
      'start': 'ಪ್ರಾರಂಭ',
      'graphs': 'ಗ್ರಾಫ್‌ಗಳು',
      'subject': 'ವಿಷಯ',
      'topic': 'ಪಾಠ',
      'allSubjects': 'ಎಲ್ಲಾ ವಿಷಯಗಳು',
      'search': 'ಗ್ರಾಫ್ ಹುಡುಕಿ',
      'addToBoard': 'ಬೋರ್ಡ್‌ಗೆ ಸೇರಿಸಿ',
      'noMatches': 'ಈ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಗ್ರಾಫ್ ಸಿಗಲಿಲ್ಲ.',
      'editGraph': 'ಗ್ರಾಫ್ ಬದಲಿಸಿ',
      'expression': 'y =',
      'moreCurves': 'ಇನ್ನಷ್ಟು ವಕ್ರಗಳು (ಸಾಲಿಗೆ ಒಂದು)',
      'xLabel': 'x-ಅಕ್ಷದ ಹೆಸರು',
      'yLabel': 'y-ಅಕ್ಷದ ಹೆಸರು',
      'title': 'ಶೀರ್ಷಿಕೆ',
      'shade': 'ಛಾಯೆ x =',
      'shadeTo': 'ರಿಂದ',
      'points': 'ಬಿಂದುಗಳನ್ನು ಎಳೆದು ಸರಿಸಿ',
      'apply': 'ಅನ್ವಯಿಸಿ',
      'subject.maths': 'ಗಣಿತ',
      'subject.physics': 'ಭೌತಶಾಸ್ತ್ರ',
      'subject.chemistry': 'ರಸಾಯನಶಾಸ್ತ್ರ',
      'subject.biology': 'ಜೀವಶಾಸ್ತ್ರ',
      'subject.economics': 'ಅರ್ಥಶಾಸ್ತ್ರ ಮತ್ತು ವಾಣಿಜ್ಯ',
      'subject.statistics': 'ಸಂಖ್ಯಾಶಾಸ್ತ್ರ',
      'graph.linear': 'ಸರಳ ರೇಖೆ',
      'graph.quadratic': 'ವರ್ಗ ಸಮೀಕರಣ',
      'graph.cubic': 'ಘನ ಸಮೀಕರಣ',
      'graph.exponential': 'ಘಾತೀಯ',
      'graph.log': 'ಲಘುಗಣಕ',
      'graph.trig': 'ಸೈನ್ ಮತ್ತು ಕೊಸೈನ್',
      'graph.circle': 'ವೃತ್ತ',
      'graph.parabola': 'ಪರವಲಯ',
      'graph.vt': 'ವೇಗ–ಸಮಯ',
      'graph.st': 'ದೂರ–ಸಮಯ',
      'graph.ohm': 'ಓಮ್‌ನ ನಿಯಮ',
      'graph.projectile': 'ಪ್ರಕ್ಷೇಪಕ',
      'graph.shm': 'ಸರಳ ಆವರ್ತ ಚಲನೆ',
      'graph.titration': 'ಅನುಮಾಪನ ವಕ್ರ',
      'graph.rate': 'ದರ ಮತ್ತು ಸಾಂದ್ರತೆ',
      'graph.boyle': 'ಬಾಯ್ಲ್‌ನ ನಿಯಮ',
      'graph.population': 'ಜನಸಂಖ್ಯೆ ಬೆಳವಣಿಗೆ',
      'graph.enzymeTemp': 'ಕಿಣ್ವ ಚಟುವಟಿಕೆ ಮತ್ತು ತಾಪಮಾನ',
      'graph.enzymePh': 'ಕಿಣ್ವ ಚಟುವಟಿಕೆ ಮತ್ತು pH',
      'graph.demandSupply': 'ಬೇಡಿಕೆ ಮತ್ತು ಪೂರೈಕೆ',
      'graph.costCurves': 'ವೆಚ್ಚದ ವಕ್ರಗಳು',
      'graph.breakEven': 'ಲಾಭ-ನಷ್ಟ ರಹಿತ ಬಿಂದು',
      'graph.ppf': 'ಉತ್ಪಾದನಾ ಸಾಧ್ಯತೆ ವಕ್ರ',
      'graph.lorenz': 'ಲೊರೆನ್ಜ್ ವಕ್ರ',
      'graph.normal': 'ಸಾಮಾನ್ಯ ವಿತರಣೆ',
    },
  };

  /// Every key, for the test that each language has them all.
  static Iterable<String> keys(String lang) => _strings[lang]!.keys;

  /// Keys every language must have (the English ones; graph titles fall back to the template).
  static Iterable<String> get requiredKeys => _strings['en']!.keys;
}

/// Shapes shown in the ＋ palette for a block of [from] (mind-map topics offer topics first).
List<FlowBlock> paletteShapes(FlowBlock from) => from == FlowBlock.topic
    ? const [FlowBlock.topic, FlowBlock.process, FlowBlock.comment]
    : [
        for (final s in FlowBlock.values)
          if (s != FlowBlock.topic) s,
      ];
