# Secrets Manager, one JSON secret per concern, all encrypted with the environment key. ECS
# injects single keys (`<arn>:<KEY>::`) as environment variables; nothing is baked into images.
#
# Generated by Terraform (rotate by tainting the random_password and re-running db-bootstrap,
# see docs/operations/security.md): db, app, redis.
# Filled in by a person outside Terraform (placeholders here; Terraform never overwrites them):
# msg91, razorpay, fcm.

resource "random_password" "jwt" {
  length  = 64
  special = false
}

resource "random_password" "pairing_hmac" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "kinetix/${var.environment}/db"
  description             = "PostgreSQL URLs: owner (migrations), app (RLS-bound, requests), admin (RDS master, db-bootstrap only)"
  kms_key_id              = aws_kms_key.data.arn
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    DATABASE_URL       = local.owner_url
    APP_DATABASE_URL   = local.app_url
    ADMIN_DATABASE_URL = local.admin_url
  })
}

resource "aws_secretsmanager_secret" "app" {
  name                    = "kinetix/${var.environment}/app"
  description             = "JWT signing key and board pairing HMAC key"
  kms_key_id              = aws_kms_key.data.arn
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    JWT_SECRET          = random_password.jwt.result
    PAIRING_HMAC_SECRET = random_password.pairing_hmac.result
  })
}

resource "aws_secretsmanager_secret" "redis" {
  name                    = "kinetix/${var.environment}/redis"
  description             = "REDIS_URL with the ElastiCache AUTH token"
  kms_key_id              = aws_kms_key.data.arn
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "redis" {
  secret_id     = aws_secretsmanager_secret.redis.id
  secret_string = jsonencode({ REDIS_URL = local.redis_url })
}

locals {
  manual_secrets = {
    msg91 = {
      description = "MSG91 (SMS sign-in codes, DLT): auth key, Flow template id, sender id"
      keys        = ["MSG91_AUTH_KEY", "MSG91_TEMPLATE_ID", "MSG91_SENDER_ID"]
    }
    razorpay = {
      description = "Razorpay live keys and webhook secret"
      keys        = ["RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET", "RAZORPAY_WEBHOOK_SECRET"]
    }
    fcm = {
      description = "Firebase service account JSON for push (pushes carry ids only)"
      keys        = ["FCM_SERVICE_ACCOUNT"]
    }
  }
}

resource "aws_secretsmanager_secret" "manual" {
  for_each                = local.manual_secrets
  name                    = "kinetix/${var.environment}/${each.key}"
  description             = each.value.description
  kms_key_id              = aws_kms_key.data.arn
  recovery_window_in_days = 7
}

# Placeholder values so the keys exist; put the real values with
#   aws secretsmanager put-secret-value --secret-id kinetix/<env>/<name> --secret-string file://x.json
resource "aws_secretsmanager_secret_version" "manual" {
  for_each      = local.manual_secrets
  secret_id     = aws_secretsmanager_secret.manual[each.key].id
  secret_string = jsonencode({ for k in each.value.keys : k => "REPLACE_ME" })

  lifecycle {
    ignore_changes = [secret_string, version_stages]
  }
}

locals {
  secret_arns = concat(
    [aws_secretsmanager_secret.db.arn, aws_secretsmanager_secret.app.arn, aws_secretsmanager_secret.redis.arn],
    [for s in aws_secretsmanager_secret.manual : s.arn],
  )

  # Environment variable name => "<secret arn>:<json key>::"
  api_secrets = merge(
    {
      DATABASE_URL        = "${aws_secretsmanager_secret.db.arn}:DATABASE_URL::"
      APP_DATABASE_URL    = "${aws_secretsmanager_secret.db.arn}:APP_DATABASE_URL::"
      JWT_SECRET          = "${aws_secretsmanager_secret.app.arn}:JWT_SECRET::"
      PAIRING_HMAC_SECRET = "${aws_secretsmanager_secret.app.arn}:PAIRING_HMAC_SECRET::"
      REDIS_URL           = "${aws_secretsmanager_secret.redis.arn}:REDIS_URL::"
    },
    var.sms_provider == "msg91" ? {
      for k in local.manual_secrets.msg91.keys : k => "${aws_secretsmanager_secret.manual["msg91"].arn}:${k}::"
    } : {},
    var.payments_provider == "razorpay" ? {
      for k in local.manual_secrets.razorpay.keys : k => "${aws_secretsmanager_secret.manual["razorpay"].arn}:${k}::"
    } : {},
    var.push_enabled ? {
      FCM_SERVICE_ACCOUNT = "${aws_secretsmanager_secret.manual["fcm"].arn}:FCM_SERVICE_ACCOUNT::"
    } : {},
  )
}
