import { A4, Pdf } from '../common/pdf-doc.js';

/** The financial year (April to March) a date falls in, as "2026-27". */
export function financialYear(day: string): string {
  const y = Number(day.slice(0, 4));
  const start = Number(day.slice(5, 7)) >= 4 ? y : y - 1;
  return `${start}-${String((start + 1) % 100).padStart(2, '0')}`;
}

const ONES = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
const TENS = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
const below100 = (n: number) => (n < 20 ? ONES[n] : `${TENS[Math.floor(n / 10)]}${n % 10 ? ' ' + ONES[n % 10] : ''}`);
const below1000 = (n: number) => (n >= 100 ? `${ONES[Math.floor(n / 100)]} Hundred${n % 100 ? ' ' + below100(n % 100) : ''}` : below100(n));

/** "Rupees One Lakh Twenty Five Thousand and Fifty Paise Only" with Indian digit grouping. */
export function amountInWords(paise: number): string {
  const rupees = Math.floor(paise / 100);
  const ps = paise % 100;
  const parts: string[] = [];
  let rest = rupees;
  for (const [div, name] of [[10_000_000, 'Crore'], [100_000, 'Lakh'], [1000, 'Thousand']] as const) {
    const q = Math.floor(rest / div);
    if (q > 0) parts.push(`${below1000(q)} ${name}`);
    rest %= div;
  }
  if (rest > 0) parts.push(below1000(rest));
  const r = parts.length ? parts.join(' ') : 'Zero';
  return `Rupees ${r}${ps ? ` and ${below100(ps)} Paise` : ''} Only`;
}

export const inr = (paise: number) => `Rs. ${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export interface ReceiptData {
  institution: string;
  serial: string;
  receivedOn: string;
  donorName: string;
  donorPan: string | null;
  donorAddress: string;
  amountPaise: number;
  mode: string;
  reference: string | null;
  campaign: string;
  note: string;
}

const MODE_LABEL: Record<string, string> = { cash: 'Cash', cheque: 'Cheque', upi: 'UPI', bank_transfer: 'Bank transfer', card: 'Card', other: 'Other' };

/** A donation receipt in the usual Section 80G form: serial number, donor, amount in figures and words, mode, and the institution's note. */
export function receiptPdf(d: ReceiptData): Buffer {
  const pdf = new Pdf(`Donation receipt ${d.serial}`).addPage();
  const left = 56;
  const right = A4.w - 56;
  pdf.rect(40, 40, A4.w - 80, 430, { stroke: '#444444', lineWidth: 1 });
  pdf.text(d.institution, A4.w / 2, 78, { size: 17, bold: true, align: 'center' });
  pdf.text('Donation receipt', A4.w / 2, 100, { size: 12, align: 'center' });
  pdf.line(left, 114, right, 114);
  pdf.text(`Receipt no. ${d.serial}`, left, 138, { size: 11, bold: true });
  pdf.text(`Date: ${d.receivedOn}`, right, 138, { size: 11, align: 'right' });
  let y = 170;
  const row = (label: string, value: string) => {
    pdf.text(label, left, y, { size: 10, color: '#555555' });
    y = pdf.paragraph(value || '-', left + 130, y, right - left - 130, { size: 11 }) + 6;
  };
  row('Received with thanks from', d.donorName);
  if (d.donorPan) row('PAN of donor', d.donorPan);
  if (d.donorAddress) row('Address', d.donorAddress);
  row('Amount', `${inr(d.amountPaise)}`);
  row('In words', amountInWords(d.amountPaise));
  row('Mode of payment', `${MODE_LABEL[d.mode] ?? d.mode}${d.reference ? ` (${d.reference})` : ''}`);
  row('Towards', d.campaign);
  if (d.note) row('Note', d.note);
  y += 16;
  pdf.line(left, y, right, y);
  y += 22;
  y = pdf.paragraph('Thank you for supporting the institution. This receipt is generated by KINETIX and is valid with the serial number above.', left, y, right - left, { size: 9, color: '#555555' });
  pdf.text('Authorised signatory', right, 440, { size: 10, align: 'right' });
  pdf.line(right - 150, 430, right, 430);
  return pdf.build();
}
