"""Electronics and current electricity on the circuit engine
(lib/src/benches/electronics/): diodes, rectifiers, transistors, gates,
RC/LCR, op-amps, the 555, Kirchhoff, metre bridge and potentiometer."""


def add(lab, W, Q):
    # Apparatus shared by many labs.
    SUPPLY = W('Variable DC power supply (0–10 V)', 'परिवर्ती DC विद्युत आपूर्ति (0–10 V)', 'ಬದಲಾಯಿಸಬಹುದಾದ DC ವಿದ್ಯುತ್ ಪೂರೈಕೆ (0–10 V)')
    MA = W('Milliammeter (and microammeter)', 'मिलीऐमीटर (और माइक्रोऐमीटर)', 'ಮಿಲಿಅಮ್ಮೀಟರ್ (ಮತ್ತು ಮೈಕ್ರೋಅಮ್ಮೀಟರ್)')
    VM = W('Voltmeter', 'वोल्टमीटर', 'ವೋಲ್ಟ್‌ಮೀಟರ್')
    WIRES = W('Connecting wires and a breadboard', 'संयोजक तार और ब्रेडबोर्ड', 'ಸಂಪರ್ಕ ತಂತಿಗಳು ಮತ್ತು ಬ್ರೆಡ್‌ಬೋರ್ಡ್')
    RES = W('Series resistor (100 Ω) to limit the current', 'धारा सीमित करने के लिए श्रेणी प्रतिरोधक (100 Ω)', 'ಪ್ರವಾಹ ಮಿತಿಗೊಳಿಸಲು ಸರಣಿ ರೋಧಕ (100 Ω)')
    CRO = W('Cathode-ray oscilloscope (CRO)', 'कैथोड किरण दोलनदर्शी (CRO)', 'ಕ್ಯಾಥೋಡ್ ಕಿರಣ ಆಂದೋಲನದರ್ಶಕ (CRO)')
    TRANS = W('Step-down transformer (230 V to 6/9/12 V)', 'अपचायी ट्रांसफ़ॉर्मर (230 V से 6/9/12 V)', 'ಇಳಿಕೆ ಪರಿವರ್ತಕ (230 V ನಿಂದ 6/9/12 V)')
    KEY = W('Plug key', 'प्लग कुंजी', 'ಪ್ಲಗ್ ಕೀ')
    GALV = W('Galvanometer', 'गैल्वेनोमीटर', 'ಗ್ಯಾಲ್ವನೋಮೀಟರ್')
    RBOX = W('Resistance box', 'प्रतिरोध बॉक्स', 'ರೋಧ ಪೆಟ್ಟಿಗೆ')
    JOCKEY = W('Jockey', 'जॉकी (सर्पी संपर्क)', 'ಜಾಕಿ (ಸರಿಯುವ ಸಂಪರ್ಕ)')
    RHEO = W('Rheostat', 'धारा नियंत्रक (रिओस्टेट)', 'ರಿಯೋಸ್ಟಾಟ್')

    P_POLARITY = W('Connect meters with + to + and choose a range larger than the expected reading.', 'मीटर + से + जोड़ें और अपेक्षित पाठ्यांक से बड़ी परास चुनें।', 'ಮೀಟರ್‌ಗಳನ್ನು + ರಿಂದ + ಗೆ ಜೋಡಿಸಿ, ನಿರೀಕ್ಷಿತ ಓದಿಗಿಂತ ದೊಡ್ಡ ವ್ಯಾಪ್ತಿ ಆರಿಸಿ.')
    P_CURRENT = W('Never let the current exceed the rated value of the device; always keep the series resistor in the circuit.', 'धारा कभी भी युक्ति के निर्धारित मान से अधिक न होने दें; श्रेणी प्रतिरोधक सदा परिपथ में रखें।', 'ಪ್ರವಾಹ ಸಾಧನದ ನಿಗದಿತ ಮೌಲ್ಯವನ್ನು ಎಂದೂ ಮೀರಬಾರದು; ಸರಣಿ ರೋಧಕವನ್ನು ಯಾವಾಗಲೂ ಮಂಡಲದಲ್ಲಿಡಿ.')
    P_SWITCH_OFF = W('Switch off the supply when changing connections.', 'संयोजन बदलते समय आपूर्ति बंद कर दें।', 'ಸಂಪರ್ಕ ಬದಲಿಸುವಾಗ ಪೂರೈಕೆ ಆಫ್ ಮಾಡಿ.')

    # ------------------------------------------------------------ diodes
    lab(
        id='pn-junction-diode', bench='diode', setup={'device': 'si'}, subject='Electronics', domain='electronics', levels=[12, 'ug'],
        curricula=['cbse', 'ncert', 'ka-puc'], mode='guided',
        keywords=['semiconductor', 'semiconductor electronics', 'p-n junction', 'pn junction', 'diode', 'forward bias', 'reverse bias', 'knee voltage', 'characteristics'],
        title=W('I–V characteristics of a p-n junction diode', 'p-n संधि डायोड के I–V अभिलक्षण', 'p-n ಸಂಧಿ ಡಯೋಡ್‌ನ I–V ಲಕ್ಷಣಗಳು'),
        summary=W('Forward- and reverse-bias a silicon diode, record V and I, and find its knee voltage.',
                  'सिलिकॉन डायोड को अग्र और पश्च अभिनति दें, V और I लिखें और उसकी घुटना वोल्टता ज्ञात करें।',
                  'ಸಿಲಿಕಾನ್ ಡಯೋಡ್‌ಗೆ ಮುಮ್ಮುಖ ಮತ್ತು ಹಿಮ್ಮುಖ ಬಯಾಸ್ ನೀಡಿ, V ಮತ್ತು I ದಾಖಲಿಸಿ, ಅದರ ನೀ (ಮೊಣಕಾಲು) ವೋಲ್ಟೇಜ್ ಕಂಡುಹಿಡಿಯಿರಿ.'),
        aim=W('To draw the I–V characteristic curves of a p-n junction diode in forward and reverse bias.',
              'अग्र और पश्च अभिनति में p-n संधि डायोड के I–V अभिलक्षण वक्र खींचना।',
              'ಮುಮ್ಮುಖ ಮತ್ತು ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ p-n ಸಂಧಿ ಡಯೋಡ್‌ನ I–V ಲಕ್ಷಣ ವಕ್ರಗಳನ್ನು ಎಳೆಯುವುದು.'),
        principle=W('A p-n junction has a depletion layer with a barrier potential (about 0.7 V for silicon). In forward bias the barrier is lowered: almost no current flows until the applied voltage nears the barrier (the knee voltage), then the current rises steeply. In reverse bias the barrier grows and only a tiny current of minority carriers (microamperes) flows.',
                    'p-n संधि में एक ह्रासी परत होती है जिसका रोधिका विभव (सिलिकॉन के लिए लगभग 0.7 V) होता है। अग्र अभिनति में रोधिका घटती है: लगाई गई वोल्टता रोधिका के निकट (घुटना वोल्टता) आने तक लगभग कोई धारा नहीं बहती, फिर धारा तेज़ी से बढ़ती है। पश्च अभिनति में रोधिका बढ़ती है और केवल अल्पसंख्यक वाहकों की बहुत छोटी धारा (माइक्रोऐम्पियर) बहती है।',
                    'p-n ಸಂಧಿಯಲ್ಲಿ ಕ್ಷೀಣಿಸಿದ ಪದರವಿದ್ದು ಅದಕ್ಕೆ ತಡೆ ವಿಭವ (ಸಿಲಿಕಾನ್‌ಗೆ ಸುಮಾರು 0.7 V) ಇರುತ್ತದೆ. ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ತಡೆ ಕಡಿಮೆಯಾಗುತ್ತದೆ: ಅನ್ವಯಿಸಿದ ವೋಲ್ಟೇಜ್ ತಡೆಯ ಹತ್ತಿರ (ನೀ ವೋಲ್ಟೇಜ್) ಬರುವವರೆಗೆ ಬಹುತೇಕ ಪ್ರವಾಹವಿಲ್ಲ, ನಂತರ ಪ್ರವಾಹ ವೇಗವಾಗಿ ಏರುತ್ತದೆ. ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ತಡೆ ಹೆಚ್ಚುತ್ತದೆ; ಅಲ್ಪಸಂಖ್ಯಾತ ವಾಹಕಗಳ ಅತಿ ಸಣ್ಣ ಪ್ರವಾಹ (ಮೈಕ್ರೋಆಂಪಿಯರ್) ಮಾತ್ರ ಹರಿಯುತ್ತದೆ.'),
        apparatus=[W('Silicon p-n junction diode', 'सिलिकॉन p-n संधि डायोड', 'ಸಿಲಿಕಾನ್ p-n ಸಂಧಿ ಡಯೋಡ್'), SUPPLY, RES, MA, VM, WIRES],
        steps=[W('Connect the diode in forward bias: p side (anode) to the + of the supply through the resistor and milliammeter; voltmeter across the diode.',
                 'डायोड को अग्र अभिनति में जोड़ें: p सिरा (ऐनोड) प्रतिरोधक और मिलीऐमीटर से होते हुए आपूर्ति के + से; वोल्टमीटर डायोड के सिरों पर।',
                 'ಡಯೋಡನ್ನು ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಜೋಡಿಸಿ: p ಭಾಗ (ಆನೋಡ್) ರೋಧಕ ಮತ್ತು ಮಿಲಿಅಮ್ಮೀಟರ್ ಮೂಲಕ ಪೂರೈಕೆಯ + ಗೆ; ವೋಲ್ಟ್‌ಮೀಟರ್ ಡಯೋಡ್‌ಗೆ ಅಡ್ಡಲಾಗಿ.'),
               W('Raise the supply in small steps and record V and I each time. Take closer readings around 0.5–0.8 V.',
                 'आपूर्ति को छोटे चरणों में बढ़ाएँ और हर बार V और I लिखें। 0.5–0.8 V के आसपास पाठ्यांक पास-पास लें।',
                 'ಪೂರೈಕೆಯನ್ನು ಸಣ್ಣ ಹಂತಗಳಲ್ಲಿ ಹೆಚ್ಚಿಸಿ ಪ್ರತಿ ಬಾರಿ V ಮತ್ತು I ದಾಖಲಿಸಿ. 0.5–0.8 V ಸುತ್ತ ಹತ್ತಿರ ಹತ್ತಿರ ಓದುಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.'),
               W('Switch to reverse bias (and a microammeter). Raise the voltage and record V and I.',
                 'पश्च अभिनति पर बदलें (और माइक्रोऐमीटर लगाएँ)। वोल्टता बढ़ाकर V और I लिखें।',
                 'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ಗೆ ಬದಲಿಸಿ (ಮೈಕ್ರೋಅಮ್ಮೀಟರ್ ಬಳಸಿ). ವೋಲ್ಟೇಜ್ ಹೆಚ್ಚಿಸಿ V ಮತ್ತು I ದಾಖಲಿಸಿ.'),
               W('Plot I against V for both biases on one graph (reverse values negative).', 'दोनों अभिनतियों के लिए I और V का ग्राफ़ एक ही कागज़ पर बनाएँ (पश्च मान ऋणात्मक)।', 'ಎರಡೂ ಬಯಾಸ್‌ಗಳಿಗೆ I ಮತ್ತು V ನಕ್ಷೆಯನ್ನು ಒಂದೇ ಹಾಳೆಯಲ್ಲಿ ಎಳೆಯಿರಿ (ಹಿಮ್ಮುಖ ಮೌಲ್ಯಗಳು ಋಣ).'),
               W('Extend the straight, steep part of the forward curve down to the V axis: that is the knee voltage.', 'अग्र वक्र के सीधे, खड़े भाग को V अक्ष तक बढ़ाएँ: वही घुटना वोल्टता है।', 'ಮುಮ್ಮುಖ ವಕ್ರದ ನೇರ, ಕಡಿದಾದ ಭಾಗವನ್ನು V ಅಕ್ಷದವರೆಗೆ ವಿಸ್ತರಿಸಿ: ಅದೇ ನೀ ವೋಲ್ಟೇಜ್.')],
        precautions=[P_CURRENT, P_POLARITY, W('Use a microammeter in reverse bias: the current is very small.', 'पश्च अभिनति में माइक्रोऐमीटर लें: धारा बहुत छोटी होती है।', 'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಮೈಕ್ರೋಅಮ್ಮೀಟರ್ ಬಳಸಿ: ಪ್ರವಾಹ ಅತಿ ಸಣ್ಣದು.')],
        conclusion=W('The diode conducts well only in forward bias, after the knee voltage (about 0.7 V for silicon); in reverse bias only microamperes flow. The diode is a one-way valve for current.',
                     'डायोड केवल अग्र अभिनति में, घुटना वोल्टता (सिलिकॉन के लिए लगभग 0.7 V) के बाद अच्छी तरह चालन करता है; पश्च अभिनति में केवल माइक्रोऐम्पियर बहते हैं। डायोड धारा के लिए एकदिशीय वाल्व है।',
                     'ಡಯೋಡ್ ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಮಾತ್ರ, ನೀ ವೋಲ್ಟೇಜ್ (ಸಿಲಿಕಾನ್‌ಗೆ ಸುಮಾರು 0.7 V) ನಂತರ ಚೆನ್ನಾಗಿ ವಾಹಕವಾಗುತ್ತದೆ; ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಮೈಕ್ರೋಆಂಪಿಯರ್ ಮಾತ್ರ. ಡಯೋಡ್ ಪ್ರವಾಹಕ್ಕೆ ಏಕಮುಖ ಕವಾಟ.'),
        viva=[Q(W('What is the knee voltage of a germanium diode?', 'जर्मेनियम डायोड की घुटना वोल्टता कितनी होती है?', 'ಜರ್ಮೇನಿಯಂ ಡಯೋಡ್‌ನ ನೀ ವೋಲ್ಟೇಜ್ ಎಷ್ಟು?'), W('About 0.3 V.', 'लगभग 0.3 V.', 'ಸುಮಾರು 0.3 V.')),
              Q(W('Why does a small current flow in reverse bias?', 'पश्च अभिनति में छोटी धारा क्यों बहती है?', 'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಸಣ್ಣ ಪ್ರವಾಹ ಏಕೆ ಹರಿಯುತ್ತದೆ?'),
                W('Minority carriers (electrons in p, holes in n) are swept across the junction by the field.', 'अल्पसंख्यक वाहक (p में इलेक्ट्रॉन, n में होल) क्षेत्र द्वारा संधि के पार धकेले जाते हैं।', 'ಅಲ್ಪಸಂಖ್ಯಾತ ವಾಹಕಗಳು (p ಯಲ್ಲಿ ಎಲೆಕ್ಟ್ರಾನ್, n ನಲ್ಲಿ ರಂಧ್ರ) ಕ್ಷೇತ್ರದಿಂದ ಸಂಧಿಯ ಆಚೆ ತಳ್ಳಲ್ಪಡುತ್ತವೆ.')),
              Q(W('What is the dynamic resistance of a diode?', 'डायोड का गतिक प्रतिरोध क्या है?', 'ಡಯೋಡ್‌ನ ಚಲನಶೀಲ ರೋಧ ಎಂದರೇನು?'),
                W('ΔV ÷ ΔI at a point on the curve: small in forward bias above the knee.', 'वक्र के किसी बिंदु पर ΔV ÷ ΔI: घुटने के ऊपर अग्र अभिनति में यह छोटा होता है।', 'ವಕ್ರದ ಒಂದು ಬಿಂದುವಿನಲ್ಲಿ ΔV ÷ ΔI: ನೀ ಮೇಲೆ ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಇದು ಸಣ್ಣದು.')),
              Q(W('Which side of the diode is marked by the band?', 'डायोड पर पट्टी किस सिरे को दर्शाती है?', 'ಡಯೋಡ್ ಮೇಲಿನ ಪಟ್ಟಿ ಯಾವ ತುದಿಯನ್ನು ಸೂಚಿಸುತ್ತದೆ?'),
                W('The cathode (n side).', 'कैथोड (n सिरा)।', 'ಕ್ಯಾಥೋಡ್ (n ಭಾಗ).'))],
    )

    lab(
        id='zener-diode', bench='diode', setup={'device': 'zener', 'bias': 'rev'}, subject='Electronics', domain='electronics', levels=[12, 'ug'],
        curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['zener', 'zener diode', 'breakdown', 'voltage regulator', 'reverse breakdown', 'semiconductor electronics'],
        title=W('Characteristics of a Zener diode', 'ज़ेनर डायोड के अभिलक्षण', 'ಜೀನರ್ ಡಯೋಡ್‌ನ ಲಕ್ಷಣಗಳು'),
        summary=W('Reverse-bias a Zener diode and find the voltage at which it breaks down and holds steady.',
                  'ज़ेनर डायोड को पश्च अभिनति दें और वह वोल्टता ज्ञात करें जिस पर यह भंजित होकर स्थिर रहता है।',
                  'ಜೀನರ್ ಡಯೋಡ್‌ಗೆ ಹಿಮ್ಮುಖ ಬಯಾಸ್ ನೀಡಿ, ಅದು ಭಂಜನಗೊಂಡು ಸ್ಥಿರವಾಗುವ ವೋಲ್ಟೇಜ್ ಕಂಡುಹಿಡಿಯಿರಿ.'),
        aim=W('To draw the reverse characteristic of a Zener diode and find its breakdown voltage.',
              'ज़ेनर डायोड का पश्च अभिलक्षण खींचना और उसकी भंजन वोल्टता ज्ञात करना।',
              'ಜೀನರ್ ಡಯೋಡ್‌ನ ಹಿಮ್ಮುಖ ಲಕ್ಷಣ ಎಳೆದು ಅದರ ಭಂಜನ ವೋಲ್ಟೇಜ್ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('A Zener diode is heavily doped, so its depletion layer is thin. At a definite reverse voltage Vz the field breaks covalent bonds and the reverse current rises sharply while the voltage stays almost constant. This is why a Zener is used as a voltage regulator.',
                    'ज़ेनर डायोड भारी मादित होता है, इसलिए उसकी ह्रासी परत पतली होती है। एक निश्चित पश्च वोल्टता Vz पर क्षेत्र सहसंयोजी बंधों को तोड़ देता है और पश्च धारा तेज़ी से बढ़ती है जबकि वोल्टता लगभग स्थिर रहती है। इसीलिए ज़ेनर को वोल्टता नियंत्रक के रूप में प्रयोग करते हैं।',
                    'ಜೀನರ್ ಡಯೋಡ್ ಹೆಚ್ಚು ಡೋಪ್ ಮಾಡಿದ್ದು, ಅದರ ಕ್ಷೀಣ ಪದರ ತೆಳು. ಒಂದು ನಿರ್ದಿಷ್ಟ ಹಿಮ್ಮುಖ ವೋಲ್ಟೇಜ್ Vz ನಲ್ಲಿ ಕ್ಷೇತ್ರವು ಸಹವೇಲೆನ್ಸೀಯ ಬಂಧಗಳನ್ನು ಮುರಿಯುತ್ತದೆ; ಹಿಮ್ಮುಖ ಪ್ರವಾಹ ವೇಗವಾಗಿ ಏರುತ್ತದೆ, ವೋಲ್ಟೇಜ್ ಬಹುತೇಕ ಸ್ಥಿರ. ಆದ್ದರಿಂದ ಜೀನರನ್ನು ವೋಲ್ಟೇಜ್ ನಿಯಂತ್ರಕವಾಗಿ ಬಳಸುತ್ತಾರೆ.'),
        apparatus=[W('Zener diode (3.3, 5.1 or 6.2 V)', 'ज़ेनर डायोड (3.3, 5.1 या 6.2 V)', 'ಜೀನರ್ ಡಯೋಡ್ (3.3, 5.1 ಅಥವಾ 6.2 V)'), SUPPLY, RES, MA, VM, WIRES],
        steps=[W('Connect the Zener in reverse bias: its cathode (band) towards the + of the supply, through the resistor and milliammeter.', 'ज़ेनर को पश्च अभिनति में जोड़ें: उसका कैथोड (पट्टी) प्रतिरोधक और मिलीऐमीटर से होते हुए आपूर्ति के + की ओर।', 'ಜೀನರನ್ನು ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಜೋಡಿಸಿ: ಅದರ ಕ್ಯಾಥೋಡ್ (ಪಟ್ಟಿ) ರೋಧಕ ಮತ್ತು ಮಿಲಿಅಮ್ಮೀಟರ್ ಮೂಲಕ ಪೂರೈಕೆಯ + ಕಡೆಗೆ.'),
               W('Raise the supply slowly from zero and record the voltage across the Zener and the current.', 'आपूर्ति को शून्य से धीरे-धीरे बढ़ाएँ और ज़ेनर के सिरों की वोल्टता तथा धारा लिखें।', 'ಪೂರೈಕೆಯನ್ನು ಶೂನ್ಯದಿಂದ ನಿಧಾನವಾಗಿ ಹೆಚ್ಚಿಸಿ, ಜೀನರ್‌ಗೆ ಅಡ್ಡ ವೋಲ್ಟೇಜ್ ಮತ್ತು ಪ್ರವಾಹ ದಾಖಲಿಸಿ.'),
               W('Near breakdown take readings in small steps; above it, note how little the voltage changes while the current grows.', 'भंजन के पास छोटे चरणों में पाठ्यांक लें; उसके ऊपर देखें कि धारा बढ़ने पर वोल्टता कितनी कम बदलती है।', 'ಭಂಜನದ ಹತ್ತಿರ ಸಣ್ಣ ಹಂತಗಳಲ್ಲಿ ಓದು ತೆಗೆದುಕೊಳ್ಳಿ; ಅದರ ಮೇಲೆ ಪ್ರವಾಹ ಹೆಚ್ಚಿದರೂ ವೋಲ್ಟೇಜ್ ಎಷ್ಟು ಕಡಿಮೆ ಬದಲಾಗುತ್ತದೆ ಗಮನಿಸಿ.'),
               W('Also take a few forward-bias readings.', 'कुछ अग्र अभिनति पाठ्यांक भी लें।', 'ಕೆಲವು ಮುಮ್ಮುಖ ಬಯಾಸ್ ಓದುಗಳನ್ನೂ ತೆಗೆದುಕೊಳ್ಳಿ.'),
               W('Plot I against V and read the breakdown voltage Vz where the reverse curve turns steeply down.', 'I और V का ग्राफ़ बनाएँ और भंजन वोल्टता Vz वहाँ पढ़ें जहाँ पश्च वक्र तेज़ी से नीचे मुड़ता है।', 'I ಮತ್ತು V ನಕ್ಷೆ ಎಳೆದು, ಹಿಮ್ಮುಖ ವಕ್ರ ಕಡಿದಾಗಿ ಕೆಳಗೆ ತಿರುಗುವಲ್ಲಿ ಭಂಜನ ವೋಲ್ಟೇಜ್ Vz ಓದಿ.')],
        precautions=[P_CURRENT, W('Keep the Zener current below its rated maximum (power = Vz × I).', 'ज़ेनर धारा को उसकी अधिकतम सीमा से नीचे रखें (शक्ति = Vz × I)।', 'ಜೀನರ್ ಪ್ರವಾಹವನ್ನು ಅದರ ಗರಿಷ್ಠ ಮಿತಿಗಿಂತ ಕಡಿಮೆ ಇಡಿ (ಶಕ್ತಿ = Vz × I).'), P_POLARITY],
        conclusion=W('In reverse bias the Zener current stays tiny up to Vz; beyond it the current rises sharply at an almost constant voltage, so the Zener can hold a load voltage steady.',
                     'पश्च अभिनति में Vz तक ज़ेनर धारा बहुत छोटी रहती है; उसके बाद लगभग स्थिर वोल्टता पर धारा तेज़ी से बढ़ती है, इसलिए ज़ेनर लोड वोल्टता को स्थिर रख सकता है।',
                     'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ Vz ವರೆಗೆ ಜೀನರ್ ಪ್ರವಾಹ ಅತಿ ಸಣ್ಣ; ಅದರ ಆಚೆ ಬಹುತೇಕ ಸ್ಥಿರ ವೋಲ್ಟೇಜ್‌ನಲ್ಲಿ ಪ್ರವಾಹ ವೇಗವಾಗಿ ಏರುತ್ತದೆ, ಆದ್ದರಿಂದ ಜೀನರ್ ಲೋಡ್ ವೋಲ್ಟೇಜನ್ನು ಸ್ಥಿರವಾಗಿಡಬಲ್ಲದು.'),
        viva=[Q(W('How is a Zener diode different from an ordinary diode?', 'ज़ेनर डायोड साधारण डायोड से कैसे भिन्न है?', 'ಜೀನರ್ ಡಯೋಡ್ ಸಾಮಾನ್ಯ ಡಯೋಡ್‌ಗಿಂತ ಹೇಗೆ ಭಿನ್ನ?'),
                W('It is heavily doped and designed to work safely in reverse breakdown.', 'यह भारी मादित होता है और पश्च भंजन में सुरक्षित काम करने के लिए बना है।', 'ಅದು ಹೆಚ್ಚು ಡೋಪ್ ಮಾಡಲ್ಪಟ್ಟಿದ್ದು ಹಿಮ್ಮುಖ ಭಂಜನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಕೆಲಸ ಮಾಡಲು ವಿನ್ಯಾಸಗೊಂಡಿದೆ.')),
              Q(W('How is a Zener connected as a voltage regulator?', 'वोल्टता नियंत्रक के रूप में ज़ेनर कैसे जोड़ा जाता है?', 'ವೋಲ್ಟೇಜ್ ನಿಯಂತ್ರಕವಾಗಿ ಜೀನರನ್ನು ಹೇಗೆ ಜೋಡಿಸುತ್ತಾರೆ?'),
                W('In reverse bias, in parallel with the load, with a series resistor from the supply.', 'पश्च अभिनति में, लोड के समानांतर, आपूर्ति से एक श्रेणी प्रतिरोधक के साथ।', 'ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ, ಲೋಡ್‌ಗೆ ಸಮಾಂತರವಾಗಿ, ಪೂರೈಕೆಯಿಂದ ಸರಣಿ ರೋಧಕದೊಂದಿಗೆ.')),
              Q(W('What is the dynamic resistance of a Zener after breakdown?', 'भंजन के बाद ज़ेनर का गतिक प्रतिरोध कैसा होता है?', 'ಭಂಜನದ ನಂತರ ಜೀನರ್‌ನ ಚಲನಶೀಲ ರೋಧ ಹೇಗಿರುತ್ತದೆ?'),
                W('Very small: a large change of current makes only a small change of voltage.', 'बहुत छोटा: धारा के बड़े परिवर्तन से वोल्टता में बहुत कम परिवर्तन होता है।', 'ಅತಿ ಸಣ್ಣ: ಪ್ರವಾಹದ ದೊಡ್ಡ ಬದಲಾವಣೆ ವೋಲ್ಟೇಜ್‌ನಲ್ಲಿ ಸ್ವಲ್ಪವೇ ಬದಲಾವಣೆ ತರುತ್ತದೆ.'))],
    )

    lab(
        id='led-characteristics', bench='diode', setup={'device': 'led'}, subject='Electronics', domain='electronics', levels=[12, 'ug'],
        curricula=['cbse', 'ka-puc'],
        keywords=['led', 'light emitting diode', 'optoelectronic devices', 'band gap', 'semiconductor electronics'],
        title=W('I–V characteristics of LEDs', 'LED के I–V अभिलक्षण', 'LED ಗಳ I–V ಲಕ್ಷಣಗಳು'),
        summary=W('Compare red, yellow, green and blue LEDs: each switches on at a different voltage.',
                  'लाल, पीले, हरे और नीले LED की तुलना करें: हर एक अलग वोल्टता पर जलता है।',
                  'ಕೆಂಪು, ಹಳದಿ, ಹಸಿರು ಮತ್ತು ನೀಲಿ LED ಗಳನ್ನು ಹೋಲಿಸಿ: ಪ್ರತಿಯೊಂದೂ ಬೇರೆ ವೋಲ್ಟೇಜ್‌ನಲ್ಲಿ ಬೆಳಗುತ್ತದೆ.'),
        aim=W('To draw the forward I–V characteristics of LEDs of different colours and relate the turn-on voltage to the colour.',
              'विभिन्न रंगों के LED के अग्र I–V अभिलक्षण खींचना और चालू होने की वोल्टता का रंग से संबंध देखना।',
              'ಬೇರೆ ಬೇರೆ ಬಣ್ಣಗಳ LED ಗಳ ಮುಮ್ಮುಖ I–V ಲಕ್ಷಣಗಳನ್ನು ಎಳೆದು, ಆರಂಭ ವೋಲ್ಟೇಜನ್ನು ಬಣ್ಣದೊಂದಿಗೆ ಸಂಬಂಧಿಸುವುದು.'),
        principle=W('In an LED, electrons and holes recombine at the junction and give out photons of energy close to the band gap, E = hc/λ. Light of shorter wavelength (blue) needs a larger band gap, so a blue LED switches on at a higher voltage (about 2.6 V) than a red one (about 1.9 V).',
                    'LED में इलेक्ट्रॉन और होल संधि पर पुनर्संयोजित होकर बैंड अंतराल के निकट ऊर्जा के फ़ोटॉन देते हैं, E = hc/λ. छोटी तरंगदैर्घ्य (नीला) के प्रकाश के लिए बड़ा बैंड अंतराल चाहिए, इसलिए नीला LED लाल (लगभग 1.9 V) से अधिक वोल्टता (लगभग 2.6 V) पर जलता है।',
                    'LED ಯಲ್ಲಿ ಎಲೆಕ್ಟ್ರಾನ್ ಮತ್ತು ರಂಧ್ರಗಳು ಸಂಧಿಯಲ್ಲಿ ಮರುಸಂಯೋಗಗೊಂಡು ಬ್ಯಾಂಡ್ ಅಂತರದ ಹತ್ತಿರದ ಶಕ್ತಿಯ ಫೋಟಾನ್‌ಗಳನ್ನು ನೀಡುತ್ತವೆ, E = hc/λ. ಕಡಿಮೆ ತರಂಗಾಂತರದ (ನೀಲಿ) ಬೆಳಕಿಗೆ ದೊಡ್ಡ ಬ್ಯಾಂಡ್ ಅಂತರ ಬೇಕು; ಆದ್ದರಿಂದ ನೀಲಿ LED ಕೆಂಪಿಗಿಂತ (ಸುಮಾರು 1.9 V) ಹೆಚ್ಚು ವೋಲ್ಟೇಜ್‌ನಲ್ಲಿ (ಸುಮಾರು 2.6 V) ಬೆಳಗುತ್ತದೆ.'),
        apparatus=[W('Red, yellow, green and blue LEDs', 'लाल, पीले, हरे और नीले LED', 'ಕೆಂಪು, ಹಳದಿ, ಹಸಿರು ಮತ್ತು ನೀಲಿ LED ಗಳು'), SUPPLY, RES, MA, VM, WIRES],
        steps=[W('Connect the red LED in forward bias (long leg to +) with the resistor and milliammeter; voltmeter across the LED.', 'लाल LED को अग्र अभिनति में (लंबी टाँग + से) प्रतिरोधक और मिलीऐमीटर के साथ जोड़ें; वोल्टमीटर LED के सिरों पर।', 'ಕೆಂಪು LED ಯನ್ನು ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ (ಉದ್ದ ಕಾಲು + ಗೆ) ರೋಧಕ ಮತ್ತು ಮಿಲಿಅಮ್ಮೀಟರ್ ಜೊತೆ ಜೋಡಿಸಿ; ವೋಲ್ಟ್‌ಮೀಟರ್ LED ಗೆ ಅಡ್ಡಲಾಗಿ.'),
               W('Raise the supply in steps and record V and I; note when the LED starts to glow.', 'आपूर्ति चरणों में बढ़ाएँ और V तथा I लिखें; देखें कि LED कब चमकने लगता है।', 'ಪೂರೈಕೆಯನ್ನು ಹಂತಗಳಲ್ಲಿ ಹೆಚ್ಚಿಸಿ V ಮತ್ತು I ದಾಖಲಿಸಿ; LED ಯಾವಾಗ ಹೊಳೆಯಲು ಆರಂಭಿಸುತ್ತದೆ ಗಮನಿಸಿ.'),
               W('Repeat for the yellow, green and blue LEDs.', 'पीले, हरे और नीले LED के लिए दोहराएँ।', 'ಹಳದಿ, ಹಸಿರು ಮತ್ತು ನೀಲಿ LED ಗಳಿಗೆ ಪುನರಾವರ್ತಿಸಿ.'),
               W('Plot all four curves and compare their knee voltages with hc/λe.', 'चारों वक्र बनाएँ और उनकी घुटना वोल्टताओं की तुलना hc/λe से करें।', 'ನಾಲ್ಕೂ ವಕ್ರಗಳನ್ನು ಎಳೆದು ಅವುಗಳ ನೀ ವೋಲ್ಟೇಜ್‌ಗಳನ್ನು hc/λe ಯೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=[P_CURRENT, W('Do not look straight into a bright LED for long.', 'तेज़ चमकते LED में देर तक सीधे न देखें।', 'ಪ್ರಕಾಶಮಾನ LED ಯೊಳಗೆ ಹೆಚ್ಚು ಹೊತ್ತು ನೇರವಾಗಿ ನೋಡಬೇಡಿ.'), W('An LED breaks down at a small reverse voltage (about 5 V): do not reverse-bias it far.', 'LED छोटी पश्च वोल्टता (लगभग 5 V) पर ही भंजित हो जाता है: उसे अधिक पश्च अभिनति न दें।', 'LED ಸಣ್ಣ ಹಿಮ್ಮುಖ ವೋಲ್ಟೇಜ್‌ನಲ್ಲೇ (ಸುಮಾರು 5 V) ಭಂಜನಗೊಳ್ಳುತ್ತದೆ: ಹೆಚ್ಚು ಹಿಮ್ಮುಖ ಬಯಾಸ್ ನೀಡಬೇಡಿ.')],
        conclusion=W('Each LED conducts and glows only above its knee voltage, and the knee voltage increases from red to blue as the photon energy hc/λ increases.',
                     'हर LED अपनी घुटना वोल्टता के ऊपर ही चालन करता और चमकता है, और फ़ोटॉन ऊर्जा hc/λ बढ़ने के साथ घुटना वोल्टता लाल से नीले की ओर बढ़ती है।',
                     'ಪ್ರತಿ LED ತನ್ನ ನೀ ವೋಲ್ಟೇಜ್ ಮೇಲೆ ಮಾತ್ರ ವಾಹಕವಾಗಿ ಹೊಳೆಯುತ್ತದೆ; ಫೋಟಾನ್ ಶಕ್ತಿ hc/λ ಹೆಚ್ಚಿದಂತೆ ನೀ ವೋಲ್ಟೇಜ್ ಕೆಂಪಿನಿಂದ ನೀಲಿಯತ್ತ ಹೆಚ್ಚುತ್ತದೆ.'),
        viva=[Q(W('Why does a blue LED need more voltage than a red one?', 'नीले LED को लाल से अधिक वोल्टता क्यों चाहिए?', 'ನೀಲಿ LED ಗೆ ಕೆಂಪಿಗಿಂತ ಹೆಚ್ಚು ವೋಲ್ಟೇಜ್ ಏಕೆ ಬೇಕು?'),
                W('Blue photons have more energy (shorter wavelength), so the band gap is larger.', 'नीले फ़ोटॉन की ऊर्जा अधिक (तरंगदैर्घ्य छोटी) है, इसलिए बैंड अंतराल बड़ा है।', 'ನೀಲಿ ಫೋಟಾನ್‌ಗಳಿಗೆ ಹೆಚ್ಚು ಶಕ್ತಿ (ಕಡಿಮೆ ತರಂಗಾಂತರ), ಆದ್ದರಿಂದ ಬ್ಯಾಂಡ್ ಅಂತರ ದೊಡ್ಡದು.')),
              Q(W('Why are LEDs not made of silicon?', 'LED सिलिकॉन से क्यों नहीं बनाए जाते?', 'LED ಗಳನ್ನು ಸಿಲಿಕಾನ್‌ನಿಂದ ಏಕೆ ಮಾಡುವುದಿಲ್ಲ?'),
                W('Silicon has an indirect band gap and gives out heat rather than light; compounds like GaAsP and InGaN are used.', 'सिलिकॉन का बैंड अंतराल अप्रत्यक्ष है और यह प्रकाश की जगह ऊष्मा देता है; GaAsP और InGaN जैसे यौगिक प्रयोग होते हैं।', 'ಸಿಲಿಕಾನ್‌ನ ಬ್ಯಾಂಡ್ ಅಂತರ ಪರೋಕ್ಷ; ಅದು ಬೆಳಕಿಗಿಂತ ಉಷ್ಣ ನೀಡುತ್ತದೆ; GaAsP, InGaN ನಂತಹ ಸಂಯುಕ್ತಗಳನ್ನು ಬಳಸುತ್ತಾರೆ.')),
              Q(W('Why is a resistor always used with an LED?', 'LED के साथ सदा प्रतिरोधक क्यों लगाया जाता है?', 'LED ಜೊತೆ ಯಾವಾಗಲೂ ರೋಧಕ ಏಕೆ ಬಳಸುತ್ತಾರೆ?'),
                W('Above the knee the current rises very steeply; the resistor limits it.', 'घुटने के ऊपर धारा बहुत तेज़ी से बढ़ती है; प्रतिरोधक उसे सीमित करता है।', 'ನೀ ಮೇಲೆ ಪ್ರವಾಹ ಅತಿ ವೇಗವಾಗಿ ಏರುತ್ತದೆ; ರೋಧಕ ಅದನ್ನು ಮಿತಿಗೊಳಿಸುತ್ತದೆ.'))],
    )

    lab(
        id='planck-constant-led', bench='planck', subject='Physics', domain='physics', levels=['ug'], curricula=['ug-physics'],
        keywords=["planck's constant", 'planck constant', 'led', 'photon energy', 'quantum', 'modern physics'],
        title=W("Planck's constant using LEDs", 'LED से प्लांक नियतांक', 'LED ಗಳಿಂದ ಪ್ಲಾಂಕ್ ಸ್ಥಿರಾಂಕ'),
        summary=W('Find the voltage at which LEDs of four colours just glow, and get h from the slope of V against 1/λ.',
                  'चार रंगों के LED जिस वोल्टता पर बस चमकने लगते हैं वह ज्ञात करें, और V तथा 1/λ के ग्राफ़ की प्रवणता से h निकालें।',
                  'ನಾಲ್ಕು ಬಣ್ಣಗಳ LED ಗಳು ಕೇವಲ ಹೊಳೆಯಲಾರಂಭಿಸುವ ವೋಲ್ಟೇಜ್ ಕಂಡುಹಿಡಿದು, V ಮತ್ತು 1/λ ನಕ್ಷೆಯ ಇಳಿಜಾರಿನಿಂದ h ಪಡೆಯಿರಿ.'),
        aim=W("To determine Planck's constant from the threshold voltages of LEDs of known wavelengths.",
              'ज्ञात तरंगदैर्घ्य वाले LED की देहली वोल्टताओं से प्लांक नियतांक ज्ञात करना।',
              'ತಿಳಿದ ತರಂಗಾಂತರದ LED ಗಳ ಹೊಸ್ತಿಲು ವೋಲ್ಟೇಜ್‌ಗಳಿಂದ ಪ್ಲಾಂಕ್ ಸ್ಥಿರಾಂಕ ನಿರ್ಧರಿಸುವುದು.'),
        principle=W('An LED starts to emit when the energy eV given to each electron equals the photon energy: eV = hc/λ. So V = (hc/e)(1/λ): a graph of the threshold voltage against 1/λ is a straight line of slope hc/e, and h = e × slope ÷ c. A small constant offset (the "just glowing" judgement) shifts the intercept but not the slope.',
                    'LED उत्सर्जन तब शुरू करता है जब हर इलेक्ट्रॉन को दी गई ऊर्जा eV फ़ोटॉन ऊर्जा के बराबर हो: eV = hc/λ. इसलिए V = (hc/e)(1/λ): देहली वोल्टता और 1/λ का ग्राफ़ hc/e प्रवणता की सीधी रेखा है, और h = e × प्रवणता ÷ c. एक छोटा स्थिर अंतर ("बस चमकना" का अनुमान) अंतःखंड बदलता है, प्रवणता नहीं।',
                    'ಪ್ರತಿ ಎಲೆಕ್ಟ್ರಾನ್‌ಗೆ ನೀಡಿದ ಶಕ್ತಿ eV ಫೋಟಾನ್ ಶಕ್ತಿಗೆ ಸಮವಾದಾಗ LED ಹೊರಸೂಸಲು ಆರಂಭಿಸುತ್ತದೆ: eV = hc/λ. ಆದ್ದರಿಂದ V = (hc/e)(1/λ): ಹೊಸ್ತಿಲು ವೋಲ್ಟೇಜ್ ಮತ್ತು 1/λ ನಕ್ಷೆ hc/e ಇಳಿಜಾರಿನ ಸರಳರೇಖೆ; h = e × ಇಳಿಜಾರು ÷ c. ಸಣ್ಣ ಸ್ಥಿರ ವ್ಯತ್ಯಾಸ ("ಕೇವಲ ಹೊಳೆಯುವಿಕೆ" ಅಂದಾಜು) ಅಂತಃಖಂಡವನ್ನು ಬದಲಿಸುತ್ತದೆ, ಇಳಿಜಾರನ್ನಲ್ಲ.'),
        apparatus=[W('LEDs of known wavelength (625, 590, 525, 470 nm)', 'ज्ञात तरंगदैर्घ्य वाले LED (625, 590, 525, 470 nm)', 'ತಿಳಿದ ತರಂಗಾಂತರದ LED ಗಳು (625, 590, 525, 470 nm)'),
                   W('DC supply with fine control (0–3.5 V)', 'सूक्ष्म नियंत्रण वाली DC आपूर्ति (0–3.5 V)', 'ಸೂಕ್ಷ್ಮ ನಿಯಂತ್ರಣದ DC ಪೂರೈಕೆ (0–3.5 V)'), RES, MA, W('Digital voltmeter', 'अंकीय वोल्टमीटर', 'ಡಿಜಿಟಲ್ ವೋಲ್ಟ್‌ಮೀಟರ್'),
                   W('A dark box or tube to view the LED', 'LED देखने के लिए अँधेरा बॉक्स या नली', 'LED ನೋಡಲು ಕತ್ತಲ ಪೆಟ್ಟಿಗೆ ಅಥವಾ ಕೊಳವೆ')],
        steps=[W('Connect the first LED in forward bias through the resistor; put the voltmeter across the LED.', 'पहले LED को प्रतिरोधक के साथ अग्र अभिनति में जोड़ें; वोल्टमीटर LED के सिरों पर लगाएँ।', 'ಮೊದಲ LED ಯನ್ನು ರೋಧಕದ ಜೊತೆ ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಜೋಡಿಸಿ; ವೋಲ್ಟ್‌ಮೀಟರ್ LED ಗೆ ಅಡ್ಡಲಾಗಿ.'),
               W('Looking into the dark box, raise the voltage very slowly until the LED just begins to glow. Record that voltage.', 'अँधेरे बॉक्स में देखते हुए वोल्टता बहुत धीरे बढ़ाएँ जब तक LED बस चमकने न लगे। वह वोल्टता लिखें।', 'ಕತ್ತಲ ಪೆಟ್ಟಿಗೆಯೊಳಗೆ ನೋಡುತ್ತಾ LED ಕೇವಲ ಹೊಳೆಯಲಾರಂಭಿಸುವವರೆಗೆ ವೋಲ್ಟೇಜನ್ನು ತುಂಬ ನಿಧಾನವಾಗಿ ಹೆಚ್ಚಿಸಿ. ಆ ವೋಲ್ಟೇಜ್ ದಾಖಲಿಸಿ.'),
               W('Repeat two or three times for each colour and take the mean.', 'हर रंग के लिए दो-तीन बार दोहराएँ और माध्य लें।', 'ಪ್ರತಿ ಬಣ್ಣಕ್ಕೆ ಎರಡು-ಮೂರು ಬಾರಿ ಪುನರಾವರ್ತಿಸಿ ಸರಾಸರಿ ತೆಗೆಯಿರಿ.'),
               W('Plot the threshold voltage against 1/λ and draw the best straight line.', 'देहली वोल्टता और 1/λ का ग्राफ़ बनाकर सर्वोत्तम सीधी रेखा खींचें।', 'ಹೊಸ್ತಿಲು ವೋಲ್ಟೇಜ್ ಮತ್ತು 1/λ ನಕ್ಷೆ ಎಳೆದು ಉತ್ತಮ ಸರಳರೇಖೆ ಎಳೆಯಿರಿ.'),
               W('Find the slope and its uncertainty, then h = e × slope ÷ c.', 'प्रवणता और उसकी अनिश्चितता ज्ञात करें, फिर h = e × प्रवणता ÷ c.', 'ಇಳಿಜಾರು ಮತ್ತು ಅದರ ಅನಿಶ್ಚಿತತೆ ಕಂಡುಹಿಡಿದು, h = e × ಇಳಿಜಾರು ÷ c.'),
               W('Export the readings as CSV for your record book.', 'अपनी रिकॉर्ड पुस्तिका के लिए पाठ्यांक CSV में निर्यात करें।', 'ನಿಮ್ಮ ದಾಖಲೆ ಪುಸ್ತಕಕ್ಕಾಗಿ ಓದುಗಳನ್ನು CSV ಆಗಿ ರಫ್ತು ಮಾಡಿ.')],
        precautions=[W('Judge "just glowing" the same way for every LED, in the dark.', '"बस चमकना" हर LED के लिए अँधेरे में एक ही तरह आँकें।', '"ಕೇವಲ ಹೊಳೆಯುವಿಕೆ"ಯನ್ನು ಪ್ರತಿ LED ಗೆ ಕತ್ತಲಲ್ಲಿ ಒಂದೇ ರೀತಿ ನಿರ್ಣಯಿಸಿ.'), P_CURRENT,
                     W("Use the manufacturer's peak wavelength for each LED.", 'हर LED के लिए निर्माता द्वारा दी गई शिखर तरंगदैर्घ्य लें।', 'ಪ್ರತಿ LED ಗೆ ತಯಾರಕರ ಶಿಖರ ತರಂಗಾಂತರ ಬಳಸಿ.')],
        conclusion=W('The threshold voltage is proportional to 1/λ, and the slope gives Planck’s constant close to 6.63 × 10⁻³⁴ J s, within the uncertainty of the fit.',
                     'देहली वोल्टता 1/λ के अनुक्रमानुपाती है, और प्रवणता से प्लांक नियतांक 6.63 × 10⁻³⁴ J s के निकट, फ़िट की अनिश्चितता के भीतर, मिलता है।',
                     'ಹೊಸ್ತಿಲು ವೋಲ್ಟೇಜ್ 1/λ ಗೆ ಅನುಪಾತೀಯ; ಇಳಿಜಾರು ಪ್ಲಾಂಕ್ ಸ್ಥಿರಾಂಕವನ್ನು 6.63 × 10⁻³⁴ J s ಹತ್ತಿರ, ಹೊಂದಿಕೆಯ ಅನಿಶ್ಚಿತತೆಯೊಳಗೆ ನೀಡುತ್ತದೆ.'),
        viva=[Q(W('What are the units of Planck’s constant?', 'प्लांक नियतांक की इकाई क्या है?', 'ಪ್ಲಾಂಕ್ ಸ್ಥಿರಾಂಕದ ಏಕಮಾನ ಯಾವುದು?'), W('Joule second (J s).', 'जूल सेकंड (J s).', 'ಜೂಲ್ ಸೆಕೆಂಡ್ (J s).')),
              Q(W('Why do we use the slope and not one LED’s voltage?', 'हम एक LED की वोल्टता के बजाय प्रवणता क्यों लेते हैं?', 'ಒಂದು LED ಯ ವೋಲ್ಟೇಜ್ ಬದಲು ಇಳಿಜಾರನ್ನು ಏಕೆ ಬಳಸುತ್ತೇವೆ?'),
                W('A constant error in judging the threshold cancels out of the slope.', 'देहली के अनुमान में स्थिर त्रुटि प्रवणता में से कट जाती है।', 'ಹೊಸ್ತಿಲು ಅಂದಾಜಿನ ಸ್ಥಿರ ದೋಷ ಇಳಿಜಾರಿನಲ್ಲಿ ರದ್ದಾಗುತ್ತದೆ.')),
              Q(W('What is the energy of a 500 nm photon in eV?', '500 nm फ़ोटॉन की ऊर्जा eV में कितनी है?', '500 nm ಫೋಟಾನ್‌ನ ಶಕ್ತಿ eV ಯಲ್ಲಿ ಎಷ್ಟು?'), W('About 2.48 eV (1240 ÷ 500).', 'लगभग 2.48 eV (1240 ÷ 500).', 'ಸುಮಾರು 2.48 eV (1240 ÷ 500).'))],
    )

    # -------------------------------------------------------- rectifiers
    rect_common = dict(subject='Electronics', domain='electronics', levels=[12, 'ug'], curricula=['cbse', 'ncert', 'ka-puc'])
    RECT_STEPS_END = [
        W('Read the DC voltage across the load and look at the output on the CRO.', 'लोड के सिरों की DC वोल्टता पढ़ें और CRO पर निर्गत देखें।', 'ಲೋಡ್‌ಗೆ ಅಡ್ಡ DC ವೋಲ್ಟೇಜ್ ಓದಿ, CRO ನಲ್ಲಿ ಹೊರಹರಿವನ್ನು ನೋಡಿ.'),
        W('Measure the AC ripple voltage across the load and work out the ripple factor γ = Vac ÷ Vdc.', 'लोड के सिरों पर AC ऊर्मिका वोल्टता मापें और ऊर्मिका गुणांक γ = Vac ÷ Vdc निकालें।', 'ಲೋಡ್‌ಗೆ ಅಡ್ಡ AC ತರಂಗ ವೋಲ್ಟೇಜ್ ಅಳೆಯಿರಿ, ತರಂಗ ಅಂಶ γ = Vac ÷ Vdc ಲೆಕ್ಕಿಸಿ.'),
        W('Connect filter capacitors of 100, 470 and 1000 µF across the load in turn and repeat.', 'बारी-बारी से 100, 470 और 1000 µF के फ़िल्टर संधारित्र लोड के सिरों पर जोड़कर दोहराएँ।', 'ಸರದಿಯಾಗಿ 100, 470 ಮತ್ತು 1000 µF ಫಿಲ್ಟರ್ ಧಾರಕಗಳನ್ನು ಲೋಡ್‌ಗೆ ಅಡ್ಡಲಾಗಿ ಜೋಡಿಸಿ ಪುನರಾವರ್ತಿಸಿ.'),
        W('Change the load resistance and see how the ripple changes.', 'लोड प्रतिरोध बदलें और देखें कि ऊर्मिका कैसे बदलती है।', 'ಲೋಡ್ ರೋಧ ಬದಲಿಸಿ ತರಂಗ ಹೇಗೆ ಬದಲಾಗುತ್ತದೆ ನೋಡಿ.'),
    ]
    RECT_PRE = [W('Never touch the 230 V mains side of the transformer.', 'ट्रांसफ़ॉर्मर के 230 V मुख्य सिरे को कभी न छुएँ।', 'ಪರಿವರ್ತಕದ 230 V ಮುಖ್ಯ ಭಾಗವನ್ನು ಎಂದೂ ಮುಟ್ಟಬೇಡಿ.'),
                W('Connect electrolytic capacitors the right way round (+ to the diode side).', 'विद्युत-अपघटनी संधारित्र सही दिशा में जोड़ें (+ डायोड वाले सिरे की ओर)।', 'ವಿದ್ಯುದ್ವಿಭಜಕ ಧಾರಕಗಳನ್ನು ಸರಿಯಾದ ದಿಕ್ಕಿನಲ್ಲಿ ಜೋಡಿಸಿ (+ ಡಯೋಡ್ ಕಡೆ).'),
                W('Use the AC range of the meter for the ripple and the DC range for Vdc.', 'ऊर्मिका के लिए मीटर की AC परास और Vdc के लिए DC परास लें।', 'ತರಂಗಕ್ಕೆ ಮೀಟರ್‌ನ AC ವ್ಯಾಪ್ತಿ, Vdc ಗೆ DC ವ್ಯಾಪ್ತಿ ಬಳಸಿ.')]
    RECT_APP = [TRANS, W('Load resistors (470 Ω, 1 kΩ, 2.2 kΩ)', 'लोड प्रतिरोधक (470 Ω, 1 kΩ, 2.2 kΩ)', 'ಲೋಡ್ ರೋಧಕಗಳು (470 Ω, 1 kΩ, 2.2 kΩ)'),
                W('Electrolytic capacitors (100, 470, 1000 µF)', 'विद्युत-अपघटनी संधारित्र (100, 470, 1000 µF)', 'ವಿದ್ಯುದ್ವಿಭಜಕ ಧಾರಕಗಳು (100, 470, 1000 µF)'),
                W('Multimeter (AC and DC)', 'मल्टीमीटर (AC और DC)', 'ಮಲ್ಟಿಮೀಟರ್ (AC ಮತ್ತು DC)'), CRO, WIRES]
    RECT_VIVA = [Q(W('What is ripple?', 'ऊर्मिका क्या है?', 'ತರಂಗ (ರಿಪಲ್) ಎಂದರೇನು?'),
                   W('The AC part left in the output of a rectifier.', 'दिष्टकारी के निर्गत में बचा AC भाग।', 'ಸರಿಪಡಿಸುವ ಸಾಧನದ ಹೊರಹರಿವಿನಲ್ಲಿ ಉಳಿದ AC ಭಾಗ.')),
                 Q(W('How does a capacitor filter work?', 'संधारित्र फ़िल्टर कैसे काम करता है?', 'ಧಾರಕ ಫಿಲ್ಟರ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ?'),
                   W('It charges to the peak and supplies the load between peaks, discharging slowly through RL.', 'यह शिखर तक आवेशित होकर शिखरों के बीच लोड को धारा देता है और RL से धीरे-धीरे निरावेशित होता है।', 'ಅದು ಶಿಖರದವರೆಗೆ ಆವೇಶಗೊಂಡು ಶಿಖರಗಳ ನಡುವೆ ಲೋಡ್‌ಗೆ ಪ್ರವಾಹ ಒದಗಿಸುತ್ತದೆ; RL ಮೂಲಕ ನಿಧಾನವಾಗಿ ವಿಸರ್ಜನೆಯಾಗುತ್ತದೆ.'))]

    lab(id='half-wave-rectifier', bench='rectifier', setup={'type': 'half'}, **rect_common,
        keywords=['rectifier', 'half-wave rectifier', 'half wave rectifier', 'diode as a rectifier', 'ripple factor', 'filter'],
        title=W('Half-wave rectifier', 'अर्ध-तरंग दिष्टकारी', 'ಅರ್ಧ-ತರಂಗ ಸರಿಪಡಿಸುವ ಸಾಧನ'),
        summary=W('One diode passes only the positive half-cycles of AC; see the output on a CRO and smooth it with a capacitor.',
                  'एक डायोड AC के केवल धनात्मक अर्ध-चक्र जाने देता है; CRO पर निर्गत देखें और संधारित्र से उसे समतल करें।',
                  'ಒಂದು ಡಯೋಡ್ AC ಯ ಧನಾತ್ಮಕ ಅರ್ಧ-ಚಕ್ರಗಳನ್ನು ಮಾತ್ರ ಬಿಡುತ್ತದೆ; CRO ನಲ್ಲಿ ಹೊರಹರಿವು ನೋಡಿ, ಧಾರಕದಿಂದ ಅದನ್ನು ನಯಗೊಳಿಸಿ.'),
        aim=W('To study a half-wave rectifier, find its DC output and ripple factor with and without a capacitor filter.',
              'अर्ध-तरंग दिष्टकारी का अध्ययन करना, संधारित्र फ़िल्टर के साथ और बिना उसका DC निर्गत और ऊर्मिका गुणांक ज्ञात करना।',
              'ಅರ್ಧ-ತರಂಗ ಸರಿಪಡಿಸುವ ಸಾಧನವನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ, ಧಾರಕ ಫಿಲ್ಟರ್ ಸಹಿತ ಮತ್ತು ರಹಿತ ಅದರ DC ಹೊರಹರಿವು ಮತ್ತು ತರಂಗ ಅಂಶ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('A diode conducts only when forward-biased, so it passes the positive half-cycles and blocks the negative ones. The output is pulsating DC with Vdc = Vm/π and ripple factor γ = 1.21. A capacitor across the load reduces the ripple to about 1/(2√3 f RL C).',
                    'डायोड केवल अग्र अभिनति में चालन करता है, इसलिए धनात्मक अर्ध-चक्र जाने देता है और ऋणात्मक रोक देता है। निर्गत स्पंदित DC है जिसमें Vdc = Vm/π और ऊर्मिका गुणांक γ = 1.21. लोड के सिरों पर संधारित्र ऊर्मिका को लगभग 1/(2√3 f RL C) तक घटा देता है।',
                    'ಡಯೋಡ್ ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿ ಮಾತ್ರ ವಾಹಕ; ಆದ್ದರಿಂದ ಧನಾತ್ಮಕ ಅರ್ಧ-ಚಕ್ರಗಳನ್ನು ಬಿಟ್ಟು ಋಣಾತ್ಮಕವನ್ನು ತಡೆಯುತ್ತದೆ. ಹೊರಹರಿವು ಸ್ಪಂದಿಸುವ DC: Vdc = Vm/π, ತರಂಗ ಅಂಶ γ = 1.21. ಲೋಡ್‌ಗೆ ಅಡ್ಡ ಧಾರಕ ತರಂಗವನ್ನು ಸುಮಾರು 1/(2√3 f RL C) ಗೆ ಇಳಿಸುತ್ತದೆ.'),
        apparatus=[W('Silicon diode (1N4007)', 'सिलिकॉन डायोड (1N4007)', 'ಸಿಲಿಕಾನ್ ಡಯೋಡ್ (1N4007)')] + RECT_APP,
        steps=[W('Connect the transformer secondary, the diode and the load resistor in series.', 'ट्रांसफ़ॉर्मर की द्वितीयक कुंडली, डायोड और लोड प्रतिरोधक को श्रेणी में जोड़ें।', 'ಪರಿವರ್ತಕದ ದ್ವಿತೀಯಕ ಸುರುಳಿ, ಡಯೋಡ್ ಮತ್ತು ಲೋಡ್ ರೋಧಕವನ್ನು ಸರಣಿಯಲ್ಲಿ ಜೋಡಿಸಿ.'),
               W('Show the input and the output together on the two channels of the CRO.', 'CRO के दो चैनलों पर निवेश और निर्गत साथ-साथ दिखाएँ।', 'CRO ಯ ಎರಡು ಚಾನಲ್‌ಗಳಲ್ಲಿ ಒಳಹರಿವು ಮತ್ತು ಹೊರಹರಿವನ್ನು ಜೊತೆಯಾಗಿ ತೋರಿಸಿ.')] + RECT_STEPS_END,
        precautions=RECT_PRE,
        conclusion=W('The half-wave rectifier passes only alternate half-cycles; without a filter the ripple factor is about 1.21, and a capacitor makes the output much smoother and raises Vdc towards the peak.',
                     'अर्ध-तरंग दिष्टकारी केवल एकांतर अर्ध-चक्र जाने देता है; बिना फ़िल्टर ऊर्मिका गुणांक लगभग 1.21 है, और संधारित्र निर्गत को बहुत समतल कर Vdc को शिखर की ओर बढ़ाता है।',
                     'ಅರ್ಧ-ತರಂಗ ಸಾಧನ ಪರ್ಯಾಯ ಅರ್ಧ-ಚಕ್ರಗಳನ್ನು ಮಾತ್ರ ಬಿಡುತ್ತದೆ; ಫಿಲ್ಟರ್ ಇಲ್ಲದೆ ತರಂಗ ಅಂಶ ಸುಮಾರು 1.21; ಧಾರಕ ಹೊರಹರಿವನ್ನು ಬಹಳ ನಯಗೊಳಿಸಿ Vdc ಯನ್ನು ಶಿಖರದತ್ತ ಏರಿಸುತ್ತದೆ.'),
        viva=RECT_VIVA + [Q(W('What is the efficiency of a half-wave rectifier at most?', 'अर्ध-तरंग दिष्टकारी की अधिकतम दक्षता कितनी है?', 'ಅರ್ಧ-ತರಂಗ ಸಾಧನದ ಗರಿಷ್ಠ ದಕ್ಷತೆ ಎಷ್ಟು?'), W('40.6 %.', '40.6 %.', '40.6 %.'))])

    lab(id='full-wave-rectifier', bench='rectifier', setup={'type': 'centre'}, **rect_common,
        keywords=['rectifier', 'full-wave rectifier', 'full wave rectifier', 'centre-tap', 'center tap', 'ripple factor', 'diode as a rectifier'],
        title=W('Full-wave rectifier (centre-tap)', 'पूर्ण-तरंग दिष्टकारी (मध्य-निष्कासित)', 'ಪೂರ್ಣ-ತರಂಗ ಸರಿಪಡಿಸುವ ಸಾಧನ (ಮಧ್ಯ-ಟ್ಯಾಪ್)'),
        summary=W('Two diodes and a centre-tapped transformer use both half-cycles; compare the ripple with the half-wave rectifier.',
                  'दो डायोड और मध्य-निष्कासित ट्रांसफ़ॉर्मर दोनों अर्ध-चक्रों का उपयोग करते हैं; ऊर्मिका की तुलना अर्ध-तरंग दिष्टकारी से करें।',
                  'ಎರಡು ಡಯೋಡ್‌ಗಳು ಮತ್ತು ಮಧ್ಯ-ಟ್ಯಾಪ್ ಪರಿವರ್ತಕ ಎರಡೂ ಅರ್ಧ-ಚಕ್ರಗಳನ್ನು ಬಳಸುತ್ತವೆ; ತರಂಗವನ್ನು ಅರ್ಧ-ತರಂಗ ಸಾಧನದೊಂದಿಗೆ ಹೋಲಿಸಿ.'),
        aim=W('To study a centre-tap full-wave rectifier and find its DC output and ripple factor with and without a filter.',
              'मध्य-निष्कासित पूर्ण-तरंग दिष्टकारी का अध्ययन करना और फ़िल्टर के साथ तथा बिना उसका DC निर्गत और ऊर्मिका गुणांक ज्ञात करना।',
              'ಮಧ್ಯ-ಟ್ಯಾಪ್ ಪೂರ್ಣ-ತರಂಗ ಸಾಧನವನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ, ಫಿಲ್ಟರ್ ಸಹಿತ ಮತ್ತು ರಹಿತ ಅದರ DC ಹೊರಹರಿವು ಮತ್ತು ತರಂಗ ಅಂಶ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('The two ends of the secondary are in opposite phase. In one half-cycle D1 conducts, in the other D2, and both send current through the load in the same direction. Vdc = 2Vm/π and γ = 0.48; the ripple is at 100 Hz, so a capacitor smooths it twice as well as in the half-wave case.',
                    'द्वितीयक के दोनों सिरे विपरीत कला में होते हैं। एक अर्ध-चक्र में D1 और दूसरे में D2 चालन करता है, और दोनों लोड में एक ही दिशा में धारा भेजते हैं। Vdc = 2Vm/π और γ = 0.48; ऊर्मिका 100 Hz की होती है, इसलिए संधारित्र उसे अर्ध-तरंग की तुलना में दोगुना अच्छा समतल करता है।',
                    'ದ್ವಿತೀಯಕದ ಎರಡು ತುದಿಗಳು ವಿರುದ್ಧ ಹಂತದಲ್ಲಿರುತ್ತವೆ. ಒಂದು ಅರ್ಧ-ಚಕ್ರದಲ್ಲಿ D1, ಇನ್ನೊಂದರಲ್ಲಿ D2 ವಾಹಕ; ಎರಡೂ ಲೋಡ್‌ನಲ್ಲಿ ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಪ್ರವಾಹ ಕಳುಹಿಸುತ್ತವೆ. Vdc = 2Vm/π, γ = 0.48; ತರಂಗ 100 Hz ನದು, ಆದ್ದರಿಂದ ಧಾರಕ ಅರ್ಧ-ತರಂಗಕ್ಕಿಂತ ಎರಡು ಪಟ್ಟು ಚೆನ್ನಾಗಿ ನಯಗೊಳಿಸುತ್ತದೆ.'),
        apparatus=[W('Two silicon diodes', 'दो सिलिकॉन डायोड', 'ಎರಡು ಸಿಲಿಕಾನ್ ಡಯೋಡ್‌ಗಳು'), W('Centre-tapped transformer (6-0-6, 9-0-9 or 12-0-12 V)', 'मध्य-निष्कासित ट्रांसफ़ॉर्मर (6-0-6, 9-0-9 या 12-0-12 V)', 'ಮಧ್ಯ-ಟ್ಯಾಪ್ ಪರಿವರ್ತಕ (6-0-6, 9-0-9 ಅಥವಾ 12-0-12 V)')] + RECT_APP[1:],
        steps=[W('Connect each end of the secondary to the anode of a diode; join the cathodes to one end of the load; the other end of the load goes to the centre tap.', 'द्वितीयक के हर सिरे को एक डायोड के ऐनोड से जोड़ें; कैथोडों को लोड के एक सिरे से जोड़ें; लोड का दूसरा सिरा मध्य-निष्कास से।', 'ದ್ವಿತೀಯಕದ ಪ್ರತಿ ತುದಿಯನ್ನು ಒಂದು ಡಯೋಡ್‌ನ ಆನೋಡ್‌ಗೆ ಜೋಡಿಸಿ; ಕ್ಯಾಥೋಡ್‌ಗಳನ್ನು ಲೋಡ್‌ನ ಒಂದು ತುದಿಗೆ ಸೇರಿಸಿ; ಲೋಡ್‌ನ ಇನ್ನೊಂದು ತುದಿ ಮಧ್ಯ-ಟ್ಯಾಪ್‌ಗೆ.'),
               W('Show one half of the secondary and the output on the CRO.', 'CRO पर द्वितीयक का एक भाग और निर्गत दिखाएँ।', 'CRO ನಲ್ಲಿ ದ್ವಿತೀಯಕದ ಒಂದು ಅರ್ಧ ಮತ್ತು ಹೊರಹರಿವು ತೋರಿಸಿ.')] + RECT_STEPS_END,
        precautions=RECT_PRE,
        conclusion=W('Both half-cycles reach the load, so the DC output is about twice that of a half-wave rectifier and the ripple factor falls to about 0.48; with a capacitor the output is nearly steady DC.',
                     'दोनों अर्ध-चक्र लोड तक पहुँचते हैं, इसलिए DC निर्गत अर्ध-तरंग का लगभग दोगुना होता है और ऊर्मिका गुणांक लगभग 0.48 रह जाता है; संधारित्र के साथ निर्गत लगभग स्थिर DC है।',
                     'ಎರಡೂ ಅರ್ಧ-ಚಕ್ರಗಳು ಲೋಡ್ ತಲುಪುತ್ತವೆ; DC ಹೊರಹರಿವು ಅರ್ಧ-ತರಂಗದ ಸುಮಾರು ಎರಡು ಪಟ್ಟು, ತರಂಗ ಅಂಶ ಸುಮಾರು 0.48; ಧಾರಕದೊಂದಿಗೆ ಹೊರಹರಿವು ಬಹುತೇಕ ಸ್ಥಿರ DC.'),
        viva=RECT_VIVA + [Q(W('What is the ripple frequency of a full-wave rectifier on 50 Hz mains?', '50 Hz मुख्य आपूर्ति पर पूर्ण-तरंग दिष्टकारी की ऊर्मिका आवृत्ति कितनी है?', '50 Hz ಮುಖ್ಯ ಪೂರೈಕೆಯಲ್ಲಿ ಪೂರ್ಣ-ತರಂಗ ಸಾಧನದ ತರಂಗ ಆವರ್ತನ ಎಷ್ಟು?'), W('100 Hz.', '100 Hz.', '100 Hz.'))])

    lab(id='bridge-rectifier', bench='rectifier', setup={'type': 'bridge', 'cap': 470.0}, **rect_common,
        keywords=['rectifier', 'bridge rectifier', 'full-wave rectifier', 'filter', 'capacitor filter', 'ripple factor', 'power supply'],
        title=W('Bridge rectifier with a capacitor filter', 'संधारित्र फ़िल्टर सहित सेतु दिष्टकारी', 'ಧಾರಕ ಫಿಲ್ಟರ್ ಸಹಿತ ಸೇತು ಸರಿಪಡಿಸುವ ಸಾಧನ'),
        summary=W('Four diodes in a bridge make full-wave DC without a centre tap; see how the filter capacitor fills the gaps.',
                  'सेतु में चार डायोड बिना मध्य-निष्कास के पूर्ण-तरंग DC बनाते हैं; देखें कि फ़िल्टर संधारित्र अंतराल कैसे भरता है।',
                  'ಸೇತುವಿನಲ್ಲಿ ನಾಲ್ಕು ಡಯೋಡ್‌ಗಳು ಮಧ್ಯ-ಟ್ಯಾಪ್ ಇಲ್ಲದೆ ಪೂರ್ಣ-ತರಂಗ DC ನೀಡುತ್ತವೆ; ಫಿಲ್ಟರ್ ಧಾರಕ ಅಂತರಗಳನ್ನು ಹೇಗೆ ತುಂಬುತ್ತದೆ ನೋಡಿ.'),
        aim=W('To study a bridge rectifier and the effect of a capacitor filter and the load on its ripple.',
              'सेतु दिष्टकारी का तथा उसकी ऊर्मिका पर संधारित्र फ़िल्टर और लोड के प्रभाव का अध्ययन करना।',
              'ಸೇತು ಸರಿಪಡಿಸುವ ಸಾಧನ ಮತ್ತು ಅದರ ತರಂಗದ ಮೇಲೆ ಧಾರಕ ಫಿಲ್ಟರ್ ಹಾಗೂ ಲೋಡ್‌ನ ಪರಿಣಾಮವನ್ನು ಅಧ್ಯಯನ ಮಾಡುವುದು.'),
        principle=W('In each half-cycle two opposite diodes of the bridge conduct in series and send current the same way through the load. Two diode drops (about 1.4 V) are lost. With a capacitor C across RL, the ripple factor is about 1/(4√3 f RL C): larger C or larger RL give smoother DC.',
                    'हर अर्ध-चक्र में सेतु के दो सामने वाले डायोड श्रेणी में चालन करते हैं और लोड में एक ही दिशा में धारा भेजते हैं। दो डायोड पात (लगभग 1.4 V) खो जाते हैं। RL के सिरों पर संधारित्र C होने पर ऊर्मिका गुणांक लगभग 1/(4√3 f RL C) है: बड़ा C या बड़ा RL अधिक समतल DC देता है।',
                    'ಪ್ರತಿ ಅರ್ಧ-ಚಕ್ರದಲ್ಲಿ ಸೇತುವಿನ ಎರಡು ಎದುರು ಡಯೋಡ್‌ಗಳು ಸರಣಿಯಲ್ಲಿ ವಾಹಕವಾಗಿ ಲೋಡ್‌ನಲ್ಲಿ ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಪ್ರವಾಹ ಕಳುಹಿಸುತ್ತವೆ. ಎರಡು ಡಯೋಡ್ ಇಳಿತಗಳು (ಸುಮಾರು 1.4 V) ನಷ್ಟ. RL ಗೆ ಅಡ್ಡ ಧಾರಕ C ಇದ್ದರೆ ತರಂಗ ಅಂಶ ಸುಮಾರು 1/(4√3 f RL C): ದೊಡ್ಡ C ಅಥವಾ ದೊಡ್ಡ RL ಹೆಚ್ಚು ನಯವಾದ DC ನೀಡುತ್ತದೆ.'),
        apparatus=[W('Four silicon diodes (or a bridge module)', 'चार सिलिकॉन डायोड (या सेतु मॉड्यूल)', 'ನಾಲ್ಕು ಸಿಲಿಕಾನ್ ಡಯೋಡ್‌ಗಳು (ಅಥವಾ ಸೇತು ಮಾಡ್ಯೂಲ್)')] + RECT_APP,
        steps=[W('Arrange the four diodes in a bridge: AC to the two junctions where an anode meets a cathode; take DC from the cathode-cathode (+) and anode-anode (−) junctions.', 'चार डायोडों को सेतु में लगाएँ: AC उन दो संधियों पर जहाँ ऐनोड कैथोड से मिलता है; DC कैथोड-कैथोड (+) और ऐनोड-ऐनोड (−) संधियों से लें।', 'ನಾಲ್ಕು ಡಯೋಡ್‌ಗಳನ್ನು ಸೇತುವಾಗಿ ಜೋಡಿಸಿ: ಆನೋಡ್ ಕ್ಯಾಥೋಡನ್ನು ಸೇರುವ ಎರಡು ಸಂಧಿಗಳಿಗೆ AC; ಕ್ಯಾಥೋಡ್-ಕ್ಯಾಥೋಡ್ (+) ಮತ್ತು ಆನೋಡ್-ಆನೋಡ್ (−) ಸಂಧಿಗಳಿಂದ DC.'),
               W('Start without the capacitor and compare input and output on the CRO.', 'संधारित्र के बिना शुरू करें और CRO पर निवेश तथा निर्गत की तुलना करें।', 'ಧಾರಕವಿಲ್ಲದೆ ಆರಂಭಿಸಿ CRO ನಲ್ಲಿ ಒಳಹರಿವು-ಹೊರಹರಿವು ಹೋಲಿಸಿ.')] + RECT_STEPS_END,
        precautions=RECT_PRE,
        conclusion=W('The bridge gives full-wave rectification from an ordinary secondary at the cost of two diode drops; the filter capacitor cuts the ripple factor to a few per cent, and less ripple comes with a larger C or a lighter load.',
                     'सेतु दो डायोड पात की क़ीमत पर साधारण द्वितीयक से पूर्ण-तरंग दिष्टकरण देता है; फ़िल्टर संधारित्र ऊर्मिका गुणांक को कुछ प्रतिशत तक घटा देता है, और बड़े C या हल्के लोड से ऊर्मिका कम होती है।',
                     'ಸೇತು ಎರಡು ಡಯೋಡ್ ಇಳಿತಗಳ ವೆಚ್ಚದಲ್ಲಿ ಸಾಮಾನ್ಯ ದ್ವಿತೀಯಕದಿಂದ ಪೂರ್ಣ-ತರಂಗ ಸರಿಪಡಿಸುವಿಕೆ ನೀಡುತ್ತದೆ; ಫಿಲ್ಟರ್ ಧಾರಕ ತರಂಗ ಅಂಶವನ್ನು ಕೆಲವು ಶೇಕಡಕ್ಕೆ ಇಳಿಸುತ್ತದೆ; ದೊಡ್ಡ C ಅಥವಾ ಹಗುರ ಲೋಡ್ ತರಂಗ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.'),
        viva=RECT_VIVA + [Q(W('Why is the peak output of a bridge about 1.4 V less than the input peak?', 'सेतु का शिखर निर्गत निवेश शिखर से लगभग 1.4 V कम क्यों होता है?', 'ಸೇತುವಿನ ಶಿಖರ ಹೊರಹರಿವು ಒಳಹರಿವಿನ ಶಿಖರಕ್ಕಿಂತ ಸುಮಾರು 1.4 V ಕಡಿಮೆ ಏಕೆ?'),
                                W('Current passes through two diodes in series in each half-cycle.', 'हर अर्ध-चक्र में धारा श्रेणी में दो डायोडों से होकर जाती है।', 'ಪ್ರತಿ ಅರ್ಧ-ಚಕ್ರದಲ್ಲಿ ಪ್ರವಾಹ ಸರಣಿಯ ಎರಡು ಡಯೋಡ್‌ಗಳ ಮೂಲಕ ಹೋಗುತ್ತದೆ.'))])

    # ------------------------------------------------------- transistor
    lab(
        id='transistor-ce', bench='transistor', subject='Electronics', domain='electronics', levels=[12, 'ug'], curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['transistor', 'npn transistor', 'common emitter', 'characteristics', 'current gain', 'amplifier', 'semiconductor electronics'],
        title=W('Characteristics of an NPN transistor (CE)', 'NPN ट्रांज़िस्टर के अभिलक्षण (उभयनिष्ठ उत्सर्जक)', 'NPN ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ನ ಲಕ್ಷಣಗಳು (ಸಾಮಾನ್ಯ ಉತ್ಸರ್ಜಕ)'),
        summary=W('Plot the input and output characteristics of a transistor in common-emitter mode and find its current gain β.',
                  'उभयनिष्ठ उत्सर्जक विन्यास में ट्रांज़िस्टर के निवेश और निर्गत अभिलक्षण बनाएँ और उसकी धारा लब्धि β ज्ञात करें।',
                  'ಸಾಮಾನ್ಯ ಉತ್ಸರ್ಜಕ ವಿನ್ಯಾಸದಲ್ಲಿ ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ನ ಒಳಹರಿವು ಮತ್ತು ಹೊರಹರಿವು ಲಕ್ಷಣಗಳನ್ನು ಎಳೆದು ಅದರ ಪ್ರವಾಹ ಲಾಭ β ಕಂಡುಹಿಡಿಯಿರಿ.'),
        aim=W('To draw the input and output characteristics of an NPN transistor in CE configuration and find its current gain.',
              'उभयनिष्ठ उत्सर्जक विन्यास में NPN ट्रांज़िस्टर के निवेश और निर्गत अभिलक्षण खींचना और उसकी धारा लब्धि ज्ञात करना।',
              'ಸಾಮಾನ್ಯ ಉತ್ಸರ್ಜಕ ವಿನ್ಯಾಸದಲ್ಲಿ NPN ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ನ ಒಳಹರಿವು ಮತ್ತು ಹೊರಹರಿವು ಲಕ್ಷಣಗಳನ್ನು ಎಳೆದು ಅದರ ಪ್ರವಾಹ ಲಾಭ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('The base-emitter junction is forward-biased and behaves like a diode (input characteristic: Ib against Vbe). With the collector-base junction reverse-biased, the collector current is about β times the base current and hardly changes with Vce (output characteristic: Ic against Vce at fixed Ib). β = Ic ÷ Ib (dc) or ΔIc ÷ ΔIb (ac).',
                    'आधार-उत्सर्जक संधि अग्र अभिनत होती है और डायोड जैसा व्यवहार करती है (निवेश अभिलक्षण: Ib और Vbe)। संग्राहक-आधार संधि पश्च अभिनत होने पर संग्राहक धारा आधार धारा की लगभग β गुनी होती है और Vce के साथ बहुत कम बदलती है (निर्गत अभिलक्षण: नियत Ib पर Ic और Vce)। β = Ic ÷ Ib (dc) या ΔIc ÷ ΔIb (ac).',
                    'ಆಧಾರ-ಉತ್ಸರ್ಜಕ ಸಂಧಿ ಮುಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿದ್ದು ಡಯೋಡ್‌ನಂತೆ ವರ್ತಿಸುತ್ತದೆ (ಒಳಹರಿವು ಲಕ್ಷಣ: Ib ಮತ್ತು Vbe). ಸಂಗ್ರಾಹಕ-ಆಧಾರ ಸಂಧಿ ಹಿಮ್ಮುಖ ಬಯಾಸ್‌ನಲ್ಲಿದ್ದಾಗ ಸಂಗ್ರಾಹಕ ಪ್ರವಾಹ ಆಧಾರ ಪ್ರವಾಹದ ಸುಮಾರು β ಪಟ್ಟು, Vce ಯೊಂದಿಗೆ ಬಹಳ ಕಡಿಮೆ ಬದಲಾಗುತ್ತದೆ (ಹೊರಹರಿವು ಲಕ್ಷಣ: ಸ್ಥಿರ Ib ನಲ್ಲಿ Ic ಮತ್ತು Vce). β = Ic ÷ Ib (dc) ಅಥವಾ ΔIc ÷ ΔIb (ac).'),
        apparatus=[W('NPN transistor (BC547)', 'NPN ट्रांज़िस्टर (BC547)', 'NPN ಟ್ರಾನ್ಸಿಸ್ಟರ್ (BC547)'), W('Two variable DC supplies (Vbb and Vcc)', 'दो परिवर्ती DC आपूर्तियाँ (Vbb और Vcc)', 'ಎರಡು ಬದಲಾಯಿಸಬಹುದಾದ DC ಪೂರೈಕೆಗಳು (Vbb ಮತ್ತು Vcc)'),
                   W('Microammeter and milliammeter', 'माइक्रोऐमीटर और मिलीऐमीटर', 'ಮೈಕ್ರೋಅಮ್ಮೀಟರ್ ಮತ್ತು ಮಿಲಿಅಮ್ಮೀಟರ್'), W('Two voltmeters', 'दो वोल्टमीटर', 'ಎರಡು ವೋಲ್ಟ್‌ಮೀಟರ್‌ಗಳು'), W('Base and collector resistors', 'आधार और संग्राहक प्रतिरोधक', 'ಆಧಾರ ಮತ್ತು ಸಂಗ್ರಾಹಕ ರೋಧಕಗಳು'), WIRES],
        steps=[W('Identify the emitter, base and collector. Connect the circuit with the emitter common to the input and output.', 'उत्सर्जक, आधार और संग्राहक पहचानें। परिपथ ऐसे जोड़ें कि उत्सर्जक निवेश और निर्गत दोनों में उभयनिष्ठ हो।', 'ಉತ್ಸರ್ಜಕ, ಆಧಾರ ಮತ್ತು ಸಂಗ್ರಾಹಕ ಗುರುತಿಸಿ. ಉತ್ಸರ್ಜಕ ಒಳಹರಿವು ಮತ್ತು ಹೊರಹರಿವಿಗೆ ಸಾಮಾನ್ಯವಾಗಿರುವಂತೆ ಮಂಡಲ ಜೋಡಿಸಿ.'),
               W('Input characteristic: keep Vce fixed (1 V or 5 V); raise Vbb and record Ib and Vbe.', 'निवेश अभिलक्षण: Vce नियत (1 V या 5 V) रखें; Vbb बढ़ाएँ और Ib तथा Vbe लिखें।', 'ಒಳಹರಿವು ಲಕ್ಷಣ: Vce ಸ್ಥಿರ (1 V ಅಥವಾ 5 V); Vbb ಹೆಚ್ಚಿಸಿ Ib ಮತ್ತು Vbe ದಾಖಲಿಸಿ.'),
               W('Output characteristic: set a base current (say 20 µA); raise Vcc and record Vce and Ic.', 'निर्गत अभिलक्षण: एक आधार धारा (मान लें 20 µA) तय करें; Vcc बढ़ाएँ और Vce तथा Ic लिखें।', 'ಹೊರಹರಿವು ಲಕ್ಷಣ: ಒಂದು ಆಧಾರ ಪ್ರವಾಹ (ಉದಾ. 20 µA) ಹೊಂದಿಸಿ; Vcc ಹೆಚ್ಚಿಸಿ Vce ಮತ್ತು Ic ದಾಖಲಿಸಿ.'),
               W('Repeat the output readings for 10, 30 and 40 µA.', '10, 30 और 40 µA के लिए निर्गत पाठ्यांक दोहराएँ।', '10, 30 ಮತ್ತು 40 µA ಗೆ ಹೊರಹರಿವು ಓದುಗಳನ್ನು ಪುನರಾವರ್ತಿಸಿ.'),
               W('Plot both families of curves and find β = ΔIc ÷ ΔIb at a fixed Vce in the active region.', 'वक्रों के दोनों समूह बनाएँ और सक्रिय क्षेत्र में नियत Vce पर β = ΔIc ÷ ΔIb ज्ञात करें।', 'ಎರಡೂ ವಕ್ರ ಕುಟುಂಬಗಳನ್ನು ಎಳೆದು, ಸಕ್ರಿಯ ಪ್ರದೇಶದಲ್ಲಿ ಸ್ಥಿರ Vce ಯಲ್ಲಿ β = ΔIc ÷ ΔIb ಕಂಡುಹಿಡಿಯಿರಿ.')],
        precautions=[W('Keep Ic and Vce within the transistor’s ratings.', 'Ic और Vce को ट्रांज़िस्टर की सीमाओं के भीतर रखें।', 'Ic ಮತ್ತು Vce ಯನ್ನು ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ನ ಮಿತಿಯೊಳಗಿಡಿ.'), P_POLARITY,
                     W('Hold the base current constant while taking each output curve.', 'हर निर्गत वक्र लेते समय आधार धारा नियत रखें।', 'ಪ್ರತಿ ಹೊರಹರಿವು ವಕ್ರ ತೆಗೆಯುವಾಗ ಆಧಾರ ಪ್ರವಾಹ ಸ್ಥಿರವಾಗಿರಲಿ.')],
        conclusion=W('The input characteristic is like a forward-biased diode; in the output characteristic Ic rises quickly at very small Vce (saturation) and then stays nearly flat (active region), with Ic about β times Ib.',
                     'निवेश अभिलक्षण अग्र अभिनत डायोड जैसा है; निर्गत अभिलक्षण में बहुत छोटे Vce पर Ic तेज़ी से बढ़ता है (संतृप्ति) और फिर लगभग समतल रहता है (सक्रिय क्षेत्र), जहाँ Ic लगभग Ib का β गुना है।',
                     'ಒಳಹರಿವು ಲಕ್ಷಣ ಮುಮ್ಮುಖ ಬಯಾಸ್ ಡಯೋಡ್‌ನಂತೆ; ಹೊರಹರಿವು ಲಕ್ಷಣದಲ್ಲಿ ಅತಿ ಸಣ್ಣ Vce ಯಲ್ಲಿ Ic ವೇಗವಾಗಿ ಏರುತ್ತದೆ (ಸಂತೃಪ್ತಿ), ನಂತರ ಬಹುತೇಕ ಸಮತಟ್ಟು (ಸಕ್ರಿಯ ಪ್ರದೇಶ); ಅಲ್ಲಿ Ic ಸುಮಾರು Ib ಯ β ಪಟ್ಟು.'),
        viva=[Q(W('Why is the base made thin and lightly doped?', 'आधार पतला और हल्का मादित क्यों बनाया जाता है?', 'ಆಧಾರವನ್ನು ತೆಳುವಾಗಿ, ಕಡಿಮೆ ಡೋಪ್ ಮಾಡಿ ಏಕೆ ಮಾಡುತ್ತಾರೆ?'),
                W('So that most electrons from the emitter cross it to the collector instead of recombining.', 'ताकि उत्सर्जक के अधिकांश इलेक्ट्रॉन पुनर्संयोजित हुए बिना उसे पार करके संग्राहक तक पहुँचें।', 'ಉತ್ಸರ್ಜಕದ ಹೆಚ್ಚಿನ ಎಲೆಕ್ಟ್ರಾನ್‌ಗಳು ಮರುಸಂಯೋಗವಾಗದೆ ಅದನ್ನು ದಾಟಿ ಸಂಗ್ರಾಹಕ ತಲುಪಲು.')),
              Q(W('Name the three regions of the output characteristic.', 'निर्गत अभिलक्षण के तीन क्षेत्रों के नाम बताइए।', 'ಹೊರಹರಿವು ಲಕ್ಷಣದ ಮೂರು ಪ್ರದೇಶಗಳನ್ನು ಹೆಸರಿಸಿ.'),
                W('Cut-off, active and saturation.', 'अंतक (कट-ऑफ़), सक्रिय और संतृप्ति।', 'ಕಟ್-ಆಫ್, ಸಕ್ರಿಯ ಮತ್ತು ಸಂತೃಪ್ತಿ.')),
              Q(W('In which region is a transistor used as an amplifier, and as a switch?', 'प्रवर्धक के रूप में और स्विच के रूप में ट्रांज़िस्टर किस क्षेत्र में प्रयोग होता है?', 'ವರ್ಧಕವಾಗಿ ಮತ್ತು ಸ್ವಿಚ್ ಆಗಿ ಟ್ರಾನ್ಸಿಸ್ಟರ್ ಯಾವ ಪ್ರದೇಶದಲ್ಲಿ ಬಳಕೆಯಾಗುತ್ತದೆ?'),
                W('Amplifier: active region. Switch: cut-off (off) and saturation (on).', 'प्रवर्धक: सक्रिय क्षेत्र। स्विच: अंतक (बंद) और संतृप्ति (चालू)।', 'ವರ್ಧಕ: ಸಕ್ರಿಯ ಪ್ರದೇಶ. ಸ್ವಿಚ್: ಕಟ್-ಆಫ್ (ಆಫ್) ಮತ್ತು ಸಂತೃಪ್ತಿ (ಆನ್).'))],
    )

    lab(
        id='logic-gates', bench='logic', subject='Electronics', domain='electronics', levels=[12, 'ug'], curricula=['cbse', 'ka-puc'], mode='explore',
        keywords=['logic gates', 'logic gate', 'truth table', 'and gate', 'or gate', 'not gate', 'nand', 'nor', 'xor', 'digital electronics', 'boolean'],
        title=W('Logic gates and truth tables', 'लॉजिक गेट और सत्यता सारणी', 'ತರ್ಕ ದ್ವಾರಗಳು ಮತ್ತು ಸತ್ಯ ಕೋಷ್ಟಕಗಳು'),
        summary=W('Switch the inputs of AND, OR, NOT, NAND, NOR, XOR and XNOR gates and build each truth table.',
                  'AND, OR, NOT, NAND, NOR, XOR और XNOR गेटों के निवेश बदलें और हर एक की सत्यता सारणी बनाएँ।',
                  'AND, OR, NOT, NAND, NOR, XOR ಮತ್ತು XNOR ದ್ವಾರಗಳ ಒಳಹರಿವುಗಳನ್ನು ಬದಲಿಸಿ ಪ್ರತಿಯೊಂದರ ಸತ್ಯ ಕೋಷ್ಟಕ ರಚಿಸಿ.'),
        aim=W('To verify the truth tables of the basic and universal logic gates.', 'मूल और सार्वत्रिक लॉजिक गेटों की सत्यता सारणियों का सत्यापन करना।', 'ಮೂಲ ಮತ್ತು ಸಾರ್ವತ್ರಿಕ ತರ್ಕ ದ್ವಾರಗಳ ಸತ್ಯ ಕೋಷ್ಟಕಗಳನ್ನು ಪರಿಶೀಲಿಸುವುದು.'),
        principle=W('A logic gate gives a high (1) or low (0) output that depends only on its inputs. AND: Y = A·B; OR: Y = A + B; NOT: Y = Ā. NAND and NOR are AND and OR followed by NOT; each can be combined to make every other gate, so they are called universal gates. XOR is 1 when the inputs differ.',
                    'लॉजिक गेट उच्च (1) या निम्न (0) निर्गत देता है जो केवल उसके निवेशों पर निर्भर करता है। AND: Y = A·B; OR: Y = A + B; NOT: Y = Ā. NAND और NOR, AND और OR के बाद NOT हैं; इनमें से प्रत्येक से हर दूसरा गेट बनाया जा सकता है, इसलिए इन्हें सार्वत्रिक गेट कहते हैं। XOR तब 1 होता है जब निवेश भिन्न हों।',
                    'ತರ್ಕ ದ್ವಾರವು ಅದರ ಒಳಹರಿವುಗಳನ್ನು ಮಾತ್ರ ಅವಲಂಬಿಸಿ ಉನ್ನತ (1) ಅಥವಾ ನಿಮ್ನ (0) ಹೊರಹರಿವು ನೀಡುತ್ತದೆ. AND: Y = A·B; OR: Y = A + B; NOT: Y = Ā. NAND ಮತ್ತು NOR ಎಂದರೆ AND ಮತ್ತು OR ನಂತರ NOT; ಇವುಗಳಲ್ಲಿ ಪ್ರತಿಯೊಂದರಿಂದಲೂ ಉಳಿದೆಲ್ಲ ದ್ವಾರಗಳನ್ನು ರಚಿಸಬಹುದು, ಆದ್ದರಿಂದ ಸಾರ್ವತ್ರಿಕ ದ್ವಾರಗಳು. ಒಳಹರಿವುಗಳು ಭಿನ್ನವಾಗಿದ್ದಾಗ XOR = 1.'),
        apparatus=[W('Digital trainer kit with gate ICs (7408, 7432, 7404, 7400, 7402, 7486)', 'गेट IC सहित डिजिटल प्रशिक्षण किट (7408, 7432, 7404, 7400, 7402, 7486)', 'ದ್ವಾರ IC ಗಳ ಡಿಜಿಟಲ್ ತರಬೇತಿ ಕಿಟ್ (7408, 7432, 7404, 7400, 7402, 7486)'),
                   W('5 V DC supply', '5 V DC आपूर्ति', '5 V DC ಪೂರೈಕೆ'), W('Input switches and an LED indicator', 'निवेश स्विच और LED सूचक', 'ಒಳಹರಿವು ಸ್ವಿಚ್‌ಗಳು ಮತ್ತು LED ಸೂಚಕ'), WIRES],
        steps=[W('Choose a gate. Set both inputs to 0 and note whether the output LED is on (1) or off (0).', 'एक गेट चुनें। दोनों निवेश 0 रखें और देखें कि निर्गत LED जल रहा है (1) या बुझा है (0)।', 'ಒಂದು ದ್ವಾರ ಆರಿಸಿ. ಎರಡೂ ಒಳಹರಿವು 0 ಇಟ್ಟು ಹೊರಹರಿವು LED ಆನ್ (1) ಅಥವಾ ಆಫ್ (0) ಗಮನಿಸಿ.'),
               W('Record the row, then try 0 1, 1 0 and 1 1.', 'पंक्ति लिखें, फिर 0 1, 1 0 और 1 1 आज़माएँ।', 'ಸಾಲು ದಾಖಲಿಸಿ, ನಂತರ 0 1, 1 0 ಮತ್ತು 1 1 ಪ್ರಯತ್ನಿಸಿ.'),
               W('Compare your table with the gate’s Boolean expression.', 'अपनी सारणी की तुलना गेट के बूलीय व्यंजक से करें।', 'ನಿಮ್ಮ ಕೋಷ್ಟಕವನ್ನು ದ್ವಾರದ ಬೂಲಿಯನ್ ಅಭಿವ್ಯಕ್ತಿಯೊಂದಿಗೆ ಹೋಲಿಸಿ.'),
               W('Repeat for every gate.', 'हर गेट के लिए दोहराएँ।', 'ಪ್ರತಿ ದ್ವಾರಕ್ಕೆ ಪುನರಾವರ್ತಿಸಿ.')],
        precautions=[W('Use exactly 5 V for TTL ICs and connect Vcc and ground pins before switching on.', 'TTL IC के लिए ठीक 5 V लें और चालू करने से पहले Vcc और भू पिन जोड़ें।', 'TTL IC ಗಳಿಗೆ ನಿಖರವಾಗಿ 5 V ಬಳಸಿ; ಆನ್ ಮಾಡುವ ಮೊದಲು Vcc ಮತ್ತು ನೆಲ ಪಿನ್‌ಗಳನ್ನು ಜೋಡಿಸಿ.'),
                     W('Do not leave TTL inputs floating: tie unused inputs to 0 or 1.', 'TTL निवेश खुले न छोड़ें: अप्रयुक्त निवेश 0 या 1 से जोड़ें।', 'TTL ಒಳಹರಿವುಗಳನ್ನು ತೇಲಲು ಬಿಡಬೇಡಿ: ಬಳಸದವನ್ನು 0 ಅಥವಾ 1 ಕ್ಕೆ ಜೋಡಿಸಿ.')],
        conclusion=W('Every gate followed its Boolean expression for all input combinations; NAND and NOR give the opposite of AND and OR.',
                     'हर गेट ने सभी निवेश संयोजनों के लिए अपने बूलीय व्यंजक का पालन किया; NAND और NOR, AND और OR का उलटा देते हैं।',
                     'ಪ್ರತಿ ದ್ವಾರವೂ ಎಲ್ಲ ಒಳಹರಿವು ಸಂಯೋಜನೆಗಳಿಗೆ ತನ್ನ ಬೂಲಿಯನ್ ಅಭಿವ್ಯಕ್ತಿಯನ್ನು ಅನುಸರಿಸಿತು; NAND ಮತ್ತು NOR, AND ಮತ್ತು OR ನ ವಿರುದ್ಧ ನೀಡುತ್ತವೆ.'),
        viva=[Q(W('Why are NAND and NOR called universal gates?', 'NAND और NOR को सार्वत्रिक गेट क्यों कहते हैं?', 'NAND ಮತ್ತು NOR ಅನ್ನು ಸಾರ್ವತ್ರಿಕ ದ್ವಾರಗಳೆಂದು ಏಕೆ ಕರೆಯುತ್ತಾರೆ?'),
                W('Any logic gate can be built from NAND gates alone (or NOR gates alone).', 'कोई भी लॉजिक गेट केवल NAND गेटों से (या केवल NOR गेटों से) बनाया जा सकता है।', 'ಯಾವುದೇ ತರ್ಕ ದ್ವಾರವನ್ನು ಕೇವಲ NAND (ಅಥವಾ ಕೇವಲ NOR) ದ್ವಾರಗಳಿಂದ ರಚಿಸಬಹುದು.')),
              Q(W('How do you make a NOT gate from a NAND gate?', 'NAND गेट से NOT गेट कैसे बनाते हैं?', 'NAND ದ್ವಾರದಿಂದ NOT ದ್ವಾರ ಹೇಗೆ ಮಾಡುತ್ತೀರಿ?'),
                W('Join its two inputs together.', 'उसके दोनों निवेश आपस में जोड़ दें।', 'ಅದರ ಎರಡು ಒಳಹರಿವುಗಳನ್ನು ಒಟ್ಟಿಗೆ ಜೋಡಿಸಿ.')),
              Q(W('When is the output of an XOR gate 1?', 'XOR गेट का निर्गत कब 1 होता है?', 'XOR ದ್ವಾರದ ಹೊರಹರಿವು ಯಾವಾಗ 1?'),
                W('When exactly one input is 1 (the inputs differ).', 'जब ठीक एक निवेश 1 हो (निवेश भिन्न हों)।', 'ನಿಖರವಾಗಿ ಒಂದು ಒಳಹರಿವು 1 ಆಗಿದ್ದಾಗ (ಒಳಹರಿವುಗಳು ಭಿನ್ನ).'))],
    )

    # ------------------------------------------------------------- RC, LCR
    lab(
        id='rc-time-constant', bench='rc', subject='Electronics', domain='electronics', levels=[12, 'ug'], curricula=['cbse', 'ka-puc', 'ug-physics'],
        keywords=['capacitor', 'capacitance', 'rc circuit', 'time constant', 'charging', 'discharging', 'exponential'],
        title=W('Charging and discharging a capacitor (RC time constant)', 'संधारित्र का आवेशन और निरावेशन (RC समय नियतांक)', 'ಧಾರಕದ ಆವೇಶ ಮತ್ತು ವಿಸರ್ಜನೆ (RC ಕಾಲ ಸ್ಥಿರಾಂಕ)'),
        summary=W('Time how the capacitor voltage rises and falls, and find the time constant τ = RC from a log graph.',
                  'संधारित्र की वोल्टता के बढ़ने और घटने का समय मापें और लघुगणक ग्राफ़ से समय नियतांक τ = RC ज्ञात करें।',
                  'ಧಾರಕ ವೋಲ್ಟೇಜ್ ಏರುವ ಮತ್ತು ಇಳಿಯುವ ಸಮಯ ಅಳೆಯಿರಿ, ಲಾಗ್ ನಕ್ಷೆಯಿಂದ ಕಾಲ ಸ್ಥಿರಾಂಕ τ = RC ಕಂಡುಹಿಡಿಯಿರಿ.'),
        aim=W('To study the charging and discharging of a capacitor through a resistor and determine the time constant.',
              'प्रतिरोधक द्वारा संधारित्र के आवेशन और निरावेशन का अध्ययन कर समय नियतांक ज्ञात करना।',
              'ರೋಧಕದ ಮೂಲಕ ಧಾರಕದ ಆವೇಶ ಮತ್ತು ವಿಸರ್ಜನೆ ಅಧ್ಯಯನ ಮಾಡಿ ಕಾಲ ಸ್ಥಿರಾಂಕ ನಿರ್ಧರಿಸುವುದು.'),
        principle=W('While charging, Vc = E(1 − e^(−t/RC)); while discharging, Vc = E e^(−t/RC). So ln(1 − Vc/E) or ln(Vc/E) falls in a straight line with t, of slope −1/τ, where τ = RC. In one time constant the capacitor goes 63 % of the way.',
                    'आवेशन के समय Vc = E(1 − e^(−t/RC)); निरावेशन के समय Vc = E e^(−t/RC). इसलिए ln(1 − Vc/E) या ln(Vc/E), t के साथ −1/τ प्रवणता की सीधी रेखा में घटता है, जहाँ τ = RC. एक समय नियतांक में संधारित्र 63 % रास्ता तय कर लेता है।',
                    'ಆವೇಶದಲ್ಲಿ Vc = E(1 − e^(−t/RC)); ವಿಸರ್ಜನೆಯಲ್ಲಿ Vc = E e^(−t/RC). ಆದ್ದರಿಂದ ln(1 − Vc/E) ಅಥವಾ ln(Vc/E), t ಯೊಂದಿಗೆ −1/τ ಇಳಿಜಾರಿನ ಸರಳರೇಖೆಯಲ್ಲಿ ಇಳಿಯುತ್ತದೆ, τ = RC. ಒಂದು ಕಾಲ ಸ್ಥಿರಾಂಕದಲ್ಲಿ ಧಾರಕ 63 % ದಾರಿ ಕ್ರಮಿಸುತ್ತದೆ.'),
        apparatus=[W('Electrolytic capacitors (100, 220, 470 µF)', 'विद्युत-अपघटनी संधारित्र (100, 220, 470 µF)', 'ವಿದ್ಯುದ್ವಿಭಜಕ ಧಾರಕಗಳು (100, 220, 470 µF)'),
                   W('Resistors (10, 47, 100 kΩ)', 'प्रतिरोधक (10, 47, 100 kΩ)', 'ರೋಧಕಗಳು (10, 47, 100 kΩ)'), W('9 V battery', '9 V बैटरी', '9 V ಬ್ಯಾಟರಿ'),
                   W('Two-way switch', 'द्विमार्गी स्विच', 'ಎರಡು-ದಾರಿ ಸ್ವಿಚ್'), W('High-resistance digital voltmeter', 'उच्च प्रतिरोध वाला अंकीय वोल्टमीटर', 'ಹೆಚ್ಚಿನ ರೋಧದ ಡಿಜಿಟಲ್ ವೋಲ್ಟ್‌ಮೀಟರ್'), W('Stopwatch', 'विराम घड़ी', 'ನಿಲುಗಡಿಯಾರ')],
        steps=[W('Discharge the capacitor fully. Connect the battery, switch, resistor and capacitor in series, with the voltmeter across the capacitor.', 'संधारित्र को पूरा निरावेशित करें। बैटरी, स्विच, प्रतिरोधक और संधारित्र श्रेणी में जोड़ें, वोल्टमीटर संधारित्र के सिरों पर।', 'ಧಾರಕವನ್ನು ಸಂಪೂರ್ಣ ವಿಸರ್ಜಿಸಿ. ಬ್ಯಾಟರಿ, ಸ್ವಿಚ್, ರೋಧಕ ಮತ್ತು ಧಾರಕವನ್ನು ಸರಣಿಯಲ್ಲಿ ಜೋಡಿಸಿ; ವೋಲ್ಟ್‌ಮೀಟರ್ ಧಾರಕಕ್ಕೆ ಅಡ್ಡಲಾಗಿ.'),
               W('Close the switch and start the stopwatch together. Record Vc every 5 s.', 'स्विच बंद करें और साथ ही विराम घड़ी चालू करें। हर 5 s पर Vc लिखें।', 'ಸ್ವಿಚ್ ಮುಚ್ಚಿ ಜೊತೆಗೇ ನಿಲುಗಡಿಯಾರ ಆರಂಭಿಸಿ. ಪ್ರತಿ 5 s ಗೆ Vc ದಾಖಲಿಸಿ.'),
               W('When it is fully charged, switch to discharge through the same resistor and record Vc again.', 'पूरा आवेशित होने पर उसी प्रतिरोधक से निरावेशन पर स्विच करें और फिर Vc लिखें।', 'ಪೂರ್ಣ ಆವೇಶವಾದಾಗ ಅದೇ ರೋಧಕದ ಮೂಲಕ ವಿಸರ್ಜನೆಗೆ ಬದಲಿಸಿ ಮತ್ತೆ Vc ದಾಖಲಿಸಿ.'),
               W('Plot Vc against t, and ln(1 − Vc/E) (or ln(Vc/E)) against t.', 'Vc और t, तथा ln(1 − Vc/E) (या ln(Vc/E)) और t के ग्राफ़ बनाएँ।', 'Vc ಮತ್ತು t, ಹಾಗೂ ln(1 − Vc/E) (ಅಥವಾ ln(Vc/E)) ಮತ್ತು t ನಕ್ಷೆಗಳನ್ನು ಎಳೆಯಿರಿ.'),
               W('Find τ from the slope and compare it with R × C.', 'प्रवणता से τ ज्ञात करें और R × C से तुलना करें।', 'ಇಳಿಜಾರಿನಿಂದ τ ಕಂಡುಹಿಡಿದು R × C ಯೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=[W('Connect the electrolytic capacitor the right way round.', 'विद्युत-अपघटनी संधारित्र सही दिशा में जोड़ें।', 'ವಿದ್ಯುದ್ವಿಭಜಕ ಧಾರಕವನ್ನು ಸರಿಯಾದ ದಿಕ್ಕಿನಲ್ಲಿ ಜೋಡಿಸಿ.'),
                     W('Use a voltmeter of much higher resistance than R, or it will discharge the capacitor.', 'R से बहुत अधिक प्रतिरोध वाला वोल्टमीटर लें, नहीं तो वह संधारित्र को निरावेशित कर देगा।', 'R ಗಿಂತ ಬಹಳ ಹೆಚ್ಚು ರೋಧದ ವೋಲ್ಟ್‌ಮೀಟರ್ ಬಳಸಿ, ಇಲ್ಲದಿದ್ದರೆ ಅದು ಧಾರಕವನ್ನು ವಿಸರ್ಜಿಸುತ್ತದೆ.'),
                     W('Start the stopwatch exactly when the switch is closed.', 'स्विच बंद करते ही ठीक उसी क्षण विराम घड़ी चालू करें।', 'ಸ್ವಿಚ್ ಮುಚ್ಚಿದ ಕ್ಷಣದಲ್ಲೇ ನಿಲುಗಡಿಯಾರ ಆರಂಭಿಸಿ.')],
        conclusion=W('The capacitor charges and discharges exponentially; the log graph is a straight line and the measured time constant agrees with RC.',
                     'संधारित्र चरघातांकी रूप से आवेशित और निरावेशित होता है; लघुगणक ग्राफ़ सीधी रेखा है और मापा गया समय नियतांक RC से मेल खाता है।',
                     'ಧಾರಕ ಘಾತೀಯವಾಗಿ ಆವೇಶ ಮತ್ತು ವಿಸರ್ಜನೆಯಾಗುತ್ತದೆ; ಲಾಗ್ ನಕ್ಷೆ ಸರಳರೇಖೆ, ಅಳೆದ ಕಾಲ ಸ್ಥಿರಾಂಕ RC ಗೆ ಹೊಂದುತ್ತದೆ.'),
        viva=[Q(W('What fraction of E is reached after one time constant while charging?', 'आवेशन में एक समय नियतांक के बाद E का कितना भाग पहुँचता है?', 'ಆವೇಶದಲ್ಲಿ ಒಂದು ಕಾಲ ಸ್ಥಿರಾಂಕದ ನಂತರ E ಯ ಎಷ್ಟು ಭಾಗ ತಲುಪುತ್ತದೆ?'), W('About 63 % (1 − 1/e).', 'लगभग 63 % (1 − 1/e).', 'ಸುಮಾರು 63 % (1 − 1/e).')),
              Q(W('Show that RC has the unit of time.', 'दिखाइए कि RC की इकाई समय की है।', 'RC ಯ ಏಕಮಾನ ಸಮಯವೆಂದು ತೋರಿಸಿ.'), W('Ω × F = (V/A) × (C/V) = C/A = s.', 'Ω × F = (V/A) × (C/V) = C/A = s.', 'Ω × F = (V/A) × (C/V) = C/A = s.')),
              Q(W('Where are RC circuits used?', 'RC परिपथ कहाँ प्रयोग होते हैं?', 'RC ಮಂಡಲಗಳು ಎಲ್ಲಿ ಬಳಕೆಯಾಗುತ್ತವೆ?'), W('In timers, filters, camera flashes and to smooth rectified DC.', 'टाइमर, फ़िल्टर, कैमरा फ़्लैश और दिष्टकृत DC को समतल करने में।', 'ಟೈಮರ್, ಫಿಲ್ಟರ್, ಕ್ಯಾಮೆರಾ ಫ್ಲ್ಯಾಶ್ ಮತ್ತು ಸರಿಪಡಿಸಿದ DC ನಯಗೊಳಿಸಲು.'))],
    )

    lab(
        id='lcr-resonance', bench='rlc', subject='Physics', domain='physics', levels=[12, 'ug'], curricula=['cbse', 'ka-puc', 'ug-physics'],
        keywords=['alternating current', 'lcr', 'series resonance', 'resonance', 'resonant frequency', 'quality factor', 'ac circuit'],
        title=W('Series LCR resonance', 'श्रेणी LCR अनुनाद', 'ಸರಣಿ LCR ಅನುನಾದ'),
        summary=W('Sweep the frequency of an AC supply across an LCR circuit and find the resonant frequency and Q factor.',
                  'LCR परिपथ में AC आपूर्ति की आवृत्ति बदलें और अनुनादी आवृत्ति तथा Q गुणांक ज्ञात करें।',
                  'LCR ಮಂಡಲದಲ್ಲಿ AC ಪೂರೈಕೆಯ ಆವರ್ತನವನ್ನು ಬದಲಿಸಿ ಅನುನಾದ ಆವರ್ತನ ಮತ್ತು Q ಅಂಶ ಕಂಡುಹಿಡಿಯಿರಿ.'),
        aim=W('To draw the resonance curve of a series LCR circuit and find its resonant frequency and quality factor.',
              'श्रेणी LCR परिपथ का अनुनाद वक्र खींचना और उसकी अनुनादी आवृत्ति तथा गुणता गुणांक ज्ञात करना।',
              'ಸರಣಿ LCR ಮಂಡಲದ ಅನುನಾದ ವಕ್ರ ಎಳೆದು ಅದರ ಅನುನಾದ ಆವರ್ತನ ಮತ್ತು ಗುಣಮಟ್ಟ ಅಂಶ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('The impedance is Z = √(R² + (ωL − 1/ωC)²). At f₀ = 1/(2π√LC) the inductive and capacitive reactances cancel, Z = R and the current is largest, I = V/R. The sharpness is the quality factor Q = f₀ ÷ (f₂ − f₁) = (1/R)√(L/C), where f₁ and f₂ are the half-power frequencies (I = Imax/√2).',
                    'प्रतिबाधा Z = √(R² + (ωL − 1/ωC)²) है। f₀ = 1/(2π√LC) पर प्रेरकीय और धारितीय प्रतिघात एक-दूसरे को निरस्त करते हैं, Z = R और धारा सबसे अधिक, I = V/R होती है। तीक्ष्णता गुणता गुणांक Q = f₀ ÷ (f₂ − f₁) = (1/R)√(L/C) है, जहाँ f₁ और f₂ अर्ध-शक्ति आवृत्तियाँ (I = Imax/√2) हैं।',
                    'ಪ್ರತಿರೋಧ Z = √(R² + (ωL − 1/ωC)²). f₀ = 1/(2π√LC) ನಲ್ಲಿ ಪ್ರೇರಕ ಮತ್ತು ಧಾರಕ ಪ್ರತಿಘಾತಗಳು ರದ್ದಾಗುತ್ತವೆ, Z = R, ಪ್ರವಾಹ ಗರಿಷ್ಠ, I = V/R. ತೀಕ್ಷ್ಣತೆ ಗುಣಮಟ್ಟ ಅಂಶ Q = f₀ ÷ (f₂ − f₁) = (1/R)√(L/C); f₁, f₂ ಅರ್ಧ-ಶಕ್ತಿ ಆವರ್ತನಗಳು (I = Imax/√2).'),
        apparatus=[W('Audio-frequency signal generator', 'श्रव्य आवृत्ति संकेत जनित्र', 'ಶ್ರವ್ಯ ಆವರ್ತನ ಸಂಕೇತ ಜನಕ'), W('Inductor (50–200 mH)', 'प्रेरक (50–200 mH)', 'ಪ್ರೇರಕ (50–200 mH)'),
                   W('Capacitor (0.47–2.2 µF)', 'संधारित्र (0.47–2.2 µF)', 'ಧಾರಕ (0.47–2.2 µF)'), W('Resistor (10–100 Ω)', 'प्रतिरोधक (10–100 Ω)', 'ರೋಧಕ (10–100 Ω)'),
                   W('AC milliammeter', 'AC मिलीऐमीटर', 'AC ಮಿಲಿಅಮ್ಮೀಟರ್'), WIRES],
        steps=[W('Connect the signal generator, R, L, C and the AC milliammeter in series. Keep the generator voltage fixed (2 V).', 'संकेत जनित्र, R, L, C और AC मिलीऐमीटर श्रेणी में जोड़ें। जनित्र की वोल्टता नियत (2 V) रखें।', 'ಸಂಕೇತ ಜನಕ, R, L, C ಮತ್ತು AC ಮಿಲಿಅಮ್ಮೀಟರನ್ನು ಸರಣಿಯಲ್ಲಿ ಜೋಡಿಸಿ. ಜನಕದ ವೋಲ್ಟೇಜ್ ಸ್ಥಿರ (2 V).'),
               W('Start at a low frequency and raise it in steps, recording the current each time.', 'कम आवृत्ति से शुरू कर चरणों में बढ़ाएँ और हर बार धारा लिखें।', 'ಕಡಿಮೆ ಆವರ್ತನದಿಂದ ಆರಂಭಿಸಿ ಹಂತಗಳಲ್ಲಿ ಹೆಚ್ಚಿಸಿ, ಪ್ರತಿ ಬಾರಿ ಪ್ರವಾಹ ದಾಖಲಿಸಿ.'),
               W('Take close readings near the maximum current.', 'अधिकतम धारा के पास पाठ्यांक पास-पास लें।', 'ಗರಿಷ್ಠ ಪ್ರವಾಹದ ಹತ್ತಿರ ಹತ್ತಿರ ಹತ್ತಿರ ಓದುಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.'),
               W('Plot I against f; read f₀ and the half-power points and work out Q.', 'I और f का ग्राफ़ बनाएँ; f₀ और अर्ध-शक्ति बिंदु पढ़ें और Q निकालें।', 'I ಮತ್ತು f ನಕ್ಷೆ ಎಳೆಯಿರಿ; f₀ ಮತ್ತು ಅರ್ಧ-ಶಕ್ತಿ ಬಿಂದುಗಳನ್ನು ಓದಿ Q ಲೆಕ್ಕಿಸಿ.'),
               W('Repeat with a larger R and compare the sharpness.', 'बड़े R के साथ दोहराएँ और तीक्ष्णता की तुलना करें।', 'ದೊಡ್ಡ R ನೊಂದಿಗೆ ಪುನರಾವರ್ತಿಸಿ ತೀಕ್ಷ್ಣತೆ ಹೋಲಿಸಿ.')],
        precautions=[W('Keep the generator output voltage the same at every frequency.', 'हर आवृत्ति पर जनित्र की निर्गत वोल्टता समान रखें।', 'ಪ್ರತಿ ಆವರ್ತನದಲ್ಲೂ ಜನಕದ ಹೊರಹರಿವು ವೋಲ್ಟೇಜ್ ಒಂದೇ ಇರಲಿ.'),
                     W('Near resonance the voltages across L and C can be much larger than the supply: do not touch them.', 'अनुनाद के पास L और C के सिरों की वोल्टता आपूर्ति से बहुत अधिक हो सकती है: उन्हें न छुएँ।', 'ಅನುನಾದದ ಹತ್ತಿರ L ಮತ್ತು C ಗೆ ಅಡ್ಡ ವೋಲ್ಟೇಜ್ ಪೂರೈಕೆಗಿಂತ ಬಹಳ ಹೆಚ್ಚಿರಬಹುದು: ಅವುಗಳನ್ನು ಮುಟ್ಟಬೇಡಿ.')],
        conclusion=W('The current peaks at f₀ = 1/(2π√LC) where it equals V/R; a smaller resistance gives a sharper peak (higher Q).',
                     'धारा f₀ = 1/(2π√LC) पर शिखर पर होती है जहाँ वह V/R के बराबर है; छोटा प्रतिरोध अधिक तीक्ष्ण शिखर (अधिक Q) देता है।',
                     'ಪ್ರವಾಹ f₀ = 1/(2π√LC) ನಲ್ಲಿ ಶಿಖರ ತಲುಪುತ್ತದೆ, ಅಲ್ಲಿ ಅದು V/R; ಕಡಿಮೆ ರೋಧ ಹೆಚ್ಚು ತೀಕ್ಷ್ಣ ಶಿಖರ (ಹೆಚ್ಚು Q) ನೀಡುತ್ತದೆ.'),
        viva=[Q(W('What is the phase difference between V and I at resonance?', 'अनुनाद पर V और I के बीच कलांतर कितना है?', 'ಅನುನಾದದಲ್ಲಿ V ಮತ್ತು I ನಡುವಿನ ಹಂತ ವ್ಯತ್ಯಾಸ ಎಷ್ಟು?'), W('Zero: the circuit is purely resistive.', 'शून्य: परिपथ शुद्ध प्रतिरोधी है।', 'ಶೂನ್ಯ: ಮಂಡಲ ಸಂಪೂರ್ಣ ರೋಧಕ.')),
              Q(W('Where is series resonance used?', 'श्रेणी अनुनाद कहाँ प्रयोग होता है?', 'ಸರಣಿ ಅನುನಾದ ಎಲ್ಲಿ ಬಳಕೆಯಾಗುತ್ತದೆ?'), W('In tuning a radio to one station.', 'रेडियो को किसी एक स्टेशन पर समस्वरित करने में।', 'ರೇಡಿಯೊವನ್ನು ಒಂದು ಕೇಂದ್ರಕ್ಕೆ ಶ್ರುತಿಗೊಳಿಸಲು.')),
              Q(W('How does f₀ change if C is made four times larger?', 'C चार गुना करने पर f₀ कैसे बदलेगी?', 'C ಯನ್ನು ನಾಲ್ಕು ಪಟ್ಟು ಮಾಡಿದರೆ f₀ ಹೇಗೆ ಬದಲಾಗುತ್ತದೆ?'), W('It halves.', 'वह आधी हो जाती है।', 'ಅದು ಅರ್ಧವಾಗುತ್ತದೆ.'))],
    )

    # -------------------------------------------------------------- op-amp
    oa_common = dict(bench='opamp', subject='Electronics', domain='electronics', levels=['ug'], curricula=['ug-electronics'])
    OA_APP = [W('Op-amp IC 741', 'ऑप-ऐम्प IC 741', 'ಆಪ್-ಆಂಪ್ IC 741'), W('Dual supply ±15 V', 'द्वि-आपूर्ति ±15 V', 'ದ್ವಿ ಪೂರೈಕೆ ±15 V'),
              W('Resistors for Rf and Rin', 'Rf और Rin के लिए प्रतिरोधक', 'Rf ಮತ್ತು Rin ಗಾಗಿ ರೋಧಕಗಳು'), W('Variable DC input (−2 to +2 V)', 'परिवर्ती DC निवेश (−2 से +2 V)', 'ಬದಲಾಯಿಸಬಹುದಾದ DC ಒಳಹರಿವು (−2 ರಿಂದ +2 V)'),
              W('Digital multimeters', 'अंकीय मल्टीमीटर', 'ಡಿಜಿಟಲ್ ಮಲ್ಟಿಮೀಟರ್‌ಗಳು'), WIRES]
    OA_PRE = [W('Connect the ±15 V supply to pins 7 and 4 before applying the input.', 'निवेश देने से पहले ±15 V आपूर्ति पिन 7 और 4 से जोड़ें।', 'ಒಳಹರಿವು ನೀಡುವ ಮೊದಲು ±15 V ಪೂರೈಕೆಯನ್ನು ಪಿನ್ 7 ಮತ್ತು 4 ಕ್ಕೆ ಜೋಡಿಸಿ.'),
              W('Keep the input small enough that the output does not saturate (about ±13.5 V).', 'निवेश इतना छोटा रखें कि निर्गत संतृप्त न हो (लगभग ±13.5 V)।', 'ಹೊರಹರಿವು ಸಂತೃಪ್ತವಾಗದಷ್ಟು (ಸುಮಾರು ±13.5 V) ಒಳಹರಿವನ್ನು ಸಣ್ಣದಾಗಿಡಿ.'), P_SWITCH_OFF]
    OA_VIVA = [Q(W('What are the two golden rules of an ideal op-amp with negative feedback?', 'ऋणात्मक पुनर्निवेश वाले आदर्श ऑप-ऐम्प के दो स्वर्णिम नियम क्या हैं?', 'ಋಣ ಪ್ರತಿಪೋಷಣೆಯ ಆದರ್ಶ ಆಪ್-ಆಂಪ್‌ನ ಎರಡು ಸುವರ್ಣ ನಿಯಮಗಳು ಯಾವುವು?'),
                 W('No current flows into the inputs, and the output makes the two inputs equal in voltage.', 'निवेशों में कोई धारा नहीं जाती, और निर्गत दोनों निवेशों की वोल्टता बराबर कर देता है।', 'ಒಳಹರಿವುಗಳಿಗೆ ಪ್ರವಾಹ ಹರಿಯುವುದಿಲ್ಲ; ಹೊರಹರಿವು ಎರಡು ಒಳಹರಿವುಗಳ ವೋಲ್ಟೇಜನ್ನು ಸಮಗೊಳಿಸುತ್ತದೆ.')),
               Q(W('Why does the output saturate near ±13.5 V?', 'निर्गत ±13.5 V के पास संतृप्त क्यों होता है?', 'ಹೊರಹರಿವು ±13.5 V ಹತ್ತಿರ ಏಕೆ ಸಂತೃಪ್ತವಾಗುತ್ತದೆ?'),
                 W('It cannot exceed the supply rails (±15 V) less a small internal drop.', 'यह आपूर्ति सीमाओं (±15 V) से थोड़ा कम से अधिक नहीं जा सकता।', 'ಅದು ಪೂರೈಕೆ ಮಿತಿಗಳಿಗಿಂತ (±15 V) ಸ್ವಲ್ಪ ಕಡಿಮೆಗಿಂತ ಹೆಚ್ಚು ಹೋಗಲಾರದು.'))]

    lab(id='opamp-inverting', setup={'config': 'inverting'}, **oa_common,
        keywords=['operational amplifier', 'op-amp', 'op amp', 'inverting amplifier', 'gain', 'negative feedback', '741'],
        title=W('Op-amp inverting amplifier', 'ऑप-ऐम्प प्रतिलोमी प्रवर्धक', 'ಆಪ್-ಆಂಪ್ ವಿಲೋಮ ವರ್ಧಕ'),
        summary=W('Measure the output of an inverting amplifier against its input and check the gain −Rf/Rin.',
                  'प्रतिलोमी प्रवर्धक का निर्गत उसके निवेश के सापेक्ष मापें और लब्धि −Rf/Rin जाँचें।',
                  'ವಿಲೋಮ ವರ್ಧಕದ ಹೊರಹರಿವನ್ನು ಒಳಹರಿವಿನ ವಿರುದ್ಧ ಅಳೆದು ಲಾಭ −Rf/Rin ಪರಿಶೀಲಿಸಿ.'),
        aim=W('To study an op-amp inverting amplifier and verify that its gain is −Rf/Rin.', 'ऑप-ऐम्प प्रतिलोमी प्रवर्धक का अध्ययन करना और सत्यापित करना कि उसकी लब्धि −Rf/Rin है।', 'ಆಪ್-ಆಂಪ್ ವಿಲೋಮ ವರ್ಧಕವನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ ಅದರ ಲಾಭ −Rf/Rin ಎಂದು ಪರಿಶೀಲಿಸುವುದು.'),
        principle=W('The + input is grounded, so the − input is held at 0 V (virtual ground). The input current Vin/Rin all flows through Rf, so Vout = −(Rf/Rin) Vin: the output is inverted and amplified, until it reaches the supply rails.',
                    '+ निवेश भू से जुड़ा है, इसलिए − निवेश 0 V (आभासी भू) पर रहता है। निवेश धारा Vin/Rin पूरी Rf से बहती है, इसलिए Vout = −(Rf/Rin) Vin: निर्गत उलटा और प्रवर्धित होता है, जब तक वह आपूर्ति सीमा तक न पहुँचे।',
                    '+ ಒಳಹರಿವು ನೆಲಕ್ಕೆ ಜೋಡಿಸಿದೆ; ಆದ್ದರಿಂದ − ಒಳಹರಿವು 0 V (ಮಿಥ್ಯ ನೆಲ) ನಲ್ಲಿರುತ್ತದೆ. ಒಳಹರಿವು ಪ್ರವಾಹ Vin/Rin ಸಂಪೂರ್ಣ Rf ಮೂಲಕ ಹರಿಯುತ್ತದೆ; ಆದ್ದರಿಂದ Vout = −(Rf/Rin) Vin: ಹೊರಹರಿವು ಪೂರೈಕೆ ಮಿತಿ ತಲುಪುವವರೆಗೆ ವಿಲೋಮ ಮತ್ತು ವರ್ಧಿತ.'),
        apparatus=OA_APP,
        steps=[W('Connect Rin from the input to the − terminal, Rf from the output back to −, and ground the + terminal.', 'Rin को निवेश से − सिरे तक, Rf को निर्गत से वापस − तक जोड़ें और + सिरे को भू से जोड़ें।', 'Rin ಅನ್ನು ಒಳಹರಿವಿನಿಂದ − ತುದಿಗೆ, Rf ಅನ್ನು ಹೊರಹರಿವಿನಿಂದ − ಗೆ ಜೋಡಿಸಿ, + ತುದಿಯನ್ನು ನೆಲಕ್ಕೆ ಜೋಡಿಸಿ.'),
               W('Set Rf = 10 kΩ, Rin = 1 kΩ. Apply inputs from −2 V to +2 V and record Vout.', 'Rf = 10 kΩ, Rin = 1 kΩ रखें। −2 V से +2 V तक निवेश देकर Vout लिखें।', 'Rf = 10 kΩ, Rin = 1 kΩ. −2 V ರಿಂದ +2 V ವರೆಗೆ ಒಳಹರಿವು ನೀಡಿ Vout ದಾಖಲಿಸಿ.'),
               W('Plot Vout against Vin; find the slope in the straight part.', 'Vout और Vin का ग्राफ़ बनाएँ; सीधे भाग की प्रवणता ज्ञात करें।', 'Vout ಮತ್ತು Vin ನಕ್ಷೆ ಎಳೆದು ನೇರ ಭಾಗದ ಇಳಿಜಾರು ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Change Rf and Rin and check the gain each time.', 'Rf और Rin बदलें और हर बार लब्धि जाँचें।', 'Rf ಮತ್ತು Rin ಬದಲಿಸಿ ಪ್ರತಿ ಬಾರಿ ಲಾಭ ಪರಿಶೀಲಿಸಿ.')],
        precautions=OA_PRE,
        conclusion=W('In the linear range Vout = −(Rf/Rin) Vin; beyond it the output saturates at the rails.', 'रैखिक परास में Vout = −(Rf/Rin) Vin; उससे आगे निर्गत सीमाओं पर संतृप्त हो जाता है।', 'ರೇಖೀಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ Vout = −(Rf/Rin) Vin; ಅದರ ಆಚೆ ಹೊರಹರಿವು ಮಿತಿಗಳಲ್ಲಿ ಸಂತೃಪ್ತ.'),
        viva=OA_VIVA + [Q(W('What is a virtual ground?', 'आभासी भू क्या है?', 'ಮಿಥ್ಯ ನೆಲ ಎಂದರೇನು?'), W('A point held at 0 V by feedback though not connected to ground.', 'ऐसा बिंदु जो भू से जुड़ा न होते हुए भी पुनर्निवेश से 0 V पर रहता है।', 'ನೆಲಕ್ಕೆ ಜೋಡಿಸದಿದ್ದರೂ ಪ್ರತಿಪೋಷಣೆಯಿಂದ 0 V ನಲ್ಲಿರುವ ಬಿಂದು.'))])

    lab(id='opamp-non-inverting', setup={'config': 'non-inverting'}, **oa_common,
        keywords=['operational amplifier', 'op-amp', 'op amp', 'non-inverting amplifier', 'gain', 'voltage follower', '741'],
        title=W('Op-amp non-inverting amplifier', 'ऑप-ऐम्प अप्रतिलोमी प्रवर्धक', 'ಆಪ್-ಆಂಪ್ ಅವಿಲೋಮ ವರ್ಧಕ'),
        summary=W('Feed the signal to the + input and verify the gain 1 + Rf/R1.', 'संकेत + निवेश पर दें और लब्धि 1 + Rf/R1 सत्यापित करें।', 'ಸಂಕೇತವನ್ನು + ಒಳಹರಿವಿಗೆ ನೀಡಿ ಲಾಭ 1 + Rf/R1 ಪರಿಶೀಲಿಸಿ.'),
        aim=W('To study an op-amp non-inverting amplifier and verify that its gain is 1 + Rf/R1.', 'ऑप-ऐम्प अप्रतिलोमी प्रवर्धक का अध्ययन करना और सत्यापित करना कि उसकी लब्धि 1 + Rf/R1 है।', 'ಆಪ್-ಆಂಪ್ ಅವಿಲೋಮ ವರ್ಧಕವನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ ಅದರ ಲಾಭ 1 + Rf/R1 ಎಂದು ಪರಿಶೀಲಿಸುವುದು.'),
        principle=W('The signal goes to the + input. Rf and R1 divide the output so the − input gets Vout·R1/(R1 + Rf); the op-amp makes this equal to Vin, so Vout = (1 + Rf/R1) Vin, in phase with the input. With Rf = 0 it becomes a voltage follower (gain 1).',
                    'संकेत + निवेश पर जाता है। Rf और R1 निर्गत को विभाजित करते हैं जिससे − निवेश को Vout·R1/(R1 + Rf) मिलता है; ऑप-ऐम्प इसे Vin के बराबर कर देता है, इसलिए Vout = (1 + Rf/R1) Vin, निवेश के साथ समान कला में। Rf = 0 होने पर यह वोल्टता अनुगामी (लब्धि 1) बन जाता है।',
                    'ಸಂಕೇತ + ಒಳಹರಿವಿಗೆ ಹೋಗುತ್ತದೆ. Rf ಮತ್ತು R1 ಹೊರಹರಿವನ್ನು ವಿಭಜಿಸಿ − ಒಳಹರಿವಿಗೆ Vout·R1/(R1 + Rf) ನೀಡುತ್ತವೆ; ಆಪ್-ಆಂಪ್ ಇದನ್ನು Vin ಗೆ ಸಮಗೊಳಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ Vout = (1 + Rf/R1) Vin, ಒಳಹರಿವಿನ ಹಂತದಲ್ಲೇ. Rf = 0 ಆದರೆ ಅದು ವೋಲ್ಟೇಜ್ ಅನುಸರಕ (ಲಾಭ 1).'),
        apparatus=OA_APP,
        steps=[W('Connect the input to the + terminal; R1 from − to ground; Rf from the output to −.', 'निवेश को + सिरे से; R1 को − से भू तक; Rf को निर्गत से − तक जोड़ें।', 'ಒಳಹರಿವನ್ನು + ತುದಿಗೆ; R1 ಅನ್ನು − ಇಂದ ನೆಲಕ್ಕೆ; Rf ಅನ್ನು ಹೊರಹರಿವಿನಿಂದ − ಗೆ ಜೋಡಿಸಿ.'),
               W('Apply inputs from −2 V to +2 V and record Vout.', '−2 V से +2 V तक निवेश देकर Vout लिखें।', '−2 V ರಿಂದ +2 V ವರೆಗೆ ಒಳಹರಿವು ನೀಡಿ Vout ದಾಖಲಿಸಿ.'),
               W('Plot Vout against Vin and find the slope.', 'Vout और Vin का ग्राफ़ बनाकर प्रवणता ज्ञात करें।', 'Vout ಮತ್ತು Vin ನಕ್ಷೆ ಎಳೆದು ಇಳಿಜಾರು ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Compare the slope with 1 + Rf/R1 for two pairs of resistors.', 'प्रतिरोधकों के दो युग्मों के लिए प्रवणता की तुलना 1 + Rf/R1 से करें।', 'ಎರಡು ರೋಧಕ ಜೋಡಿಗಳಿಗೆ ಇಳಿಜಾರನ್ನು 1 + Rf/R1 ಯೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=OA_PRE,
        conclusion=W('The output is in phase with the input and Vout = (1 + Rf/R1) Vin in the linear range; the gain is never less than 1.', 'निर्गत निवेश के साथ समान कला में है और रैखिक परास में Vout = (1 + Rf/R1) Vin; लब्धि कभी 1 से कम नहीं होती।', 'ಹೊರಹರಿವು ಒಳಹರಿವಿನ ಹಂತದಲ್ಲೇ; ರೇಖೀಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ Vout = (1 + Rf/R1) Vin; ಲಾಭ ಎಂದೂ 1 ಕ್ಕಿಂತ ಕಡಿಮೆಯಿಲ್ಲ.'),
        viva=OA_VIVA + [Q(W('What is a voltage follower used for?', 'वोल्टता अनुगामी किसके लिए प्रयोग होता है?', 'ವೋಲ್ಟೇಜ್ ಅನುಸರಕವನ್ನು ಯಾವುದಕ್ಕೆ ಬಳಸುತ್ತಾರೆ?'), W('As a buffer: very high input resistance and low output resistance with gain 1.', 'बफ़र के रूप में: लब्धि 1 के साथ बहुत उच्च निवेश प्रतिरोध और कम निर्गत प्रतिरोध।', 'ಬಫರ್ ಆಗಿ: ಲಾಭ 1 ಜೊತೆಗೆ ಅತಿ ಹೆಚ್ಚು ಒಳಹರಿವು ರೋಧ ಮತ್ತು ಕಡಿಮೆ ಹೊರಹರಿವು ರೋಧ.'))])

    lab(
        id='astable-555', bench='astable', subject='Electronics', domain='electronics', levels=['ug'], curricula=['ug-electronics'], mode='explore',
        keywords=['555 timer', '555', 'astable multivibrator', 'multivibrator', 'oscillator', 'square wave', 'duty cycle'],
        title=W('555 timer as an astable multivibrator', '555 टाइमर अस्थिर बहुकंपित्र के रूप में', '555 ಟೈಮರ್ ಅಸ್ಥಿರ ಬಹುಕಂಪಕವಾಗಿ'),
        summary=W('Watch the 555 charge and discharge its capacitor between ⅓ and ⅔ Vcc and blink an LED; check the frequency formula.',
                  'देखें कि 555 अपने संधारित्र को ⅓ और ⅔ Vcc के बीच कैसे आवेशित-निरावेशित करता है और LED झपकाता है; आवृत्ति सूत्र जाँचें।',
                  '555 ತನ್ನ ಧಾರಕವನ್ನು ⅓ ಮತ್ತು ⅔ Vcc ನಡುವೆ ಆವೇಶ-ವಿಸರ್ಜನೆ ಮಾಡಿ LED ಮಿನುಗಿಸುವುದನ್ನು ನೋಡಿ; ಆವರ್ತನ ಸೂತ್ರ ಪರಿಶೀಲಿಸಿ.'),
        aim=W('To build an astable multivibrator with a 555 timer and compare its frequency and duty cycle with the formula.', '555 टाइमर से अस्थिर बहुकंपित्र बनाना और उसकी आवृत्ति तथा कार्य चक्र की तुलना सूत्र से करना।', '555 ಟೈಮರ್‌ನಿಂದ ಅಸ್ಥಿರ ಬಹುಕಂಪಕ ರಚಿಸಿ ಅದರ ಆವರ್ತನ ಮತ್ತು ಕಾರ್ಯ ಚಕ್ರವನ್ನು ಸೂತ್ರದೊಂದಿಗೆ ಹೋಲಿಸುವುದು.'),
        principle=W('The capacitor charges through RA + RB until it reaches ⅔ Vcc; then the output goes low and the capacitor discharges through RB to ⅓ Vcc, and the cycle repeats. High time = 0.693(RA + RB)C, low time = 0.693 RB C, so f = 1.44 ÷ ((RA + 2RB)C) and the duty cycle is (RA + RB) ÷ (RA + 2RB).',
                    'संधारित्र RA + RB से आवेशित होकर ⅔ Vcc तक पहुँचता है; तब निर्गत निम्न हो जाता है और संधारित्र RB से ⅓ Vcc तक निरावेशित होता है, और चक्र दोहराता है। उच्च समय = 0.693(RA + RB)C, निम्न समय = 0.693 RB C, इसलिए f = 1.44 ÷ ((RA + 2RB)C) और कार्य चक्र (RA + RB) ÷ (RA + 2RB) है।',
                    'ಧಾರಕ RA + RB ಮೂಲಕ ಆವೇಶಗೊಂಡು ⅔ Vcc ತಲುಪುತ್ತದೆ; ಆಗ ಹೊರಹರಿವು ನಿಮ್ನವಾಗಿ ಧಾರಕ RB ಮೂಲಕ ⅓ Vcc ವರೆಗೆ ವಿಸರ್ಜನೆಯಾಗುತ್ತದೆ; ಚಕ್ರ ಪುನರಾವರ್ತಿಸುತ್ತದೆ. ಉನ್ನತ ಸಮಯ = 0.693(RA + RB)C, ನಿಮ್ನ ಸಮಯ = 0.693 RB C; ಆದ್ದರಿಂದ f = 1.44 ÷ ((RA + 2RB)C), ಕಾರ್ಯ ಚಕ್ರ (RA + RB) ÷ (RA + 2RB).'),
        apparatus=[W('555 timer IC', '555 टाइमर IC', '555 ಟೈಮರ್ IC'), W('Resistors RA and RB', 'प्रतिरोधक RA और RB', 'ರೋಧಕಗಳು RA ಮತ್ತು RB'), W('Capacitors (1 µF, 10 µF) and 0.01 µF for pin 5', 'संधारित्र (1 µF, 10 µF) और पिन 5 के लिए 0.01 µF', 'ಧಾರಕಗಳು (1 µF, 10 µF) ಮತ್ತು ಪಿನ್ 5 ಗೆ 0.01 µF'),
                   W('9 V supply', '9 V आपूर्ति', '9 V ಪೂರೈಕೆ'), W('LED with resistor', 'प्रतिरोधक सहित LED', 'ರೋಧಕ ಸಹಿತ LED'), CRO],
        steps=[W('Wire the 555 as an astable: pins 4 and 8 to Vcc, 1 to ground, RA from Vcc to 7, RB from 7 to 6 and 2, C from 2 to ground, output at 3.', '555 को अस्थिर रूप में जोड़ें: पिन 4 और 8 को Vcc, 1 को भू, RA को Vcc से 7, RB को 7 से 6 और 2, C को 2 से भू, निर्गत 3 पर।', '555 ಅನ್ನು ಅಸ್ಥಿರವಾಗಿ ಜೋಡಿಸಿ: ಪಿನ್ 4 ಮತ್ತು 8 Vcc ಗೆ, 1 ನೆಲಕ್ಕೆ, RA Vcc ಇಂದ 7 ಕ್ಕೆ, RB 7 ರಿಂದ 6 ಮತ್ತು 2 ಕ್ಕೆ, C 2 ರಿಂದ ನೆಲಕ್ಕೆ, ಹೊರಹರಿವು 3 ರಲ್ಲಿ.'),
               W('Watch the output and the capacitor voltage on the CRO.', 'CRO पर निर्गत और संधारित्र वोल्टता देखें।', 'CRO ನಲ್ಲಿ ಹೊರಹರಿವು ಮತ್ತು ಧಾರಕ ವೋಲ್ಟೇಜ್ ನೋಡಿ.'),
               W('Measure the period and the high time; work out f and the duty cycle.', 'आवर्तकाल और उच्च समय मापें; f और कार्य चक्र निकालें।', 'ಆವರ್ತಕಾಲ ಮತ್ತು ಉನ್ನತ ಸಮಯ ಅಳೆದು f ಮತ್ತು ಕಾರ್ಯ ಚಕ್ರ ಲೆಕ್ಕಿಸಿ.'),
               W('Change RA, RB and C and compare each time with the formula.', 'RA, RB और C बदलें और हर बार सूत्र से तुलना करें।', 'RA, RB ಮತ್ತು C ಬದಲಿಸಿ ಪ್ರತಿ ಬಾರಿ ಸೂತ್ರದೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=[W('Do not exceed the 555 supply limit (4.5–16 V).', '555 की आपूर्ति सीमा (4.5–16 V) से अधिक न दें।', '555 ರ ಪೂರೈಕೆ ಮಿತಿ (4.5–16 V) ಮೀರಬೇಡಿ.'), W('Keep RA at least 1 kΩ so the discharge transistor is not overloaded.', 'RA कम से कम 1 kΩ रखें ताकि निरावेशन ट्रांज़िस्टर पर अधिक भार न पड़े।', 'ವಿಸರ್ಜನೆ ಟ್ರಾನ್ಸಿಸ್ಟರ್ ಅತಿಭಾರವಾಗದಂತೆ RA ಕನಿಷ್ಠ 1 kΩ ಇರಲಿ.')],
        conclusion=W('The 555 produces a square wave whose frequency matches 1.44 ÷ ((RA + 2RB)C); the duty cycle is above 50 % and approaches 50 % when RB is much larger than RA.', '555 एक वर्ग तरंग देता है जिसकी आवृत्ति 1.44 ÷ ((RA + 2RB)C) से मेल खाती है; कार्य चक्र 50 % से अधिक है और RB के RA से बहुत बड़ा होने पर 50 % के निकट पहुँचता है।', '555 ಚೌಕ ತರಂಗ ನೀಡುತ್ತದೆ; ಅದರ ಆವರ್ತನ 1.44 ÷ ((RA + 2RB)C) ಗೆ ಹೊಂದುತ್ತದೆ; ಕಾರ್ಯ ಚಕ್ರ 50 % ಕ್ಕಿಂತ ಹೆಚ್ಚು; RB, RA ಗಿಂತ ಬಹಳ ದೊಡ್ಡದಾದಾಗ 50 % ಸಮೀಪಿಸುತ್ತದೆ.'),
        viva=[Q(W('Why is it called astable?', 'इसे अस्थिर क्यों कहते हैं?', 'ಇದನ್ನು ಅಸ್ಥಿರ ಎಂದು ಏಕೆ ಕರೆಯುತ್ತಾರೆ?'), W('It has no stable state: it keeps switching between high and low by itself.', 'इसकी कोई स्थिर अवस्था नहीं: यह स्वयं उच्च और निम्न के बीच बदलता रहता है।', 'ಅದಕ್ಕೆ ಸ್ಥಿರ ಸ್ಥಿತಿಯಿಲ್ಲ: ಅದು ತಾನಾಗಿಯೇ ಉನ್ನತ-ನಿಮ್ನ ನಡುವೆ ಬದಲಾಗುತ್ತಿರುತ್ತದೆ.')),
              Q(W('Between which voltages does the capacitor swing?', 'संधारित्र किन वोल्टताओं के बीच दोलन करता है?', 'ಧಾರಕ ಯಾವ ವೋಲ್ಟೇಜ್‌ಗಳ ನಡುವೆ ತೂಗಾಡುತ್ತದೆ?'), W('⅓ Vcc and ⅔ Vcc.', '⅓ Vcc और ⅔ Vcc.', '⅓ Vcc ಮತ್ತು ⅔ Vcc.')),
              Q(W('Give one use of an astable multivibrator.', 'अस्थिर बहुकंपित्र का एक उपयोग बताइए।', 'ಅಸ್ಥಿರ ಬಹುಕಂಪಕದ ಒಂದು ಉಪಯೋಗ ತಿಳಿಸಿ.'), W('Clock pulses, LED flashers, tone generators.', 'घड़ी स्पंद, LED फ़्लैशर, स्वर जनित्र।', 'ಗಡಿಯಾರ ಸ್ಪಂದನಗಳು, LED ಮಿನುಗುಕಗಳು, ಸ್ವರ ಜನಕಗಳು.'))],
    )

    # --------------------------------------------- current electricity
    lab(
        id='kirchhoff-laws', bench='kirchhoff', subject='Physics', domain='physics', levels=[12, 'ug'], curricula=['cbse', 'ka-puc', 'ug-physics'],
        keywords=["kirchhoff's laws", 'kirchhoff', 'current electricity', 'junction rule', 'loop rule', 'network'],
        title=W("Verification of Kirchhoff's laws", 'किरखॉफ़ के नियमों का सत्यापन', 'ಕಿರ್ಚಾಫ್ ನಿಯಮಗಳ ಪರಿಶೀಲನೆ'),
        summary=W('Measure the currents in a two-source network and check the junction and loop rules.', 'दो स्रोतों वाले जाल की धाराएँ मापें और संधि तथा पाश नियम जाँचें।', 'ಎರಡು ಮೂಲಗಳ ಜಾಲದ ಪ್ರವಾಹಗಳನ್ನು ಅಳೆದು ಸಂಧಿ ಮತ್ತು ಕುಣಿಕೆ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.'),
        aim=W("To verify Kirchhoff's current law and voltage law in a network with two sources.", 'दो स्रोतों वाले जाल में किरखॉफ़ के धारा नियम और वोल्टता नियम का सत्यापन करना।', 'ಎರಡು ಮೂಲಗಳ ಜಾಲದಲ್ಲಿ ಕಿರ್ಚಾಫ್‌ನ ಪ್ರವಾಹ ನಿಯಮ ಮತ್ತು ವೋಲ್ಟೇಜ್ ನಿಯಮ ಪರಿಶೀಲಿಸುವುದು.'),
        principle=W('Junction rule (KCL): the currents entering a junction add up to the currents leaving it (charge is conserved). Loop rule (KVL): round any closed loop the EMFs equal the sum of the IR drops (energy is conserved).',
                    'संधि नियम (KCL): किसी संधि में आने वाली धाराओं का योग उससे जाने वाली धाराओं के योग के बराबर है (आवेश संरक्षण)। पाश नियम (KVL): किसी भी बंद पाश में EMF का योग IR पातों के योग के बराबर है (ऊर्जा संरक्षण)।',
                    'ಸಂಧಿ ನಿಯಮ (KCL): ಸಂಧಿಗೆ ಬರುವ ಪ್ರವಾಹಗಳ ಮೊತ್ತ ಹೊರಹೋಗುವ ಪ್ರವಾಹಗಳ ಮೊತ್ತಕ್ಕೆ ಸಮ (ಆವೇಶ ಸಂರಕ್ಷಣೆ). ಕುಣಿಕೆ ನಿಯಮ (KVL): ಯಾವುದೇ ಮುಚ್ಚಿದ ಕುಣಿಕೆಯಲ್ಲಿ EMF ಗಳ ಮೊತ್ತ IR ಇಳಿತಗಳ ಮೊತ್ತಕ್ಕೆ ಸಮ (ಶಕ್ತಿ ಸಂರಕ್ಷಣೆ).'),
        apparatus=[W('Two DC supplies (or batteries)', 'दो DC आपूर्तियाँ (या बैटरियाँ)', 'ಎರಡು DC ಪೂರೈಕೆಗಳು (ಅಥವಾ ಬ್ಯಾಟರಿಗಳು)'), W('Three resistors', 'तीन प्रतिरोधक', 'ಮೂರು ರೋಧಕಗಳು'), W('Three milliammeters', 'तीन मिलीऐमीटर', 'ಮೂರು ಮಿಲಿಅಮ್ಮೀಟರ್‌ಗಳು'), VM, WIRES],
        steps=[W('Connect E1 with R1 and E2 with R2 so both feed a common junction; R3 goes from the junction back to the common return.', 'E1 को R1 के साथ और E2 को R2 के साथ ऐसे जोड़ें कि दोनों एक उभयनिष्ठ संधि को धारा दें; R3 संधि से उभयनिष्ठ वापसी तार तक।', 'E1 ಅನ್ನು R1 ಜೊತೆ, E2 ಅನ್ನು R2 ಜೊತೆ ಎರಡೂ ಸಾಮಾನ್ಯ ಸಂಧಿಗೆ ಪ್ರವಾಹ ನೀಡುವಂತೆ ಜೋಡಿಸಿ; R3 ಸಂಧಿಯಿಂದ ಸಾಮಾನ್ಯ ಹಿಂದಿರುಗುವ ತಂತಿಗೆ.'),
               W('Put a milliammeter in each branch and read I1, I2 and I3.', 'हर शाखा में मिलीऐमीटर लगाकर I1, I2 और I3 पढ़ें।', 'ಪ್ರತಿ ಶಾಖೆಯಲ್ಲಿ ಮಿಲಿಅಮ್ಮೀಟರ್ ಇಟ್ಟು I1, I2 ಮತ್ತು I3 ಓದಿ.'),
               W('Check I1 + I2 = I3 at the junction.', 'संधि पर I1 + I2 = I3 जाँचें।', 'ಸಂಧಿಯಲ್ಲಿ I1 + I2 = I3 ಪರಿಶೀಲಿಸಿ.'),
               W('Measure the voltage across each resistor and check E1 = I1R1 + I3R3 round loop 1 (and similarly loop 2).', 'हर प्रतिरोधक की वोल्टता मापें और पाश 1 में E1 = I1R1 + I3R3 जाँचें (और इसी तरह पाश 2)।', 'ಪ್ರತಿ ರೋಧಕಕ್ಕೆ ಅಡ್ಡ ವೋಲ್ಟೇಜ್ ಅಳೆದು ಕುಣಿಕೆ 1 ರಲ್ಲಿ E1 = I1R1 + I3R3 ಪರಿಶೀಲಿಸಿ (ಹಾಗೆಯೇ ಕುಣಿಕೆ 2).'),
               W('Repeat with other EMFs and resistors.', 'दूसरे EMF और प्रतिरोधकों के साथ दोहराएँ।', 'ಬೇರೆ EMF ಮತ್ತು ರೋಧಕಗಳೊಂದಿಗೆ ಪುನರಾವರ್ತಿಸಿ.')],
        precautions=[P_POLARITY, W('Use sources of low internal resistance, or include it in the loop sum.', 'कम आंतरिक प्रतिरोध वाले स्रोत लें, या उसे पाश योग में शामिल करें।', 'ಕಡಿಮೆ ಆಂತರಿಕ ರೋಧದ ಮೂಲಗಳನ್ನು ಬಳಸಿ, ಅಥವಾ ಅದನ್ನು ಕುಣಿಕೆ ಮೊತ್ತದಲ್ಲಿ ಸೇರಿಸಿ.'), P_SWITCH_OFF],
        conclusion=W("Within meter accuracy the currents at the junction balance and the voltages round each loop add to zero: Kirchhoff's laws hold.", 'मीटर की परिशुद्धता के भीतर संधि पर धाराएँ संतुलित होती हैं और हर पाश में वोल्टताओं का योग शून्य होता है: किरखॉफ़ के नियम सत्य हैं।', 'ಮೀಟರ್ ನಿಖರತೆಯೊಳಗೆ ಸಂಧಿಯಲ್ಲಿ ಪ್ರವಾಹಗಳು ಸಮತೋಲಿತ, ಪ್ರತಿ ಕುಣಿಕೆಯಲ್ಲಿ ವೋಲ್ಟೇಜ್‌ಗಳ ಮೊತ್ತ ಶೂನ್ಯ: ಕಿರ್ಚಾಫ್ ನಿಯಮಗಳು ಸತ್ಯ.'),
        viva=[Q(W('Which conservation law is behind KCL?', 'KCL के पीछे कौन-सा संरक्षण नियम है?', 'KCL ಹಿಂದಿರುವ ಸಂರಕ್ಷಣಾ ನಿಯಮ ಯಾವುದು?'), W('Conservation of charge.', 'आवेश संरक्षण।', 'ಆವೇಶ ಸಂರಕ್ಷಣೆ.')),
              Q(W('Which conservation law is behind KVL?', 'KVL के पीछे कौन-सा संरक्षण नियम है?', 'KVL ಹಿಂದಿರುವ ಸಂರಕ್ಷಣಾ ನಿಯಮ ಯಾವುದು?'), W('Conservation of energy.', 'ऊर्जा संरक्षण।', 'ಶಕ್ತಿ ಸಂರಕ್ಷಣೆ.')),
              Q(W('What does a negative current in your answer mean?', 'उत्तर में ऋणात्मक धारा का क्या अर्थ है?', 'ಉತ್ತರದಲ್ಲಿ ಋಣ ಪ್ರವಾಹದ ಅರ್ಥವೇನು?'), W('The current flows opposite to the direction assumed.', 'धारा मानी गई दिशा के विपरीत बहती है।', 'ಪ್ರವಾಹ ಊಹಿಸಿದ ದಿಕ್ಕಿಗೆ ವಿರುದ್ಧವಾಗಿ ಹರಿಯುತ್ತದೆ.'))],
    )

    lab(
        id='meter-bridge', bench='meter-bridge', subject='Physics', domain='physics', levels=[12], curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['meter bridge', 'metre bridge', 'wheatstone bridge', 'resistivity', 'specific resistance', 'current electricity', 'null point'],
        title=W('Resistivity of a wire with a metre bridge', 'मीटर सेतु से तार की प्रतिरोधकता', 'ಮೀಟರ್ ಸೇತುವೆಯಿಂದ ತಂತಿಯ ರೋಧಕತೆ'),
        summary=W('Find the null point of a metre bridge for several known resistances, then the unknown resistance and the resistivity of its wire.',
                  'कई ज्ञात प्रतिरोधों के लिए मीटर सेतु का शून्य विक्षेप बिंदु ज्ञात करें, फिर अज्ञात प्रतिरोध और उसके तार की प्रतिरोधकता।',
                  'ಹಲವು ತಿಳಿದ ರೋಧಗಳಿಗೆ ಮೀಟರ್ ಸೇತುವೆಯ ಶೂನ್ಯ ಬಿಂದು ಕಂಡುಹಿಡಿದು, ಅಜ್ಞಾತ ರೋಧ ಮತ್ತು ಅದರ ತಂತಿಯ ರೋಧಕತೆ ಪಡೆಯಿರಿ.'),
        aim=W('To find the resistance of a given wire using a metre bridge and hence the resistivity of its material.', 'मीटर सेतु से दिए गए तार का प्रतिरोध और उससे उसके पदार्थ की प्रतिरोधकता ज्ञात करना।', 'ಮೀಟರ್ ಸೇತುವೆಯಿಂದ ಕೊಟ್ಟ ತಂತಿಯ ರೋಧ ಮತ್ತು ಆ ಮೂಲಕ ಅದರ ವಸ್ತುವಿನ ರೋಧಕತೆ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('A metre bridge is a Wheatstone bridge whose ratio arms are the two parts of a uniform 1 m wire. At the null point (no galvanometer current) R ÷ X = l ÷ (100 − l), so X = R(100 − l) ÷ l. The resistivity is ρ = Xπr² ÷ L for a wire of length L and radius r.',
                    'मीटर सेतु एक व्हीटस्टोन सेतु है जिसकी अनुपात भुजाएँ 1 m के एकसमान तार के दो भाग हैं। शून्य विक्षेप बिंदु पर (गैल्वेनोमीटर में धारा नहीं) R ÷ X = l ÷ (100 − l), इसलिए X = R(100 − l) ÷ l. लंबाई L और त्रिज्या r के तार की प्रतिरोधकता ρ = Xπr² ÷ L है।',
                    'ಮೀಟರ್ ಸೇತುವೆ ಒಂದು ವೀಟ್‌ಸ್ಟೋನ್ ಸೇತುವೆ; ಅದರ ಅನುಪಾತ ಭುಜಗಳು 1 m ಏಕರೂಪ ತಂತಿಯ ಎರಡು ಭಾಗಗಳು. ಶೂನ್ಯ ಬಿಂದುವಿನಲ್ಲಿ (ಗ್ಯಾಲ್ವನೋಮೀಟರ್‌ನಲ್ಲಿ ಪ್ರವಾಹವಿಲ್ಲ) R ÷ X = l ÷ (100 − l); ಆದ್ದರಿಂದ X = R(100 − l) ÷ l. ಉದ್ದ L ಮತ್ತು ತ್ರಿಜ್ಯ r ಇರುವ ತಂತಿಯ ರೋಧಕತೆ ρ = Xπr² ÷ L.'),
        apparatus=[W('Metre bridge', 'मीटर सेतु', 'ಮೀಟರ್ ಸೇತುವೆ'), W('Wire of unknown resistance', 'अज्ञात प्रतिरोध का तार', 'ಅಜ್ಞಾತ ರೋಧದ ತಂತಿ'), RBOX, GALV, JOCKEY,
                   W('Leclanché cell and plug key', 'लेक्लांशे सेल और प्लग कुंजी', 'ಲೆಕ್ಲಾಂಶೆ ಕೋಶ ಮತ್ತು ಪ್ಲಗ್ ಕೀ'), W('Screw gauge and metre scale', 'पेंच गेज और मीटर पैमाना', 'ಸ್ಕ್ರೂ ಗೇಜ್ ಮತ್ತು ಮೀಟರ್ ಅಳತೆಪಟ್ಟಿ')],
        steps=[W('Put the resistance box in the left gap and the wire in the right gap. Connect the cell and key across the ends of the bridge wire.', 'प्रतिरोध बॉक्स बाएँ अंतराल में और तार दाएँ अंतराल में लगाएँ। सेल और कुंजी को सेतु तार के सिरों पर जोड़ें।', 'ರೋಧ ಪೆಟ್ಟಿಗೆಯನ್ನು ಎಡ ಅಂತರದಲ್ಲಿ, ತಂತಿಯನ್ನು ಬಲ ಅಂತರದಲ್ಲಿ ಇಡಿ. ಕೋಶ ಮತ್ತು ಕೀಯನ್ನು ಸೇತು ತಂತಿಯ ತುದಿಗಳಿಗೆ ಜೋಡಿಸಿ.'),
               W('Connect the galvanometer between the middle strip and the jockey.', 'गैल्वेनोमीटर को बीच की पट्टी और जॉकी के बीच जोड़ें।', 'ಗ್ಯಾಲ್ವನೋಮೀಟರನ್ನು ಮಧ್ಯದ ಪಟ್ಟಿ ಮತ್ತು ಜಾಕಿಯ ನಡುವೆ ಜೋಡಿಸಿ.'),
               W('Take out a resistance R, put the key in, and touch the jockey along the wire until the galvanometer shows no deflection. Read l.', 'एक प्रतिरोध R निकालें, कुंजी लगाएँ, और जॉकी को तार पर छुआते चलें जब तक गैल्वेनोमीटर में विक्षेप न रहे। l पढ़ें।', 'ಒಂದು ರೋಧ R ತೆಗೆದು, ಕೀ ಹಾಕಿ, ಗ್ಯಾಲ್ವನೋಮೀಟರ್ ವಿಚಲನೆ ತೋರದವರೆಗೆ ಜಾಕಿಯನ್ನು ತಂತಿಯ ಮೇಲೆ ಮುಟ್ಟಿಸುತ್ತಾ ಹೋಗಿ. l ಓದಿ.'),
               W('Repeat for four or five values of R, keeping the null point between 30 and 70 cm.', 'R के चार-पाँच मानों के लिए दोहराएँ, शून्य बिंदु 30 और 70 cm के बीच रखें।', 'R ನ ನಾಲ್ಕು-ಐದು ಮೌಲ್ಯಗಳಿಗೆ ಪುನರಾವರ್ತಿಸಿ; ಶೂನ್ಯ ಬಿಂದು 30 ರಿಂದ 70 cm ನಡುವೆ ಇರಲಿ.'),
               W('Measure the length and diameter of the wire and work out its resistivity.', 'तार की लंबाई और व्यास मापें और उसकी प्रतिरोधकता निकालें।', 'ತಂತಿಯ ಉದ್ದ ಮತ್ತು ವ್ಯಾಸ ಅಳೆದು ಅದರ ರೋಧಕತೆ ಲೆಕ್ಕಿಸಿ.')],
        precautions=[W('Touch the jockey gently; do not slide it along the wire.', 'जॉकी को हल्के से छुआएँ; उसे तार पर घसीटें नहीं।', 'ಜಾಕಿಯನ್ನು ಮೃದುವಾಗಿ ಮುಟ್ಟಿಸಿ; ತಂತಿಯ ಮೇಲೆ ಎಳೆಯಬೇಡಿ.'),
                     W('Take the key out between readings so the wire does not heat.', 'पाठ्यांकों के बीच कुंजी निकाल दें ताकि तार गरम न हो।', 'ತಂತಿ ಬಿಸಿಯಾಗದಂತೆ ಓದುಗಳ ನಡುವೆ ಕೀ ತೆಗೆಯಿರಿ.'),
                     W('Keep the null point near the middle of the wire to reduce end errors.', 'सिरे की त्रुटियाँ घटाने के लिए शून्य बिंदु तार के बीच के पास रखें।', 'ಅಂಚಿನ ದೋಷ ಕಡಿಮೆಗೊಳಿಸಲು ಶೂನ್ಯ ಬಿಂದುವನ್ನು ತಂತಿಯ ಮಧ್ಯದ ಹತ್ತಿರ ಇಡಿ.')],
        conclusion=W('The unknown resistance comes out the same for every R (within error), and its resistivity agrees with the table value for the material.', 'हर R के लिए अज्ञात प्रतिरोध (त्रुटि के भीतर) समान आता है, और उसकी प्रतिरोधकता पदार्थ के सारणी मान से मेल खाती है।', 'ಪ್ರತಿ R ಗೂ ಅಜ್ಞಾತ ರೋಧ (ದೋಷದೊಳಗೆ) ಒಂದೇ ಬರುತ್ತದೆ; ಅದರ ರೋಧಕತೆ ವಸ್ತುವಿನ ಕೋಷ್ಟಕ ಮೌಲ್ಯಕ್ಕೆ ಹೊಂದುತ್ತದೆ.'),
        viva=[Q(W('Why is the bridge most sensitive when the null point is near the middle?', 'शून्य बिंदु बीच के पास होने पर सेतु सबसे सुग्राही क्यों होता है?', 'ಶೂನ್ಯ ಬಿಂದು ಮಧ್ಯದ ಹತ್ತಿರ ಇದ್ದಾಗ ಸೇತುವೆ ಅತಿ ಸಂವೇದಿ ಏಕೆ?'), W('All four arms are then of similar resistance, and end resistances matter least.', 'तब चारों भुजाओं का प्रतिरोध लगभग समान होता है, और सिरों के प्रतिरोध का प्रभाव सबसे कम होता है।', 'ಆಗ ನಾಲ್ಕೂ ಭುಜಗಳ ರೋಧ ಸುಮಾರು ಸಮ; ಅಂಚಿನ ರೋಧಗಳ ಪ್ರಭಾವ ಕನಿಷ್ಠ.')),
              Q(W('Why is the bridge wire made of manganin or constantan?', 'सेतु तार मैंगनिन या कॉन्सटैंटन का क्यों बनाते हैं?', 'ಸೇತು ತಂತಿಯನ್ನು ಮ್ಯಾಂಗನಿನ್ ಅಥವಾ ಕಾನ್‌ಸ್ಟಂಟನ್‌ನಿಂದ ಏಕೆ ಮಾಡುತ್ತಾರೆ?'), W('High resistivity and very small change of resistance with temperature.', 'उच्च प्रतिरोधकता और ताप के साथ प्रतिरोध में बहुत कम परिवर्तन।', 'ಹೆಚ್ಚು ರೋಧಕತೆ ಮತ್ತು ತಾಪದೊಂದಿಗೆ ರೋಧದಲ್ಲಿ ಅತಿ ಕಡಿಮೆ ಬದಲಾವಣೆ.')),
              Q(W('Does resistivity depend on the length of the wire?', 'क्या प्रतिरोधकता तार की लंबाई पर निर्भर करती है?', 'ರೋಧಕತೆ ತಂತಿಯ ಉದ್ದವನ್ನು ಅವಲಂಬಿಸುತ್ತದೆಯೇ?'), W('No; it depends only on the material and temperature.', 'नहीं; यह केवल पदार्थ और ताप पर निर्भर करती है।', 'ಇಲ್ಲ; ಅದು ವಸ್ತು ಮತ್ತು ತಾಪವನ್ನು ಮಾತ್ರ ಅವಲಂಬಿಸುತ್ತದೆ.'))],
    )

    POT_APP = [W('Potentiometer (4 wires of 1 m)', 'विभवमापी (1 m के 4 तार)', 'ವಿಭವಮಾಪಕ (1 m ನ 4 ತಂತಿಗಳು)'), W('Battery of two accumulators (4 V)', 'दो संचायकों की बैटरी (4 V)', 'ಎರಡು ಸಂಚಯಕಗಳ ಬ್ಯಾಟರಿ (4 V)'), RHEO, GALV, JOCKEY, KEY]
    POT_PRE = [W('The EMF of the driver battery must be greater than that of the cell, and + terminals must be joined to the same end of the wire.', 'चालक बैटरी का EMF सेल से अधिक हो, और + सिरे तार के एक ही छोर से जुड़े हों।', 'ಚಾಲಕ ಬ್ಯಾಟರಿಯ EMF ಕೋಶಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು; + ತುದಿಗಳು ತಂತಿಯ ಒಂದೇ ತುದಿಗೆ ಜೋಡಿಸಿರಬೇಕು.'),
               W('Do not change the rheostat between the readings that are to be compared.', 'जिन पाठ्यांकों की तुलना करनी है उनके बीच रिओस्टेट न बदलें।', 'ಹೋಲಿಸಬೇಕಾದ ಓದುಗಳ ನಡುವೆ ರಿಯೋಸ್ಟಾಟ್ ಬದಲಿಸಬೇಡಿ.'),
               W('Touch the jockey gently and only for a moment.', 'जॉकी को हल्के से और केवल क्षण भर छुआएँ।', 'ಜಾಕಿಯನ್ನು ಮೃದುವಾಗಿ, ಕ್ಷಣಮಾತ್ರ ಮುಟ್ಟಿಸಿ.')]
    lab(
        id='potentiometer-emf', bench='potentiometer', setup={'task': 'compare'}, subject='Physics', domain='physics', levels=[12], curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['potentiometer', 'emf', 'compare emf', 'electromotive force', 'current electricity', 'null point', 'potential gradient'],
        title=W('Comparing the EMFs of two cells (potentiometer)', 'दो सेलों के EMF की तुलना (विभवमापी)', 'ಎರಡು ಕೋಶಗಳ EMF ಹೋಲಿಕೆ (ವಿಭವಮಾಪಕ)'),
        summary=W('Balance a Leclanché cell and a Daniell cell on a potentiometer wire and compare their EMFs from the balancing lengths.', 'लेक्लांशे और डेनियल सेल को विभवमापी तार पर संतुलित करें और संतुलन लंबाइयों से उनके EMF की तुलना करें।', 'ಲೆಕ್ಲಾಂಶೆ ಮತ್ತು ಡೇನಿಯಲ್ ಕೋಶಗಳನ್ನು ವಿಭವಮಾಪಕ ತಂತಿಯಲ್ಲಿ ಸಮತೋಲಿಸಿ, ಸಮತೋಲನ ಉದ್ದಗಳಿಂದ ಅವುಗಳ EMF ಹೋಲಿಸಿ.'),
        aim=W('To compare the EMFs of two primary cells using a potentiometer.', 'विभवमापी से दो प्राथमिक सेलों के EMF की तुलना करना।', 'ವಿಭವಮಾಪಕದಿಂದ ಎರಡು ಪ್ರಾಥಮಿಕ ಕೋಶಗಳ EMF ಹೋಲಿಸುವುದು.'),
        principle=W('A steady current in a uniform wire makes the potential fall evenly along it: V = kl. At the balance point no current is drawn from the cell, so its full EMF is measured: E = kl. For two cells E₁ ÷ E₂ = l₁ ÷ l₂.', 'एकसमान तार में स्थिर धारा से उसके साथ विभव समान रूप से गिरता है: V = kl. संतुलन बिंदु पर सेल से कोई धारा नहीं ली जाती, इसलिए उसका पूरा EMF मापा जाता है: E = kl. दो सेलों के लिए E₁ ÷ E₂ = l₁ ÷ l₂.', 'ಏಕರೂಪ ತಂತಿಯಲ್ಲಿ ಸ್ಥಿರ ಪ್ರವಾಹವಿದ್ದರೆ ಅದರ ಉದ್ದಕ್ಕೂ ವಿಭವ ಸಮವಾಗಿ ಇಳಿಯುತ್ತದೆ: V = kl. ಸಮತೋಲನ ಬಿಂದುವಿನಲ್ಲಿ ಕೋಶದಿಂದ ಪ್ರವಾಹ ತೆಗೆಯುವುದಿಲ್ಲ; ಆದ್ದರಿಂದ ಅದರ ಪೂರ್ಣ EMF ಅಳೆಯಲ್ಪಡುತ್ತದೆ: E = kl. ಎರಡು ಕೋಶಗಳಿಗೆ E₁ ÷ E₂ = l₁ ÷ l₂.'),
        apparatus=POT_APP + [W('Leclanché cell and Daniell cell with a two-way key', 'द्विमार्गी कुंजी सहित लेक्लांशे और डेनियल सेल', 'ಎರಡು-ದಾರಿ ಕೀ ಸಹಿತ ಲೆಕ್ಲಾಂಶೆ ಮತ್ತು ಡೇನಿಯಲ್ ಕೋಶಗಳು')],
        steps=[W('Connect the driver battery, key and rheostat across the ends of the potentiometer wire (+ to end A).', 'चालक बैटरी, कुंजी और रिओस्टेट को विभवमापी तार के सिरों पर जोड़ें (+ सिरा A पर)।', 'ಚಾಲಕ ಬ್ಯಾಟರಿ, ಕೀ ಮತ್ತು ರಿಯೋಸ್ಟಾಟನ್ನು ವಿಭವಮಾಪಕ ತಂತಿಯ ತುದಿಗಳಿಗೆ ಜೋಡಿಸಿ (+ ತುದಿ A ಗೆ).'),
               W('Join the + terminals of both cells to A; their − terminals go through the two-way key and galvanometer to the jockey.', 'दोनों सेलों के + सिरे A से जोड़ें; उनके − सिरे द्विमार्गी कुंजी और गैल्वेनोमीटर से होते हुए जॉकी तक।', 'ಎರಡೂ ಕೋಶಗಳ + ತುದಿಗಳನ್ನು A ಗೆ ಜೋಡಿಸಿ; ಅವುಗಳ − ತುದಿಗಳು ಎರಡು-ದಾರಿ ಕೀ ಮತ್ತು ಗ್ಯಾಲ್ವನೋಮೀಟರ್ ಮೂಲಕ ಜಾಕಿಗೆ.'),
               W('With cell 1 in circuit, find the balancing length l₁.', 'सेल 1 को परिपथ में रखकर संतुलन लंबाई l₁ ज्ञात करें।', 'ಕೋಶ 1 ಮಂಡಲದಲ್ಲಿದ್ದಾಗ ಸಮತೋಲನ ಉದ್ದ l₁ ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Switch to cell 2 without touching the rheostat and find l₂.', 'रिओस्टेट को छुए बिना सेल 2 पर बदलें और l₂ ज्ञात करें।', 'ರಿಯೋಸ್ಟಾಟ್ ಮುಟ್ಟದೆ ಕೋಶ 2 ಕ್ಕೆ ಬದಲಿಸಿ l₂ ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Repeat for two more rheostat settings and find E₁ ÷ E₂ each time.', 'रिओस्टेट की दो और स्थितियों के लिए दोहराएँ और हर बार E₁ ÷ E₂ ज्ञात करें।', 'ರಿಯೋಸ್ಟಾಟ್‌ನ ಇನ್ನೆರಡು ಸ್ಥಾನಗಳಿಗೆ ಪುನರಾವರ್ತಿಸಿ ಪ್ರತಿ ಬಾರಿ E₁ ÷ E₂ ಕಂಡುಹಿಡಿಯಿರಿ.')],
        precautions=POT_PRE,
        conclusion=W('The ratio l₁ ÷ l₂ stays the same for every rheostat setting and gives E₁ ÷ E₂ ≈ 1.39 for a Leclanché and a Daniell cell.', 'अनुपात l₁ ÷ l₂ रिओस्टेट की हर स्थिति में समान रहता है और लेक्लांशे तथा डेनियल सेल के लिए E₁ ÷ E₂ ≈ 1.39 देता है।', 'ಅನುಪಾತ l₁ ÷ l₂ ರಿಯೋಸ್ಟಾಟ್‌ನ ಪ್ರತಿ ಸ್ಥಾನದಲ್ಲೂ ಒಂದೇ; ಲೆಕ್ಲಾಂಶೆ ಮತ್ತು ಡೇನಿಯಲ್ ಕೋಶಗಳಿಗೆ E₁ ÷ E₂ ≈ 1.39 ನೀಡುತ್ತದೆ.'),
        viva=[Q(W('Why is a potentiometer better than a voltmeter for measuring EMF?', 'EMF मापने के लिए विभवमापी वोल्टमीटर से अच्छा क्यों है?', 'EMF ಅಳೆಯಲು ವಿಭವಮಾಪಕ ವೋಲ್ಟ್‌ಮೀಟರ್‌ಗಿಂತ ಉತ್ತಮ ಏಕೆ?'), W('At balance it draws no current from the cell, so it measures the EMF and not the terminal voltage.', 'संतुलन पर यह सेल से कोई धारा नहीं लेता, इसलिए टर्मिनल वोल्टता नहीं, EMF मापता है।', 'ಸಮತೋಲನದಲ್ಲಿ ಅದು ಕೋಶದಿಂದ ಪ್ರವಾಹ ತೆಗೆಯುವುದಿಲ್ಲ; ಆದ್ದರಿಂದ ತುದಿ ವೋಲ್ಟೇಜ್ ಅಲ್ಲ, EMF ಅಳೆಯುತ್ತದೆ.')),
              Q(W('What is the potential gradient?', 'विभव प्रवणता क्या है?', 'ವಿಭವ ಪ್ರವಣತೆ ಎಂದರೇನು?'), W('The fall of potential per unit length of the wire, k.', 'तार की प्रति इकाई लंबाई में विभव का पतन, k.', 'ತಂತಿಯ ಪ್ರತಿ ಏಕಮಾನ ಉದ್ದಕ್ಕೆ ವಿಭವದ ಇಳಿತ, k.')),
              Q(W('Why might you find no null point at all?', 'हो सकता है कोई शून्य बिंदु न मिले, क्यों?', 'ಶೂನ್ಯ ಬಿಂದು ಸಿಗದೇ ಇರಬಹುದು, ಏಕೆ?'), W('The potential across the whole wire is less than the cell’s EMF, or the + terminals are not joined to the same end.', 'पूरे तार का विभव सेल के EMF से कम है, या + सिरे एक ही छोर से नहीं जुड़े।', 'ಇಡೀ ತಂತಿಯ ವಿಭವ ಕೋಶದ EMF ಗಿಂತ ಕಡಿಮೆ, ಅಥವಾ + ತುದಿಗಳು ಒಂದೇ ತುದಿಗೆ ಜೋಡಿಸಿಲ್ಲ.'))],
    )

    lab(
        id='potentiometer-internal-resistance', bench='potentiometer', setup={'task': 'internal'}, subject='Physics', domain='physics', levels=[12], curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['potentiometer', 'internal resistance', 'cell', 'emf', 'terminal voltage', 'current electricity'],
        title=W('Internal resistance of a cell (potentiometer)', 'सेल का आंतरिक प्रतिरोध (विभवमापी)', 'ಕೋಶದ ಆಂತರಿಕ ರೋಧ (ವಿಭವಮಾಪಕ)'),
        summary=W('Balance a cell on open circuit and then while it drives a known resistance; the two lengths give its internal resistance.', 'सेल को खुले परिपथ में और फिर ज्ञात प्रतिरोध को धारा देते हुए संतुलित करें; दोनों लंबाइयों से उसका आंतरिक प्रतिरोध मिलता है।', 'ಕೋಶವನ್ನು ತೆರೆದ ಮಂಡಲದಲ್ಲಿ ಮತ್ತು ನಂತರ ತಿಳಿದ ರೋಧಕ್ಕೆ ಪ್ರವಾಹ ನೀಡುವಾಗ ಸಮತೋಲಿಸಿ; ಎರಡು ಉದ್ದಗಳು ಅದರ ಆಂತರಿಕ ರೋಧ ನೀಡುತ್ತವೆ.'),
        aim=W('To find the internal resistance of a primary cell using a potentiometer.', 'विभवमापी से प्राथमिक सेल का आंतरिक प्रतिरोध ज्ञात करना।', 'ವಿಭವಮಾಪಕದಿಂದ ಪ್ರಾಥಮಿಕ ಕೋಶದ ಆಂತರಿಕ ರೋಧ ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('With K₂ open the balancing length l₁ measures the EMF: E = kl₁. With a resistance R across the cell, it delivers current and the terminal voltage V = kl₂ is less. Since E ÷ V = (R + r) ÷ R, the internal resistance is r = R(l₁ − l₂) ÷ l₂.', 'K₂ खुली होने पर संतुलन लंबाई l₁ EMF मापती है: E = kl₁. सेल के सिरों पर प्रतिरोध R लगाने पर वह धारा देता है और टर्मिनल वोल्टता V = kl₂ कम हो जाती है। क्योंकि E ÷ V = (R + r) ÷ R, आंतरिक प्रतिरोध r = R(l₁ − l₂) ÷ l₂ है।', 'K₂ ತೆರೆದಿದ್ದಾಗ ಸಮತೋಲನ ಉದ್ದ l₁ EMF ಅಳೆಯುತ್ತದೆ: E = kl₁. ಕೋಶಕ್ಕೆ ಅಡ್ಡ ರೋಧ R ಇದ್ದಾಗ ಅದು ಪ್ರವಾಹ ನೀಡುತ್ತದೆ; ತುದಿ ವೋಲ್ಟೇಜ್ V = kl₂ ಕಡಿಮೆ. E ÷ V = (R + r) ÷ R ಆದ್ದರಿಂದ ಆಂತರಿಕ ರೋಧ r = R(l₁ − l₂) ÷ l₂.'),
        apparatus=POT_APP + [W('Leclanché cell', 'लेक्लांशे सेल', 'ಲೆಕ್ಲಾಂಶೆ ಕೋಶ'), RBOX, W('Second plug key K₂', 'दूसरी प्लग कुंजी K₂', 'ಎರಡನೇ ಪ್ಲಗ್ ಕೀ K₂')],
        steps=[W('Set up the driver circuit across the wire. Connect the cell (+ to A) through the galvanometer to the jockey, with the resistance box and K₂ across the cell.', 'तार पर चालक परिपथ लगाएँ। सेल (+ को A से) गैल्वेनोमीटर से होते हुए जॉकी तक जोड़ें, प्रतिरोध बॉक्स और K₂ सेल के सिरों पर।', 'ತಂತಿಗೆ ಅಡ್ಡ ಚಾಲಕ ಮಂಡಲ ಜೋಡಿಸಿ. ಕೋಶವನ್ನು (+ A ಗೆ) ಗ್ಯಾಲ್ವನೋಮೀಟರ್ ಮೂಲಕ ಜಾಕಿಗೆ ಜೋಡಿಸಿ; ರೋಧ ಪೆಟ್ಟಿಗೆ ಮತ್ತು K₂ ಕೋಶಕ್ಕೆ ಅಡ್ಡಲಾಗಿ.'),
               W('With K₂ open, find the balancing length l₁.', 'K₂ खुली रखकर संतुलन लंबाई l₁ ज्ञात करें।', 'K₂ ತೆರೆದಿಟ್ಟು ಸಮತೋಲನ ಉದ್ದ l₁ ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Take out R = 2 Ω from the box, close K₂ and find l₂ at once.', 'बॉक्स से R = 2 Ω निकालें, K₂ बंद करें और तुरंत l₂ ज्ञात करें।', 'ಪೆಟ್ಟಿಗೆಯಿಂದ R = 2 Ω ತೆಗೆದು, K₂ ಮುಚ್ಚಿ ತಕ್ಷಣ l₂ ಕಂಡುಹಿಡಿಯಿರಿ.'),
               W('Repeat for R = 5 Ω and 10 Ω, checking l₁ again each time.', 'R = 5 Ω और 10 Ω के लिए दोहराएँ, हर बार l₁ फिर जाँचें।', 'R = 5 Ω ಮತ್ತು 10 Ω ಗೆ ಪುನರಾವರ್ತಿಸಿ, ಪ್ರತಿ ಬಾರಿ l₁ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.'),
               W('Work out r = R(l₁ − l₂) ÷ l₂ for each R and take the mean.', 'हर R के लिए r = R(l₁ − l₂) ÷ l₂ निकालें और माध्य लें।', 'ಪ್ರತಿ R ಗೆ r = R(l₁ − l₂) ÷ l₂ ಲೆಕ್ಕಿಸಿ ಸರಾಸರಿ ತೆಗೆಯಿರಿ.')],
        precautions=POT_PRE + [W('Close K₂ only while finding l₂: the cell runs down while it supplies current.', 'K₂ केवल l₂ ज्ञात करते समय बंद करें: धारा देते समय सेल क्षीण होता है।', 'l₂ ಕಂಡುಹಿಡಿಯುವಾಗ ಮಾತ್ರ K₂ ಮುಚ್ಚಿ: ಪ್ರವಾಹ ನೀಡುವಾಗ ಕೋಶ ಕ್ಷೀಣಿಸುತ್ತದೆ.')],
        conclusion=W('The balancing length is shorter when the cell supplies current; r = R(l₁ − l₂) ÷ l₂ comes out about the same for each R, about 1 Ω for a Leclanché cell.', 'सेल के धारा देने पर संतुलन लंबाई छोटी होती है; r = R(l₁ − l₂) ÷ l₂ हर R के लिए लगभग समान, लेक्लांशे सेल के लिए लगभग 1 Ω आता है।', 'ಕೋಶ ಪ್ರವಾಹ ನೀಡುವಾಗ ಸಮತೋಲನ ಉದ್ದ ಕಡಿಮೆ; r = R(l₁ − l₂) ÷ l₂ ಪ್ರತಿ R ಗೂ ಸುಮಾರು ಒಂದೇ, ಲೆಕ್ಲಾಂಶೆ ಕೋಶಕ್ಕೆ ಸುಮಾರು 1 Ω.'),
        viva=[Q(W('Why is l₂ less than l₁?', 'l₂, l₁ से कम क्यों है?', 'l₂, l₁ ಗಿಂತ ಕಡಿಮೆ ಏಕೆ?'), W('Some EMF is lost as Ir inside the cell, so the terminal voltage is less than the EMF.', 'सेल के भीतर कुछ EMF, Ir के रूप में खो जाता है, इसलिए टर्मिनल वोल्टता EMF से कम है।', 'ಕೋಶದೊಳಗೆ ಸ್ವಲ್ಪ EMF, Ir ಆಗಿ ನಷ್ಟವಾಗುತ್ತದೆ; ಆದ್ದರಿಂದ ತುದಿ ವೋಲ್ಟೇಜ್ EMF ಗಿಂತ ಕಡಿಮೆ.')),
              Q(W('On what does the internal resistance of a cell depend?', 'सेल का आंतरिक प्रतिरोध किन पर निर्भर करता है?', 'ಕೋಶದ ಆಂತರಿಕ ರೋಧ ಯಾವುದನ್ನು ಅವಲಂಬಿಸುತ್ತದೆ?'), W('The electrolyte and its concentration, the distance between and area of the electrodes, and temperature.', 'विद्युत-अपघट्य और उसकी सांद्रता, इलेक्ट्रोडों के बीच की दूरी तथा क्षेत्रफल, और ताप।', 'ವಿದ್ಯುದ್ವಿಭಾಜ್ಯ ಮತ್ತು ಅದರ ಸಾಂದ್ರತೆ, ವಿದ್ಯುದ್ವಾರಗಳ ನಡುವಿನ ದೂರ ಮತ್ತು ವಿಸ್ತೀರ್ಣ, ಹಾಗೂ ತಾಪ.')),
              Q(W('Why should a car battery have a very small internal resistance?', 'कार की बैटरी का आंतरिक प्रतिरोध बहुत कम क्यों होना चाहिए?', 'ಕಾರಿನ ಬ್ಯಾಟರಿಯ ಆಂತರಿಕ ರೋಧ ಅತಿ ಕಡಿಮೆ ಏಕೆ ಇರಬೇಕು?'), W('To give the very large current the starter motor needs without a big voltage drop.', 'बड़ी वोल्टता गिरावट के बिना स्टार्टर मोटर को चाहिए बहुत बड़ी धारा देने के लिए।', 'ದೊಡ್ಡ ವೋಲ್ಟೇಜ್ ಇಳಿತವಿಲ್ಲದೆ ಸ್ಟಾರ್ಟರ್ ಮೋಟಾರ್‌ಗೆ ಬೇಕಾದ ಅತಿ ದೊಡ್ಡ ಪ್ರವಾಹ ನೀಡಲು.'))],
    )
