"""The five simulations built as their own widgets (lib/src/labs/): free
exploration, so mode 'explore' and bench 'sim'. Their ids are the ones lesson
content already links (lab.ohms-law, lab.lens-mirror, ...)."""


def add(lab, W, Q):
    lab(
        id='lab.ohms-law', bench='sim', subject='Physics', domain='physics', levels=[10, 12], mode='explore', curricula=['cbse', 'ncert', 'ka-sslc'],
        keywords=['electricity', "ohm's law", 'series', 'parallel', 'equivalent resistance', 'circuit'],
        title=W("Ohm's law and resistances", 'ओम का नियम और प्रतिरोध', 'ಓಮ್‌ನ ನಿಯಮ ಮತ್ತು ರೋಧಗಳು'),
        summary=W('Build a circuit with one to three resistors in series or parallel and watch the V–I graph grow.',
                  'एक से तीन प्रतिरोधकों को श्रेणी या पार्श्व में जोड़कर परिपथ बनाएँ और V–I ग्राफ़ बनते देखें।',
                  'ಒಂದರಿಂದ ಮೂರು ರೋಧಕಗಳನ್ನು ಸರಣಿ ಅಥವಾ ಸಮಾಂತರದಲ್ಲಿ ಜೋಡಿಸಿ ಮಂಡಲ ರಚಿಸಿ, V–I ನಕ್ಷೆ ಬೆಳೆಯುವುದನ್ನು ನೋಡಿ.'),
        aim=W('To explore how current depends on voltage, and how resistors combine in series and in parallel.',
              'यह खोजना कि धारा वोल्टता पर कैसे निर्भर करती है, और प्रतिरोधक श्रेणी और पार्श्व में कैसे जुड़ते हैं।',
              'ಪ್ರವಾಹವು ವೋಲ್ಟೇಜ್ ಮೇಲೆ ಹೇಗೆ ಅವಲಂಬಿಸಿದೆ ಮತ್ತು ರೋಧಕಗಳು ಸರಣಿ ಹಾಗೂ ಸಮಾಂತರದಲ್ಲಿ ಹೇಗೆ ಸೇರುತ್ತವೆ ಎಂದು ಅನ್ವೇಷಿಸುವುದು.'),
        principle=W("Ohm's law: V = IR. In series the resistances add (R = R₁ + R₂ + …); in parallel the reciprocals add (1/R = 1/R₁ + 1/R₂ + …), so the total is less than the smallest.",
                    'ओम का नियम: V = IR. श्रेणी में प्रतिरोध जुड़ते हैं (R = R₁ + R₂ + …); पार्श्व में उनके व्युत्क्रम जुड़ते हैं (1/R = 1/R₁ + 1/R₂ + …), इसलिए कुल प्रतिरोध सबसे छोटे से भी कम होता है।',
                    'ಓಮ್‌ನ ನಿಯಮ: V = IR. ಸರಣಿಯಲ್ಲಿ ರೋಧಗಳು ಕೂಡುತ್ತವೆ (R = R₁ + R₂ + …); ಸಮಾಂತರದಲ್ಲಿ ಅವುಗಳ ವಿಲೋಮಗಳು ಕೂಡುತ್ತವೆ (1/R = 1/R₁ + 1/R₂ + …), ಆದ್ದರಿಂದ ಒಟ್ಟು ರೋಧ ಅತಿ ಚಿಕ್ಕದಕ್ಕಿಂತಲೂ ಕಡಿಮೆ.'),
        apparatus=[W('Battery with adjustable voltage', 'बदलने योग्य वोल्टता वाली बैटरी', 'ಬದಲಿಸಬಹುದಾದ ವೋಲ್ಟೇಜ್‌ನ ಬ್ಯಾಟರಿ'),
                   W('Up to three resistors', 'तीन तक प्रतिरोधक', 'ಮೂರುವರೆಗೆ ರೋಧಕಗಳು'),
                   W('Ammeter and voltmeter', 'ऐमीटर और वोल्टमीटर', 'ಅಮ್ಮೀಟರ್ ಮತ್ತು ವೋಲ್ಟ್‌ಮೀಟರ್'),
                   W('Plug key and wires', 'प्लग कुंजी और तार', 'ಪ್ಲಗ್ ಕೀ ಮತ್ತು ತಂತಿಗಳು')],
        steps=[W('Choose series or parallel and the number of resistors.', 'श्रेणी या पार्श्व और प्रतिरोधकों की संख्या चुनें।', 'ಸರಣಿ ಅಥವಾ ಸಮಾಂತರ ಮತ್ತು ರೋಧಕಗಳ ಸಂಖ್ಯೆ ಆರಿಸಿ.'),
               W('Set each resistance with its slider.', 'हर प्रतिरोध उसके स्लाइडर से तय करें।', 'ಪ್ರತಿ ರೋಧವನ್ನು ಅದರ ಸ್ಲೈಡರ್‌ನಿಂದ ಹೊಂದಿಸಿ.'),
               W('Raise the voltage step by step and watch the ammeter and the V–I graph.', 'वोल्टता धीरे-धीरे बढ़ाएँ और ऐमीटर तथा V–I ग्राफ़ देखें।', 'ವೋಲ್ಟೇಜ್ ಹಂತ ಹಂತವಾಗಿ ಹೆಚ್ಚಿಸಿ, ಅಮ್ಮೀಟರ್ ಮತ್ತು V–I ನಕ್ಷೆ ಗಮನಿಸಿ.'),
               W('Compare the equivalent resistance shown with your own calculation.', 'दिखाए गए तुल्य प्रतिरोध की तुलना अपनी गणना से करें।', 'ತೋರಿಸಿದ ಸಮಾನ ರೋಧವನ್ನು ನಿಮ್ಮ ಲೆಕ್ಕದೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=[W('In a real circuit, keep the key out between readings so the wires do not heat up.', 'असली परिपथ में पाठ्यांकों के बीच कुंजी निकाल दें ताकि तार गरम न हों।', 'ನಿಜವಾದ ಮಂಡಲದಲ್ಲಿ ತಂತಿಗಳು ಬಿಸಿಯಾಗದಂತೆ ಓದುಗಳ ನಡುವೆ ಕೀ ತೆಗೆಯಿರಿ.'),
                     W('Connect the ammeter in series and the voltmeter in parallel.', 'ऐमीटर श्रेणी में और वोल्टमीटर पार्श्व में जोड़ें।', 'ಅಮ್ಮೀಟರ್ ಸರಣಿಯಲ್ಲಿ, ವೋಲ್ಟ್‌ಮೀಟರ್ ಸಮಾಂತರದಲ್ಲಿ ಜೋಡಿಸಿ.')],
        conclusion=W('The V–I graph is a straight line through the origin whose slope is the resistance. Series resistances add; parallel combinations give less than the smallest resistor.',
                     'V–I ग्राफ़ मूल बिंदु से जाने वाली सीधी रेखा है जिसकी प्रवणता प्रतिरोध है। श्रेणी के प्रतिरोध जुड़ते हैं; पार्श्व संयोजन सबसे छोटे प्रतिरोधक से भी कम देता है।',
                     'V–I ನಕ್ಷೆ ಮೂಲಬಿಂದುವಿನ ಮೂಲಕ ಹೋಗುವ ಸರಳರೇಖೆ; ಅದರ ಇಳಿಜಾರೇ ರೋಧ. ಸರಣಿ ರೋಧಗಳು ಕೂಡುತ್ತವೆ; ಸಮಾಂತರ ಜೋಡಣೆ ಅತಿ ಚಿಕ್ಕ ರೋಧಕಕ್ಕಿಂತಲೂ ಕಡಿಮೆ ನೀಡುತ್ತದೆ.'),
        viva=[Q(W('What is the equivalent of 6 Ω and 3 Ω in parallel?', '6 Ω और 3 Ω पार्श्व में हों तो तुल्य प्रतिरोध क्या है?', '6 Ω ಮತ್ತು 3 Ω ಸಮಾಂತರದಲ್ಲಿದ್ದರೆ ಸಮಾನ ರೋಧ ಎಷ್ಟು?'),
                W('2 Ω, because 1/R = 1/6 + 1/3 = 1/2.', '2 Ω, क्योंकि 1/R = 1/6 + 1/3 = 1/2.', '2 Ω, ಏಕೆಂದರೆ 1/R = 1/6 + 1/3 = 1/2.')),
              Q(W('Why are household appliances connected in parallel?', 'घरेलू उपकरण पार्श्व में क्यों जोड़े जाते हैं?', 'ಮನೆಯ ಉಪಕರಣಗಳನ್ನು ಸಮಾಂತರದಲ್ಲಿ ಏಕೆ ಜೋಡಿಸುತ್ತಾರೆ?'),
                W('Each gets the full mains voltage and can be switched on or off by itself.', 'हर उपकरण को पूरी वोल्टता मिलती है और उसे अलग से चालू या बंद किया जा सकता है।', 'ಪ್ರತಿಯೊಂದಕ್ಕೂ ಪೂರ್ಣ ವೋಲ್ಟೇಜ್ ಸಿಗುತ್ತದೆ ಮತ್ತು ಅದನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ಆನ್/ಆಫ್ ಮಾಡಬಹುದು.')),
              Q(W('What does the slope of a V–I graph give?', 'V–I ग्राफ़ की प्रवणता क्या देती है?', 'V–I ನಕ್ಷೆಯ ಇಳಿಜಾರು ಏನನ್ನು ನೀಡುತ್ತದೆ?'),
                W('The resistance R.', 'प्रतिरोध R.', 'ರೋಧ R.'))],
    )

    lab(
        id='lab.lens-mirror', bench='sim', subject='Physics', domain='physics', levels=[10, 12], mode='explore', curricula=['cbse', 'ncert', 'ka-sslc'],
        keywords=['ray diagram', 'lens', 'mirror', 'image formation', 'magnification', 'mirror formula', 'lens formula'],
        title=W('Lens and mirror ray diagrams', 'लेंस और दर्पण के किरण आरेख', 'ಮಸೂರ ಮತ್ತು ದರ್ಪಣದ ಕಿರಣ ಚಿತ್ರಗಳು'),
        summary=W('Drag the object along the axis and watch the principal rays form the image.',
                  'वस्तु को अक्ष पर खिसकाएँ और देखें कि मुख्य किरणें प्रतिबिंब कैसे बनाती हैं।',
                  'ವಸ್ತುವನ್ನು ಅಕ್ಷದ ಮೇಲೆ ಎಳೆಯಿರಿ, ಮುಖ್ಯ ಕಿರಣಗಳು ಪ್ರತಿಬಿಂಬವನ್ನು ಹೇಗೆ ರೂಪಿಸುತ್ತವೆ ನೋಡಿ.'),
        aim=W('To explore the position, nature and size of images formed by convex and concave lenses and mirrors.',
              'उत्तल और अवतल लेंसों तथा दर्पणों से बने प्रतिबिंबों की स्थिति, प्रकृति और आकार की खोज करना।',
              'ಪೀನ ಮತ್ತು ನಿಮ್ನ ಮಸೂರ ಹಾಗೂ ದರ್ಪಣಗಳು ರೂಪಿಸುವ ಪ್ರತಿಬಿಂಬಗಳ ಸ್ಥಾನ, ಸ್ವರೂಪ ಮತ್ತು ಗಾತ್ರವನ್ನು ಅನ್ವೇಷಿಸುವುದು.'),
        principle=W('With the New Cartesian sign convention, a mirror obeys 1/v + 1/u = 1/f and a lens obeys 1/v − 1/u = 1/f. Magnification is m = −v/u for a mirror and m = v/u for a lens.',
                    'नई कार्तीय चिह्न परिपाटी में दर्पण के लिए 1/v + 1/u = 1/f और लेंस के लिए 1/v − 1/u = 1/f. आवर्धन दर्पण के लिए m = −v/u और लेंस के लिए m = v/u है।',
                    'ಹೊಸ ಕಾರ್ಟೀಸಿಯನ್ ಚಿಹ್ನೆ ಸಂಪ್ರದಾಯದಲ್ಲಿ ದರ್ಪಣಕ್ಕೆ 1/v + 1/u = 1/f ಮತ್ತು ಮಸೂರಕ್ಕೆ 1/v − 1/u = 1/f. ವರ್ಧನೆ ದರ್ಪಣಕ್ಕೆ m = −v/u, ಮಸೂರಕ್ಕೆ m = v/u.'),
        apparatus=[W('Convex and concave lenses', 'उत्तल और अवतल लेंस', 'ಪೀನ ಮತ್ತು ನಿಮ್ನ ಮಸೂರಗಳು'), W('Concave and convex mirrors', 'अवतल और उत्तल दर्पण', 'ನಿಮ್ನ ಮತ್ತು ಪೀನ ದರ್ಪಣಗಳು'),
                   W('An object (arrow) on the principal axis', 'मुख्य अक्ष पर एक वस्तु (तीर)', 'ಮುಖ್ಯ ಅಕ್ಷದ ಮೇಲೆ ಒಂದು ವಸ್ತು (ಬಾಣ)')],
        steps=[W('Choose a lens or a mirror.', 'लेंस या दर्पण चुनें।', 'ಮಸೂರ ಅಥವಾ ದರ್ಪಣ ಆರಿಸಿ.'),
               W('Place the object beyond 2F (or C) and note the image.', 'वस्तु को 2F (या C) से परे रखें और प्रतिबिंब देखें।', 'ವಸ್ತುವನ್ನು 2F (ಅಥವಾ C) ಆಚೆ ಇಟ್ಟು ಪ್ರತಿಬಿಂಬ ಗಮನಿಸಿ.'),
               W('Move it to 2F, between F and 2F, at F and inside F, noting each image.', 'उसे 2F पर, F और 2F के बीच, F पर और F के भीतर ले जाएँ और हर प्रतिबिंब लिखें।', 'ಅದನ್ನು 2F ನಲ್ಲಿ, F ಮತ್ತು 2F ನಡುವೆ, F ನಲ್ಲಿ ಮತ್ತು F ಒಳಗೆ ಇಟ್ಟು ಪ್ರತಿ ಪ್ರತಿಬಿಂಬ ಬರೆಯಿರಿ.'),
               W('Check v and m against the formula for one position.', 'एक स्थिति के लिए v और m को सूत्र से जाँचें।', 'ಒಂದು ಸ್ಥಾನಕ್ಕೆ v ಮತ್ತು m ಅನ್ನು ಸೂತ್ರದಿಂದ ಪರೀಕ್ಷಿಸಿ.')],
        precautions=[W('Measure every distance from the pole or optical centre.', 'हर दूरी ध्रुव या प्रकाशिक केंद्र से मापें।', 'ಪ್ರತಿ ದೂರವನ್ನು ಧ್ರುವ ಅಥವಾ ದ್ಯುತಿ ಕೇಂದ್ರದಿಂದ ಅಳೆಯಿರಿ.'),
                     W('Use the sign convention consistently.', 'चिह्न परिपाटी का हर जगह एक-सा प्रयोग करें।', 'ಚಿಹ್ನೆ ಸಂಪ್ರದಾಯವನ್ನು ಎಲ್ಲೆಡೆ ಒಂದೇ ರೀತಿ ಬಳಸಿ.')],
        conclusion=W('Convex lenses and concave mirrors give real, inverted images when the object is beyond F and virtual, erect, magnified images inside F; concave lenses and convex mirrors always give virtual, erect, diminished images.',
                     'वस्तु F से परे हो तो उत्तल लेंस और अवतल दर्पण वास्तविक, उल्टे प्रतिबिंब देते हैं और F के भीतर हो तो आभासी, सीधे, बड़े; अवतल लेंस और उत्तल दर्पण सदा आभासी, सीधे, छोटे प्रतिबिंब देते हैं।',
                     'ವಸ್ತು F ಆಚೆ ಇದ್ದರೆ ಪೀನ ಮಸೂರ ಮತ್ತು ನಿಮ್ನ ದರ್ಪಣ ನೈಜ, ತಲೆಕೆಳಗಾದ ಪ್ರತಿಬಿಂಬ ನೀಡುತ್ತವೆ; F ಒಳಗಿದ್ದರೆ ಮಿಥ್ಯ, ನೇರ, ದೊಡ್ಡ ಪ್ರತಿಬಿಂಬ. ನಿಮ್ನ ಮಸೂರ ಮತ್ತು ಪೀನ ದರ್ಪಣ ಯಾವಾಗಲೂ ಮಿಥ್ಯ, ನೇರ, ಚಿಕ್ಕ ಪ್ರತಿಬಿಂಬ ನೀಡುತ್ತವೆ.'),
        viva=[Q(W('Where must the object be for a convex lens to give a same-size image?', 'उत्तल लेंस से समान आकार का प्रतिबिंब पाने के लिए वस्तु कहाँ हो?', 'ಪೀನ ಮಸೂರದಿಂದ ಸಮಾನ ಗಾತ್ರದ ಪ್ರತಿಬಿಂಬಕ್ಕೆ ವಸ್ತು ಎಲ್ಲಿರಬೇಕು?'),
                W('At 2F₁; the image forms at 2F₂.', '2F₁ पर; प्रतिबिंब 2F₂ पर बनता है।', '2F₁ ನಲ್ಲಿ; ಪ್ರತಿಬಿಂಬ 2F₂ ನಲ್ಲಿ ಮೂಡುತ್ತದೆ.')),
              Q(W('Which mirror is used as a rear-view mirror, and why?', 'पीछे देखने के लिए कौन-सा दर्पण लगाते हैं, और क्यों?', 'ಹಿಂಬದಿ ನೋಟಕ್ಕೆ ಯಾವ ದರ್ಪಣ ಬಳಸುತ್ತಾರೆ, ಏಕೆ?'),
                W('A convex mirror: it always gives an erect image and a wide field of view.', 'उत्तल दर्पण: यह सदा सीधा प्रतिबिंब और चौड़ा दृश्य क्षेत्र देता है।', 'ಪೀನ ದರ್ಪಣ: ಅದು ಯಾವಾಗಲೂ ನೇರ ಪ್ರತಿಬಿಂಬ ಮತ್ತು ವಿಶಾಲ ನೋಟ ಕ್ಷೇತ್ರ ನೀಡುತ್ತದೆ.')),
              Q(W('What does a negative magnification mean?', 'ऋणात्मक आवर्धन का क्या अर्थ है?', 'ಋಣ ವರ್ಧನೆಯ ಅರ್ಥವೇನು?'),
                W('The image is inverted (and real).', 'प्रतिबिंब उल्टा (और वास्तविक) है।', 'ಪ್ರತಿಬಿಂಬ ತಲೆಕೆಳಗಾಗಿದೆ (ಮತ್ತು ನೈಜ).'))],
    )

    lab(
        id='lab.pendulum', bench='sim', subject='Physics', domain='physics', levels=[9, 11], mode='explore', curricula=['cbse', 'ncert', 'ka-puc'],
        keywords=['oscillations', 'simple harmonic motion', 'time period', 'pendulum', 'gravity'],
        title=W('Simple pendulum explorer', 'सरल लोलक अन्वेषक', 'ಸರಳ ಲೋಲಕ ಅನ್ವೇಷಕ'),
        summary=W('Change the length, the planet and the amplitude, and time ten swings with the stopwatch.',
                  'लंबाई, ग्रह और आयाम बदलें और विराम घड़ी से दस दोलन मापें।',
                  'ಉದ್ದ, ಗ್ರಹ ಮತ್ತು ವಿಸ್ತಾರ ಬದಲಿಸಿ, ನಿಲುಗಡಿಯಾರದಿಂದ ಹತ್ತು ಆಂದೋಲನಗಳ ಸಮಯ ಅಳೆಯಿರಿ.'),
        aim=W('To explore how the period of a pendulum depends on its length, on g and on the amplitude.',
              'यह खोजना कि लोलक का आवर्तकाल उसकी लंबाई, g और आयाम पर कैसे निर्भर करता है।',
              'ಲೋಲಕದ ಆವರ್ತಕಾಲವು ಉದ್ದ, g ಮತ್ತು ವಿಸ್ತಾರದ ಮೇಲೆ ಹೇಗೆ ಅವಲಂಬಿಸಿದೆ ಎಂದು ಅನ್ವೇಷಿಸುವುದು.'),
        principle=W('For small swings T = 2π√(L/g): the period grows with the square root of the length, falls on a planet with larger g, and does not depend on the mass. Large swings take slightly longer.',
                    'छोटे दोलनों के लिए T = 2π√(L/g): आवर्तकाल लंबाई के वर्गमूल के साथ बढ़ता है, अधिक g वाले ग्रह पर घटता है और द्रव्यमान पर निर्भर नहीं करता। बड़े दोलन थोड़ा अधिक समय लेते हैं।',
                    'ಸಣ್ಣ ಆಂದೋಲನಗಳಿಗೆ T = 2π√(L/g): ಆವರ್ತಕಾಲ ಉದ್ದದ ವರ್ಗಮೂಲದೊಂದಿಗೆ ಹೆಚ್ಚುತ್ತದೆ, ಹೆಚ್ಚು g ಇರುವ ಗ್ರಹದಲ್ಲಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ, ದ್ರವ್ಯರಾಶಿಯನ್ನು ಅವಲಂಬಿಸುವುದಿಲ್ಲ. ದೊಡ್ಡ ಆಂದೋಲನಗಳಿಗೆ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಸಮಯ.'),
        apparatus=[W('Bob on a thread', 'धागे पर गोलक', 'ದಾರಕ್ಕೆ ಕಟ್ಟಿದ ಗುಂಡು'), W('Stand and clamp', 'स्टैंड और क्लैंप', 'ಸ್ಟ್ಯಾಂಡ್ ಮತ್ತು ಕ್ಲ್ಯಾಂಪ್'),
                   W('Stopwatch', 'विराम घड़ी', 'ನಿಲುಗಡಿಯಾರ'), W('Metre scale', 'मीटर पैमाना', 'ಮೀಟರ್ ಅಳತೆಪಟ್ಟಿ')],
        steps=[W('Set a length and a small amplitude.', 'एक लंबाई और छोटा आयाम तय करें।', 'ಒಂದು ಉದ್ದ ಮತ್ತು ಸಣ್ಣ ವಿಸ್ತಾರ ಹೊಂದಿಸಿ.'),
               W('Start the stopwatch as the bob passes the mean position and time 10 oscillations.', 'गोलक के माध्य स्थिति से गुजरते ही विराम घड़ी चालू करें और 10 दोलनों का समय लें।', 'ಗುಂಡು ಮಧ್ಯಸ್ಥಾನ ದಾಟುವಾಗ ನಿಲುಗಡಿಯಾರ ಆರಂಭಿಸಿ 10 ಆಂದೋಲನಗಳ ಸಮಯ ಅಳೆಯಿರಿ.'),
               W('Change the length, then the planet, and compare the periods.', 'लंबाई, फिर ग्रह बदलें और आवर्तकालों की तुलना करें।', 'ಉದ್ದ, ನಂತರ ಗ್ರಹ ಬದಲಿಸಿ, ಆವರ್ತಕಾಲಗಳನ್ನು ಹೋಲಿಸಿ.'),
               W('Try a large amplitude and compare with the formula.', 'बड़ा आयाम आज़माएँ और सूत्र से तुलना करें।', 'ದೊಡ್ಡ ವಿಸ್ತಾರ ಪ್ರಯತ್ನಿಸಿ, ಸೂತ್ರದೊಂದಿಗೆ ಹೋಲಿಸಿ.')],
        precautions=[W('Keep the amplitude small (under about 10°).', 'आयाम छोटा रखें (लगभग 10° से कम)।', 'ವಿಸ್ತಾರ ಸಣ್ಣದಾಗಿರಲಿ (ಸುಮಾರು 10° ಕ್ಕಿಂತ ಕಡಿಮೆ).'),
                     W('Time many oscillations, not one.', 'एक नहीं, कई दोलनों का समय लें।', 'ಒಂದಲ್ಲ, ಹಲವು ಆಂದೋಲನಗಳ ಸಮಯ ಅಳೆಯಿರಿ.')],
        conclusion=W('The period depends on length and g but not on the mass; for small swings it matches T = 2π√(L/g).',
                     'आवर्तकाल लंबाई और g पर निर्भर करता है, द्रव्यमान पर नहीं; छोटे दोलनों के लिए यह T = 2π√(L/g) से मेल खाता है।',
                     'ಆವರ್ತಕಾಲ ಉದ್ದ ಮತ್ತು g ಮೇಲೆ ಅವಲಂಬಿಸಿದೆ, ದ್ರವ್ಯರಾಶಿಯ ಮೇಲಲ್ಲ; ಸಣ್ಣ ಆಂದೋಲನಗಳಿಗೆ ಅದು T = 2π√(L/g) ಗೆ ಹೊಂದುತ್ತದೆ.'),
        viva=[Q(W('Would a pendulum clock run fast or slow on the Moon?', 'चंद्रमा पर लोलक घड़ी तेज़ चलेगी या धीमी?', 'ಚಂದ್ರನ ಮೇಲೆ ಲೋಲಕ ಗಡಿಯಾರ ವೇಗವಾಗಿ ಓಡುತ್ತದೆಯೇ ನಿಧಾನವಾಗಿಯೇ?'),
                W('Slow: g is smaller, so each swing takes longer.', 'धीमी: g कम है, इसलिए हर दोलन अधिक समय लेता है।', 'ನಿಧಾನ: g ಕಡಿಮೆ, ಆದ್ದರಿಂದ ಪ್ರತಿ ಆಂದೋಲನಕ್ಕೆ ಹೆಚ್ಚು ಸಮಯ.')),
              Q(W('If the length is made four times, what happens to T?', 'लंबाई चार गुनी करने पर T का क्या होगा?', 'ಉದ್ದವನ್ನು ನಾಲ್ಕು ಪಟ್ಟು ಮಾಡಿದರೆ T ಏನಾಗುತ್ತದೆ?'),
                W('It doubles.', 'यह दोगुना हो जाता है।', 'ಅದು ಎರಡು ಪಟ್ಟಾಗುತ್ತದೆ.')),
              Q(W('Why start timing at the mean position?', 'समय मापन माध्य स्थिति से क्यों शुरू करते हैं?', 'ಸಮಯ ಅಳತೆಯನ್ನು ಮಧ್ಯಸ್ಥಾನದಿಂದ ಏಕೆ ಆರಂಭಿಸುತ್ತೇವೆ?'),
                W('The bob moves fastest there, so the moment it passes is easiest to judge.', 'वहाँ गोलक सबसे तेज़ चलता है, इसलिए उसके गुजरने का क्षण पहचानना सबसे आसान है।', 'ಅಲ್ಲಿ ಗುಂಡು ಅತಿ ವೇಗವಾಗಿ ಚಲಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಅದು ದಾಟುವ ಕ್ಷಣ ಗುರುತಿಸುವುದು ಸುಲಭ.'))],
    )

    lab(
        id='lab.break-even', bench='sim', subject='Mathematics', domain='maths', levels=['ug'], mode='explore', curricula=['bu-bcom'],
        keywords=['break-even', 'marginal costing', 'cost accounting', 'contribution', 'margin of safety', 'p/v ratio'],
        title=W('Break-even analysis', 'सम-विच्छेद विश्लेषण', 'ಲಾಭ-ನಷ್ಟ ಸಮತೋಲನ ವಿಶ್ಲೇಷಣೆ'),
        summary=W('Change fixed cost, variable cost, price and sales and watch the break-even point move.',
                  'स्थायी लागत, परिवर्ती लागत, मूल्य और बिक्री बदलें और सम-विच्छेद बिंदु खिसकते देखें।',
                  'ಸ್ಥಿರ ವೆಚ್ಚ, ಬದಲಾಗುವ ವೆಚ್ಚ, ಬೆಲೆ ಮತ್ತು ಮಾರಾಟ ಬದಲಿಸಿ, ಸಮತೋಲನ ಬಿಂದು ಸರಿಯುವುದನ್ನು ನೋಡಿ.'),
        aim=W('To find the break-even point, P/V ratio and margin of safety from a break-even chart.',
              'सम-विच्छेद चार्ट से सम-विच्छेद बिंदु, P/V अनुपात और सुरक्षा सीमा ज्ञात करना।',
              'ಸಮತೋಲನ ಚಾರ್ಟ್‌ನಿಂದ ಸಮತೋಲನ ಬಿಂದು, P/V ಅನುಪಾತ ಮತ್ತು ಸುರಕ್ಷತಾ ಅಂಚು ಕಂಡುಹಿಡಿಯುವುದು.'),
        principle=W('Contribution per unit = price − variable cost. Break-even units = fixed cost ÷ contribution per unit. P/V ratio = contribution ÷ sales. Margin of safety = actual sales − break-even sales.',
                    'प्रति इकाई अंशदान = मूल्य − परिवर्ती लागत. सम-विच्छेद इकाइयाँ = स्थायी लागत ÷ प्रति इकाई अंशदान. P/V अनुपात = अंशदान ÷ बिक्री. सुरक्षा सीमा = वास्तविक बिक्री − सम-विच्छेद बिक्री.',
                    'ಪ್ರತಿ ಘಟಕದ ಕೊಡುಗೆ = ಬೆಲೆ − ಬದಲಾಗುವ ವೆಚ್ಚ. ಸಮತೋಲನ ಘಟಕಗಳು = ಸ್ಥಿರ ವೆಚ್ಚ ÷ ಪ್ರತಿ ಘಟಕದ ಕೊಡುಗೆ. P/V ಅನುಪಾತ = ಕೊಡುಗೆ ÷ ಮಾರಾಟ. ಸುರಕ್ಷತಾ ಅಂಚು = ನಿಜ ಮಾರಾಟ − ಸಮತೋಲನ ಮಾರಾಟ.'),
        apparatus=[W('Cost and price data', 'लागत और मूल्य के आँकड़े', 'ವೆಚ್ಚ ಮತ್ತು ಬೆಲೆಯ ದತ್ತಾಂಶ'), W('Break-even chart', 'सम-विच्छेद चार्ट', 'ಸಮತೋಲನ ಚಾರ್ಟ್'),
                   W('Calculator', 'कैलकुलेटर', 'ಕ್ಯಾಲ್ಕುಲೇಟರ್')],
        steps=[W('Enter the fixed cost.', 'स्थायी लागत डालें।', 'ಸ್ಥಿರ ವೆಚ್ಚ ನಮೂದಿಸಿ.'), W('Enter the variable cost per unit and the selling price.', 'प्रति इकाई परिवर्ती लागत और विक्रय मूल्य डालें।', 'ಪ್ರತಿ ಘಟಕದ ಬದಲಾಗುವ ವೆಚ್ಚ ಮತ್ತು ಮಾರಾಟ ಬೆಲೆ ನಮೂದಿಸಿ.'),
               W('Read the break-even point where the sales and total cost lines cross.', 'जहाँ बिक्री और कुल लागत रेखाएँ कटती हैं वहाँ सम-विच्छेद बिंदु पढ़ें।', 'ಮಾರಾಟ ಮತ್ತು ಒಟ್ಟು ವೆಚ್ಚದ ರೇಖೆಗಳು ಛೇದಿಸುವಲ್ಲಿ ಸಮತೋಲನ ಬಿಂದು ಓದಿ.'),
               W('Change the sales volume and read the profit or loss and the margin of safety.', 'बिक्री की मात्रा बदलें और लाभ या हानि तथा सुरक्षा सीमा पढ़ें।', 'ಮಾರಾಟದ ಪ್ರಮಾಣ ಬದಲಿಸಿ, ಲಾಭ ಅಥವಾ ನಷ್ಟ ಮತ್ತು ಸುರಕ್ಷತಾ ಅಂಚು ಓದಿ.')],
        precautions=[W('Keep the price above the variable cost, or there is no break-even point.', 'मूल्य परिवर्ती लागत से अधिक रखें, नहीं तो सम-विच्छेद बिंदु नहीं होगा।', 'ಬೆಲೆ ಬದಲಾಗುವ ವೆಚ್ಚಕ್ಕಿಂತ ಹೆಚ್ಚಿರಲಿ, ಇಲ್ಲದಿದ್ದರೆ ಸಮತೋಲನ ಬಿಂದು ಇರದು.'),
                     W('Use the same units (₹, units) throughout.', 'सब जगह एक-सी इकाइयाँ (₹, इकाइयाँ) लें।', 'ಎಲ್ಲೆಡೆ ಒಂದೇ ಏಕಮಾನಗಳನ್ನು (₹, ಘಟಕಗಳು) ಬಳಸಿ.')],
        conclusion=W('Below the break-even point the firm makes a loss and above it a profit; a higher fixed cost moves the break-even point up, a higher contribution moves it down.',
                     'सम-विच्छेद बिंदु से नीचे फ़र्म को हानि और ऊपर लाभ होता है; अधिक स्थायी लागत बिंदु को ऊपर और अधिक अंशदान उसे नीचे ले जाता है।',
                     'ಸಮತೋಲನ ಬಿಂದುವಿನ ಕೆಳಗೆ ಸಂಸ್ಥೆಗೆ ನಷ್ಟ, ಮೇಲೆ ಲಾಭ; ಹೆಚ್ಚಿನ ಸ್ಥಿರ ವೆಚ್ಚ ಬಿಂದುವನ್ನು ಮೇಲೆ, ಹೆಚ್ಚಿನ ಕೊಡುಗೆ ಅದನ್ನು ಕೆಳಗೆ ಸರಿಸುತ್ತದೆ.'),
        viva=[Q(W('What is contribution?', 'अंशदान क्या है?', 'ಕೊಡುಗೆ ಎಂದರೇನು?'), W('Sales minus variable cost.', 'बिक्री घटा परिवर्ती लागत।', 'ಮಾರಾಟ ಕಳೆ ಬದಲಾಗುವ ವೆಚ್ಚ.')),
              Q(W('Fixed cost ₹40,000, contribution ₹20 per unit: find the BEP.', 'स्थायी लागत ₹40,000, अंशदान ₹20 प्रति इकाई: सम-विच्छेद बिंदु ज्ञात करें।', 'ಸ್ಥಿರ ವೆಚ್ಚ ₹40,000, ಪ್ರತಿ ಘಟಕದ ಕೊಡುಗೆ ₹20: ಸಮತೋಲನ ಬಿಂದು ಕಂಡುಹಿಡಿಯಿರಿ.'),
                W('2,000 units.', '2,000 इकाइयाँ।', '2,000 ಘಟಕಗಳು.')),
              Q(W('What does a large margin of safety show?', 'बड़ी सुरक्षा सीमा क्या दर्शाती है?', 'ದೊಡ್ಡ ಸುರಕ್ಷತಾ ಅಂಚು ಏನನ್ನು ತೋರಿಸುತ್ತದೆ?'),
                W('Sales can fall a lot before the firm makes a loss.', 'हानि होने से पहले बिक्री काफ़ी घट सकती है।', 'ನಷ್ಟವಾಗುವ ಮೊದಲು ಮಾರಾಟ ಸಾಕಷ್ಟು ಕುಸಿಯಬಹುದು.'))],
    )

    lab(
        id='lab.graph-plotter', bench='sim', subject='Mathematics', domain='maths', levels=[9, 10, 11], mode='explore', curricula=['cbse', 'ncert'],
        keywords=['graph', 'polynomials', 'quadratic equations', 'linear equations', 'trigonometry', 'roots'],
        title=W('Graph plotter', 'ग्राफ़ प्लॉटर', 'ನಕ್ಷೆ ರಚಕ'),
        summary=W('Plot lines, parabolas and sine curves, move the coefficients and watch roots and vertex change.',
                  'रेखाएँ, परवलय और ज्या वक्र बनाएँ, गुणांक बदलें और मूल तथा शीर्ष बदलते देखें।',
                  'ರೇಖೆಗಳು, ಪರವಲಯಗಳು ಮತ್ತು ಸೈನ್ ವಕ್ರಗಳನ್ನು ರಚಿಸಿ, ಗುಣಾಂಕ ಬದಲಿಸಿ ಮೂಲಗಳು ಮತ್ತು ಶೃಂಗ ಬದಲಾಗುವುದನ್ನು ನೋಡಿ.'),
        aim=W('To explore how the coefficients of a function change its graph, its roots and its vertex.',
              'यह खोजना कि फलन के गुणांक उसके ग्राफ़, मूलों और शीर्ष को कैसे बदलते हैं।',
              'ಫಲನದ ಗುಣಾಂಕಗಳು ಅದರ ನಕ್ಷೆ, ಮೂಲಗಳು ಮತ್ತು ಶೃಂಗವನ್ನು ಹೇಗೆ ಬದಲಿಸುತ್ತವೆ ಎಂದು ಅನ್ವೇಷಿಸುವುದು.'),
        principle=W('The zeros of a polynomial are where its graph meets the x-axis. For y = ax² + bx + c the discriminant b² − 4ac decides whether there are two, one or no real roots, and the vertex is at x = −b/2a.',
                    'बहुपद के शून्यक वहाँ हैं जहाँ उसका ग्राफ़ x-अक्ष से मिलता है। y = ax² + bx + c के लिए विविक्तकर b² − 4ac तय करता है कि दो, एक या कोई वास्तविक मूल नहीं है, और शीर्ष x = −b/2a पर है।',
                    'ಬಹುಪದದ ಶೂನ್ಯಗಳು ಅದರ ನಕ್ಷೆ x-ಅಕ್ಷವನ್ನು ಸಂಧಿಸುವಲ್ಲಿವೆ. y = ax² + bx + c ಗೆ ವಿವೇಚಕ b² − 4ac ಎರಡು, ಒಂದು ಅಥವಾ ಯಾವುದೇ ನೈಜ ಮೂಲ ಇಲ್ಲವೇ ಎಂದು ನಿರ್ಧರಿಸುತ್ತದೆ; ಶೃಂಗ x = −b/2a ನಲ್ಲಿದೆ.'),
        apparatus=[W('Graph plotter on the board', 'बोर्ड पर ग्राफ़ प्लॉटर', 'ಬೋರ್ಡ್‌ನಲ್ಲಿ ನಕ್ಷೆ ರಚಕ'), W('Coefficient sliders', 'गुणांक स्लाइडर', 'ಗುಣಾಂಕ ಸ್ಲೈಡರ್‌ಗಳು'),
                   W('Typed expression box', 'व्यंजक लिखने का बॉक्स', 'ಅಭಿವ್ಯಕ್ತಿ ಬರೆಯುವ ಪೆಟ್ಟಿಗೆ')],
        steps=[W('Choose linear, quadratic, sine or cosine.', 'रैखिक, द्विघात, ज्या या कोज्या चुनें।', 'ರೇಖೀಯ, ವರ್ಗ, ಸೈನ್ ಅಥವಾ ಕೊಸೈನ್ ಆರಿಸಿ.'),
               W('Move one coefficient at a time and describe what changes.', 'एक समय में एक गुणांक बदलें और बताएँ कि क्या बदलता है।', 'ಒಮ್ಮೆಗೆ ಒಂದು ಗುಣಾಂಕ ಸರಿಸಿ, ಏನು ಬದಲಾಗುತ್ತದೆ ಹೇಳಿ.'),
               W('Read the roots and the vertex and check them with the formula.', 'मूल और शीर्ष पढ़ें और सूत्र से जाँचें।', 'ಮೂಲಗಳು ಮತ್ತು ಶೃಂಗ ಓದಿ, ಸೂತ್ರದಿಂದ ಪರೀಕ್ಷಿಸಿ.'),
               W('Type your own expression and plot it.', 'अपना व्यंजक लिखकर उसका ग्राफ़ बनाएँ।', 'ನಿಮ್ಮದೇ ಅಭಿವ್ಯಕ್ತಿ ಬರೆದು ನಕ್ಷೆ ರಚಿಸಿ.')],
        precautions=[W('Zoom out before deciding a graph has no roots.', 'यह तय करने से पहले कि ग्राफ़ का कोई मूल नहीं, ज़ूम आउट करें।', 'ನಕ್ಷೆಗೆ ಮೂಲವಿಲ್ಲ ಎನ್ನುವ ಮೊದಲು ಝೂಮ್ ಔಟ್ ಮಾಡಿ.'),
                     W('Angles for sine and cosine are in degrees.', 'ज्या और कोज्या के कोण अंशों में हैं।', 'ಸೈನ್ ಮತ್ತು ಕೊಸೈನ್ ಕೋನಗಳು ಡಿಗ್ರಿಗಳಲ್ಲಿವೆ.')],
        conclusion=W('The sign of a opens the parabola up or down, c is the y-intercept, and the discriminant decides the number of real roots.',
                     'a का चिह्न परवलय को ऊपर या नीचे खोलता है, c y-अंतःखंड है, और विविक्तकर वास्तविक मूलों की संख्या तय करता है।',
                     'a ಯ ಚಿಹ್ನೆ ಪರವಲಯವನ್ನು ಮೇಲೆ ಅಥವಾ ಕೆಳಗೆ ತೆರೆಯುತ್ತದೆ, c y-ಅಂತಃಖಂಡ, ವಿವೇಚಕ ನೈಜ ಮೂಲಗಳ ಸಂಖ್ಯೆ ನಿರ್ಧರಿಸುತ್ತದೆ.'),
        viva=[Q(W('How many zeros does y = x² + 1 have?', 'y = x² + 1 के कितने शून्यक हैं?', 'y = x² + 1 ಗೆ ಎಷ್ಟು ಶೂನ್ಯಗಳಿವೆ?'), W('None (real): the graph never meets the x-axis.', 'कोई (वास्तविक) नहीं: ग्राफ़ x-अक्ष से नहीं मिलता।', 'ಯಾವುದೂ (ನೈಜ) ಇಲ್ಲ: ನಕ್ಷೆ x-ಅಕ್ಷವನ್ನು ಸಂಧಿಸುವುದಿಲ್ಲ.')),
              Q(W('What does the slope m of y = mx + c tell you?', 'y = mx + c में प्रवणता m क्या बताती है?', 'y = mx + c ಯಲ್ಲಿ ಇಳಿಜಾರು m ಏನನ್ನು ತಿಳಿಸುತ್ತದೆ?'), W('How steep the line is: y rises by m for each unit of x.', 'रेखा कितनी खड़ी है: x की हर इकाई पर y, m बढ़ता है।', 'ರೇಖೆ ಎಷ್ಟು ಕಡಿದಾಗಿದೆ: x ನ ಪ್ರತಿ ಘಟಕಕ್ಕೆ y, m ಹೆಚ್ಚುತ್ತದೆ.')),
              Q(W('Where is the vertex of y = x² − 4x + 3?', 'y = x² − 4x + 3 का शीर्ष कहाँ है?', 'y = x² − 4x + 3 ರ ಶೃಂಗ ಎಲ್ಲಿದೆ?'), W('At (2, −1).', '(2, −1) पर।', '(2, −1) ನಲ್ಲಿ.'))],
    )
