import type { MessageKey } from '@/i18n/messages';

/** Words for the statuses and event kinds the operations APIs send; anything else is shown as is. */
const STATUS: Record<string, MessageKey> = {
  active: 'ops.st.active',
  inactive: 'ops.st.inactive',
  maintenance: 'ops.st.maintenance',
  retired: 'ops.st.retired',
  running: 'ops.st.running',
  ended: 'ops.st.ended',
  started: 'ops.st.started',
  stop_reached: 'ops.st.stop_reached',
  approaching: 'ops.st.approaching',
  issued: 'ops.st.issued',
  out: 'ops.st.out',
  in: 'ops.st.in',
  cancelled: 'ops.st.cancelled',
  open: 'ops.st.open',
  in_progress: 'ops.st.in_progress',
  resolved: 'ops.st.resolved',
  submitted: 'ops.st.submitted',
  approved: 'ops.st.approved',
  rejected: 'ops.st.rejected',
  matched: 'ops.st.matched',
  mismatch: 'ops.st.mismatch',
  paid: 'ops.st.paid',
  received: 'ops.st.received',
  partially_received: 'ops.st.partially_received',
  in_maintenance: 'ops.st.in_maintenance',
  disposed: 'ops.st.disposed',
  slm: 'ops.st.slm',
  wdv: 'ops.st.wdv',
  boys: 'ops.st.boys',
  girls: 'ops.st.girls',
  mixed: 'ops.st.mixed',
  food: 'ops.st.food',
  cleanliness: 'ops.st.cleanliness',
  safety: 'ops.st.safety',
  other: 'ops.st.other',
  service: 'ops.st.service',
  repair: 'ops.st.repair',
  inspection: 'ops.st.inspection',
  breakfast: 'ops.st.breakfast',
  lunch: 'ops.st.lunch',
  snacks: 'ops.st.snacks',
  dinner: 'ops.st.dinner',
  awarded: 'ops.st.awarded',
  fuel: 'ops.st.fuel',
  toll: 'ops.st.toll',
  accident: 'ops.st.accident',
  breakdown: 'ops.st.breakdown',
  delay: 'ops.st.delay',
  behaviour: 'ops.st.behaviour',
  low: 'ops.st.low',
  medium: 'ops.st.medium',
  high: 'ops.st.high',
};

export const st = (t: (k: MessageKey) => string, s: string): string => (STATUS[s] ? t(STATUS[s]) : s);
