#!/usr/bin/env python3
"""Writes lib/src/core/strings_hi.dart and strings_kn.dart: the Hindi and
Kannada for every interface string the lab code passes to tr()/trn().

Translations come from tool/strings/*.py (each defines S = {english: (hindi,
kannada)}); keys the code no longer uses are dropped. Run from the package:

    python3 tool/build_strings.py
"""
import glob, importlib.util, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_strings import ROOT, used_keys  # noqa: E402


def q(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def load():
    merged = {}
    for path in sorted(glob.glob(os.path.join(ROOT, 'tool/strings/*.py'))):
        spec = importlib.util.spec_from_file_location(os.path.basename(path)[:-3], path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        merged.update(mod.S)
    return merged


def main():
    keys = used_keys([os.path.join(ROOT, 'lib')])
    t = load()
    missing = sorted(k for k in keys if k not in t)
    for k in missing:
        print('missing: %r' % k)
    for i, (lang, name) in enumerate([('hi', 'Hindi'), ('kn', 'Kannada')]):
        with open(os.path.join(ROOT, 'lib/src/core/strings_%s.dart' % lang), 'w', encoding='utf-8') as f:
            f.write('// GENERATED by tool/build_strings.py from tool/strings/*.py: do not edit.\n')
            f.write('// Lab interface strings, English -> %s. Keys are the English text exactly as\n' % name)
            f.write('// passed to tr()/trn(); test/i18n_test.dart fails when one is missing.\n')
            f.write('// Machine-assisted translation: have a native speaker review before a wide release.\n\n')
            f.write('const labStrings%s = <String, String>{\n' % lang.capitalize())
            for k in sorted(keys):
                if k in t:
                    f.write('  %s: %s,\n' % (q(k), q(t[k][i])))
            f.write('};\n')
    print('%d keys, %d missing' % (len(keys), len(missing)))
    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
