import 'package:flutter/widgets.dart';

import '../../l10n/feature_strings.dart';

FeatureStrings classroomStrings(BuildContext context) => FeatureStrings(boardLang(context), classroomStringTable);

/// The words of the teacher's profile on the board: Your Classrooms, Schedule a Training, the
/// End class summary and the student buzzer.
const classroomStringTable = <String, Map<String, String>>{
  'en': {
    'classroomsTitle': 'Your classrooms',
    'classroomsEmpty': 'No classes yet. They appear here once you are on the timetable or have taken a class.',
    'classroomsSessions': '{n} sessions',
    'classroomsLast': 'Last taken {d}',
    'classroomsNever': 'Not taken yet',
    'classroomsOpen': 'Open class',
    'classroomsOpened': 'Opened {c}',
    'classroomsFailed': 'Could not load or open the class',
    'classroomsStandard': 'Standard {n}',
    'trainingSchedule': 'Schedule a training',
    'trainingPick': 'Pick a slot',
    'trainingTopic': 'What do you want to learn?',
    'trainingSend': 'Request training',
    'trainingFull': 'Full',
    'trainingSent': 'Requested for {d}. It shows below once confirmed.',
    'trainingMine': 'Your requests',
    'trainingNone': 'No requests yet',
    'trainingFailed': 'Could not send the request',
    'trainingSignIn': 'Sign in to schedule a training.',
    'stRequested': 'Requested',
    'stConfirmed': 'Confirmed',
    'stDone': 'Done',
    'stCancelled': 'Cancelled',
    'endNotes': 'Class notes',
    'endNotesHint': 'What was covered, homework, reminders',
    'endPublish': 'Publish notes to students',
    'endSummaryTitle': 'Class ended',
    'endSummaryLine': '{m} minutes · {s}',
    'endSummaryBuzz': '{n} buzzer answers',
    'endNotesPublished': 'Notes published to students',
    'endNotesSaved': 'Notes saved',
    'endShare': 'Share on WhatsApp',
    'endShareText': 'Class notes: {u}',
    'endDone': 'Done',
    'buzzerStudents': 'From the Student App',
    'buzzerOpenStudents': 'Open for students',
    'buzzerLockStudents': 'Lock',
    'buzzerNoBuzz': 'Nobody has buzzed yet',
    'buzzerLocked': 'Locked',
    'buzzerOpenNow': 'Open',
  },
  'hi': {
    'classroomsTitle': 'आपकी कक्षाएँ',
    'classroomsEmpty': 'अभी कोई कक्षा नहीं। समय-सारणी में आने या कक्षा लेने पर वे यहाँ दिखेंगी।',
    'classroomsSessions': '{n} सत्र',
    'classroomsLast': 'पिछली बार {d}',
    'classroomsNever': 'अभी तक नहीं ली',
    'classroomsOpen': 'कक्षा खोलें',
    'classroomsOpened': '{c} खुली',
    'classroomsFailed': 'कक्षा लोड या खोली नहीं जा सकी',
    'classroomsStandard': 'कक्षा {n}',
    'trainingSchedule': 'प्रशिक्षण तय करें',
    'trainingPick': 'समय चुनें',
    'trainingTopic': 'आप क्या सीखना चाहते हैं?',
    'trainingSend': 'प्रशिक्षण का अनुरोध करें',
    'trainingFull': 'भरा हुआ',
    'trainingSent': '{d} के लिए अनुरोध भेजा गया। पुष्टि होने पर वह नीचे दिखेगा।',
    'trainingMine': 'आपके अनुरोध',
    'trainingNone': 'अभी कोई अनुरोध नहीं',
    'trainingFailed': 'अनुरोध नहीं भेजा जा सका',
    'trainingSignIn': 'प्रशिक्षण तय करने के लिए साइन इन करें।',
    'stRequested': 'अनुरोध किया',
    'stConfirmed': 'पुष्टि हुई',
    'stDone': 'पूरा हुआ',
    'stCancelled': 'रद्द',
    'endNotes': 'कक्षा के नोट्स',
    'endNotesHint': 'क्या पढ़ाया, गृहकार्य, याद दिलाने वाली बातें',
    'endPublish': 'नोट्स विद्यार्थियों को प्रकाशित करें',
    'endSummaryTitle': 'कक्षा समाप्त',
    'endSummaryLine': '{m} मिनट · {s}',
    'endSummaryBuzz': '{n} बज़र उत्तर',
    'endNotesPublished': 'नोट्स विद्यार्थियों को प्रकाशित हुए',
    'endNotesSaved': 'नोट्स सहेजे गए',
    'endShare': 'व्हाट्सऐप पर साझा करें',
    'endShareText': 'कक्षा के नोट्स: {u}',
    'endDone': 'ठीक है',
    'buzzerStudents': 'विद्यार्थी ऐप से',
    'buzzerOpenStudents': 'विद्यार्थियों के लिए खोलें',
    'buzzerLockStudents': 'बंद करें',
    'buzzerNoBuzz': 'अभी किसी ने बज़र नहीं दबाया',
    'buzzerLocked': 'बंद',
    'buzzerOpenNow': 'खुला',
  },
  'kn': {
    'classroomsTitle': 'ನಿಮ್ಮ ತರಗತಿಗಳು',
    'classroomsEmpty': 'ಇನ್ನೂ ತರಗತಿಗಳಿಲ್ಲ. ವೇಳಾಪಟ್ಟಿಗೆ ಸೇರಿದ ಅಥವಾ ತರಗತಿ ತೆಗೆದುಕೊಂಡ ಮೇಲೆ ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.',
    'classroomsSessions': '{n} ಅವಧಿಗಳು',
    'classroomsLast': 'ಕೊನೆಯದಾಗಿ {d}',
    'classroomsNever': 'ಇನ್ನೂ ತೆಗೆದುಕೊಂಡಿಲ್ಲ',
    'classroomsOpen': 'ತರಗತಿ ತೆರೆಯಿರಿ',
    'classroomsOpened': '{c} ತೆರೆಯಲಾಯಿತು',
    'classroomsFailed': 'ತರಗತಿಯನ್ನು ಲೋಡ್ ಅಥವಾ ತೆರೆಯಲು ಆಗಲಿಲ್ಲ',
    'classroomsStandard': 'ತರಗತಿ {n}',
    'trainingSchedule': 'ತರಬೇತಿ ನಿಗದಿಪಡಿಸಿ',
    'trainingPick': 'ಸಮಯ ಆರಿಸಿ',
    'trainingTopic': 'ನೀವು ಏನು ಕಲಿಯಬೇಕು?',
    'trainingSend': 'ತರಬೇತಿಗೆ ವಿನಂತಿಸಿ',
    'trainingFull': 'ತುಂಬಿದೆ',
    'trainingSent': '{d} ಗೆ ವಿನಂತಿಸಲಾಗಿದೆ. ದೃಢೀಕರಿಸಿದಾಗ ಕೆಳಗೆ ಕಾಣುತ್ತದೆ.',
    'trainingMine': 'ನಿಮ್ಮ ವಿನಂತಿಗಳು',
    'trainingNone': 'ಇನ್ನೂ ವಿನಂತಿಗಳಿಲ್ಲ',
    'trainingFailed': 'ವಿನಂತಿ ಕಳುಹಿಸಲು ಆಗಲಿಲ್ಲ',
    'trainingSignIn': 'ತರಬೇತಿ ನಿಗದಿಪಡಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    'stRequested': 'ವಿನಂತಿಸಲಾಗಿದೆ',
    'stConfirmed': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'stDone': 'ಮುಗಿದಿದೆ',
    'stCancelled': 'ರದ್ದಾಗಿದೆ',
    'endNotes': 'ತರಗತಿಯ ಟಿಪ್ಪಣಿಗಳು',
    'endNotesHint': 'ಏನು ಕಲಿಸಿದಿರಿ, ಮನೆಕೆಲಸ, ನೆನಪಿನ ಮಾತುಗಳು',
    'endPublish': 'ಟಿಪ್ಪಣಿಗಳನ್ನು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಪ್ರಕಟಿಸಿ',
    'endSummaryTitle': 'ತರಗತಿ ಮುಗಿಯಿತು',
    'endSummaryLine': '{m} ನಿಮಿಷ · {s}',
    'endSummaryBuzz': '{n} ಬಜರ್ ಉತ್ತರಗಳು',
    'endNotesPublished': 'ಟಿಪ್ಪಣಿಗಳನ್ನು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಪ್ರಕಟಿಸಲಾಗಿದೆ',
    'endNotesSaved': 'ಟಿಪ್ಪಣಿಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
    'endShare': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    'endShareText': 'ತರಗತಿಯ ಟಿಪ್ಪಣಿಗಳು: {u}',
    'endDone': 'ಸರಿ',
    'buzzerStudents': 'ವಿದ್ಯಾರ್ಥಿ ಆ್ಯಪ್‌ನಿಂದ',
    'buzzerOpenStudents': 'ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ತೆರೆಯಿರಿ',
    'buzzerLockStudents': 'ಲಾಕ್ ಮಾಡಿ',
    'buzzerNoBuzz': 'ಇನ್ನೂ ಯಾರೂ ಬಜರ್ ಒತ್ತಿಲ್ಲ',
    'buzzerLocked': 'ಲಾಕ್ ಆಗಿದೆ',
    'buzzerOpenNow': 'ತೆರೆದಿದೆ',
  },
};
