import 'package:flutter/widgets.dart';

/// Strings for the Smartboard spec features (toolbar groups, freeze, sharing, branding, stylus
/// tips, Text AI, quiz scan, smart tools). English, Hindi and Kannada, like LayoutStrings.
class SbStrings {
  const SbStrings(this.lang);

  final String lang;

  static SbStrings of(BuildContext context) => SbStrings(Localizations.maybeLocaleOf(context)?.languageCode ?? 'en');

  String call(String key, [Map<String, Object> args = const {}]) {
    var s = (_strings[lang] ?? _strings['en']!)[key] ?? _strings['en']![key] ?? key;
    args.forEach((k, v) => s = s.replaceAll('{$k}', '$v'));
    return s;
  }

  static const _strings = <String, Map<String, String>>{
    'en': {
      'switch': 'Switch',
      'hide': 'Hide',
      'restore': 'Show tools',
      'share': 'Share',
      'whatsapp': 'WhatsApp',
      'email': 'Email',
      'qr': 'QR code',
      'endClass': 'End class',
      'guest': 'Guest',
      'freeze': 'Freeze screen',
      'unfreeze': 'Close',
      'frozen': 'Screen frozen',
      'addPageBlank': 'Write something on this page first',
      'shareTitle': 'Share whiteboard',
      'preparing': 'Preparing {n} pages…',
      'shareScan': 'Scan to open the board',
      'copyLink': 'Copy link',
      'copied': 'Link copied',
      'moreApps': 'Other apps',
      'linkExpires': 'The link works for 30 days.',
      'shareNeedsSignIn': 'Sign in to share by link. You can still send the PDF from this panel.',
      'shareFailed': 'Could not prepare the link. Your board is safe. Try again.',
      'boardTitle': 'Whiteboard',
      'emailSubject': 'Whiteboard: {t}',
      'emailBody': 'Here are the board notes from class:\n{u}',
      'waText': 'Board notes: {t}\n{u}',
      'versions': 'Version history',
      'versionsEmpty': 'No earlier saves yet. Each save keeps the one before it.',
      'restoreVersion': 'Restore',
      'restored': 'Restored the save from {d}',
      'pagesN': '{n} pages',
      'brandName': 'Brand name on exports',
      'watermark': 'Watermark',
      'logo': 'Logo',
      'chooseLogo': 'Choose logo',
      'removeLogo': 'Remove logo',
      'branding': 'Branding',
      'brandingHint': 'Shown on shared and exported PDFs.',
      'tooLarge': 'That picture is over 10 MB. Choose a smaller one.',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'preview': 'Preview',
      'template': 'Template',
      'background': 'Background',
      'custom': 'Custom',
      'twoSide': 'Two Side',
      'frontTip': 'Front Tip',
      'backTip': 'Back Tip',
      'tipWrite': 'Write',
      'tipErase': 'Erase',
      'tipSelect': 'Select',
      'tipHighlight': 'Highlight',
      'twoSideHint': 'For a stylus with two ends. The panel tells the board which end touches.',
      'solidPen': 'Solid Pen',
      'highlighter': 'Highlighter',
      'textAi': 'Text AI',
      'shapeAi': 'Shape AI',
      'language': 'Language',
      'font': 'Font',
      'fontDefault': 'Default',
      'fontKalam': 'Kalam',
      'fontCustom': 'Custom',
      'slideToClear': 'Slide to clear the page',
      'eraserSize': 'Eraser size',
      'bringForward': 'Forward',
      'sendBackward': 'Backward',
      'faceColour': 'Colour a face',
      'faceColourHint': 'Tap a face, then a colour',
      'pptPrev': 'Previous slide',
      'pptNext': 'Next slide',
      'pptAddPage': 'Add page to whiteboard',
      'pptAddAll': 'Add all pages to whiteboard',
      'pptEdge': 'Edge to edge',
      'pptPresent': 'Present with animations',
      'pptClose': 'Close presentation',
      'pptNoPresenter': 'No presentation app on this panel. Slides show here without animations.',
      'pptAdded': 'Added {n} pages to the whiteboard',
      'catPdf': 'PDF',
      'catImages': 'Images',
      'catVideos': 'Videos',
      'catPpt': 'PPT',
      'catClipboard': 'Clipboard',
      'catGeometry': 'Geometry',
      'catTable': 'Table',
      'catFlowchart': 'Flowchart',
      'clipboardEmpty': 'Nothing copied yet. Copy text in any app, or an object on the board.',
      'quizSource': 'Questions from',
      'fromTopic': 'Topic',
      'scanBoard': 'Scan the board',
      'scanAll': 'Complete pages',
      'scanPick': 'Choose pages',
      'pageN': 'Page {n}',
      'qtMcq': 'MCQ',
      'qtTrueFalse': 'True / False',
      'qtFillBlank': 'Fill in the blanks',
      'qtShortAnswer': 'Short answer',
      'level': 'Class, board and subject',
      'levelHint': 'e.g. Class 11 CBSE Science',
      'timer': 'Timer',
      'timerOff': 'No timer',
      'seconds': '{n} s',
      'teams': 'Teams',
      'teamsOff': 'Whole class',
      'teamN': 'Team {n}',
      'important': 'Important',
      'askedIn': 'Asked in {n} past papers',
      'addToBoard': 'Add to board',
      'addedToBoard': 'Added to the board',
      'misconception': 'Common mistake',
      'answerIs': 'Answer: {a}',
      'point': '+1',
      'hwQa': 'Questions & answers',
      'hwFill': 'Fill in the blanks',
      'hwMcq': 'MCQ',
      'hwTf': 'True / False',
      'hw2': '2-mark',
      'hw3': '3-mark',
      'hw5': '5-mark',
      'hwDiagram': 'Diagrams',
      'formats': 'Formats',
      'smartTools': 'Smart Tools',
      'smartSummary': 'Summary',
      'smartLecture': 'Lecture',
      'smartPeriodic': 'Periodic Table',
      'smartDictionary': 'Dictionary',
      'smartCalculator': 'Calculator',
      'selectAsk': 'Ask about selection',
      'selectAskHint': 'Select writing or an object on the board, then pick what KINETIX AI should do.',
      'selectNothing': 'Select something on the board first.',
      'saExplain': 'Explain',
      'saSimplify': 'Simplify',
      'saExpand': 'Expand',
      'saSolve': 'Solve',
      'saTranslate': 'Translate',
      'saExample': 'Create example',
      'saQuiz': 'Create quiz',
      'saHomework': 'Create homework',
      'saDiagram': 'Create diagram',
      'saBoardReady': 'Board-ready notes',
      'sumFormat': 'For',
      'sumTeacher': 'Teacher',
      'sumStudent': 'Student notes',
      'sumRevision': 'Revision sheet',
      'sumRecap': 'Class recap',
      'sumFromBoard': 'Summarise the board',
      'sumConcepts': 'Key concepts',
      'sumDefinitions': 'Definitions',
      'sumFormulas': 'Formulas',
      'sumExamples': 'Examples',
      'sumPoints': 'Important points',
      'sumQuestions': 'Questions',
      'lecMake': 'Prepare lecture',
      'lecOutline': 'Outline',
      'lecExplanation': 'Explanation',
      'lecAnalogies': 'Analogies',
      'lecBoardPlan': 'Board plan',
      'lecActivities': 'Activities',
      'lecRecap': 'Recap',
      'minutes': 'Minutes',
      'aiDraft': 'AI-generated draft: check it before you use it.',
      'profileNew': 'New',
      'yourClassrooms': 'Your Classrooms',
      'configurations': 'Configurations',
      'scheduleTraining': 'Schedule a Training',
      'whatsNew': "What's New",
      'exit': 'Exit',
      'newBoardSave': 'Save this whiteboard before starting a new one?',
      'saveAndNew': 'Save and start new',
      'discardAndNew': 'Start new without saving',
      'trainingTitle': 'Teacher training',
      'trainingScan': 'Scan to book a training session or watch the tutorials.',
      'trainingNoLink': 'Your institution has not set a training link yet. Try the guided tour and practice board now.',
      'trainingContact': 'Contact: {c}',
      'tourNow': 'Guided tour',
      'practiceNow': 'Practice board',
      'fromInstitution': 'From your institution',
      'inThisVersion': 'New in KINETIX Board',
      'classroomsTitle': 'Your classrooms',
      'classroomsNone': "No classes on today's timetable.",
      'openClass': 'Switch class',
      'apps': 'Classroom Apps',
      'otherTools': 'Other Tools',
      'appStudyMaterial': 'Study Material',
      'appLiveClass': 'Live Class',
      'appHomework': 'Homework',
      'appLessons': 'Lessons',
      'appAttendance': 'Attendance',
      'appClassPrep': 'Class Prep',
      'appStudents': 'Students',
      'appTests': 'Tests',
      'appRecordings': 'Recordings',
      'appBooks': 'Books',
      'appCalculator': 'Calculator',
      'appSpotlight': 'Spotlight',
      'recMarker': 'Mark a chapter',
      'tabs2d': '2D',
      'tabs3d': '3D',
      'lined': 'Lined',
      'filled': 'Filled',
    },
    'hi': {
      'switch': 'बदलें',
      'hide': 'छिपाएँ',
      'restore': 'टूल दिखाएँ',
      'share': 'साझा करें',
      'whatsapp': 'WhatsApp',
      'email': 'ईमेल',
      'qr': 'QR कोड',
      'endClass': 'कक्षा समाप्त',
      'guest': 'अतिथि',
      'freeze': 'स्क्रीन रोकें',
      'unfreeze': 'बंद करें',
      'frozen': 'स्क्रीन रुकी है',
      'addPageBlank': 'पहले इस पेज पर कुछ लिखें',
      'shareTitle': 'व्हाइटबोर्ड साझा करें',
      'preparing': '{n} पेज तैयार हो रहे हैं…',
      'shareScan': 'बोर्ड खोलने के लिए स्कैन करें',
      'copyLink': 'लिंक कॉपी करें',
      'copied': 'लिंक कॉपी हुआ',
      'moreApps': 'अन्य ऐप',
      'linkExpires': 'लिंक 30 दिन तक चलेगा।',
      'shareNeedsSignIn': 'लिंक से साझा करने के लिए साइन इन करें। PDF यहीं से भेज सकते हैं।',
      'shareFailed': 'लिंक तैयार नहीं हुआ। आपका बोर्ड सुरक्षित है। फिर कोशिश करें।',
      'boardTitle': 'व्हाइटबोर्ड',
      'versions': 'संस्करण इतिहास',
      'restoreVersion': 'वापस लाएँ',
      'brandName': 'निर्यात पर ब्रांड नाम',
      'watermark': 'वॉटरमार्क',
      'logo': 'लोगो',
      'branding': 'ब्रांडिंग',
      'apply': 'लागू करें',
      'cancel': 'रद्द करें',
      'template': 'टेम्पलेट',
      'background': 'पृष्ठभूमि',
      'custom': 'कस्टम',
      'twoSide': 'दो सिरे',
      'frontTip': 'आगे का सिरा',
      'backTip': 'पीछे का सिरा',
      'tipWrite': 'लिखें',
      'tipErase': 'मिटाएँ',
      'tipSelect': 'चुनें',
      'tipHighlight': 'हाइलाइट',
      'solidPen': 'पेन',
      'highlighter': 'हाइलाइटर',
      'language': 'भाषा',
      'font': 'फ़ॉन्ट',
      'slideToClear': 'पेज साफ़ करने के लिए खिसकाएँ',
      'smartTools': 'स्मार्ट टूल',
      'smartSummary': 'सारांश',
      'smartLecture': 'व्याख्यान',
      'smartPeriodic': 'आवर्त सारणी',
      'smartDictionary': 'शब्दकोश',
      'smartCalculator': 'कैलकुलेटर',
      'selectAsk': 'चयन के बारे में पूछें',
      'apps': 'कक्षा ऐप',
      'otherTools': 'अन्य टूल',
      'important': 'महत्वपूर्ण',
      'addToBoard': 'बोर्ड पर जोड़ें',
      'whatsNew': 'नया क्या है',
      'scheduleTraining': 'प्रशिक्षण तय करें',
      'configurations': 'कॉन्फ़िगरेशन',
      'yourClassrooms': 'आपकी कक्षाएँ',
      'profileNew': 'नया',
      'exit': 'बाहर निकलें',
      'eraserSize': 'रबर का आकार',
    },
    'kn': {
      'switch': 'ಬದಲಿಸಿ',
      'hide': 'ಮರೆಮಾಡಿ',
      'restore': 'ಉಪಕರಣ ತೋರಿಸಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'whatsapp': 'WhatsApp',
      'email': 'ಇಮೇಲ್',
      'qr': 'QR ಕೋಡ್',
      'endClass': 'ತರಗತಿ ಮುಗಿಸಿ',
      'guest': 'ಅತಿಥಿ',
      'freeze': 'ಪರದೆ ನಿಲ್ಲಿಸಿ',
      'unfreeze': 'ಮುಚ್ಚಿ',
      'frozen': 'ಪರದೆ ನಿಂತಿದೆ',
      'addPageBlank': 'ಮೊದಲು ಈ ಪುಟದಲ್ಲಿ ಏನಾದರೂ ಬರೆಯಿರಿ',
      'shareTitle': 'ವೈಟ್‌ಬೋರ್ಡ್ ಹಂಚಿಕೊಳ್ಳಿ',
      'shareScan': 'ಬೋರ್ಡ್ ತೆರೆಯಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'copyLink': 'ಲಿಂಕ್ ನಕಲಿಸಿ',
      'versions': 'ಆವೃತ್ತಿ ಇತಿಹಾಸ',
      'restoreVersion': 'ಮರುಸ್ಥಾಪಿಸಿ',
      'watermark': 'ವಾಟರ್‌ಮಾರ್ಕ್',
      'logo': 'ಲೋಗೋ',
      'apply': 'ಅನ್ವಯಿಸಿ',
      'cancel': 'ರದ್ದು',
      'template': 'ಟೆಂಪ್ಲೇಟ್',
      'background': 'ಹಿನ್ನೆಲೆ',
      'custom': 'ಕಸ್ಟಮ್',
      'frontTip': 'ಮುಂದಿನ ತುದಿ',
      'backTip': 'ಹಿಂದಿನ ತುದಿ',
      'tipWrite': 'ಬರೆಯಿರಿ',
      'tipErase': 'ಅಳಿಸಿ',
      'tipSelect': 'ಆಯ್ಕೆ',
      'tipHighlight': 'ಹೈಲೈಟ್',
      'language': 'ಭಾಷೆ',
      'font': 'ಫಾಂಟ್',
      'smartTools': 'ಸ್ಮಾರ್ಟ್ ಉಪಕರಣಗಳು',
      'smartSummary': 'ಸಾರಾಂಶ',
      'smartLecture': 'ಉಪನ್ಯಾಸ',
      'smartPeriodic': 'ಆವರ್ತ ಕೋಷ್ಟಕ',
      'smartDictionary': 'ನಿಘಂಟು',
      'smartCalculator': 'ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'selectAsk': 'ಆಯ್ಕೆಯ ಬಗ್ಗೆ ಕೇಳಿ',
      'apps': 'ತರಗತಿ ಆ್ಯಪ್‌ಗಳು',
      'otherTools': 'ಇತರ ಉಪಕರಣಗಳು',
      'important': 'ಮುಖ್ಯ',
      'addToBoard': 'ಬೋರ್ಡ್‌ಗೆ ಸೇರಿಸಿ',
      'whatsNew': 'ಹೊಸದೇನು',
      'scheduleTraining': 'ತರಬೇತಿ ನಿಗದಿಪಡಿಸಿ',
      'configurations': 'ಸಂರಚನೆಗಳು',
      'yourClassrooms': 'ನಿಮ್ಮ ತರಗತಿಗಳು',
      'profileNew': 'ಹೊಸದು',
      'exit': 'ನಿರ್ಗಮಿಸಿ',
    },
  };
}
