import 'package:flutter/widgets.dart';

/// Strings for the Smartboard spec features (toolbar groups, freeze, sharing, branding, stylus
/// tips, Text AI, quiz scan, smart tools). English, Hindi and Kannada, like LayoutStrings.
class SbStrings {
  const SbStrings(this.lang);

  final String lang;

  static SbStrings of(BuildContext context) => SbStrings(Localizations.maybeLocaleOf(context)?.languageCode ?? 'en');

  String call(String key, [Map<String, Object> args = const {}]) {
    var s = (_strings[lang] ?? _strings['en']!)[key] ?? _strings['en']![key] ?? key;
    args.forEach((k, v) => s = s.replaceAll('{$k}', '$v'));
    return s;
  }

  static const _strings = <String, Map<String, String>>{
    'en': {
      'switch': 'Switch',
      'hide': 'Hide',
      'restore': 'Show tools',
      'share': 'Share',
      'whatsapp': 'WhatsApp',
      'email': 'Email',
      'qr': 'QR code',
      'endClass': 'End class',
      'guest': 'Guest',
      'freeze': 'Freeze screen',
      'unfreeze': 'Close',
      'frozen': 'Screen frozen',
      'addPageBlank': 'Write something on this page first',
      'shareTitle': 'Share whiteboard',
      'preparing': 'Preparing {n} pages…',
      'shareScan': 'Scan to open the board',
      'copyLink': 'Copy link',
      'copied': 'Link copied',
      'moreApps': 'Other apps',
      'linkExpires': 'The link works for 30 days.',
      'shareNeedsSignIn': 'Sign in to share by link. You can still send the PDF from this panel.',
      'shareFailed': 'Could not prepare the link. Your board is safe. Try again.',
      'boardTitle': 'Whiteboard',
      'emailSubject': 'Whiteboard: {t}',
      'emailBody': 'Here are the board notes from class:\n{u}',
      'waText': 'Board notes: {t}\n{u}',
      'versions': 'Version history',
      'versionsEmpty': 'No earlier saves yet. Each save keeps the one before it.',
      'restoreVersion': 'Restore',
      'restored': 'Restored the save from {d}',
      'pagesN': '{n} pages',
      'brandName': 'Brand name on exports',
      'watermark': 'Watermark',
      'logo': 'Logo',
      'chooseLogo': 'Choose logo',
      'removeLogo': 'Remove logo',
      'branding': 'Branding',
      'brandingHint': 'Shown on shared and exported PDFs.',
      'tooLarge': 'That picture is over 10 MB. Choose a smaller one.',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'preview': 'Preview',
      'template': 'Template',
      'background': 'Background',
      'custom': 'Custom',
      'twoSide': 'Two Side',
      'frontTip': 'Front Tip',
      'backTip': 'Back Tip',
      'tipWrite': 'Write',
      'tipErase': 'Erase',
      'tipSelect': 'Select',
      'tipHighlight': 'Highlight',
      'twoSideHint': 'For a stylus with two ends. The panel tells the board which end touches.',
      'solidPen': 'Solid Pen',
      'highlighter': 'Highlighter',
      'textAi': 'Text AI',
      'shapeAi': 'Shape AI',
      'language': 'Language',
      'font': 'Font',
      'fontDefault': 'Default',
      'fontKalam': 'Kalam',
      'fontCustom': 'Custom',
      'slideToClear': 'Slide to clear the page',
      'eraserSize': 'Eraser size',
      'bringForward': 'Forward',
      'sendBackward': 'Backward',
      'faceColour': 'Colour a face',
      'faceColourHint': 'Tap a face, then a colour',
      'tabs2d': '2D',
      'tabs3d': '3D',
      'lined': 'Lined',
      'filled': 'Filled',
    },
    'hi': {
      'switch': 'बदलें',
      'hide': 'छिपाएँ',
      'restore': 'टूल दिखाएँ',
      'share': 'साझा करें',
      'whatsapp': 'WhatsApp',
      'email': 'ईमेल',
      'qr': 'QR कोड',
      'endClass': 'कक्षा समाप्त',
      'guest': 'अतिथि',
      'freeze': 'स्क्रीन रोकें',
      'unfreeze': 'बंद करें',
      'frozen': 'स्क्रीन रुकी है',
      'addPageBlank': 'पहले इस पेज पर कुछ लिखें',
      'shareTitle': 'व्हाइटबोर्ड साझा करें',
      'preparing': '{n} पेज तैयार हो रहे हैं…',
      'shareScan': 'बोर्ड खोलने के लिए स्कैन करें',
      'copyLink': 'लिंक कॉपी करें',
      'copied': 'लिंक कॉपी हुआ',
      'moreApps': 'अन्य ऐप',
      'linkExpires': 'लिंक 30 दिन तक चलेगा।',
      'shareNeedsSignIn': 'लिंक से साझा करने के लिए साइन इन करें। PDF यहीं से भेज सकते हैं।',
      'shareFailed': 'लिंक तैयार नहीं हुआ। आपका बोर्ड सुरक्षित है। फिर कोशिश करें।',
      'boardTitle': 'व्हाइटबोर्ड',
      'versions': 'संस्करण इतिहास',
      'restoreVersion': 'वापस लाएँ',
      'brandName': 'निर्यात पर ब्रांड नाम',
      'watermark': 'वॉटरमार्क',
      'logo': 'लोगो',
      'branding': 'ब्रांडिंग',
      'apply': 'लागू करें',
      'cancel': 'रद्द करें',
      'template': 'टेम्पलेट',
      'background': 'पृष्ठभूमि',
      'custom': 'कस्टम',
      'twoSide': 'दो सिरे',
      'frontTip': 'आगे का सिरा',
      'backTip': 'पीछे का सिरा',
      'tipWrite': 'लिखें',
      'tipErase': 'मिटाएँ',
      'tipSelect': 'चुनें',
      'tipHighlight': 'हाइलाइट',
      'solidPen': 'पेन',
      'highlighter': 'हाइलाइटर',
      'language': 'भाषा',
      'font': 'फ़ॉन्ट',
      'slideToClear': 'पेज साफ़ करने के लिए खिसकाएँ',
      'eraserSize': 'रबर का आकार',
    },
    'kn': {
      'switch': 'ಬದಲಿಸಿ',
      'hide': 'ಮರೆಮಾಡಿ',
      'restore': 'ಉಪಕರಣ ತೋರಿಸಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'whatsapp': 'WhatsApp',
      'email': 'ಇಮೇಲ್',
      'qr': 'QR ಕೋಡ್',
      'endClass': 'ತರಗತಿ ಮುಗಿಸಿ',
      'guest': 'ಅತಿಥಿ',
      'freeze': 'ಪರದೆ ನಿಲ್ಲಿಸಿ',
      'unfreeze': 'ಮುಚ್ಚಿ',
      'frozen': 'ಪರದೆ ನಿಂತಿದೆ',
      'addPageBlank': 'ಮೊದಲು ಈ ಪುಟದಲ್ಲಿ ಏನಾದರೂ ಬರೆಯಿರಿ',
      'shareTitle': 'ವೈಟ್‌ಬೋರ್ಡ್ ಹಂಚಿಕೊಳ್ಳಿ',
      'shareScan': 'ಬೋರ್ಡ್ ತೆರೆಯಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'copyLink': 'ಲಿಂಕ್ ನಕಲಿಸಿ',
      'versions': 'ಆವೃತ್ತಿ ಇತಿಹಾಸ',
      'restoreVersion': 'ಮರುಸ್ಥಾಪಿಸಿ',
      'watermark': 'ವಾಟರ್‌ಮಾರ್ಕ್',
      'logo': 'ಲೋಗೋ',
      'apply': 'ಅನ್ವಯಿಸಿ',
      'cancel': 'ರದ್ದು',
      'template': 'ಟೆಂಪ್ಲೇಟ್',
      'background': 'ಹಿನ್ನೆಲೆ',
      'custom': 'ಕಸ್ಟಮ್',
      'frontTip': 'ಮುಂದಿನ ತುದಿ',
      'backTip': 'ಹಿಂದಿನ ತುದಿ',
      'tipWrite': 'ಬರೆಯಿರಿ',
      'tipErase': 'ಅಳಿಸಿ',
      'tipSelect': 'ಆಯ್ಕೆ',
      'tipHighlight': 'ಹೈಲೈಟ್',
      'language': 'ಭಾಷೆ',
      'font': 'ಫಾಂಟ್',
    },
  };
}
