import 'package:flutter/widgets.dart';

import '../l10n/feature_strings.dart';

/// The demo class switcher's words (lib/demo/demo_class_switcher.dart).
FeatureStrings demoStrings(BuildContext context) => FeatureStrings(boardLang(context), demoStringTable);

const demoStringTable = <String, Map<String, String>>{
  'en': {
    'switcher': 'Demo classes',
    'switcherHint': "Today's timetable. Pick a class to open it on the board.",
    'switch': 'Switch class',
    'now': 'Open now',
    'opened': 'Opened {n}',
    'thisClass': 'This class',
    'syllabus': 'Syllabus',
    'topic': "Today's topic",
    'plan': "Today's plan",
    'min': '{n} min',
    'videos': 'Concept videos',
    'kit': 'Subject kit',
    'labs': 'Labs',
    'models': '3D models',
    'sims': 'PhET sims',
    'animations': 'Animations',
    'primary': 'Start with',
    'roster': 'Students',
    'openPlan': 'Open plan',
    'noClass': 'No demo class is open.',
  },
  'hi': {
    'switcher': 'डेमो कक्षाएँ',
    'switcherHint': 'आज की समय-सारणी। बोर्ड पर खोलने के लिए कक्षा चुनें।',
    'switch': 'कक्षा बदलें',
    'now': 'अभी खुली',
    'opened': '{n} खोली गई',
    'thisClass': 'यह कक्षा',
    'syllabus': 'पाठ्यक्रम',
    'topic': 'आज का विषय',
    'plan': 'आज की योजना',
    'min': '{n} मिनट',
    'videos': 'कॉन्सेप्ट वीडियो',
    'kit': 'विषय किट',
    'labs': 'लैब',
    'models': '3D मॉडल',
    'sims': 'PhET सिम',
    'animations': 'एनिमेशन',
    'primary': 'शुरुआत करें',
    'roster': 'विद्यार्थी',
    'openPlan': 'योजना खोलें',
    'noClass': 'कोई डेमो कक्षा खुली नहीं है।',
  },
  'kn': {
    'switcher': 'ಡೆಮೊ ತರಗತಿಗಳು',
    'switcherHint': 'ಇಂದಿನ ವೇಳಾಪಟ್ಟಿ. ಬೋರ್ಡ್‌ನಲ್ಲಿ ತೆರೆಯಲು ತರಗತಿಯನ್ನು ಆರಿಸಿ.',
    'switch': 'ತರಗತಿ ಬದಲಿಸಿ',
    'now': 'ಈಗ ತೆರೆದಿದೆ',
    'opened': '{n} ತೆರೆಯಲಾಗಿದೆ',
    'thisClass': 'ಈ ತರಗತಿ',
    'syllabus': 'ಪಠ್ಯಕ್ರಮ',
    'topic': 'ಇಂದಿನ ವಿಷಯ',
    'plan': 'ಇಂದಿನ ಯೋಜನೆ',
    'min': '{n} ನಿಮಿಷ',
    'videos': 'ಕಾನ್ಸೆಪ್ಟ್ ವೀಡಿಯೊಗಳು',
    'kit': 'ವಿಷಯ ಕಿಟ್',
    'labs': 'ಪ್ರಯೋಗಾಲಯಗಳು',
    'models': '3D ಮಾದರಿಗಳು',
    'sims': 'PhET ಸಿಮ್‌ಗಳು',
    'animations': 'ಅನಿಮೇಷನ್‌ಗಳು',
    'primary': 'ಇದರಿಂದ ಆರಂಭಿಸಿ',
    'roster': 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    'openPlan': 'ಯೋಜನೆ ತೆರೆಯಿರಿ',
    'noClass': 'ಯಾವುದೇ ಡೆಮೊ ತರಗತಿ ತೆರೆದಿಲ್ಲ.',
  },
};
