#!/usr/bin/env node
// Builds docs/product/role-matrix.md: for every API module, which roles may read, create, update, delete, approve, publish, export
// and audit, taken from the @Auth(...) decorators on its controllers. Run: node services/api/scripts/role-matrix.mjs
// A test (test/role-matrix.spec.ts) fails when the committed file is out of date.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const SRC = join(here, '..', 'src');
export const OUT = join(here, '..', '..', '..', 'docs', 'product', 'role-matrix.md');

const walk = (dir) => readdirSync(dir).flatMap((f) => {
  const p = join(dir, f);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

/** `const NAME: RoleName[] = [ 'a', ...OTHER ]`, per file (a name defined in the file wins) and across the source tree. */
function roleSets(files) {
  const local = new Map();
  const global = new Map();
  for (const f of files) {
    const text = readFileSync(f, 'utf8');
    const here = new Map();
    for (const m of text.matchAll(/(export\s+)?const ([A-Z_]+)(?::\s*[A-Za-z<>\[\]]+)?\s*=\s*(\[[\s\S]*?\])(?:\s*as const)?;/g)) {
      here.set(m[2], m[3]);
      if (m[1]) global.set(m[2], m[3]);
    }
    local.set(f, here);
  }
  const make = (file) => {
    const defs = (name) => local.get(file)?.get(name) ?? global.get(name);
    const resolve = (name, seen = new Set()) => {
      const def = defs(name);
      if (seen.has(name) || !def) return [];
      seen.add(name);
      return expand(def, seen);
    };
    const expand = (arrayText, seen = new Set()) => {
      const roles = new Set();
      for (const m of arrayText.matchAll(/'([a-z_]+)'|\.\.\.([A-Z_]+)/g)) {
        if (m[1]) roles.add(m[1]);
        else for (const r of resolve(m[2], seen)) roles.add(r);
      }
      return [...roles];
    };
    return { resolve, expand };
  };
  return make;
}

const VERBS = [
  ['approve', /approve|decide|return|reject|verify|moderate/i],
  ['publish', /publish|lock|issue|release/i],
  ['export', /export|\.csv|\.pdf|download/i],
  ['audit', /audit|audit-log/i],
];

function actionOf(method, path) {
  for (const [name, re] of VERBS) if (re.test(path)) return name;
  return { Get: 'read', Post: 'create', Put: 'update', Patch: 'update', Delete: 'delete' }[method];
}

export function buildMatrix() {
  const files = walk(SRC).filter((f) => f.endsWith('.ts') && !f.endsWith('.spec.ts'));
  const setsFor = roleSets(files);
  const modules = new Map();
  for (const f of files.filter((x) => x.endsWith('.controller.ts'))) {
    const text = readFileSync(f, 'utf8');
    const sets = setsFor(f);
    const mod = relative(SRC, f).split('/')[0];
    for (const cls of text.split(/@Controller\(/).slice(1)) {
      const prefix = /^'([^']*)'/.exec(cls)?.[1] ?? '';
      for (const m of cls.matchAll(/@(Get|Post|Put|Patch|Delete)\(([^)]*)\)([\s\S]{0,260}?)@Auth\(([^)]*(?:\[[^\]]*\][^)]*)?)\)/g)) {
        const sub = /'([^']*)'/.exec(m[2])?.[1] ?? '';
        const path = `${prefix}/${sub}`;
        // The decorator must belong to this handler: no other HTTP decorator between them.
        if (/@(Get|Post|Put|Patch|Delete)\(/.test(m[3])) continue;
        const arg = m[4].trim();
        const kind = /^'(user|device)'/.exec(arg)?.[1];
        if (!kind) continue;
        let roles;
        const rest = arg.replace(/^'(user|device)'\s*,?\s*/, '');
        if (kind === 'device') roles = ['(board device)'];
        else if (!rest) roles = ['(any signed-in user; the handler checks ownership)'];
        else if (rest.startsWith('[')) roles = sets.expand(rest);
        else roles = sets.resolve(rest.replace(/[^A-Z_]/g, ''));
        if (roles.length === 0) roles = ['(see controller)'];
        const entry = modules.get(mod) ?? new Map();
        const a = actionOf(m[1], sub);
        entry.set(a, new Set([...(entry.get(a) ?? []), ...roles]));
        modules.set(mod, entry);
      }
    }
  }
  const ACTIONS = ['read', 'create', 'update', 'delete', 'approve', 'publish', 'export', 'audit'];
  const lines = [
    '# Role matrix',
    '',
    'Which roles may do what, per API module, read from the `@Auth(...)` decorators on every controller. Generated by `node services/api/scripts/role-matrix.mjs`; a test keeps this file in step with the code.',
    '"Approve", "publish", "export" and "audit" are the handlers whose path says so (approve, decide, return, publish, lock, issue, export, csv, pdf, audit); the rest are read (GET), create (POST), update (PUT, PATCH) and delete (DELETE).',
    'A role in brackets is not a staff role: `(board device)` is a smartboard, `(any signed-in user ...)` means the handler itself checks that the record belongs to the person.',
    '',
    '| Module | ' + ACTIONS.join(' | ') + ' |',
    '|---|' + ACTIONS.map(() => '---').join('|') + '|',
  ];
  for (const mod of [...modules.keys()].sort()) {
    const e = modules.get(mod);
    lines.push(`| ${mod} | ` + ACTIONS.map((a) => (e.has(a) ? [...e.get(a)].sort().join(', ') : '-')).join(' | ') + ' |');
  }
  lines.push('');
  return lines.join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--stdout')) process.stdout.write(buildMatrix());
  else {
    writeFileSync(OUT, buildMatrix());
    console.log(`Wrote ${relative(process.cwd(), OUT)}`);
  }
}
